### ISSUE TITLE
Missing in lokalise text from Development tools/Statistics

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18365] opened 2023-10-23 17:26 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise text from Development tools/Statistics (red marked in screenshot below)

![Snag_3fe54cc](https://github.com/home-assistant/frontend/assets/61636045/6d9ebc3f-9a81-4a5a-9fa1-a10c8839b24a)

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment] 2023-10-27 04:53
Looks like you opened the same issue twice, I'll close this one, though let me know if I misread it. 

Duplicate of #18363

**Closed by karwosts** 2023-10-27 04:53 UTC
Labels: localization
