### ISSUE TITLE
Impossibility of creating tariff in counter with the helper interface

### ISSUE THREAD

**Issue by Tsompi** [home-assistant/frontend#14727] opened 2022-12-12 12:02 UTC
### The problem

Since the update to version 2022.12. When creating a counter with the helper interface, it does not allow you to enter tariff.
![Screenshot_4](https://user-images.githubusercontent.com/104169046/207038198-dd2bad59-1be4-4a64-a8f9-1b4888f0caea.jpg)

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.3

### What was the last working version of Home Assistant Core?

Home Assistant 2022.11.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Helpers, Counter

### Additional information

In the previous version 2022.11.5 it worked without problems, since I just created a tariff before updating.

**Comment by lyricnz** [comment] 2022-12-15 21:41
Duplicate of https://github.com/home-assistant/frontend/issues/14703

**Comment by frenck** [comment] 2022-12-16 08:34
Closing as a duplicate

**Closed by frenck** 2022-12-16 08:34 UTC
