### ISSUE TITLE
Automation/Script Editor does not show new lines when scrolling - impossible to use in a text mode

### ISSUE THREAD

**Issue by gribouk** [home-assistant/frontend#8557] opened 2021-03-05 11:18 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Home Assistant has a very convenient tool to edit scripts and autpomations. It has a feature to switch to manual editing (text mode). However, after the update to the latest version of HA core 2021.3.1 the followint bug persists:

1. Open any script/automation.
2. Switch to text mode (partially or completely)
3. Try to scroll the text
You would find, that the new text  does not appear when scrolling.
I have asked if I am the only with this issue at discussions branch dedicated to this release, and got replies, that other experiencing this isue as well (https://community.home-assistant.io/t/2021-3-my-oh-my/286346/274). Thus, I concluded - it is a BUG.

### Describe the behavior you expected

I expect to see the text lines of the scripts as before...

### Steps to reproduce the issue

1. Open any script/automation.
2. Switch to text mode (partially ore completely)
3. Try to scroll the text

### What version of Home Assistant Core has the issue?

core-2021.3.1

### What was the last working version of Home Assistant Core?

core-2021.2.3

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.190| Opera

### Which operating system are you using to run this browser?

Win10 buid 21322

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by bramkragten** [comment] 2021-03-05 13:21
As a workaround: If you click in the text field the text will show btw.

**Comment by gribouk** [comment] 2021-03-05 14:17
Yeah, I know that, but it does not save you if you have a big script - you need the normal scrolling for the navigation. At the moment, when a chunk of text appeares out from nowhere, I just cannot understand what part of code it is related to... I had to roll back for the time being to the last working version.

**Comment by gribouk** [comment] 2021-04-08 10:34
> As a workaround: If you click in the text field the text will show btw.

As of V 2021.3 - the scrolling in the script/automation editor in the text mode does not work.
For those of you who thinks that clicking the mouse to make a missing lines to appear is a ‘workaround’ - try to copy several screens of code (first couple of screens it would show) - for this reason it is the second update I have to miss and roll back to the last working version - 2021.2.

I know I cannot ask for anything with a free software, thus I bagg - please, do something about it...

**Comment by spacegaier** [comment] 2021-04-08 10:56
I cannot reproduce this. Scrolling works fine for me on Win 10 + FF and Chrome. Can you add a short clip to visualize your issue?

**Comment by gribouk** [comment] 2021-04-08 11:47
I just rolled back to 2.3, but deliberatelly for you' I've reupdated to 4.0 and made a video of this bug - yes, it is still there and it is a FAAAT one this time, eating our gras... It is one of my smaller scripts - 5K lines only, and I have 4-5 times bigger than that (Jinja - a lot of stuff is just a copy-paste over and over again...) - imagine how nice it is to navigate through it with such a scrolling?

**Comment by gribouk** [comment] 2021-04-08 11:47
https://user-images.githubusercontent.com/72703085/114021442-5fc2d180-9879-11eb-9c47-c14f08ab3a88.mp4

**Comment by spacegaier** [comment] 2021-04-08 15:02
Looking at your example, my test automation might have been too small, since I think the issue does not immediately appear when you start scrolling (since for a few lines you still get new data scrolled into view), but then after a certain amount of lines, the content stops.

If you scroll very slowly does the issue still appear or does it then "load" the data fast enough so you never notice the issue?

**Comment by gribouk** [comment] 2021-04-08 15:16
Yes, actually, the bug appeares almost instantly. The video gives missrepresentation of the bug since it gives no indication where I press the mouse button to update the screen content. So, every time there is a time lag on the video for a new lines to appear - I press a mouse button. This is to understand that the lines do not appear automatically, but it is me pressing the button for this to happen. It does store in memory a couple of screens at the best though, but the rest is blank. And again, on the video, when I try to select a text, the reason I can scroll so deep is that I hold the mouse button pressed. But, eventually, even this trick fails and new lines appear no more...

And by the way, I have found that this issue was also reported by another person who posted similar video.
https://github.com/home-assistant/frontend/issues/8631

**Comment by gribouk** [comment] 2021-04-08 15:21
And one more thing to mention: assume you've scrolled somewhere. You press the button and content updates. When you scroll again to where you came from - it is blank there. This is important to understand, that once you've updated the content, it does not stay there available for the view through scrolling.

**Comment by bramkragten** [comment] 2021-04-08 15:58
Can you check the automation editor in yaml mode in 2021.4 is the issue also present there?

**Comment by gribouk** [comment] 2021-04-08 16:52
I have installed new instance on another machine (Debian) in a docker in order not to update and rollback again - hope it does not effect the purity of the experiment.

O.k. Gentelmen, it looks like you've done a pretty good job during this time, I am very pleased with what you've done to the automations text editor:

1. the window is !!!WIDE!!!. I no longer have to torture myself with this narrow rectangle usind bearly 20% of the actual screen width. Thank you for that (BTW, I was thinking to open a 'feature request' for that as soon as this bug was supposed to be fixed, but you've read my mind obviously). Hope in HassOs version it is the same now, unfortunatelly I was too dissapointed and forgot to check...

2.  there is no scrolling bug as last time.


For the script editor, for some reason, everything as before... Could you do it as for the atomations, please-please...

I enclose 2 pics of 'good' editor - automations, and 'bad' editor - scripts.

**Comment by gribouk** [comment] 2021-04-08 16:52
![good_editor_automations](https://user-images.githubusercontent.com/72703085/114066032-f1dfcf80-98a3-11eb-9664-b955d2eeebca.jpg)
![bad_editor_scripts](https://user-images.githubusercontent.com/72703085/114066043-f4422980-98a3-11eb-8c95-45e54baf7d11.jpg)

**Comment by gribouk** [comment] 2021-04-09 16:26
> Can you check the automation editor in yaml mode in 2021.4 is the issue also present there?

Just updated to the 2021.4.1 in a Docker - the bug in the script editor is still there - no scrolling.

Just to let you know incase you did something and need a feed back.

**Comment by bramkragten** [comment] 2021-04-09 18:00
Yeah, we will implement the same editor UI for scripts

**Comment by RichieFrame** [comment] 2021-04-16 03:59
I have confirmed this issue also occurs in the "Automation Config" tab of the new automation tracing ui, as well as the "Step Config" subtab of the "Step Details" tab

**Comment by bramkragten** [comment] 2021-04-16 16:59
Created upstream issue:
<https://github.com/codemirror/codemirror.next/issues/461>

**Comment by bramkragten** [comment] 2021-04-19 13:27
Fixed upstream, waiting for upstream release to close this issue.

**Closed** 2021-04-21 17:22 UTC
Labels: bug

**Comment by gribouk** [comment] 2021-04-21 17:54
Am I missing something or doing wrong, but on the machine which runs HA in a Docker (not the main instance for me, just for tests) I just updated to V2021.4.6 and the bug is still there (see the pic). How can I the bugless version if you say the issue is closed?
![editor_bug_persists](https://user-images.githubusercontent.com/72703085/115599033-c1585680-a2e3-11eb-9a57-979f7204aa83.jpg)

**Comment by spacegaier** [comment] 2021-04-21 18:02
2021.4.6. does not contain this fix. The fix is so far only available in the development version of the frontend.

**Comment by gribouk** [comment] 2021-05-04 22:15
I have tested new script editor under the 2021.5b4 and 5b7. It looks wonderfull and is a massive step forwards compared to what it was before!

There are two minor issues which I see that are still left to address:

1. Empty string 'home' button press issue - when you press enter, you get to an empty string, lets call it number N, into position 0, or (N,0) in coordinates. If you press 'home' now, you get into possition (0,0) - line 0, shift 0, which is somwhat disterbing if you adit a script few screen down, since you have to search for the place where you've just jumped from... If the string is not empty, hovewer, everything works as suggested - pressimg 'home' keeps you within same string.
2. Browser search problem - if in your browser you've decided to find some entry, lets say 'variable_name', in your script and you use 'find' in a browsers menu, it searches for the entry within an active screen only - not a whole document as before. This is pretty inconvenient...

I've tested it under Chrome and Edge with same outcome.
