### ISSUE TITLE
Automations: Selecting a tag does not update the trigger title to include the name

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22588] opened 2024-10-29 14:01 UTC
### Describe the issue you are experiencing

When you add a Tag scan as a trigger to an automation the title of the trigger should include the tag name.

But when you add the tag the default title from here remains active:

https://github.com/home-assistant/frontend/blob/42f2341e065daf4245134b7df14252513f3fa048/src/translations/en.json#L3042

![image](https://github.com/user-attachments/assets/cce9121f-9a88-4bda-93da-eedb2ef0b244)

### Describe the behavior you expected

I assume this should be extended to:

     "empty": "When a tag is scanned",
     "full": "When tag {name} is scanned",

plus the necessary logic.

A similar string is already defined here but not used in this context:

https://github.com/home-assistant/frontend/blob/42f2341e065daf4245134b7df14252513f3fa048/src/translations/en.json#L2143

For proper translation a hint about its usage would be cool, BTW ;-)

### Steps to reproduce the issue

1. Create a new automation
2. Select + Add trigger 
3. Search for "tag"
4. Select some existing tag from the dropdown menu.

### What version of Home Assistant Core has the issue?

core-2024.10.4

**Comment by silamon** [comment] 2024-11-10 17:45
Duplicate of https://github.com/home-assistant/frontend/issues/22588

**Closed by silamon** 2024-11-10 17:45 UTC
