### ISSUE TITLE
History Graph refresh causing hover popup to disappear immediately

### ISSUE THREAD

**Issue by skrenes** [home-assistant/frontend#8348] opened 2021-02-08 03:56 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When hovering over the graph to see details, the hover popup is immediatly dismissed due to what appears to be a refresh. This appears to have started with 2021.2.x (I'm presently on 2021.2.1)

## Expected behavior
The onHover popup should not be dismissed, especially within a half second.

## Steps to reproduce
Simple hover over a history graph for any state that produces a numerical history graph like WiFi signal or Climate graph. This happens on both my iOS devices as well as Chromium on MacOS.

## Environment

- Home Assistant release with the issue: 2021.2.1 (Docker)
- Last working Home Assistant release (if known): 2021.2.1
- Browser and browser version: Chromium 88.0.4324.146 & Home Assistant Companion 2021.39
- Operating system: MacOS 11.2 / iOS 14.4

## State of relevant entities

![image](https://user-images.githubusercontent.com/5075909/107174106-a0d85b80-6986-11eb-983f-d114b2eaf2d0.png)

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by blair287** [comment] 2021-02-24 23:37
Yep I have same issue along with Lovelace hanging after closing more info screen.

**Comment by spacegaier** [comment] 2021-02-25 08:49
Sounds like duplicate of https://github.com/home-assistant/frontend/issues/8274 which has already been fixed (should be in the current beta).

**Closed by spacegaier** 2021-02-25 08:49 UTC
Labels: bug
