### ISSUE TITLE
IOs, navigations except the main one unreadable with Voice Over

### ISSUE THREAD

**Issue by tyrylu** [home-assistant/frontend#19921] opened 2024-02-29 16:52 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On IOs 17.3.1, any navigation except the main one (for example, the categories in settings and any sublevel thereof) is basically unusable, because Voice Over reports the menu items only as menu items, and nothing else, e. g. they're missing its labels. Because the Home assistant app is just a webview (basically, ignoring a lot of details), it is affected as well.

### Describe the behavior you expected

It is sometimes weird on Windows in Firefox with NVDA, but not always.

### Steps to reproduce the issue

1. Navigate to settings
2. Observe the broken navigation items (don't forget to use Voice Over)

### What version of Home Assistant Core has the issue?

The latest, 24.2.5.

### In which browser are you experiencing the issue with?

See the issue description for version details.

### Which operating system are you using to run this browser?

Also see issue description for version details.

**Comment by steverep** [comment] 2024-03-02 05:47
Duplicate of #18759 

This was caused by a regression in Safari.  Please see the linked issue for details.  At this point it has been fixed on their end but hasn't been released yet.  I'm hoping it'll be in 17.4.

**Closed by steverep** 2024-03-02 05:47 UTC
