### ISSUE TITLE
Entity name not showing correctly History Graph Card

### ISSUE THREAD

**Issue by ColinRobbins** [home-assistant/frontend#9955] opened 2021-09-05 07:25 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The full entity name is not showing correctly in a History Graph.
The bugs shows in the [example](https://www.home-assistant.io/images/lovelace/lovelace_history_graph.png) used in the documentation, where the title is shown as “orative lights” with the start of the text omitted.

### Describe the behavior you expected

See the full title.

### Steps to reproduce the issue

1.  Create a History Graph
2.  Who an entity with a name of longer than about 10 characters

### What version of Home Assistant Core has the issue?

core-2021.9.2

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

Any

### Additional information

First reported in https://github.com/home-assistant/home-assistant.io/issues/19209

**Comment by spacegaier** [comment] 2021-09-05 12:02
I think we should render the beginning of the name and then add ellipsis plus a "title" tooltip for the full name (similar to https://github.com/home-assistant/frontend/pull/9264).

**Comment by spacegaier** [comment] 2021-09-06 10:12
Duplicate of https://github.com/home-assistant/frontend/issues/9852

**Closed by spacegaier** 2021-09-06 10:12 UTC
Labels: bug
