### ISSUE TITLE
Add card view hangs since 0.118

### ISSUE THREAD

**Issue by Depechie** [home-assistant/frontend#7840] opened 2020-11-27 23:04 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I'm doing all my UI within the frontend, so no YAML config. But since 0.118 when pressing the Add card button in the edit dashboard view, the popup with all the card types is super slow.
I need to wait a while before I can use it.

## Expected behavior

Able to directly type a card name and filter the types.

## Steps to reproduce

Click edit dashboard
Click add card
Time how long you have to wait to be able to enter a name

## Environment

Currently running 0.118.4 on an Intel NUC i5 gen 10 with 16GB ram and 500GB SSD.
Everything is lightning fast, except the cards view.

- Home Assistant release with the issue: 0.118.0
- Last working Home Assistant release (if known): 0.117.x
- Browser and browser version: Microsoft Edge, Safari, Chrome
- Operating system: Linux Debian 10

**Comment by ppmt** [comment] 2020-11-29 22:38
I came here to write an issue about exactly the same problem that I have.

So +1

**Comment by zsarnett** [comment] 2020-11-29 22:58
We made some changes in 0.119 (not release) so that the card picker will not load state history. This may fix it but we will take a closer look to make sure

**Comment by ppmt** [comment] 2020-11-30 11:58
> We made some changes in 0.119 (not release) so that the card picker will not load state history. This may fix it but we will take a closer look to make sure

The history bit intrigued me so I went and purge my history and bingo it is immediately much faster. No more waiting time

So not loading the history it seems will help. 

@zsarnett what is the configuration setting for your history?

**Comment by SeByDocKy** [comment] 2020-12-03 08:36
I can confirm the crash too :( :( ... annoying :(

**Comment by spacegaier** [comment] 2020-12-03 09:08
Can you test with the latest dev version / beta? There was at least one more optimization merged yesterday by Bram (https://github.com/home-assistant/frontend/pull/7760) that might help here.

**Comment by ppmt** [comment] 2020-12-03 11:35
@spacegaier what do I need to do to load the latest dev version?

**Comment by zsarnett** [comment] 2020-12-03 13:57
@ppmt If you run beta that will work

**Comment by ppmt** [comment] 2020-12-05 18:15
@spacegaier , @zsarnett 
I have activated the beta channel and updated to 1.0.0b1

I am afraid the problem is still present. There is still a very delay before I can choose the card I want. Pressing any key to filter out cards takes forever.

**Comment by zsarnett** [comment] 2020-12-05 18:18
How many entities do you have?

**Comment by ppmt** [comment] 2020-12-05 18:29
@zsarnett 
Including the hidden one : 296

**Comment by Depechie** [comment] 2020-12-06 10:50
For reference ( still on 0.118.5 though ) my count
domain:21
entities:469

**Comment by ppmt** [comment] 2020-12-13 20:16
Just installed beta6 and it looks much better.

Response time is now very quick. I noticed now that the history graph  card says "No state history found"...so may be that is the difference.

I will try it again in a few hours to make sure it still work...

**Comment by spacegaier** [comment] 2021-01-02 18:02
@Depechie @ppmt Can you check again if all is still good? If yes, I will close this ticket.
This PR https://github.com/home-assistant/frontend/pull/7760 beginning of December ensured that for the history graph preview we only use the "sun" entity if available. So much less data to read an render for the card selector.

@ppmt I would assume you do not have the "sun" integration active and hence you see "No state history found" in the preview.

**Comment by ppmt** [comment] 2021-01-02 18:22
@spacegaier : correct I do not use the sun integration. I might try to define it to see if it has any impacts

**Comment by Depechie** [comment] 2021-01-02 18:36
@spacegaier looking good for me! Thx for the fox.

**Comment by spacegaier** [comment] 2021-01-02 20:37
@ppmt Then it should normally get picked up for the preview, but of course only if it actually has recently collected state changes to render.

@Depechie Then please close this ticket. Thanks.

**Closed** 2021-01-02 20:37 UTC
Labels: bug
