### ISSUE TITLE
Can't change user visibility setting

### ISSUE THREAD

**Issue by itkama** [home-assistant/frontend#20018] opened 2024-03-07 18:05 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When changing the visibility toggle for a user, the toggle jumps back after a split second.

### Describe the behavior you expected

Toggle should turn off so it is not visible to user.

### Steps to reproduce the issue

Just try changing the visibility.

### What version of Home Assistant Core has the issue?

core.2024.3.0

### In which browser are you experiencing the issue with?

Latest Chrome, Latest Edge

### Which operating system are you using to run this browser?

Windows 11 Pro

### Javascript errors shown in your browser console/inspector

```txt
Uncaught TypeError: Cannot add property visible, object is not extensible
    at F.value (hui-dialog-edit-view.ts:475:20)
    at F.handleEvent (lit-html.ts:2018:29)
    at r (fire_event.ts:76:8)
    at t.value (hui-view-visibility-editor.ts:136:5)
    at F.handleEvent (lit-html.ts:2018:29)
    at HTMLDivElement.<anonymous> (mwc-switch-base.ts:121:14)
hui-dialog-edit-view.ts:475
```

### Additional information

Edit: I tried reproducing this in another instance, but it works as expected there.

**Comment by karwosts** [comment] 2024-03-07 19:21
Duplicate of #20010, fix should be in 2024.3.1

**Closed by karwosts** 2024-03-07 19:21 UTC
