### ISSUE TITLE
Frontend does not reconnect in Fully Kiosk Browser

### ISSUE THREAD

**Issue by hanzoh** [home-assistant/frontend#6266] opened 2020-06-28 09:11 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

With Fully Kiosk Browser (1.40, WebView 83), the frontend does not reconnect after the tablet's screen turned off (after a 10s timeout) and on again (after the tablet's front camera registered motion). The URL has to be reloaded manually.

## Expected behavior

Frontend automatically reconnects after screen turns back on.

## Steps to reproduce

    1. Configure Fully Kiosk Browser on Android with local Home Assistant IP as Start URL (e.g. http://192.168.0.10:8123).
    2. Let the screen turn off via timeout.
    3. Turn the screen back on (either manually or via motion trigger)

## Environment

- Home Assistant release with the issue: 0.112.0b2
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Fully Kiosk Browser 1.40 (using WebView 83)
- Operating system: Android 8.1

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by balloob** [comment] 2020-06-28 20:10
Duplicate of #6227

**Closed by balloob** 2020-06-28 20:10 UTC
Labels: bug
