### ISSUE TITLE
The value displayed above the slider is not on top the card and can be cut off

### ISSUE THREAD

**Issue by WRoss7** [home-assistant/frontend#9271] opened 2021-05-26 19:16 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Cursor](https://user-images.githubusercontent.com/74879713/119717628-d4bc8b80-be66-11eb-826b-b50634bb1d12.png)

The image speaks for itself

### Describe the behavior you expected

Correct display of the graphic element

### Steps to reproduce the issue

1. I create a nameless card with an input number
2. I move the cursor with the mouse
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2021.5.5

### In which browser are you experiencing the issue with?

Chrome and Firefox - latest versions

### Which operating system are you using to run this browser?

Windows

**Comment by spacegaier** [comment] 2021-05-26 19:24
Duplicate of https://github.com/home-assistant/frontend/issues/7560

**Closed by spacegaier** 2021-05-26 19:24 UTC
Labels: bug

**Comment by WRoss7** [comment] 2021-05-26 20:08
oops I hadn't found it
