### ISSUE TITLE
Deprecate all HTML imports

### ISSUE THREAD

**Issue by balloob** [home-assistant/frontend#5014] opened 2020-02-28 01:23 UTC
## The request

We should remove HTML import support from both backend and frontend. It's not part of any browser anymore. 

We should first start with logging errors when it's used. Remove it in a couple of months.

**Comment by bramkragten** [comment] 2020-07-14 09:24
Duplicate of https://github.com/home-assistant/frontend/issues/6028

**Closed by bramkragten** 2020-07-14 09:24 UTC
Labels: feature request, p1
