### ISSUE TITLE
Tag Automations Disappear After Saving

### ISSUE THREAD

**Issue by bluemonkeydev** [home-assistant/frontend#20448] opened 2024-04-06 15:51 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The first time you create an automation for a tag, it does save & the automation will work "forever" that way. However, if you edit the automation, it shows nothing is saved, even if you choose to edit the YAML. The automation are always blank and if you create a new one, it will still use the old (original) automation when the Tag was created.

I have tested this in Firefox & in the app, it does the same thing.

Creating Tag:
![Screenshot_3](https://github.com/home-assistant/frontend/assets/1980947/9922fc39-884f-41dc-9d89-de14978bb724)

Editing Tag after Saved: (missing automation)
![Screenshot_4](https://github.com/home-assistant/frontend/assets/1980947/9d0e6d5a-bff3-4b59-8db1-c4db1f995a29)

Editing Tag YAML after saved: (also missing automation)
![Screenshot_5](https://github.com/home-assistant/frontend/assets/1980947/87974ba5-524a-44fe-be10-dda2eb1ea75c)

### Describe the behavior you expected

When you go back and edit the automation, it shows you the current automation.

### Steps to reproduce the issue

1. Create a new Tag
2. Add an automation "Then" action
3. Save
4. Now go back and edit the automation
...

### What version of Home Assistant Core has the issue?

2024.4.0

### In which browser are you experiencing the issue with?

Firefox 124.0.2 (64-bit) / plus mobile app

### Which operating system are you using to run this browser?

Windows 11 / Android phone

**Comment by karwosts** [comment] 2024-04-07 01:09
I think this is a misunderstanding of how the tag page works. When you click the button to create an automation from tag page, it always just creates a new empty automation with that trigger. 

If you save that automation, it is saved/visible if you go to automations, but you can't navigate back to it or view it from the tag page where it was first created.

**Comment by bluemonkeydev** [comment] 2024-04-07 13:40
Ahhh. You are correct, that was not clear to me. Thank you!

**Comment by karwosts** [comment] 2024-04-21 14:00
I'll close this as it is not a bug, though I do think it would be good if we could add more discoverability from tags to existing automations, as this is a frequent point of confusion.

**Closed by karwosts** 2024-04-21 14:00 UTC
