### ISSUE TITLE
Visibility option only functional on top level card, not on nested card

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#21009] opened 2024-06-06 12:14 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

as title, the new (2024.6) visibility option for cards does not work when doing below snippet

the card with the visibility option set is visible always.

using that exact configuration as separate cards works as expected

### Describe the behavior you expected

have the visibility option work on nested card

### Steps to reproduce the issue

1. see yaml
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.0

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

sonoma 14.5

### Problem-relevant frontend configuration

```yaml
    - type: vertical-stack
      cards:
        - type: entities
          entities:
            - input_boolean.test_2

        - type: conditional
          conditions:
            - condition: state
              entity: input_boolean.test_2
              state: 'on'
          card:
            type: entities
            title: Type Conditional
            entities:
              - light.zitkamer

        - type: entities
          title: Visibility
          visibility:
            - condition: state
              entity: input_boolean.test_2
              state: 'off'
          entities:
            - light.zitkamer
```

**Comment by piitaya** [comment] 2024-06-07 08:36
Yeah, it's not supported yet on nested cards. We changed the way we load cards in views and sections but not in nested card. It will be supported with this PR : https://github.com/home-assistant/frontend/pull/21018.

Also, we need to add visibility support in the UI for stack cards (grid, vertical, horizontal).

**Comment by Mariusthvdb** [comment] 2024-06-07 09:03
thx Paul, appreciated.
should we close then? or wait until #21018 is merged

**Comment by piitaya** [comment] 2024-06-07 11:02
You can keep it open. It will be closed when the PR is merged.

**Closed** 2024-06-12 11:38 UTC

**Comment by jdesai61** [comment] 2024-08-12 14:53
This is marked as closed, but I just got 2024.8 installed and I still can't add visibility to nested cards. When will this be released? Thanks

**Comment by piitaya** [comment] 2024-08-12 18:02
The feature is available using YAML but not in the UI editor yet.

**Comment by jdesai61** [comment] 2024-08-16 00:42
Thanks - tried it in YAML and it works

**Comment by rutalreja-deloitte** [comment] 2024-08-18 22:34
could u show an example yaml I cant get it to work inside a stack card

**Comment by kernel610** [comment] 2024-08-25 19:11
> could u show an example yaml I cant get it to work inside a stack card Here is mine:
> 
> ```
> - type: horizontal-stack
>   cards:
>     - type: glance
>       visibility:
>         - condition: state
>           entity: binary_sensor.patio_door_sensor_opening
>           state: Open
>       entities:
>         - binary_sensor.patio_door_sensor_opening
>       state_color: true
> ```

@rutalreja-deloitte This looks correct. Did you make sure you exited edit mode and test the visibility conditions both with the patio door sensor open and closed? It will not apply the visibility in the dashboard edit mode so it can be confusing that the feature isn't working.

If you tried that and it's still not working, make sure your conditions are correct. The binary_sensor may be returning an on/off instead Open/Closed.

**Comment by tkmoney01** [comment] 2024-10-19 12:31
@rutalreja-deloitte did you ever get this working? I have the same issue on 2024.10.3. I know the code works because the whole card is hidden if applied at the top level of the card. "Visibility" doesn't seem to work to hide individual entities within the horizontal stack card.

**Comment by Mariusthvdb** [comment] 2024-10-19 13:43
the yaml I added in the opening post works just fine.

please check what you did and compare with that?

**Comment by tkmoney01** [comment] 2024-10-19 15:21
> @rutalreja-deloitte did you ever get this working? I have the same issue on 2024.10.3. I know the code works because the whole card is hidden if applied at the top level of the card. "Visibility" doesn't seem to work to hide individual entities within the horizontal stack card.

I was able to get it working. I thought I was on 2024.10.3 but was actually on an older version. I upgraded and the yaml appears to be working as intended now!
