### ISSUE TITLE
Overview dashboard not working after 2022.12.7 upgrade

### ISSUE THREAD

**Issue by Birillo71** [home-assistant/frontend#14862] opened 2022-12-22 10:17 UTC
### The problem

Hi,

I use the standard Overview dashboard without customisations. 
Since I upgraded to version 2022.12.7 I get the following error:

`Error loading the view strategy:

TypeError: Cannot read properties of undefined (reading 'area_id')`

I cannot find anything useful in the log files.
My other customised dashboards are working without any issues.

Can you please help?

### What version of Home Assistant Core has the issue?

2022-12-8

### What was the last working version of Home Assistant Core?

2022-12-6

### What type of installation are you running?

Home Assistant OS

**Comment by Osjuh** [comment] 2022-12-24 22:05
+1 - Same feedback - Nothing shown in Logs.

**Comment by karwosts** [comment] 2022-12-25 16:33
What do you mean you "get" an error. Is it in the browser console, or the HA log?

If its in the browser, if you look in the developer console, can you find more information? Sometimes you can expand an error to see the full call stack, any such information may be helpful.

**Comment by Birillo71** [comment] 2022-12-25 18:21
This is what I see:
![Screenshot 2022-12-25 at 18 20 17 png](https://user-images.githubusercontent.com/25371685/209478470-e5c1c185-acc5-480e-9067-83b8828dd8f1.png)

**Comment by Osjuh** [comment] 2022-12-25 21:49
Merry Christmas - See the printscreens I have been able to gather from my home assistant.
<img width="535" alt="Screenshot 2022-12-25 at 22 47 57" src="https://user-images.githubusercontent.com/70666523/209482765-6b57b425-8096-45fe-93d7-7c3a8437f800.png">
<img width="913" alt="Screenshot 2022-12-25 at 22 48 19" src="https://user-images.githubusercontent.com/70666523/209482768-7f0c1382-a851-4ebb-b9ea-1bb29bf092b8.png">

**Comment by shawnhaywood** [comment] 2022-12-28 18:13
Same issue here. Tracking thread.

**Comment by glnces** [comment] 2022-12-28 18:15
Same error on my dashboard (auto-provisioned as well).

**Comment by WakeUp911** [comment] 2023-01-02 19:04
Same issue here.

**Comment by Birillo71** [comment] 2023-01-03 11:22
Hi, I have upgraded to version 2022.12.9 but still the same.
Is there any news about this error, please?
Do you think it can be a consequence of the fact that some entities do not have a unique_id defined?
If it is the case is there a way to check which are those entities?

**Comment by karwosts** [comment] 2023-01-03 16:35
Wish I had some better advice, without reproducing this in a development environment it is difficult to isolate the reason. 

All I can suggest is someone who is having this issue do some more work to try to narrow down the issue more. That would either involve:
- setting up a development environment and restoring your config there, to be able to isolate the real line number of the failure, - or, maybe make a backup and start removing devices until you figure out which device is having the issue. 

Thats the way I could see to make progress here.

**Comment by Osjuh** [comment] 2023-01-03 19:28
Thank you @karwosts ...

This line have helped me resolve my issue in a test environment and then in production: 

- maybe make a backup and start removing devices until you figure out which device is having the issue.

 I've managed to get it fixed by removing the Browser-Mod intergration (Not HACS add-on) and re-add the intergration. this gave me some work, as I had to reconfigure all my screens and automations I had with the Browser-Mod.

**Comment by glnces** [comment] 2023-01-03 20:56
> Thank you @karwosts ...
> 
> This line have helped me resolve my issue in a test environment and then in production:
> 
> * maybe make a backup and start removing devices until you figure out which device is having the issue.
> 
> I've managed to get it fixed by removing the Browser-Mod intergration (Not HACS add-on) and re-add the intergration. this gave me some work, as I had to reconfigure all my screens and automations I had with the Browser-Mod.

Confused by this. Isn't the only way to add the Browser-Mod integration through HACS?

**Closed** 2023-01-04 10:29 UTC
