### ISSUE TITLE
Status column is cut from "Entities" (URL /config/entities)

### ISSUE THREAD

**Issue by fcastilloec** [home-assistant/frontend#22240] opened 2024-10-04 17:40 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The header for the "Status" column under the "Devices & services > Entities" is always cut. You can't see the whole word. I've tried it on Firefox, Chrome, and Edge, they all have the same problem.
**Firefox**
![Screenshot from 2024-10-04 12-27-33](https://github.com/user-attachments/assets/0a9db255-1c19-4d89-b9cb-f0a3231a0cd6)
**Edge**
![Screenshot from 2024-10-04 12-53-32](https://github.com/user-attachments/assets/30ffa2e5-386f-4a87-8e31-60c18f02df28)

It doesn't matter if the window is maximized or not, the same issue is shown. I thought that resizing the columns could fix it, but columns are not resizable.

### Describe the behavior you expected

I expected to see the whole text "Status" on the column

### Steps to reproduce the issue

1. Go to Settings > Devices & services > Entities
2. See the "Status" column text cut

### What version of Home Assistant Core has the issue?

2024.10.0

### What was the last working version of Home Assistant Core?

2024.10.0

### In which browser are you experiencing the issue with?

Firefox 131.0, Chrome 129.0.6668.89, Edge 129.0.2792.79

### Which operating system are you using to run this browser?

Windows 11, Ubuntu 22.04

**Comment by karwosts** [comment] 2024-10-04 17:47
Duplicate of #15666

**Closed by karwosts** 2024-10-04 17:47 UTC
