### ISSUE TITLE
Users page should include the username

### ISSUE THREAD

**Issue by gerardo15** [home-assistant/frontend#7628] opened 2020-11-09 08:19 UTC
Hey!

I just spent like 40 minutes trying to figure out why i got invalid username/password when trying to login with my wifes account, even after resetting the password.. just to realize that nowhere in the frontend i can see my wifes username.. i had to config/.storage/auth to see the username was different... i believe it should be included just below name in the following screenshot, and of course be able to change that username

related posts : https://community.home-assistant.io/t/how-to-view-a-users-username/105461

![image](https://user-images.githubusercontent.com/12488663/98516178-746c5080-226c-11eb-984f-bf9049b59a7a.png)

**Comment by iantrich** [comment] 2020-11-11 19:48
similar enough to be duplicate of https://github.com/home-assistant/frontend/issues/3907

**Closed by iantrich** 2020-11-11 19:48 UTC
Labels: bug
