### ISSUE TITLE
Add-ons Module not Loading

### ISSUE THREAD

**Issue by diegocade1** [home-assistant/frontend#16885] opened 2023-06-12 17:43 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since last update, when navigating to Settings->Add-ons page, the first time you select the option, it opens fine, but then if you go to another option then go back to Add-ons, the page cant load and stays empty:

![image](https://github.com/home-assistant/frontend/assets/46531987/455452c5-0196-48e6-b844-8920bbd855d5)

You have to reload the page for it to show the options:

![image](https://github.com/home-assistant/frontend/assets/46531987/f8901825-1cf5-4ce8-a132-efbccbffa8b5)

Happens just in firefox, downloaded opera gx and it works as intended.

### Describe the behavior you expected

For the page to load normally and show the options:

![image](https://github.com/home-assistant/frontend/assets/46531987/af6aa9fd-2180-4027-9d25-dc4b4a43006c)

### Steps to reproduce the issue

1. Navigating to Settings->Add-ons page
2. go to another option, (example to Dashboard)
3. Go back to Navigating to Settings->Add-ons page again.
4. Page doesn't load.

### What version of Home Assistant Core has the issue?

2023.6.1

### What was the last working version of Home Assistant Core?

2023.5.X

### In which browser are you experiencing the issue with?

Firefox 114.0.1 (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
None
```

### Problem-relevant frontend configuration

```yaml
None
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

None

**Comment by MisterT87** [comment] 2023-06-12 18:34
#16859 
have the same issue

**Comment by johspa933** [comment] 2023-06-14 11:28
Same issue here...

**Comment by johspa933** [comment] 2023-06-14 11:29
I have this issue as well.

**Comment by gourdo1** [comment] 2023-06-14 20:56
Same issue here on Firefox 113 and 114.0.1 on two HA instances both running 2023.06.1. For what it's worth, it appears to work fine in Chrome.

**Comment by tgost** [comment] 2023-06-17 21:17
I have the same behaviour for Add-ons option and System -> Backups too.

**Comment by gourdo1** [comment] 2023-06-17 23:10
Confirmed, same here.

**Comment by gourdo1** [comment] 2023-06-17 23:18
FWIW, this seems to be a duplicate of https://github.com/home-assistant/frontend/issues/16859...

**Comment by IanBJ23** [comment] 2023-06-26 16:32
I have the same issue. Display of Settings/Add-ons tab/page in Firefox browser works the 1st time but on next attempt I just get an blank 'data' pane with the rotating "refreshing" circle for ages (>30mins).
If I do use the Firefox "Reload Current Page" button then the HA tab reverts to the Login page, not to "Add-ons" refreshed.
I'm on Home Assistant 2023.6.2   Supervisor 2023.06.2   Operating System 10.3  Frontend 20230608.0 running on a new Odroid M1 with HA pre-installed, then updated, and I have Add-ons Z-Wave-JS and Studio Code Server installed, plus various Z-Wave devices found, and others.
Firefox 114.0.2 (64-bit) is on my WIn 10 laptop, fully updated.

Tried in Microsoft Edge and the issue does NOT appear.

**Comment by karwosts** [comment] 2023-06-30 16:59
Closing as duplicate of #16859

**Closed by karwosts** 2023-06-30 16:59 UTC

**Comment by lordvalium** [comment] 2023-08-07 18:58
For me Addons does not even exist :)
<img width="1299" alt="Bildschirmfoto 2023-08-07 um 20 55 23" src="https://github.com/home-assistant/frontend/assets/2970225/5acce3d8-f204-49eb-a069-6bc7c4492ac7">

**Comment by renemrobinson** [comment] 2023-11-15 21:19
Mine hangs with a blank screen. I tried it in Safari and It pops up the message "you don't have any add-ons installed yet" with a link. Google for the loss....I wasted 3 days over this crap.
