### ISSUE TITLE
2023.6 Home Assistant UI reload Icon appearing

### ISSUE THREAD

**Issue by cloudbr34k84** [home-assistant/frontend#16854] opened 2023-06-10 07:07 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the update of 2023.6 my UI gets stuck only on mobile. I noticed that the home assistant cloud page is now saying loading all the time. When I click it I just the blue reload icon showing and then I get this screen when I go to my dashboard

### Describe the behavior you expected

The page should reload and not cause issues

### Steps to reproduce the issue

1.go to home assistant page on mobile
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.1

### What was the last working version of Home Assistant Core?

Home Assistant 2023.5

### In which browser are you experiencing the issue with?

Mobile App

### Additional information

![Screenshot_20230610-112659](https://github.com/home-assistant/frontend/assets/58960644/0e3b77cf-9e57-4e93-a3f2-f7bf3609fad7)
![Screenshot_20230610-112751](https://github.com/home-assistant/frontend/assets/58960644/71778efb-2357-4969-abb3-b7f985a50ed1)
![Screenshot_20230608-205240](https://github.com/home-assistant/frontend/assets/58960644/9929ad38-f371-444d-98bf-b9bc9dd3a955)
![Screenshot_20230610-112627](https://github.com/home-assistant/frontend/assets/58960644/d1339b85-e3e4-4c54-b6c4-4acb1d2673be)
https://github.com/home-assistant/frontend/assets/58960644/778348d6-5416-4c7d-9f12-560d2aaadbf5

**Comment by AshIzat** [comment] 2023-06-11 23:38
I'm getting exactly the same issue. 
Can reproduce in both the home assistant android app, and in Firefox for android.

Can't reproduce on desktop.

All was working fine until I upgraded to 2023.6.1 (from 2023.5.x)

**Comment by formatBCE** [comment] 2023-06-14 01:01
Same.

**Comment by shlomki** [comment] 2023-06-14 18:23
Exact same issue here as well

**Comment by tomcatxx** [comment] 2023-06-14 18:33
same issue here.

**Comment by smarthomefamilyverrips** [comment] 2023-06-14 19:42
Same +1

**Comment by zagnuts** [comment] 2023-06-14 22:04
Also same. It usually fixes itself, but killing the app and restarting it generally fixes it immediately, so could be a low memory problem (Android S21FE). Also started to see it with a wall mounted iPad though, so perhaps there's a memory leak. Just in case it's an issue with my sd card I'm going to replace it.

**Comment by craigrouse** [comment] 2023-06-14 22:07
> Also same. It usually fixes itself, but killing the app and restarting it generally fixes it immediately, so could be a low memory problem (Android S21FE). Also started to see it with a wall mounted iPad though, so perhaps there's a memory leak. Just in case it's an issue with my sd card I'm going to replace it.

I can say with confidence that it's not a low memory issue. It started as soon as I updated to 2023.6, and I've never seen this screen before. I have a pretty beefy android device with a boatload of memory and onboard storage. I wouldn't bother replacing your SD card.

**Comment by cloudbr34k84** [comment] 2023-06-14 22:34
It's not appearing on my wife's Galaxy s23. And yeah appeared straight away after 2023.1

**Comment by eleven38am** [comment] 2023-06-15 02:14
Happening with android app, Chrome on s20 and Chromium on raspbian.

So far fine on Firefox s20 and linux laptop, but have not tested for a long period.

Version 2023.6.1

**Comment by zagnuts** [comment] 2023-06-15 03:20
So the 'hail mary' of replacing the SD card didn't make any difference - as expected. It was a long shot. Have now uninstalled and reinstalled the app, and rebooted the 'phone to see if that makes any difference - will update.

hassio:
Raspberry pi 3b+
Home Assistant 2023.6.1
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0

Client
Android (Samsung SM-G990E ie S21FE 5G)
App - 2023.6.0-full
Memory: 5GB of 8GB used

**Comment by ohadlevy** [comment] 2023-06-15 07:30
same here, i did notice the main navigation (e.g. moving from one dashboard to another, or settings etc) sometimes works if the reload btn is visible, but once disconnected, the only way is to kill and restart the mobile app.

**Comment by cloudbr34k84** [comment] 2023-06-15 07:52
Saw this on the Facebook group.  Might be related somehow

https://www.facebook.com/groups/HomeAssistant/permalink/3523091541295524/?mibextid=Nif5oz

**Comment by cloudbr34k84** [comment] 2023-06-15 10:08
Issue seems to be fixed with the latest update

**Comment by tomcatxx** [comment] 2023-06-15 10:12
For me not. I'm now on 2023.6.2 and have the same Problem.

**Comment by cloudbr34k84** [comment] 2023-06-15 10:23
> For me not. I'm now on 2023.6.2 and have the same Problem.

Ahhh bugger.. 
Anything in the logs??

**Comment by DaveP317** [comment] 2023-06-15 11:12
It just happened to me with 2023.6.2. Here's the log entry that seems
relevant:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:53
Integration: Home Assistant WebSocket API (documentation
<https://www.home-assistant.io/integrations/websocket_api>, issues
<https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22>
)
First occurred: 7:09:21 AM (7 occurrences)
Last logged: 7:09:29 AM

   - [546865831824] David Pullen from 192.168.2.7 (Mozilla/5.0 (Linux;
   Android 10; SM-N960U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML,
   like Gecko) Version/4.0 Chrome/114.0.5735.60 Mobile Safari/537.36 Home
   Assistant/2023.6.0-10170 (Android 10; SM-N960U)): Client unable to keep up
   with pending messages. Reached 4096 pending messages. The system's load is
   too high or an integration is misbehaving; Last message was:
   {"id":4972,"type":"result","success":true,"result":null}

**Comment by tomcatxx** [comment] 2023-06-15 16:22
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:53
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 11:58:02 (53 occurrences)
Last logged: 18:21:15

[140094375967248] Tom from 192.168.5.2 (Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; Pixel 6)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":5768,"type":"event","event":{"type":"current","notifications":{}}}
[140094635142608] Tom from 192.168.5.2 (Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; Pixel 6)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":4035,"type":"event","event":{"type":"current","notifications":{}}}
[140094373877072] Tom from 192.168.5.2 (Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; Pixel 6)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":3724,"type":"result","success":true,"result":null}
[140094526189520] Tom from 192.168.5.2 (Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; Pixel 6)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":4860,"type":"result","success":true,"result":null}
[140094516935184] Tom from 192.168.5.2 (Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; Pixel 6)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":4457,"type":"result","success":true,"result":null}
```
Thats what i find in the logs

**Comment by zagnuts** [comment] 2023-06-15 23:35
I'm wondering if when the device 'goes to sleep', any status changes are getting queued up until it hits that 4096 byte buffer/limit. Maybe in the past this was ignored, but now the system is expecting some sort of acknowledgment from the client that updates (such as temp sensor changes) have been received?

**Comment by zagnuts** [comment] 2023-06-16 01:30
So, found that if I kept playing with the device eventually the error sometimes clears - my theory is it eventually it might catch up with the messages waiting in the queue. The error returns again after the 'phone has been left alone for a while. I changed background access for the app to run in the background, but still have the issue. The iPad was already set to enable background access.

**Comment by brooksben11** [comment] 2023-06-16 14:35
Same issue for me...

**Comment by zagnuts** [comment] 2023-06-17 03:31
OK - update. Went to Developer Tools and listened to "*". Found that there were an unusual amount of events being fired by one of my esphome sensors. I had recently physically disconnected a door sensor switch, and it was rapidly sending on/off events. Normal average for the entire house would be maybe 100 events a minute, but because of the faulty sensor it was more than 300 events per minute. Could be pure coincidence, but since I've fixed that, the 'reload ui' message appears far less frequently. Still happens though.

So the good news is I think we may have found the cause - my theory is events queue up when a device running the HA client app is 'asleep'. When the queue of events waiting to be sent to the client hits a set limit of 4096 (4 kibibits) events the client is toast when it comes back online. Not sure if this is only being seen now by me because I have more sensors than I used to, or if it's a change to the host/client app where it now tracks if a client has received an event. For now if you are seeing this error a lot I'd suggest checking if you have excessive events happening in your environment like I did, and if so try to reduce them. Assuming this is the cause (and to confirm perhaps people seeing this problem could go into developer tools and record the number of events per minute they have), then medium/long term would be seeing if we can change the host/client so there is either an option to increase that cache or have it drop or trim it somehow.

**Comment by craigrouse** [comment] 2023-06-17 06:59
The fact is that this only started happening with the latest HA update. Something must have changed. My device setup didn't change at all, but I saw this issue immediately after upgrading to .6.

**Comment by shlomki** [comment] 2023-06-17 07:04
@craigrouse is 100% correct. In fact, I went back to 2023.05.4 because of my wife complaining about this happening constantly and basically rendered HA unusable. It has been running fine since the downgrade, and didn't happen again.
So this is definitely a 2023.6 issue.

**Comment by zagnuts** [comment] 2023-06-17 07:16
Absolutely this seems to have only recently treated its ugly head, but to reduce the frequency for the short term just suggesting checking if there is something causing excessive events... not a fix but it's helping me a little.

**Comment by zagnuts** [comment] 2023-06-18 06:43
May be unrelated, but I'm seeing a lot of "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py" error messages in the log as well. Wonder if our issue is related to the update to Python 3.11 that happened in this release......

> TimeoutError: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
resp = conn.urlopen(
^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 798, in urlopen
retries = retries.increment(
^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
raise six.reraise(type(error), error, _stacktrace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
raise value
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 714, in urlopen
httplib_response = self._make_request(
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
raise ReadTimeoutError(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by JohnDepon** [comment] 2023-06-18 11:03
Same issue here, but not on mobile (I haven't tested) but on desktop.

On windows 10 (multiple computers), with Home Assistant Desktop (electron app), or custom made electron app (nativefier), or even with Chrome itself, when left idle for many hours (eg during night sleep) it will show what the OP posted.
Cannot recover until app restart.

The issue started on 2023.06 and the last update hasn't resolved the issue for me.

**Comment by JohnDepon** [comment] 2023-06-18 11:51
> So the good news is I think we may have found the cause - my theory is events queue up when a device running the HA client app is 'asleep'. When the queue of events waiting to be sent to the client hits a set limit of 4096 (4 kibibits) events the client is toast when it comes back online. Not sure if this is only being seen now by me because I have more sensors than I used to, or if it's a change to the host/client app where it now tracks if a client has received an event. For now if you are seeing this error a lot I'd suggest checking if you have excessive events happening in your environment like I did, and if so try to reduce them. Assuming this is the cause (and to confirm perhaps people seeing this problem could go into developer tools and record the number of events per minute they have), then medium/long term would be seeing if we can change the host/client so there is either an option to increase that cache or have it drop or trim it somehow.

This theory appears to have merit. After leaving my PC idle for about half an hour, upon returning I saw the 'Reload UI' screen, which seemed to refreshed on its own a bunch of times and then it actually recovered on its own without any action.
So I guess the queue was smaller and thus it managed to recover from it.

**Comment by smarthomefamilyverrips** [comment] 2023-06-18 13:59
Every times the "reload ui" screen appears at my mobile app I get this error in logs

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:53
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:03:28 (7 occurrences)
Last logged: 16:57:14

[281468804282448] Marco from 192.168.0.75 (Mozilla/5.0 (Linux; Android 13; SM-N986B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.60 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; SM-N986B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":4045,"type":"result","success":true,"result":null}
[281471495495376] Marco from 192.168.0.75 (Mozilla/5.0 (Linux; Android 13; SM-N986B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.60 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; SM-N986B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":9357,"type":"result","success":true,"result":null}
[281469358314512] Marco from 192.168.0.75 (Mozilla/5.0 (Linux; Android 13; SM-N986B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.60 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; SM-N986B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":10676,"type":"result","success":true,"result":null}
[281469349920464] Marco from 192.168.0.75 (Mozilla/5.0 (Linux; Android 13; SM-N986B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.60 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; SM-N986B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":9056,"type":"result","success":true,"result":null}
[281469358119440] Marco from 192.168.0.75 (Mozilla/5.0 (Linux; Android 13; SM-N986B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.60 Mobile Safari/537.36 Home Assistant/2023.6.0-10170 (Android 13; SM-N986B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":7371,"type":"result","success":true,"result":null}

**Comment by brooksben11** [comment] 2023-06-18 17:37
Where specifically are you getting the logs? I definitely am having this specific issue, but I've never been able to find the logger error you all keep seeing.

**Comment by smarthomefamilyverrips** [comment] 2023-06-18 17:49
Setting>System>Logs

**Comment by brooksben11** [comment] 2023-06-18 18:18
Just for HA Core? Do I need my default logger setting on something other than 'critical' in my configuration YAML for it to show up?

**Comment by smarthomefamilyverrips** [comment] 2023-06-18 18:30
Yes.... should be minimal be set to "error" or else "warning"

**Comment by pkscout** [comment] 2023-06-18 18:57
I am able to trigger this issue basically on demand.  I have an automation then sends me notifications via the HA persistent notification anytime something updates.  If I manually change one of the booleans to TRUE (indicating there is an update), I get the notification, and then the three Pi4s I have in the house running a chunk of HA interface via kiosk mode in Chromium all go into that loop of trying to reload the UI until Chromium finally throws up an error page asking me to reload the page.  If I reload it, it works fine until I trigger another update notification.  Here's the automation that will crap out the UI every time:
```
alias: Notify on Updates Available
description: ""
trigger:
  - platform: numeric_state
    entity_id: sensor.hacs
    above: 0
  - platform: state
    entity_id:
      - binary_sensor.hdhomerun
      - binary_sensor.hubitat_update
      - update.dvr_dsm_update
      - binary_sensor.home_assistant_update
      - input_boolean.ecowitt2mqtt_release
      - input_boolean.iperf3_image
      - input_boolean.mariadb_image
      - input_boolean.mosquitto_image
      - input_boolean.nextpvr_image
      - input_boolean.php_myadmin_release
      - update.johnson_udm_se
      - update.u6_lite_br
      - update.u6_lite_lr
      - update.u6_lite_st
      - update.usw_flex_mini
      - input_boolean.espresence_release
    to: "on"
condition: []
action:
  - service: persistent_notification.create
    data:
      title: Updates Available
      message: "{{ trigger.to_state.name }}"
mode: queued
```

**Comment by sodre90** [comment] 2023-06-19 09:14
> @craigrouse is 100% correct. In fact, I went back to 2023.05.4 because of my wife complaining about this happening constantly and basically rendered HA unusable. It has been running fine since the downgrade, and didn't happen again. So this is definitely a 2023.6 issue.

Same situation here, my wife was also complaining about this, and I restored the 2023.05 backup, and it is fine since. 

Error is the same as for the others: 
`* [547314008336] Péter Erdős from 192.168.1.1 (Mozilla/5.0 (Linux; Android 13; SM-S918B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; SM-S918B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":3930,"type":"event","event":{"type":"current","notifications":{}}}
* [547181010384] Péter Erdős from 192.168.1.1 (Mozilla/5.0 (Linux; Android 13; SM-S918B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; SM-S918B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":3526,"type":"result","success":true,"result":null}
* [546318330704] Péter Erdős from 192.168.1.1 (Mozilla/5.0 (Linux; Android 13; SM-S918B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; SM-S918B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":3141,"type":"result","success":true,"result":null}
* [547104135056] Péter Erdős from 192.168.1.1 (Mozilla/5.0 (Linux; Android 13; SM-S918B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; SM-S918B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":2742,"type":"event","event":{"type":"current","notifications":{}}}
* [546913263056] Péter Erdős from 192.168.1.1 (Mozilla/5.0 (Linux; Android 13; SM-S918B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36 Home Assistant/2023.3.0-3260 (Android 13; SM-S918B)): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":2304,"type":"result","success":true,"result":null}`

**Comment by X4V1** [comment] 2023-06-20 18:05
The problem is still there after updating to 2023.6.2 for me too.

**Comment by HarlemSquirrel** [comment] 2023-06-21 11:52
I haven't had this problem in a few days now.

**Comment by DaveP317** [comment] 2023-06-21 12:40
I can confirm that 2023.6.3 does not fix the issue.

**Comment by tomcatxx** [comment] 2023-06-21 13:57
For me it looks like the responsible Devs not even noticed that issue 😔

**Comment by pvprodk** [comment] 2023-06-21 19:30
Same issue here on 2023.6.2 (was also on the previous 2023.6.X versions)

`Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/http.py:53
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:42:39 (45 occurrences)
Last logged: 21:20:22

[140401299491408] PVPro from 192.168.177.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":4845,"type":"result","success":true,"result":null}
[140401048361808] PVPro from 192.168.177.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":3031,"type":"result","success":true,"result":null}
[140401064882064] PVPro from 192.168.177.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":4627,"type":"result","success":true,"result":null}
[140401009536912] PVPro from 192.168.177.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":3251,"type":"result","success":true,"result":null}
[140400988293200] PVPro from 192.168.177.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36): Client unable to keep up with pending messages. Reached 4096 pending messages. The system's load is too high or an integration is misbehaving; Last message was: {"id":4804,"type":"result","success":true,"result":null}`

**Comment by zagnuts** [comment] 2023-06-22 02:00
So, dug around the code and found the error message in ([core](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132)/[homeassistant](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132/homeassistant)/[components](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132/homeassistant/components)/[websocket_api](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132/homeassistant/components/websocket_api)/http.py). I'm not a huge python person but the code seems to imply that if the client is not active then it should not try to send messages to it, but if it is then it queues them up. My knee-jerk guess is something has changed where the test to check if the client is accepting messages (eg is asleep) is not working. The 4096 is set in "MAX_PENDING_MSG" in [core](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132)/[homeassistant](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132/homeassistant)/[components](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132/homeassistant/components)/[websocket_api](https://github.com/home-assistant/core/tree/90f5b1c323102840b6dc553ae5d59cfc70715132/homeassistant/components/websocket_api)/const.py specifically:

> DOMAIN: Final = "websocket_api"
URL: Final = "/api/websocket"
PENDING_MSG_PEAK: Final = 1024
PENDING_MSG_PEAK_TIME: Final = 5
MAX_PENDING_MSG: Final = 4096

Could always edit that to increase the limit, if you're feeling brave. Take a full backup first, and if you break HA don't blame me though! ;-)

Also found the issue appears to also be mentioned at https://github.com/home-assistant/core/issues/91400 and https://github.com/home-assistant/core/issues/90281

**Comment by DaveP317** [comment] 2023-06-22 06:21
This is interesting; one of the updates to 2023.6 was to a newer version of
python with performance improvements, right?

Could it be that .5 and earlier couldn't hit this limit due to lower python
performance, and now it can hit this limit?

The solution may be more complex than just increasing the message limit.
There may need to be adjustments to how messages are generated, or internal
throttling, etc.

**Comment by shlomki** [comment] 2023-06-22 06:29
I believe you're looking in the wrong place.
This limit was always there. Something else changed that made HA hit this limit much more often than before.

**Comment by zagnuts** [comment] 2023-06-22 06:59
Agree absolutely that something has changed - just noting that potentially some people could try a temporary 'hack' to increase the buffer to then reduce the number of errors being experienced. I'm rarely seeing the error now that I have around 1k events per minute, so if you have five times that then maybe increasing the buffer 5 times might help. It would never be a permanent fix though. I also suspect the new version of Python may have contributed to the problem - like I say the code seems to indicate that if the client does not respond then it should not add events to the queue, but this does not seem to be happening. From a more encouraging aspect, the fact that there are a number of issues raised makes it more likely this will be hunted down and resolved.

**Comment by hapklaar** [comment] 2023-06-23 09:26
Not sure if this is still helpful, but just want to report this problem also occurs multiple times a day on my iOS dashboard via HA app, and also on Android (Flip4) HA app. Running HAOS 10.3 (2023.6.2)

**Comment by DaveP317** [comment] 2023-06-24 15:43
I updated HA core to 2023.6.3 this morning, and I haven't seen the issue
since...

**Comment by hapklaar** [comment] 2023-06-24 15:52
> I updated HA core to 2023.6.3 this morning, and I haven't seen the issue since...

same here

**Comment by DaveP317** [comment] 2023-06-24 16:13
I saw the message pop up, but then it recovered on its own. I didn't have
to kill and restart the app. That's an improvement...

**Comment by DaveP317** [comment] 2023-06-24 16:15
It just happened again and did not recover. Oh well, still an issue...

**Comment by pkscout** [comment] 2023-06-24 16:28
I'm cautiously optimistic that 2023.06.03 helped.  The script I mentioned in [this comment](https://github.com/home-assistant/frontend/issues/16854#issuecomment-1596237287) no longer triggers the UI on my kiosk mode Raspberry Pis to crap out.  It used to cause them to crap out 100% of the time.  I've re-enabled all the scripts I disabled, so we'll see if this update resolves it for me longer term.

**Comment by tomcatxx** [comment] 2023-06-24 17:46
For me its the same shit as before :-(

**Comment by pkscout** [comment] 2023-06-25 10:12
Well, never mind.  Today the script that always triggers this issue again consistently craps out the UI on the Pis.  I should have known better.  There was nothing in the release notes that gave any hint this was fixed.

**Comment by kmalinich** [comment] 2023-06-25 13:06
I've had this issue for about a week now, not sure on exactly what version(s) I had when it started. It's present only in the android companion app, on my Pixel 7 Pro and my wife's Pixel 6 Pro. Running latest versions on both phones as well as latest version of Home Assistant on bare metal x86.

**Comment by zagnuts** [comment] 2023-06-25 23:23
> EDIT3: About 4 hours after I implemented the changes, it's working well and I've not had the issue reoccur. Dashboard feels snappier too (which makes sense)

Glad to hear it's not just me then! I was also blissfully unaware of my esphome sensor going crazy, so to an extent I guess this was a good thing? Anyhow, like I noted earlier since reducing the number of events happening on my network the dreaded reload UI is hardly ever seen by me now. I needed to get the number down below 300 events per minute - and perhaps that number may vary depending on how powerful the device running HA actually is (in my case a fairly old 3B+). Anyhow, something has definitely changed that has introduced this issue - I still suspect that the test if the remote client is available to accept events is not working, maybe due to the python update. Not everyone will be able to reduce the number of events on their network - so hopefully this will be addressed soon.

**Comment by arief1986** [comment] 2023-06-28 18:26
Thanks for the hints, lowering the number of events worked for me as well (no reload UI warnings anymore). Had to lower it to around 250 events per minute (came down from around 1000-1200 events per minute). HA is running on a powerful Intel Nuc here, so maybe not related to CPU power, but definitely linked to the number of events coming in. Not the final solution, but it works for now.

**Comment by shlomki** [comment] 2023-06-28 19:31
So I went ahead and started the tedious work of looking the the [full list of changes](https://www.home-assistant.io/changelogs/core-2023.6) that were introduced in 2023.06.
Here are some changes that were made around event handling. I'm not at all sure that this is related to this bug, but it's a good place to start looking.

#93431 - @bdraco 
#93532 - @bdraco 
#93579 - @bdraco 
#93611 - @bdraco 
#93602 - @bdraco 
#93823 - @bdraco 
#93859 - @cdce8p 

I'm not a python expert but I'll start looking into the code. Any help would be appreciated.
Perhaps @bdraco and/or @cdce8p would be kind enough to help us understand these changes a little better. Fingers crossed!

**Comment by bdraco** [comment] 2023-06-28 20:22
The PRs you referenced have nothing to do with this issue

Please don't tag people to bring them into issues they were not already participating in. It's not appreciated.

**Comment by bdraco** [comment] 2023-06-28 20:24
Also this issue was likely already fixed by https://github.com/home-assistant/frontend/commit/2b51228665b7247d4b4ea6d3ff0c2919fd30c2a6

**Comment by shlomki** [comment] 2023-06-28 20:35
> Please don't tag people to bring them into issues they were not already participating in. It's not appreciated.

Sorry for that, I didn't intend to be impolite. I'll wait patiently for this change to be merged and test it right away.
Thank you for all of your contributions!

**Comment by bdraco** [comment] 2023-06-28 20:42
The change I mentioned above was already merged and is in todays beta

**Comment by shlomki** [comment] 2023-06-28 21:40
Thanks again! I hadn't noticed. I've installed it now and waiting to see if it fixed the issue.

Guys, I encourage you to do the same and install the beta, we need more testers because this bug happens intermittently.

**Comment by lesleypersyn** [comment] 2023-06-29 18:55
Update to 2023.7.0b0 solves the issue for me!
Thanks!

**Closed** 2023-06-29 19:26 UTC
