### ISSUE TITLE
Statistics card no longer allows individual stat types to be enabled/disabled

### ISSUE THREAD

**Issue by l-mb** [home-assistant/frontend#20058] opened 2024-03-11 15:24 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

With 2024.3, I've noticed that stat types can no longer be individually toggled directly from the dashboard when viewing.

There's only the option to disable/enable the whole entity in the view.

Right now, the only alternative is to edit the dashboard card to either add/remove the stat type entirely, or set up multiple cards, which is not great.

### Describe the behavior you expected

I'd like to retain the ability to disable/individual stat types again, at least as an option, as it was possible in previous releases - and as the "Statistics Graph Card" in the doc actually shows still https://www.home-assistant.io/dashboards/statistics-graph/ .

### Steps to reproduce the issue

1. Create a statistics graph card for an eligible entity.
2. Enable multiple stat types in the card.
3. Note how there's no (min)/(max)/(mean) individual options in the dashboard view then, just for the entity itself.

### What version of Home Assistant Core has the issue?

core-2024.3.0, frontend-20240306.0

### What was the last working version of Home Assistant Core?

core-2024-2.x

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Linux

**Comment by l-mb** [comment] 2024-03-11 15:26
I wanted to add that I checked the release notes and didn't find that this is a documented/intended change.

**Comment by karwosts** [comment] 2024-03-11 15:35
Duplicate of #20029, you can add your comments there. 

It was intended, you can read the discussion behind the change here: https://github.com/home-assistant/frontend/pull/19089

Seems the primary UX designers did not like the original legend with multiple bubbles.

**Closed by karwosts** 2024-03-11 15:35 UTC
