### ISSUE TITLE
Incorrect link in notification related to Home Assistant Cloud

### ISSUE THREAD

**Issue by AlainPeccable** [home-assistant/frontend#19149] opened 2023-12-26 20:25 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The link to our portal in the below notification is pointing to the current page.
![image](https://github.com/home-assistant/frontend/assets/132245586/f64f61ac-388b-4f15-951d-02011b5fdb78)

If you are on the default dashboard it will that page.
Your remote access is now available.
You can manage your connectivity on the [Cloud Panel](http://homessistant.local:8123/config/cloud) or with our [Portal](http://homeassistant.local:8123/lovelace/default_view).

If you are on the config page it will be config page
Your remote access is now available.
You can manage your connectivity on the [Cloud Panel](http://homeassistant.local:8123/config/cloud) or with our [Portal](http://homeassistant.local:8123/config/dashboard).

### Describe the behavior you expected

I suppose the link should be pointing to https://account.nabucasa.com/

### Steps to reproduce the issue

1. Activate Remote Access

### What version of Home Assistant Core has the issue?

2023.12.3

### In which browser are you experiencing the issue with?

Google Chrome 120.0.6099.111

### Which operating system are you using to run this browser?

Microsoft Windows [version 10.0.22000.2538]

**Comment by karwosts** [comment] 2023-12-26 20:35
Wonder if this issue belongs in the NabuCasa repo, that message string is from here.

https://github.com/NabuCasa/hass-nabucasa/blob/d2599d4492979e2d998a735f49699740783574ca/hass_nabucasa/const.py#L55-L58

I can reproduce if I use `persistent_notification.create` with that string, however if I add `https://` then I get a notification with the correct external link:

> You can manage your connectivity on the [Cloud Panel](/config/cloud) or with our [Portal](https://account.nabucasa.com/)

**Comment by karwosts** [comment] 2023-12-28 02:11
I opened a PR in the other repo, will close this issue here seems to be out of scope.

**Closed by karwosts** 2023-12-28 02:11 UTC
