### ISSUE TITLE
Conditional card not working properly with input_text helper

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/frontend#15043] opened 2023-01-08 21:49 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Conditional card does not allow empty inout_text helper as condition. This is necessary condition for inout_text.
![image](https://user-images.githubusercontent.com/57034871/211220903-5922d57d-1e02-4be2-bffc-64acdfb121e8.png)

### Describe the behavior you expected

Allow `state_not: ''` 

### Steps to reproduce the issue

1. create input_text
2. create conditional card and try to set empty input_text as condition
3.
...

### What version of Home Assistant Core has the issue?

2023.1.1

**Comment by karwosts** [comment] 2023-01-08 22:34
Duplicate of #13870

PR #14918 already awaiting merge for this issue.

**Closed** 2023-01-23 19:27 UTC
