### ISSUE TITLE
Boolean inputs in blueprint with default `true` don't toggle correctly

### ISSUE THREAD

**Issue by mdegat01** [home-assistant/frontend#12269] opened 2022-04-08 16:23 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a blueprint with the following input:
```yaml
blueprint:
  input:
    take_backup:
      name: Take backup
      description: Do a partial backup before updating if able
      default: true
      selector:
        boolean:
```
It is presented in the UI like this (which is correct):
![Screen Shot 2022-04-08 at 12 18 06 PM](https://user-images.githubusercontent.com/2037026/162482018-45cc65dc-f462-4a37-9cd2-f31014505f48.png)

The problem is that toggling it to off doesn't seem to do anything. When I toggle it to off I still see this in the yaml:
![Screen Shot 2022-04-08 at 12 20 52 PM](https://user-images.githubusercontent.com/2037026/162482443-56b6b0d5-ba11-4366-b42c-b464b524cdf4.png)
![Screen Shot 2022-04-08 at 12 15 27 PM](https://user-images.githubusercontent.com/2037026/162481905-38e98374-5e63-4bdb-8d17-70941293527c.png)

Note that the boolean inputs in the first screenshot which have `default: false` don't seem to have this issue. Toggling them to `true` sets the yaml correctly, they work fine. It's only an issue with ones that default to `false`.

I will also note that I am displaying the yaml as I found its the easiest way to convey the issue. I can also assure you that if I click "save" on this screen when the toggle is off the automation is still behaving as if "Take backup" is set to `true`.

### Describe the behavior you expected

Toggling this input to `false` should set the value of that input to `false`.

### Steps to reproduce the issue

1. Make a blueprint with a boolean input
2. Add `default: true` to that input
3. Make an automation from that blueprint
4. Toggle that input to `false`
5. Switch to YAML mode and notice that it is still `true`. Or save your automation and run it and notice the automation still acts as if the value was `true`.
...

### What version of Home Assistant Core has the issue?

core-2022.4.1

### In which browser are you experiencing the issue with?

Firefox 98.02

### Which operating system are you using to run this browser?

macOS Monterey (12.2)

**Comment by crkochan** [comment] 2022-07-12 00:10
This bug is still present on the latest stable Home Assistant as of this date.

```
Home Assistant 2022.7.3
Supervisor 2022.07.0
Operating System 8.2
Frontend 20220707.0 - latest
```

**Comment by schiz0phr3ne** [comment] 2022-07-15 14:18
Still present here too.

```
Home Assistant 2022.7.5
Supervisor 2022.07.0
Operating System 8.2
Interface utilisateur : 20220707.1 - latest 
```

**Comment by cymone-smart** [comment] 2022-09-22 18:19
Still present...

Home Assistant 2022.9.6
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest

**Comment by cymone-smart** [comment] 2022-10-11 20:59
Issue is still present

Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Comment by karwosts** [comment] 2022-12-24 16:39
Duplicate of #13206 ?

**Comment by crkochan** [comment] 2022-12-24 16:51
Other way around, actually.

**Comment by karwosts** [comment] 2023-06-28 21:08
I believe this is fixed. If you still see an issue, please leave a comment.

**Closed by karwosts** 2023-06-28 21:08 UTC
