### ISSUE TITLE
Error loading the view strategy: TypeError: t[0] is undefined

### ISSUE THREAD

**Issue by Jo-Highness** [home-assistant/frontend#16645] opened 2023-05-28 11:22 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening the default dashboard (automatically created one) in Firefox the error message "Error loading the view strategy: TypeError: t[0] is undefined" shows up and the dashboard isn't displayed. No further information (also in the log) is provided. Opening the same dashboard in Chrome leads to the error message: "Error loading the view strategy: TypeError: Cannot read properties of undefined (reading 'toUpperCase')".

### Describe the behavior you expected

Dashboard should load.

### Steps to reproduce the issue

1. Do something unknown wrong
2. restart HA with valid config
3. Klick on the dashboard

### What version of Home Assistant Core has the issue?

2023.5.4

### In which browser are you experiencing the issue with?

FF 113.0.2 (64-bit)

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment] 2023-06-24 14:16
Close as duplicate of #16260

**Closed by karwosts** 2023-06-24 14:16 UTC
