### ISSUE TITLE
Choose actions overflow is half hidden

### ISSUE THREAD

**Issue by jesserockz** [home-assistant/frontend#12232] opened 2022-04-05 21:04 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Screenshot from 2022-04-06 09-03-15](https://user-images.githubusercontent.com/3060199/161848718-7c9935a0-4ead-4786-8e8c-f9868b423110.png)

### Describe the behavior you expected

The overflow menu should render correctly

### Steps to reproduce the issue

1. Create a new Automation
2. Create a `Choose` Action
3. Add an action inside the choose action
4. click the overflow button

### What version of Home Assistant Core has the issue?

core-2022.4.0b5

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.75, Firefox 98.0.2, Android Mobile Companion

### Which operating system are you using to run this browser?

Arch Linux, Android 11

**Comment by spacegaier** [comment] 2022-04-05 21:49
Duplicate of https://github.com/home-assistant/frontend/issues/12032 and I already fixed that yesterday 😜.

**Closed by spacegaier** 2022-04-05 21:49 UTC

**Comment by jesserockz** [comment] 2022-04-05 23:53
Thanks @spacegaier
