### ISSUE TITLE
SolarEdge integration with entity current_power is available, but when adding as solar to energy dashboard.

### ISSUE THREAD

**Issue by drstruggle** [home-assistant/frontend#16156] opened 2023-04-13 06:57 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I added the solaredge integration. It has 2 entities: total_energy and current_energy.
I am trying to add the current energy to the energy dashboard (under solar), but it's not available. The total_energy is.

### Describe the behavior you expected

I am expecting the current_energy to be available to create a chart on the energy dashboard (like kwh use, m3 use)

### Steps to reproduce the issue

1. add solaredge integration (cloud)
2. add current_energy to energy dashboard
3.
...

 Home Assistant 2023.4.3 Supervisor 2023.04.0 Operating System 9.5 Frontend-versie: 20230411.0 - latest 

### What version of Home Assistant Core has the issue?

2023.4.3

### What was the last working version of Home Assistant Core?

never worked for me

### In which browser are you experiencing the issue with?

firefox 111.0.1 (64-bits)

### Which operating system are you using to run this browser?

windows 11

### State of relevant entities

```txt
sensor.solaredge_current_power Solaredge zonnepanelen
	0.1550346 	
state_class: measurement
unit_of_measurement: kW
device_class: power
icon: mdi:solar-power
friendly_name: Solaredge zonnepanelen

sensor.solaredge_lifetime_energy solaredge (Lifetime energy)
	907851.0 	
state_class: total
unit_of_measurement: Wh
device_class: energy
icon: mdi:solar-power
friendly_name: solaredge (Lifetime energy)
```

### Javascript errors shown in your browser console/inspector

```txt
Not.
Same occurs in Edge browser.
```

**Comment by karwosts** [comment] 2023-06-28 19:02
Closing as this is working as intended (energy dashboard does not support power sensors). If you want to continue the discussion, feel free to comment and I can reopen it.

**Closed by karwosts** 2023-06-28 19:02 UTC
