### ISSUE TITLE
Entity id changed to required inside the button card

### ISSUE THREAD

**Issue by pdeelen** [home-assistant/frontend#7965] opened 2020-12-14 06:48 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Environment

- Home Assistant release with the issue: 2020.12
- Last working Home Assistant release (if known): 0.118

## Additional information
Here is the currunt documentation for the button card: 
https://www.home-assistant.io/lovelace/button/

The entity field is optional in here. In the latest version of home assistant 2020.12 it is changed to required.

**Comment by spacegaier** [comment] 2020-12-14 09:26
Can you please check again if you really cleared your cache, because there was a merged change that remove that requirement again some days ago: https://github.com/home-assistant/frontend/pull/7909

Duplicate of https://github.com/home-assistant/frontend/issues/7908.

**Comment by pdeelen** [comment] 2020-12-14 09:33
i cleared the cache again, problem still exist.

**Comment by pdeelen** [comment] 2020-12-14 09:33
![Knipsel](https://user-images.githubusercontent.com/47855097/102064650-dda92b80-3df7-11eb-9b30-d93f54ec1387.PNG)

**Comment by spacegaier** [comment] 2020-12-14 09:34
Then please provide your YAML configuration for the card. Is it really a "button" and not an "entity-button" because the latter does require an entity as the name suggests.

**Comment by pdeelen** [comment] 2020-12-14 09:56
Thanks, that's the problem! I was using entity-button instead of button.

**Closed** 2020-12-14 09:56 UTC
Labels: bug
