### ISSUE TITLE
Thermostat Card - can't change temperature since 2023.3.0

### ISSUE THREAD

**Issue by GittyBaer** [home-assistant/frontend#15681] opened 2023-03-02 16:26 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I did the Update to 2023.3.0 today, 
since then I can't change the temperature in the thermostat card with  the orange wheel
Only in the details of the card the temperature can be changed

### Describe the behavior you expected

it should be possible to grab the "wheel" and change the temperature since before ;-)

### Steps to reproduce the issue

1. try to change the temperature in the thermostat card
2.
3.
...

### What version of Home Assistant Core has the issue?

Frontend 20230301.0 - latest

### What was the last working version of Home Assistant Core?

202302.x

**Comment by piitaya** [comment] 2023-03-02 16:29
Hello 👋 It's a duplicate of https://github.com/home-assistant/frontend/issues/15662. It will be fixed in the next patch.

I will closed it when the patch will be available to avoid other issue coming

**Closed** 2023-03-02 18:02 UTC
