### ISSUE TITLE
History Card Text Alignment

### ISSUE THREAD

**Issue by blandry3** [home-assistant/frontend#9748] opened 2021-08-08 17:47 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

See the screenshot below. 

![CB5F989A-56B1-4E35-B79F-FA5FAA8995CC](https://user-images.githubusercontent.com/9467857/128640823-8b10c602-9fec-40d9-b8a2-d153ff2d5275.png)

### Describe the behavior you expected

N/A

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

2021.8.3

### What was the last working version of Home Assistant Core?

Not sure, it’s been there for a while. 

### In which browser are you experiencing the issue with?

Home Assistant App for iOS 2021.8

### Which operating system are you using to run this browser?

iOS 13 & iOS 14

**Comment by spacegaier** [comment] 2021-09-06 10:21
Duplicate of #9852

**Closed by spacegaier** 2021-09-06 10:21 UTC
Labels: bug
