### ISSUE TITLE
New energy UI (2021.8) jumps when changing date

### ISSUE THREAD

**Issue by erd82** [home-assistant/frontend#9781] opened 2021-08-11 19:34 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the new energy UI (2021.8) the graphic jumps when changing the date.

### Describe the behavior you expected

I expect the same graph when changing the date back and forth.

### Steps to reproduce the issue

1. Change the date to yesterday
2. Change back to today
3.
...

### What version of Home Assistant Core has the issue?

2021.8.6

### What was the last working version of Home Assistant Core?

none

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 10

### Additional information

Please watch the attached video.

https://user-images.githubusercontent.com/63564291/129091685-5a403027-c1d4-4f04-b30e-659948920090.mp4

**Comment by bramkragten** [comment] 2021-08-11 19:44
duplicate of https://github.com/home-assistant/frontend/issues/9722

**Closed by bramkragten** 2021-08-11 19:44 UTC
Labels: bug
