### ISSUE TITLE
Settings>System blank page after update to 2022.9.3

### ISSUE THREAD

**Issue by shirou93** [home-assistant/frontend#13737] opened 2022-09-14 08:58 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Settings>System blank page after update to 2022.9.3

### Describe the behavior you expected

Load page system with options.

### Steps to reproduce the issue

1. Open settings 
2. Try open system page
3. Got blank page

### What version of Home Assistant Core has the issue?

2022.9.3

### What was the last working version of Home Assistant Core?

2022.9.2

### In which browser are you experiencing the issue with?

HA Android 2022.8.0-full

### Which operating system are you using to run this browser?

Android 12

**Comment by ludeeus** [comment] 2022-09-14 08:59
Duplicate of https://github.com/home-assistant/frontend/issues/13728

**Closed by ludeeus** 2022-09-14 08:59 UTC
