### ISSUE TITLE
Automation time_pattern is not working well since 0.114

### ISSUE THREAD

**Issue by ruzickav** [home-assistant/frontend#7087] opened 2020-09-21 17:18 UTC
Checklist
- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

The problem
I have found an issue started in 0.114. Automation is not triggered on specified time_pattern when added through GUI. I would like to start automation every hour exactly on half hour (for example 9:30, 10:30, 11:30,....)
![automation](https://user-images.githubusercontent.com/58104955/93798120-70915a00-fc3d-11ea-8cb2-5de6e8f0fcc9.jpg)
Unfortunately it is triggered at whole hour, or never... It is doing this since upgrade to version 0.114. As you can see from logbook...
![logbook](https://user-images.githubusercontent.com/58104955/93798392-e4cbfd80-fc3d-11ea-9d10-adf27a954363.jpg)
 

Expected behavior
Run automation based on time pattern every hour exactly at half hour...

Steps to reproduce
1. add automation through GUI with like this
![automation](https://user-images.githubusercontent.com/58104955/93798506-16dd5f80-fc3e-11ea-813b-e94137e47b5c.jpg)
2. check logs if automation is triggered at desired time 
3. check automations.yaml for saved automation settings

Environment
Now i have version 0.115 installed, but this behavior is in place since 0.114
Google chrome
windows 10 pro

State of relevant entities
Nothing

Problem-relevant configuration
When added through GUI, the yaml setting for automation are like this:
```
- minutes: '30'
    platform: time_pattern
```

To make it working as expected I have to change it manually to:
```
- minutes: 30
    platform: time_pattern
```

Additional information
It has been working as expected since upgrade to 0.114. Start "at time" working well, time_pattern with slash (for example /30) working well

**Comment by spacegaier** [comment] 2020-09-22 19:55
I can confirm the issue and PR is created that fixes it.

**Comment by amelchio** [comment] 2020-09-22 22:07
This was unintended, see https://github.com/home-assistant/core/pull/40470

**Comment by zsarnett** [comment] 2020-09-22 22:14
Closing this as it seems this is a core issue

**Closed by zsarnett** 2020-09-22 22:14 UTC
Labels: bug

**Comment by barberio** [comment] 2021-05-20 08:11
This issue should be re-opened until it is decided how Frontend and Core should interact.
