### ISSUE TITLE
Logs Phone Search bar

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#16294] opened 2023-04-24 16:35 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Why Phone not have Search bar?
![Screenshot_20230424_182624_Home Assistant](https://user-images.githubusercontent.com/42905545/234060058-78e7e4ee-44ac-47c1-b8f3-eaedb4d99c6c.jpg)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

*

**Comment by christophwen** [comment] 2023-05-17 10:02
I'll take a look at it, and if there's no reason why there's no search bar, and it's desired there, I'll implement that.

**Comment by christophwen** [comment] 2023-06-13 16:34
Update, I will continue working on this issue soon. 

Currently I have to setup a supervised instance of HA to work on this issue. Just with the HA Core it is not possible to reproduce the problem, because the search bar is shown on mobile next to the back button: 

| Desktop | Mobile |
| ----| ---- |
|![dev_ha_desktop.png](https://github.com/home-assistant/frontend/assets/43651938/07c742a7-1d4d-4c63-a3e5-c4248cd96120)|![dev_ha_mobile.png](https://github.com/home-assistant/frontend/assets/43651938/524d0b6a-3bc4-4ca6-86b1-8c002a871400)|

On my private HA instance the issue is visible:
| Desktop | Mobile |
| ----| ---- |
|![private_ha_desktop.png](https://github.com/home-assistant/frontend/assets/43651938/a11a5ed1-23e5-40fc-9205-1789b6854315)|![private_ha_mobile.png](https://github.com/home-assistant/frontend/assets/43651938/eb93839d-9da2-4395-9da2-6e8df5abeade)|

**Comment by LTTS1991** [comment] 2023-09-12 05:34
Hey. We've got a search bar now. But for me it's unclickable since I updated Core passed 9.0. It's broken on both mobile and browser mobile.

**Comment by milandzuris** [comment] 2023-09-13 19:48
@christophwen

**Comment by christophwen** [comment] 2023-09-14 05:26
Hello, 
sorry that I am not that responsive as usual but currently I am very busy. I didn't fix the initial issue, that was somebody else. I think it would be better to close this issue and create a new one for the new problem. 

Somebody else with a running supervised HA instance for debugging should look into it, because I have problems with setting it up, and did not get support on Discord.

**Closed** 2023-09-17 18:23 UTC
