### ISSUE TITLE
Energy dashboard no history of predicted energy

### ISSUE THREAD

**Issue by gieljnssns** [home-assistant/frontend#10591] opened 2021-11-10 08:08 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I'm using forecast solar to predict the energy.
On the current day there is a line visible on the dashboard
![Schermafbeelding 2021-11-10 om 09 00 24](https://user-images.githubusercontent.com/17234951/141073310-9f7984c3-58a4-47b3-9bba-8d355ecba306.png)
.
When I go back one day (or more) the line is gon
![Schermafbeelding 2021-11-10 om 09 01 43](https://user-images.githubusercontent.com/17234951/141073502-87dcadb0-0060-442a-bc64-ec7b94e46a78.png)
e

When using a `custom_component` `solcast` the line is visible in the histor
![Schermafbeelding 2021-11-10 om 09 05 15](https://user-images.githubusercontent.com/17234951/141074037-248100b5-623e-4fd2-b26f-438e7ffcf1ea.png)
y

But I would like to use as less as possible `custom_components`

### Describe the behavior you expected

I expect to see the line inn the history

### Steps to reproduce the issue

1. Open energy dashboard
2. Go back in history
3.
...

### What version of Home Assistant Core has the issue?

core-2021.11.2

### In which browser are you experiencing the issue with?

Brave Versie 1.31.88 Chromium: 95.0.4638.69 (Officiële build) (x86_64)
Colibri Versie 1.22.0 (1.22.0)

### Which operating system are you using to run this browser?

MacOS 12.0.1 (21A559)

**Comment by bramkragten** [comment] 2021-11-10 08:13
This would be a future request and not a bug

**Comment by gieljnssns** [comment] 2021-11-10 08:17
I thought it was a bug since with `solcast` the line is visible

**Comment by gieljnssns** [comment] 2021-11-10 08:20
Can I start a discussion and link to this issue?

**Comment by bramkragten** [comment] 2021-11-10 09:25
> I thought it was a bug since with `solcast` the line is visible

That would make it a FR for the forecast.solar integration then?

**Comment by bramkragten** [comment] 2021-11-10 09:26
We request the data from the backend, and show everything we get. This is not a frontend issue, closing.

**Closed by bramkragten** 2021-11-10 09:26 UTC
Labels: bug
