### ISSUE TITLE
Tarif cannot be selected in Energy Utility Meter

### ISSUE THREAD

**Issue by Ric57100** [home-assistant/frontend#14806] opened 2022-12-16 08:30 UTC
### The problem

When creating new Energy Meter with dual tariff (Full UI method), it's not possible to select corresponding tariff. No list of supported tariffs appears.

It still worked in my LAB with version 2022.11.5.

As workaround, I had to restore version 2022.11.5 to be able to add my dual tariff energy meters before applying 2022.12.x again

### What version of Home Assistant Core has the issue?

2022.12.6

### What was the last working version of Home Assistant Core?

sure 2022.11.5, maybe last 2022.11

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

9.4

**Comment by MacVille** [comment] 2022-12-17 23:07
I can confirm that, with the following Version it's not possible to add tariffs to an Utility Meter.
Home Assistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4
Frontend 20221213.0 - latest

My Work-A-Round is to create the Utility Meter on the Config.yaml

**Comment by bramstroker** [comment] 2022-12-18 09:15
+1

**Comment by mriksman** [comment] 2022-12-18 11:21
I was losing my mind. Couldn't work out why I couldn't create a new tariff. Works fine on my other HA installation (2022.6.6), but not on my new one (2022.12.6)

**Comment by karwosts** [comment] 2022-12-18 20:14
Probably duplicate of #14703

**Comment by Ric57100** [comment] 2022-12-19 12:47
> Probably duplicate of #14703

Yes, it seems to be the same

**Closed** 2022-12-20 11:51 UTC
