### ISSUE TITLE
Editing elements on config/energy doesn't 

### ISSUE THREAD

**Issue by reedy** [home-assistant/frontend#17291] opened 2023-07-12 20:28 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you go to `/config/energy` and click edit (the pencil) on any element
![Screenshot 2023-07-12 at 21 15 41](https://github.com/home-assistant/frontend/assets/67615/44f3f7fd-73a9-4b07-96c6-022a9673dcf0)

you are presented with a screen that doesn't have the previously selected sensor selected in `ha-textfield`, so you've got to select it again from the list to be able to edit it

![Screenshot 2023-07-12 at 21 15 47](https://github.com/home-assistant/frontend/assets/67615/c953e56a-2c76-4b28-bd99-1acff4c98fda)

### Describe the behavior you expected

When you go to`/config/energy` and click edit (the pencil) on any element

![Screenshot 2023-07-12 at 21 15 41](https://github.com/home-assistant/frontend/assets/67615/44f3f7fd-73a9-4b07-96c6-022a9673dcf0)

it should be presented as such, with the previously selected sensor shown on the config page preloaded/selected in the `ha-textfield`

![Screenshot 2023-07-12 at 21 15 52](https://github.com/home-assistant/frontend/assets/67615/f9d13e92-4ff8-41ef-9ad8-7dbc6e4f76ae)

### Steps to reproduce the issue

1. Visit `/config/energy`
2. Click the pencil on any energy relating setting (if you have set one up before), else Add one
3. Pick a sensor from the drop down box
4. Click save
5. Click the pencil on the same item again
6. See that the sensor is not selected, the box has been cleared and has to be selected again
...

### What version of Home Assistant Core has the issue?

2023.7.1

### In which browser are you experiencing the issue with?

FF 115.0.2

### Which operating system are you using to run this browser?

macOS 13.4.1

**Comment by karwosts** [comment] 2023-07-12 20:40
Duplicate of #17216

This was just fixed, and the fix will be in the next release with a frontend bump.

**Closed by karwosts** 2023-07-12 20:40 UTC
