### ISSUE TITLE
Labels: Selecting Entities or Devices from the overflow menu does not set the Filter

### ISSUE THREAD

**Issue by NoRi2909** [home-assistant/frontend#22460] opened 2024-10-21 15:03 UTC
#### Describe the issue you are experiencing

When you select either Devices or Entities from the overflow menu for a Label this does not set the Filter to only show matching items.

### Describe the behavior you expected

It does work when doing the same for Automations. There the Filter is set.

### Steps to reproduce the issue

1. Make sure you have labelled some devices and entities
2. Go to Settings > Areas, labels & zones > Labels
3. From the overflow menu for the label from step 1 select either Devices or Entities
4. Compare to the result for Automations

### What version of Home Assistant Core has the issue?

core-2024.10.3

**Comment by karwosts** [comment] 2024-10-21 15:17
Duplicate of #22354, just fixed yesterday.

**Closed by karwosts** 2024-10-21 15:17 UTC
