### ISSUE TITLE
History page, last week not working correct with end of year.

### ISSUE THREAD

**Issue by Claton** [home-assistant/frontend#8058] opened 2020-12-31 15:54 UTC
## The problem

It's Dec. 31st 2020.  clicked on last week in history, date switched to Jan. 20th 2021 to Jan 26th 2021.  Should have been Dec 2020

## Environment

Using Release 2020.12.1 32bit on rpi 4
 
- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): 
- Operating environment (OS/Container/Supervised/Core): 
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by spacegaier** [comment] 2021-01-01 19:52
Duplicate of https://github.com/home-assistant/frontend/issues/7147.

**Closed** 2021-01-01 19:52 UTC
