### ISSUE TITLE
button cards disappeared from dashboard with update with the latest version 2023.4.3

### ISSUE THREAD

**Issue by pjdesira** [home-assistant/frontend#16164] opened 2023-04-13 11:12 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

button cards disappeared from dashboard with update with the latest version 2023.4.3

### Describe the behavior you expected

The button-cards must be in the dashboard

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.4.3

### What was the last working version of Home Assistant Core?

2023.4.2

**Comment by ludeeus** [comment] 2023-04-13 11:13
Duplicate of https://github.com/home-assistant/frontend/issues/16155

**Closed by ludeeus** 2023-04-13 11:13 UTC
