### ISSUE TITLE
Wrong icons color selecting a theme (always are blue)

### ISSUE THREAD

**Issue by luckkmaxx** [home-assistant/frontend#15398] opened 2023-02-08 18:42 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to the latest until now, my buttons icons that was colored with a theme when the reffered entity is enabled, now at least all media player related icons are blue. Only the icon, the background of the button is well themed.
Maybe related to #87304 ?

Buttons like lights are well themed, icon and background.

Rolling back to previous docker image (v2023.1.7) shows the icons as expected.

### Describe the behavior you expected

Show the colors as the selected theme.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.3

### What was the last working version of Home Assistant Core?

2023.1.7

### In which browser are you experiencing the issue with?

HA android app, Bromite

### Which operating system are you using to run this browser?

android

### State of relevant entities

```txt
Android TV
```

**Comment by Eric-boop** [comment] 2023-02-08 21:32
I'm having the same thing happen after core update 2023.2.3 Themes not correct colors for binary sensor icons and switch icon in grid cards only.

**Comment by luckkmaxx** [comment] 2023-02-08 23:26
I rolled back one by one and the issue starts on 2023.2.0b0

**Comment by Eric-boop** [comment] 2023-02-10 02:08
I'm still on 2023.2.3 and I'm working it out. Looks like the syntax has changed. state-active-color: state-fan-active-color: This github frontend/ha-styles page helped. Looks like I was using some deprecated syntax. [https://github.com/home-assistant/frontend/blob/master/src/resources/ha-style.ts](url)

**Comment by luckkmaxx** [comment] 2023-02-10 08:15
That is internal code, right?
So at the moment nothing to do on HA instance, since we only set the "theme" string on each card.

**Comment by Eric-boop** [comment] 2023-02-10 10:56
That git page shows the syntax for HTML, but just remove the -- and add them to you theme. "state-active-color:" is what fixed most my icons. The paper colors, I did not have an issue with. The theme I created, most colors with old syntax are fine. I just had an Icon color that was defaulting to default amber. I took me some time to get the correct syntax to work. I have everything back to my normal now. That's two months in a row not I have to modify my themes to keep up with changes.

**Comment by Eric-boop** [comment] 2023-02-10 10:59
It looks to be some kind of state class change is the issue. Maybe they added more or just changed them. I don't know, above my pay grade.

**Comment by teaserrr** [comment] 2023-02-11 13:13
I'm seeing black icons instead of yellow for light-entities that are turned on. Switch-entities are displayed correctly.

![image](https://user-images.githubusercontent.com/34370173/218259913-266aaddf-1bc1-4fd2-82ba-50e7c8e3a406.png)

![image](https://user-images.githubusercontent.com/34370173/218259853-92d1af56-ab00-43de-bc77-e13ca71f081c.png)

**Comment by Eric-boop** [comment] 2023-02-11 14:20
Use... state-light-active-color: '#f44336' #red

**Comment by Eric-boop** [comment] 2023-02-11 14:21
or if it's a switch them... state-switch-active-color: '#f44336' #red

**Comment by honikos** [comment] 2023-02-18 21:44
--state-light-color is missing in src/resources/ha-style.ts

**Comment by teaserrr** [comment] 2023-02-19 09:55
Duplicate of https://github.com/home-assistant/frontend/issues/15319

**Comment by piitaya** [comment] 2023-02-20 10:46
State theme variables was unofficial before 2023.2. We updated it and make them predictable and official : https://www.home-assistant.io/integrations/frontend/#supported-theme-variables.

Regarding the issue with black icon for lights. It fixed with https://github.com/home-assistant/frontend/pull/15379 and will be deployed in the 2023.3 release.

**Closed by piitaya** 2023-02-20 10:46 UTC
