### ISSUE TITLE
energy dashboard showing incorrect costs for power consumed

### ISSUE THREAD

**Issue by siobhanellis** [home-assistant/frontend#17536] opened 2023-08-09 16:10 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

My Grid consumption shows 3.8kWh, I have set the cost to be 0.30GBP, yet the cost associated in the dashboard is -£40.32.

### Describe the behavior you expected

I expect to see 3.8 x 0.3 = 1.14

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.8.1

### In which browser are you experiencing the issue with?

Using Home Assist App (default Safari)

### Which operating system are you using to run this browser?

macOS 13.4.1(c)

### State of relevant entities

```txt
sensor.foxess_grid_consumption

FoxESS - Grid Consumption
3.80000000000018	

state_class: total_increasing
unit_of_measurement: kWh
device_class: energy
friendly_name: FoxESS - Grid Consumption
```

### Additional information

![Screenshot 2023-08-09 at 17 08 32](https://github.com/home-assistant/frontend/assets/33163141/97840159-2660-4e3b-86d5-3f0e64f7f36f)
![Screenshot 2023-08-09 at 17 09 01](https://github.com/home-assistant/frontend/assets/33163141/04d10bad-841f-430d-967d-95134c8eced3)

**Comment by karwosts** [comment] 2023-08-09 17:02
The cost is actually not calculated in the frontend with a simple multiplication, it comes from a separate sensor created by the energy integration, and it doesn't change retroactively. 

If the cost is showing wrong, then you have some bad historical data in the `_cost` sensor that was created for your entity. 

See if you can find that sensor and look at its history to see what's going on. Optionally you can fix a bad datapoint in developer-tools/statistics.

**Comment by ckglobalroaming** [comment] 2023-11-12 03:23
This issue is related to #79638 [Energy cost sensors reset during HA restart even though the energy sensor they track do not](https://github.com/home-assistant/core/issues/79638#top)
This issue is unresolved as at 2023.12.2
Cost sensor resets to zero on system restart.

**Comment by Tosko4** [comment] 2023-11-13 00:53
same issue

**Comment by karwosts** [comment] 2023-11-13 13:55
Again I will reiterate that the cost comes from the backend, the frontend just displays what the backend reports for statistics sensor. 

Knowing that, if anyone suspects there is a *frontend* bug here, and you can provide supporting data/evidence, I can look at it, else I will close this issue.

**Comment by Tosko4** [comment] 2023-11-13 16:35
I am sure you are right. Fact is, that when I reset my HA instance, the counters are starting from 0, not picking up the state before restart and continue on it. 

Also, tracking this: https://github.com/home-assistant/core/issues/79638#top you mentioned that it wasn’t fixed. You link to a PR which is closed, but I cant tell from the comments that it is solved. Paired with the comments here and other ticket, the assumption I made is that it is still not solved. 


i can try to provide info later today or tomorrow.

**Comment by karwosts** [comment] 2023-11-13 18:17
> You link to a PR which is closed, but I cant tell from the comments that it is solved. 

I linked an issue which got closed, but that issue has a core PR which is still open/pending ( #97031 )

It's unfortunate that #79638 got closed by stale bot, but if this issue is in the core code, this frontend ticket can't help unless there's something to be fixed in frontend. Maybe a new core issue needs to be opened, or get a moderator to reopen that issue.

**Comment by Tosko4** [comment] 2023-11-13 22:00
Gotcha. Indeed i dont think this is a frontend issue.

**Comment by n0b00nn0** [comment] 2024-01-20 14:31
+1

**Comment by heisenberg2980** [comment] 2024-01-21 02:07
> > You link to a PR which is closed, but I cant tell from the comments that it is solved.
> 
> I linked an issue which got closed, but that issue has a core PR which is still open/pending ( [home-assistant/core#97031](https://github.com/home-assistant/core/pull/97031) )
> 
> It's unfortunate that #79638 got closed by stale bot, but if this issue is in the core code, this frontend ticket can't help unless there's something to be fixed in frontend. Maybe a new core issue needs to be opened, or get a moderator to reopen that issue.

The PR https://github.com/home-assistant/core/pull/97031 got merged in December but the issue is still hapenning, does anyone know if there is another issue to track this problem where the energy cost is initialized to 0 every time Home Assistant restarts?

**Comment by Tosko4** [comment] 2024-04-20 04:50
Please reipen. It is still the case

**Comment by baxgit** [comment] 2024-04-20 08:30
+1 to keep open as definitely still an issue

**Comment by silamon** [comment] 2024-04-20 12:07
Please open a new core issue at https://github.com/home-assistant/core to get this fixed or tracked. Keeping the issue open here won't help it.

**Closed by silamon** 2024-04-20 12:07 UTC

**Comment by Tosko4** [comment] 2024-04-20 13:29
@silamon funny how you guys keep pointing back and forth. There are 2 other issues closed as well

**Comment by silamon** [comment] 2024-04-20 13:56
I'm not really trying to point back and forth. We're all saying that it's an issue in core, and you acknowledged that it's not a frontend issue. 😉 If the issue is about the frontend, and something that should be fixed in the frontend code, we're happy to have your issue here until it's solved. We're not going to track issues here if the issue is to be solved elsewhere.

**Comment by Scoopien** [comment] 2024-10-11 10:28
Cost sensor resets to zero on system restart.

**Comment by Null-Mind** [comment] 2024-10-17 17:08
same problem here !!

**Comment by lullatscho** [comment] 2024-11-20 09:58
same problem already with energy sensors and individual energy usage in energy dashboard

![image](https://github.com/user-attachments/assets/c67b7dd8-8481-4ff9-82e0-83412cdc71b4)
![image](https://github.com/user-attachments/assets/be0639dd-a060-44a4-b250-5d90cdcccd26)

**Comment by bdelima** [comment] 2025-07-23 21:22
I don't understand why this issue was closed. It's a definite problem and makes the energy cost tracking in HA pretty much pointless. Is this never going to be fixed? It's a great feature, but it needs to actually work correctly!
