### ISSUE TITLE
Error while loading page * IOS 12.5.7 HA core 2024.5.1

### ISSUE THREAD

**Issue by PaulHam211** [home-assistant/frontend#20744] opened 2024-05-06 16:03 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since Home Assistant Core 2024.05  I get 'Error while loading page *'. when navigating to any dashboard on a iPad Air 2 IOS 12.5.7.
Issue happens in Home Assistant app and safari. 
Sidebar loads, dashboards do not.

### Describe the behavior you expected

Dashboards should load, like they did before the 2024.05 update.

### Steps to reproduce the issue

1. Open Home Assistant IOS app, or use safari
2. Try to open any dashboard (except app settings, this does load)
3.
...

### What version of Home Assistant Core has the issue?

2024.05

### What was the last working version of Home Assistant Core?

2024.04

### Which operating system are you using to run this browser?

IOS 12.5.7

**Comment by silamon** [comment] 2024-05-06 16:13
Duplicate of #20697.

**Closed by silamon** 2024-05-06 16:13 UTC

**Comment by PaulHam211** [comment] 2024-05-06 16:15
[Error] Error loading page – "dashboard"
TypeError: i is not a function. (In 'i()', 'i' is an instance of Object)
(anonymous function) — 15.E8JuIwivucc.js:1:8457
(anonymous function) — 15.E8JuIwivucc.js:1:19681
l — bootstrap:19
l
promiseReactionJob
	(anonymous function) (app.9QvPhNMccVE.js:2:98247)
	promiseReactionJob
	
	
[Error] Error loading page – "energy"
TypeError: r is not a function. (In 'r()', 'r' is an instance of Object)
(anonymous function) — 22845.i2Rn18iy0Xg.js:1:78824
(anonymous function) — 22845.i2Rn18iy0Xg.js:1:88140
l — bootstrap:19
l
promiseReactionJob
	(anonymous function) (app.9QvPhNMccVE.js:2:98247)
	promiseReactionJob
	
	
[Error] Error loading page – "history"
TypeError: r is not a function. (In 'r()', 'r' is an instance of Object)
(anonymous function) — 63682.NvZxrBas0Es.js:1:38194
(anonymous function) — 63682.NvZxrBas0Es.js:1:55042
l — bootstrap:19
l
promiseReactionJob
	(anonymous function) (app.9QvPhNMccVE.js:2:98247)
	promiseReactionJob
