### ISSUE TITLE
ISO 8061 Date Format

### ISSUE THREAD

**Issue by Tragen** [home-assistant/frontend#21577] opened 2024-08-03 21:23 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I cannot selet date format in the international standard format of [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (YYYY-MM-DD),

### Describe the behavior you expected

See discussion https://github.com/home-assistant/frontend/discussions/18689
I expect to be able to select the ISO date format YYYY-MM-DD

### Steps to reproduce the issue

Try to change the date format to ISO. It's not possible and it's not possible to configure a custom date format.

### What version of Home Assistant Core has the issue?

2024.7.4

### What was the last working version of Home Assistant Core?

2024.7.4

### In which browser are you experiencing the issue with?

Firefox 128, Edge newst version of today

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment] 2024-08-05 13:15
This is still a feature request, the discussion is the right place for it. Closing as this is not a bug.

The suggestion to offer dashes as well as slashes was mentioned when this feature was developed, but it was ultimately decided against as having too many options. https://github.com/home-assistant/frontend/pull/16489

**Closed by karwosts** 2024-08-05 13:15 UTC

**Comment by ypid** [comment] 2025-01-12 13:25
A discussion already exists for this feature request: https://github.com/home-assistant/frontend/discussions/18689 I am also very interested and in support of this feature.
