### ISSUE TITLE
Login fails after password change

### ISSUE THREAD

**Issue by dawiinci** [home-assistant/frontend#13265] opened 2022-07-24 10:15 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Login doesn't work when using autofill in Safari after I changed the password.
<img width="395" alt="1" src="https://user-images.githubusercontent.com/11598216/180642477-c3474c45-758b-4000-aa70-c9271d4ec430.png">

With old password it was working.

When I enter the password manually it works. 
When I cut and paste the autofilled password it works.

### Describe the behavior you expected

Login...

### Steps to reproduce the issue

1. Use Safari autologin
2. Change password
3. Login with autologin and new password
...

### What version of Home Assistant Core has the issue?

2022.7.6

### What was the last working version of Home Assistant Core?

2022.7.6

### In which browser are you experiencing the issue with?

Safari Version 15.6 (17613.3.9.1.5)

### Which operating system are you using to run this browser?

macOS Monterey 12.5

### State of relevant entities

```txt
Please just fix the proper behavior for saving and autofilling passwords like every other website does!
```

### Additional information

Checked with latest Mobile Safari as well.

I am not sure if the password change is the problem. I just created the auto login entry later.

I checked with "31 digits number and characters" password.

**Comment by dawiinci** [comment] 2022-07-28 07:31
It looks like there is a invisible character in the auto filled password field. If I remove that last character I can login. 

This character is not present in key chain.

**Comment by steverep** [comment] 2022-08-31 02:03
Duplicate of #10274

**Closed by steverep** 2022-08-31 02:03 UTC

**Comment by steverep** [comment] 2022-08-31 02:05
I'm not sure I'm following your issue correctly, but this seems like it is a duplicate of the above referenced issue.  If you think that is not the case, please reply with much more detail.  Thanks.

**Comment by dawiinci** [comment] 2022-09-03 12:23
Thanks, it just didn't accept the password. However, after deleting and adding it again it works now. Might be a bug in Safari or a weird combination.
