### ISSUE TITLE
Button card disappeared 

### ISSUE THREAD

**Issue by mobileboy2018** [home-assistant/frontend#16114] opened 2023-04-07 18:55 UTC
### The problem

After 2023.4.0 button cards disappears when set to show state of a sensor with unit of measurement %. (Humidity) other sensors ok.  Turning show state off brings  back the card into view but obviously isn’t showing the State.

### What version of Home Assistant Core has the issue?

2023.4.0 

### What was the last working version of Home Assistant Core?

2023.3.6

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Any that use button card with unit of measurement %

**Comment by karwosts** [comment] 2023-04-08 14:03
duplicate #16099

**Comment by kksligh** [comment] 2023-04-09 20:51
I'm having the same issue but it's not related to humidity. For some reason it is was close stating these were custom buttons but that's not what is missing - they are all standard button cards. 

https://github.com/home-assistant/core/issues/91124

**Comment by ildar170975** [comment] 2023-04-10 11:32
There is a registered issue for the button-card with "unit = %", check github.

**Comment by kksligh** [comment] 2023-04-10 11:53
That's not the only situation where the button disappears.

**Comment by ildar170975** [comment] 2023-04-10 12:12
> That's not the only situation where the button disappears.

Then list all possible observed cases (with a minimal code) when the button-card is not displayed.

**Comment by plbartie** [comment] 2023-04-13 06:26
I'm having same issues after update

**Comment by morphylive** [comment] 2023-04-13 06:37
having the same issue. after 2023.4 button card with % value diasppeared. with the last update 2023.4.3 all the button disappeared. also simple button with a light entities.

**Comment by Loic691** [comment] 2023-04-13 07:27
+1 same !

**Comment by scoop643** [comment] 2023-04-13 07:36
Here the same with 2023.4.3, all buttons are gone

**Comment by nikos458** [comment] 2023-04-13 07:46
I have the same issue 2023.4.3. A fix should be coming it is reported by many.

**Comment by ehouarn35** [comment] 2023-04-13 09:04
hi same all 2023.04.3 on intel core
Restore to 2023.3.6 look working back fine
we'll see and wait a new version

**Comment by bramkragten** [comment] 2023-04-13 09:50
Duplicate of https://github.com/home-assistant/frontend/issues/16155

**Closed by bramkragten** 2023-04-13 09:50 UTC

**Comment by mtibbett67** [comment] 2023-04-14 01:29
Broken for me after update today
Home Assistant 2023.4.4
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.0 - latest

**Comment by ehouarn35** [comment] 2023-04-24 07:51
I've updating yesterday all fine, button working good
