### ISSUE TITLE
Safari Showing Arrows Next To Lovelace Views

### ISSUE THREAD

**Issue by bradich** [home-assistant/frontend#17413] opened 2023-07-27 05:43 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When viewing my Home Assistant dashboard on macOS Safari, the iOS app, and iOS Safari, I'm seeing arrows before and after my Lovelace views. I have a five Lovelace views and nine subviews, and I think I only started seeing this after creating subviews for each of my rooms. The arrows disappear after clicking or tapping on them. 

![Home Assistant Lovelace View Arrows 1](https://github.com/home-assistant/frontend/assets/3728785/8956f27d-a9a1-4ff3-aa7c-83a7ec28b322)

![Home Assistant Lovelace View Arrows 2](https://github.com/home-assistant/frontend/assets/3728785/b3b0c4b5-5974-4f3d-8631-b86113b8d2e5)

### Describe the behavior you expected

I expect that these arrows are not displayed, since they don't do anything and disappear after you click or tap them. 

### Steps to reproduce the issue

Hard to say what is causing this. I have a fairly simple dashboard. 

### What version of Home Assistant Core has the issue?

2023.7.3

### In which browser are you experiencing the issue with?

Safari Version 16.5.1 (18615.2.9.11.7)

### Which operating system are you using to run this browser?

macOS Ventura 13.4.1 (22F82)

### Additional information

This seems to be isolated to Safari. I have tested Edge (Version 115.0.1901.183 (Official build) (arm64)) and Firefox (115.0.2 (64-bit)) and cannot replicate the issue.

**Comment by erikgeurts** [comment] 2023-07-27 06:39
Duplicate of #16091

**Comment by karwosts** [comment] 2023-07-27 12:52
Close as duplicate.

**Closed by karwosts** 2023-07-27 12:52 UTC
