### ISSUE TITLE
Time helper looses focus when entering first digit

### ISSUE THREAD

**Issue by christianschneider89** [home-assistant/frontend#12283] opened 2022-04-10 13:10 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a helper with time.
When I will change the time and I type the first digit, the focus is lost (and the keyboard disappears) and I need to select the time helper again to enter the correct time.

It only works as expected on the second try (see video).

Same behavior in the App and in Chrome (version see below)

### Describe the behavior you expected

The focus of the time helper field shouldn't be lost.

### Steps to reproduce the issue

See this video:

https://user-images.githubusercontent.com/15085873/162619706-ddecc3fb-5ff2-4ab1-ba41-88eff7d98615.mp4

### What version of Home Assistant Core has the issue?

core-2022.4.1

### What was the last working version of Home Assistant Core?

core-2022.2

### In which browser are you experiencing the issue with?

Google Chrome 100.0.4896.75 and iOS App 2022.358

### Which operating system are you using to run this browser?

Windows 10, iOS 15.4.1

**Comment by yurgh** [comment] 2022-05-14 17:32
Ditto;
I came here to see if it was just me, as this bug has annoyed me a lot lately. It seems that focus is lost when the value of the input box is changed.

If I want to change minutes from 35 to 36 I activate the control and type 3. This cause a change-event since 3 is different from 35. This also unfocus the control which now show "03".  I focus the control again and type 3 which does nothing since 3 is the same value as 03, and then type 6 which cause the change-event to fire and unfocus the control. (Which now correctly contains "36"). The automation triggered by the time-helper is called with both 3 and 36.

I would like the control to not trigger any event until it's lost focus enter is pressed like it used to.

**Comment by Recte** [comment] 2022-05-27 08:20
Didn't have time to report earlier, so happy to see it's already reported.
For what it's worth, I only experience this behavior using my phone and tablet (both iOS, app or browser doesn't matter). Windows, using FireFox, works fine.

**Comment by nao-pon** [comment] 2022-07-07 14:55
HA 2022.7.0 has a similar issue.

I'm getting this issue on Windows Chrome (103.0.5060.114 (Official Build) 64bit) and Android APP (latest).

**Comment by steverep** [comment] 2022-08-29 00:54
Duplicate of #11861

The fix for this has already been merged and should be in the next release.

**Closed** 2022-08-29 00:55 UTC
Labels: Duplicate
