### ISSUE TITLE
Location for maximize control not obvious on a popup window

### ISSUE THREAD

**Issue by davet2001** [home-assistant/frontend#17406] opened 2023-07-25 12:04 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking on a popup window in the UI, it can be maximized, but this is done by clicking on the title text of the popup.  There is no icon, or even change of pointer (pointer is i bar style as per normal text), and no hover over hint.

The problem is that this is not obvious to users, resulting in other [issues](https://github.com/home-assistant/core/issues/96352) being raised.

### Describe the behavior you expected

The popup window should have an icon or visible hint on how to maximize and not require any guesswork clicking.

### Steps to reproduce the issue

1. Open https://demo.home-assistant.io/#/lovelace/0
2. Click one of the camera icons
3. [No maximise icon]
4. Click title text
5. [Popup maximises]

### What version of Home Assistant Core has the issue?

2023.7.2

### What was the last working version of Home Assistant Core?

None known

### In which browser are you experiencing the issue with?

Google Chrome 114.0.5735.199

### Which operating system are you using to run this browser?

win10

**Comment by karwosts** [comment] 2023-07-25 12:38
Duplicate of #11625 - we have talked about this a little bit, but haven't quite come up with a consensus yet of what to replace it with. See also relevant discussion #17379

**Closed by karwosts** 2023-07-25 12:38 UTC
