### ISSUE TITLE
2023.3.0 Thermostat card missing dot to set temp and throws error

### ISSUE THREAD

**Issue by luke7101** [home-assistant/frontend#15680] opened 2023-03-02 15:41 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Capture d'écran 2023-03-02 163354](https://user-images.githubusercontent.com/58976540/222474529-cf8829d5-31ec-452a-ad3e-a81ed1975772.png)
Thermostat card is missing the dot which is needed to set the temperature, and by clicking the area where it should be located an error pops in the logs :

`ERROR (MainThread) [frontend.js.latest.202303010] https://*****.*******.**/frontend_latest/eb71732c.js:2:25186 Uncaught TypeError: Cannot read properties of null (reading 'classList')`

### Describe the behavior you expected

The dot should slide in order to allow the user to set the temperature

### Steps to reproduce the issue

1. Update to 2023.3.0
2. Refresh page on browser or restart companion app on device
3.
...

### What version of Home Assistant Core has the issue?

2023.3.0

### What was the last working version of Home Assistant Core?

2023.2.5

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.178 (64 bits)

### Which operating system are you using to run this browser?

Windows 11 x64

**Comment by piitaya** [comment] 2023-03-02 16:05
Hello 👋 It's a duplicate of https://github.com/home-assistant/frontend/issues/15662. It will be fixed in the next patch

**Closed by piitaya** 2023-03-02 16:05 UTC
