### ISSUE TITLE
Pasting content into the "Icon" field for any Lovelace element causes crash

### ISSUE THREAD

**Issue by ChirpyTurnip** [home-assistant/frontend#14462] opened 2022-11-28 00:39 UTC
### The problem

When editing a dashboard element a user will sometimes set a custom mdi icon. When the same change is made multiple times it is easier to copy and paste the mdi:<string> from one entity to the next, rather than searching for the icon again each time. 

While it is possible to paste just the <string> part, if the user includes the 'mdi:' part the browser tab crashes.

Given that the 'mdi:' section is part of the displayed value in the icon field it is not unreasonable that this should be copied, and if it can be copied then you should be able to paste it without crashing. :-)

### What version of Home Assistant Core has the issue?

Home Assistant 2022.11.4

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Core

**Comment by spacegaier** [comment] 2022-11-28 20:47
I can confirm the issue (tested in Desktop Chrome). The whole browser tab freezes up and it looks to be a endless loop inside lit/vaadin:

![image](https://user-images.githubusercontent.com/114137/204377398-77fe2150-7bc0-4a08-8b5b-27521e4d7092.png)

`_filterChanged()` in `ha-icon-picker` seems to behave correctly, but then inside the other libs the issuer occurs. Not really sure, where to go from here...

**Comment by steverep** [comment] 2022-11-29 17:05
Duplicate of #14147

**Closed by steverep** 2022-11-29 17:05 UTC
