### ISSUE TITLE
Entities Card: TP-Link switches open more-info panel rather than toggle state when tapping toggle switch (iOS)

### ISSUE THREAD

**Issue by krazos** [home-assistant/frontend#10801] opened 2021-12-05 14:09 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to core-2021.12.0b0, tapping the toggle switch in an entities card for TP-Link switches on iOS (both Companion App and Mobile Safari) opens the more-info panel rather than toggling the state of the switch.  Other, non-TP-Link switches continue to function as expected on iOS, and TP-Link switches function as expected on various desktop web browsers.

### Describe the behavior you expected

Prior to core-2021.12.0b0, tapping the toggle switch for a TP-Link switch on iOS app/mobile Safari would toggle the state of the switch, which is the default tap action for a switch entity.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.12.0b0

### What was the last working version of Home Assistant Core?

core-2021.11.5

### In which browser are you experiencing the issue with?

Home Assistant iOS Companion App 2021.11.1; Mobile Safari on iOS

### Which operating system are you using to run this browser?

iOS 15.1

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: switch.christmas_tree
  - entity: switch.christmas_decorations
title: Seasonal Decorations
```

**Comment by spacegaier** [comment] 2021-12-05 14:42
Duplicate of https://github.com/home-assistant/frontend/issues/10790 and already fixed in dev.

**Closed by spacegaier** 2021-12-05 14:42 UTC
Labels: bug

**Comment by krazos** [comment] 2021-12-05 14:57
Oops, I tried to search but missed this one. Sorry for the confusion, and thanks for the fix!
