### ISSUE TITLE
Card Mod Styles Disappearing

### ISSUE THREAD

**Issue by Daniel-dev22** [home-assistant/frontend#23034] opened 2024-11-27 23:58 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I know card mod is custom but it appears that everytime I save a card mod style it saves but when I go to edit the card the style is removed so if I make a change elsewhere and save the styles are removed. 

This is happening on all cards with different card mod style configurations.

I noticed this happening lately and I recall a similar issue years ago with fire dom event not being recognized by the frontend and dropping the keys.

Is it possible these keys are now being dropped too?

```
          card_mod:
              style: |
                ha-card {
                  padding-bottom: 0px !important;
                  padding-right: 0px !important;
                  padding-left: 0px !important;
                  --card-secondary-font-size: 11px;
                  --ha-card-background: transparent;
                  --ha-card-border-radius: 0px;
                  --ha-card-box-shadow: 0px;
                  --icon-size: 60px;
                  margin-right: -40px;
                }
```

### Describe the behavior you expected

My card mod style to be saved and still remain when I come back and edit the file.

### Steps to reproduce the issue

1. Use card mod to customize a card click save
2. Return to card and find the styles are removed when you open the editor
3.
...

### What version of Home Assistant Core has the issue?

2024.11.3

### In which browser are you experiencing the issue with?

Companion app

**Comment by ildar170975** [comment] 2024-11-28 00:10
1. card-mod is a custom plugin & there is a registered issue: https://github.com/thomasloven/lovelace-card-mod/issues/337
2. It happens to some cards only.
3. It started to happen a year ago.

**Comment by karwosts** [comment] 2024-11-28 00:30
Do not reproduce with stock frontend. I do not use card mod but just doing this to note that the editor does not eat the keys on its own. 


Unless someone can show that the actual core frontend has a bug, I will probably close this as off topic, as it seems like a card mod bug. Can you reproduce this behavior of missing yaml in safe mode?

I will say that I note that when I add a card_mod key it disables the visual editor. Yet in all the screenshots of this issue show card mod still has the visual editor available when using a card_mod key. I would tend to suspect something in the way that is hacked in might be contributing to this, I have seen issues where visual editor can mess up the yaml if it is not properly disabled. 

![cardmod](https://github.com/user-attachments/assets/71538419-1e4a-4957-b076-784491c696e5)

**Comment by ildar170975** [comment] 2024-11-28 00:34
> Do not reproduce with stock frontend

Try with custom:bar-card (https://github.com/thomasloven/lovelace-card-mod/issues/337#issuecomment-1872610429), Tile (https://github.com/thomasloven/lovelace-card-mod/issues/337#issuecomment-1892579315)

**Comment by karwosts** [comment] 2024-11-28 00:55
Not interested in custom cards behavior. Don't see an issue with tile. 

![cardmod2](https://github.com/user-attachments/assets/df3ea06c-2a92-41b3-b0dd-69512a314a25)

**Comment by ildar170975** [comment] 2024-11-28 01:07
>  Don't see an issue with tile.

Well, I see. The card-mod code is not added into Editor - thus a preview not styled.
But a card on a background is still red.

Also, I do not see any changes on your gif - a color is not changed like you have no card-mod installed.

**Comment by karwosts** [comment] 2024-11-28 01:12
Correct I am not using card mod, I said that in my original post. 

> Do not reproduce with stock frontend. I do not use card mod but just doing this to note that the editor does not eat the keys on its own.

Just trying to prove that this is not something frontend is responsible for, and belongs on card mod repo.

**Comment by ildar170975** [comment] 2024-11-28 01:15
> and belongs on card mod repo.

Seems to be so.

Also,
> Not interested in custom cards behavior

I do you think that a custom bar-card may affect Editor.

**Comment by karwosts** [comment] 2024-11-28 01:19
> I do you think that a custom bar-card may affect Editor differently than a stock Tile? Do not think so.

I would suspect it's something related to custom visual editors. I suspect the visual editor is somehow eating it. Do not know if that behavior is part of custom bar-card or card-mod itself.

**Comment by ildar170975** [comment] 2024-11-28 01:23
As for card-mod - it does not have a custom visual editor. Interesting that it happens to some cards only. For instance, does not to Entities card - but does to Tile.

**Comment by karwosts** [comment] 2024-11-28 01:27
>  - but does to Tile.

When you add card_mod key to stock Tile, does it show the "visual editor disabled" warning?

**Comment by ildar170975** [comment] 2024-11-28 01:35
> When you add card_mod key to stock Tile, does it show the "visual editor disabled" warning?

Does not:
![image](https://github.com/user-attachments/assets/f00e1a69-9234-4fd0-99fd-aa69ce65dabe)

After switching to UI editor:
![image](https://github.com/user-attachments/assets/085e976e-dc6b-4660-bce1-de056ddee8bb)

After switching back:
![image](https://github.com/user-attachments/assets/64967513-8123-46d6-b0f8-2501836e1108)

After saving & reopening:
![image](https://github.com/user-attachments/assets/2ecb48da-7eda-465f-9b81-47c95a2a271f)

**Comment by ildar170975** [comment] 2024-11-28 01:38
As for Entities card - no warnings "visual editor disabled" as well, the card-mod code is shown after reopening:
![image](https://github.com/user-attachments/assets/27d3b351-21c0-47b3-9b90-90170e59b595)

**Comment by karwosts** [comment] 2024-11-28 01:38
Some custom code you have installed is allowing you to use the visual editor still when unknown keys are present. I guess that has to be card mod patching over the normal code overriding that behavior.

**Comment by ildar170975** [comment] 2024-11-28 01:40
For the record - for Entity card this warning is shown:
![image](https://github.com/user-attachments/assets/6a6917bc-0a01-4f7f-a3a3-2020eb72190b)

but card-mod code is also shown after saving & reopening.
So, difficult case ))))

**Comment by karwosts** [comment] 2024-11-28 01:44
Suspicious: https://github.com/thomasloven/lovelace-card-mod/blob/master/src/patch/hui-card-element-editor.ts#L15

**Comment by ildar170975** [comment] 2024-11-28 01:48
Hmm, this file (at leas it's name) proves that card-mod does something to Editor.
Imho THIS should be closed - but would be great to continue discussing the problem.

**Closed** 2024-11-29 04:33 UTC

**Comment by WRoss7** [comment] 2025-01-04 22:39
@karwosts, @ildar170975
My theme is broken.
And I confirm that the problem exists even with entities card. See the example below:

type: entities
show_header_toggle: false
state_color: false
entities:
  - entity: sensor.processor_use
    name: CPU
    card_mod:
      style: >-
        {% if states('sensor.processor_use') | float(0) > 2.5 and
        states('sensor.processor_use') | float(0) <= 5 %}
          div {
            color: wheat;
            font-weight: bold;
          }
          .....

This allowed me to color the value and consequently the unit of measurement, leaving the entity text unchanged.

![Image](https://github.com/user-attachments/assets/3c95136f-15e8-415e-9500-8a8e70baa062)

Now, if I am not mistaken, the color variable is inherited from :host

@karwosts, I understand your point of view, but since something broke the themes (I assume to several people), and the last card-mod update was on March 13, I don't agree with closing this bug.

**Comment by ildar170975** [comment] 2025-01-04 22:52
@WRoss7 
Check the main card-mod thread, there was an issue in 2025.1 caused by some PR and we found a fix.
It is meaningless to report here...

**Comment by WRoss7** [comment] 2025-01-06 19:16
@ildar170975 
sorry but I didn't know where to bring it back because, as written above, my theme is broken before 2025.1.
Now I have opened a bug in card-mod, but I don't think it is correct for what I wrote above: unless I am completely wrong, the problem lies on the frontend side

**Comment by karwosts** [comment] 2025-01-06 19:38
This bug was about the visual editor only. It has nothing to do with your themes being applied outside the visual editor.
