### ISSUE TITLE
Self sufficiency 'quota' graph and 'i' info

### ISSUE THREAD

**Issue by gemmaker** [home-assistant/frontend#17198] opened 2023-07-07 00:42 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The title of the new energy graph should just be 'self sufficiency' as there is no 'quota'. The word quota included in the title is wrong.

Also, the 'i' for more info on all three of the energy graphs aren't working since the new graphs were introduced.

### Describe the behavior you expected

The 'i' doesn't provide more information anymore.

Title of graphs should reflect what they are also.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.7.0

**Comment by brainfrz82** [comment] 2023-07-07 07:16
Came here to say pretty much this, i think the confusion comes from the word quotient which can be used as a synonym for ratio.

For the Dutch translation, it's exactly the same case.

**Comment by gemmaker** [comment] 2023-07-07 07:36
> Came here to say pretty much this, i think the confusion comes from the word quotient which can be used as a synonym for ratio.
> 
> For the Dutch translation, it's exactly the same case.

You're probably right - 'quotient' at least makes more sense! 'Contribution ratio' is probably a better term for the new graph (whereby 100% is self sufficiency)

**Comment by wtadler** [comment] 2023-07-09 20:49
I agree with you and addressed it in the above PR.

As for the tooltip "i" button not working, I think that's only on mobile. They seem to work fine on desktop. That was noted here but never fixed: https://github.com/home-assistant/frontend/issues/12141

**Comment by karwosts** [comment] 2023-07-20 22:56
I'm going to close this as 1/2 of the issue is fixed, and the other 1/2 is a duplicate. Tooltips can be tracked in 12141.

**Closed by karwosts** 2023-07-20 22:56 UTC
