### ISSUE TITLE
HA Login Page - AutoComplete Issue

### ISSUE THREAD

**Issue by meluvalli** [home-assistant/frontend#17247] opened 2023-07-10 07:31 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

There is an issue with HA login page.  It's been around for a long time...  Basically, if you have the username/password stored in an iPhone and it auto completes the fields (Username and Password) and tries to sign in, it'll come back and say "Invalid username or password".  You have to go into each field (Username and Password), and back out the last character and put it back in manually. or add a character and back the added character out.  Then it'll login.  This issue only happens with HA, so it's not an iOS/MacOS issue...  

It appears HA doesn't know you typed in the fields when it auto-completes!  I think that's the problem :)

I have not tried this with google/android device.

### Describe the behavior you expected

Should accept username/password with auto-complete on.  

### Steps to reproduce the issue

1.Save your username/password in iOS/MacOS for your HA domain.  Example ha.mydomain.com
2.Login with iOS and allow it to auto-complete the username/password field.
3.Click login.

### What version of Home Assistant Core has the issue?

2023.7.1

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

iOS (Multiple Versions tested) and MacOS

### State of relevant entities

```txt
This seems to happen on all iOS devices.  I also tested this on MacOS.  Same result.
```

**Comment by karwosts** [comment] 2023-07-10 23:32
Duplicate of #16976?

**Comment by steverep** [comment] 2023-08-08 19:50
Duplicate of #16976 

Please subscribe and track this there.

**Closed by steverep** 2023-08-08 19:50 UTC
