### ISSUE TITLE
supervisor snapshot file name differences

### ISSUE THREAD

**Issue by justinesmithies** [home-assistant/frontend#6088] opened 2020-06-01 20:16 UTC
**Home Assistant release with the issue:**
 Home Assistant 0.110.4

**Operating environment (HassOS/Generic):**

**Supervisor logs:**

**Description of problem:**
Downloading a snapshot logged in via the local IP i get the filename Hass_io_Monday_1_Jun_2020.tar but if I go via my external domain url when clicking download snapshot in the supervisor i get a file called Download which is a valid tar archive just wrongly named

**Comment by bramkragten** [comment] 2020-06-02 10:38
Please share your environment specs, works as expected here.

**Comment by justinesmithies** [comment] 2020-06-02 10:49
I'm using a pi 4 with the official HA os install. 
HassOS 4.8 , Supervisor 225

If I login via my external HTTPS URL I can create a snapshot but when I click download the filename is just Download. If I login via my local I.P and do the same the file downloaded has the proper Hass_io_Tuesday_2_Jun_2020.tar format.

**Comment by bramkragten** [comment] 2020-06-02 10:59
How is your external https URL configured? Do you use Home Assistant Cloud?

**Comment by justinesmithies** [comment] 2020-06-02 11:01
Sorry no I'm using the add-on Nginx reverse proxy manager which utilises let's encrypt certificates .

**Comment by bramkragten** [comment] 2020-06-02 11:03
I tried both methods but can not replicate the issue... Do you use the same device and browser for local and remote?

**Comment by justinesmithies** [comment] 2020-06-02 11:13
Yes I'm using Arch Linux with Firefox version 77

**Comment by tofuSCHNITZEL** [comment] 2020-06-07 20:39
Home Assistant release with the issue:
Home Assistant 0.110.4

Operating environment (HassOS/Generic):
HassOS 4.8 on RPI3B+
Supervisor Version 227

Supervisor logs:
n/a

Description of problem:
When downloading a snapshot only a file named "download" (without ending) is received by the browser. Issue occurs with Firefox 77.0.1 but not e.g. in MS Edge (chromium edition)

**Comment by agners** [comment] 2020-10-10 16:17
I do observe this issue too on Arch Linux Firefox 81.0.1.

Similar to #7258 this bug seems to be Service Worker related as well: When using a non-https URL (no Service Worker in play in this case) or unregistring it manually (Ctrl+Shift+I -> tab "Application" -> "Service Workers" the button "Unregister" on the right side), the file name seems fine.

It seems that Firefox (used to) have bugs in this area: https://bugzilla.mozilla.org/show_bug.cgi?id=1625769. However, I cannot reproduce that particular issue today, so it seems not to be directly related to this issue.

**Comment by ludeeus** [comment] 2020-10-15 09:05
We have added a content-disposition header to handle this issue.
Will be in working from HA 0.117 and SU 248

**Closed by ludeeus** 2020-10-15 09:05 UTC
Labels: supervisor
