### ISSUE TITLE
Theme does not change when set with service or node-red

### ISSUE THREAD

**Issue by dflvunoooooo** [home-assistant/frontend#16309] opened 2023-04-25 20:42 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I used to change my theme with an automation from a light to a dark or the other way around depending on the sun. Now with the new dark / light mode this does not work anymore. I can call a service and set the theme with dark or light mode, but it does not change. But there is not anything in the logs. 

### Describe the behavior you expected

If I set the theme with a service to dark, it should switch to the dark theme.

### Steps to reproduce the issue

1. Set theme to backend selected.
2. Chose a theme and set it for example to light mode.
3. Run a service to set this theme to dark mode.

### What version of Home Assistant Core has the issue?

2023.4.6

### What was the last working version of Home Assistant Core?

Not sure maybe 2023.4.4

### In which browser are you experiencing the issue with?

firefox and chrome

### Which operating system are you using to run this browser?

Arch-Linux

### Additional information

If anything is needed I am happy to provide it.

**Comment by karwosts** [comment] 2023-06-14 21:27
I think this might be duplicate of #11405. You can read my last comment there and see if it helps clear this up. 

I think this may not be broken but it is not that intuitive how it is supposed to work. 

Maybe continue the discussion there if you agree it is the same issue.

**Comment by karwosts** [comment] 2023-06-24 21:41
I'm going to close this as duplicate of #11405, but even that one I believe is probably working as intended. You cannot change your browser from light to dark theme selected with the existing service calls.

**Closed by karwosts** 2023-06-24 21:41 UTC

**Comment by dflvunoooooo** [comment] 2023-07-04 10:58
Thank you your post [comment](https://github.com/home-assistant/frontend/issues/11405#issuecomment-1592003731) in #11405 explains this behaviour.
