### ISSUE TITLE
Energy Monitor Individual Devices - need to hover mouse to load

### ISSUE THREAD

**Issue by Alexivia** [home-assistant/frontend#13376] opened 2022-08-12 23:06 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When in the Energy dashboard, the bottom graph for the individual devices under "Monitor Individual Devices" does not show properly until I hover the mouse (while on a browser) or touch the graphs (when on mobile / companion app).

### Describe the behavior you expected

The graphs should show properly right when the page is loaded.

### Steps to reproduce the issue

1. Open Energy Dashboard
2. Individual graphs sometimes show as they should
3. Change view from current mode (day/week/month/year) to another mode
4. Graphs appear cropped, most of the times not showing the zero kWh mark
5. Hover mouse / touch graphs
6. Graphs pop back into their place
7. Repeat from 3)

### What version of Home Assistant Core has the issue?

2022.8.3

### In which browser are you experiencing the issue with?

Safari, but also the iOS/iPadOS companion apps

### Which operating system are you using to run this browser?

macOS 12.4, iOS/iPadOS 15.6

### Additional information

I notice this behaviour has been happening for quite some time, even before 2022.07, if I recall correctly. I can send a video to show the behaviour.

**Comment by t-luetkenhaus** [comment] 2022-08-26 05:43
I have the same problem. Also, the entity name is not displayed correctly:
![grafik](https://user-images.githubusercontent.com/22255295/186830580-b058d499-a8f9-4125-9355-31f7505e9281.png)

**Comment by thomas-svrts** [comment] 2022-09-06 09:13
it is safari related. duplicate of https://github.com/home-assistant/frontend/issues/10007

**Comment by thomas-svrts** [comment] 2022-09-18 11:28
Fixed in iOS 16

**Comment by t-luetkenhaus** [comment] 2022-09-26 16:27
In my case the issue was cause by selecting a value twice.

**Comment by thomas-svrts** [comment] 2022-12-28 21:13
👍

**Comment by karwosts** [comment] 2023-06-28 20:54
Closing as there are multiple reports that this is fixed here and in the duplicate #10007.

If you still experience this issue, please leave a comment.

**Closed by karwosts** 2023-06-28 20:54 UTC
