### ISSUE TITLE
Netatmo Sensors Icons

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#14920] opened 2022-12-29 21:51 UTC
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have cleared the cache of my browser.

### Describe the issue you are experiencing

On new Beta Netatmo Sensors dont have Icons

![image](https://user-images.githubusercontent.com/42905545/210014269-afb5ed00-5e9e-4c52-b9b2-cd3b0c961549.png)
![image](https://user-images.githubusercontent.com/42905545/210014444-3fea6fae-81e5-4d18-9bd4-b43838d3aada.png)

### Describe the behavior you expected

***

### Steps to reproduce the issue

****

### What version of Home Assistant Core has the issue?

2023.1.1

**Comment by piitaya** [comment] 2023-01-06 15:19
You're using Mushroom chip. The issue is for Mushroom not HA front-end. This will be fixed with a future Mushroom update : https://github.com/piitaya/lovelace-mushroom/pull/931

**Closed by piitaya** 2023-01-06 15:19 UTC
