### ISSUE TITLE
Number of days error when selecting consumption periods in the energy panel

### ISSUE THREAD

**Issue by damianjdaniel** [home-assistant/frontend#20100] opened 2024-03-15 21:13 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello. Checking my electric bill against what was measured in HA with my Shelly, I noticed a huge difference for exactly the same period. I checked Shelly's dashboard and the measurement is correct since it is more similar to what was billed.
The period was from 01/11 to 03/11.
I am writing to you because I found the problem in the period selection in HA. I explain with the values:
1) The bill between 01/11 and 03/11 was 1356kwh
2) In HA in the period from 01/11 to 03/11 it is 1608kwh
3) If I put periods from 01/01 or 01/2 or 01/6 to 03/11 it always gives me 1608kwh.
4) When I detected this possible error, I made the periods for each month separately and added them. So from 01/11 to 01/31 + 02/1 to 02/29 + 03/1 to 03/11 there it did give me an acceptable difference of 1382kwh.
In conclusion, there is some type of error in the selection of energy consumption periods.
Anything I can send you to help you, let me know.
Greetings.

### Describe the behavior you expected

Give me a consumption value close to the invoiced and observed from the manufacturer's dashboard.

### Steps to reproduce the issue

1.In a past month, put different periods within the same month (in my case it was January)
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.3.1

### What was the last working version of Home Assistant Core?

I don t know

### In which browser are you experiencing the issue with?

Google Chrome 122.0.6261.129 (Build oficial) (64 bits)

### Which operating system are you using to run this browser?

Windows 11 Pro 22H2

### Additional information

The device Shelly 3EM

**Comment by karwosts** [comment] 2024-03-15 22:48
Duplicate of #18883

**Closed by karwosts** 2024-03-15 22:48 UTC
