### ISSUE TITLE
History graph won't accept fractions of an hour as duration

### ISSUE THREAD

**Issue by RubenKelevra** [home-assistant/frontend#21842] opened 2024-08-31 13:52 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

![Screenshot_20240831_154828](https://github.com/user-attachments/assets/0b0a8e69-818b-4d6b-9289-2dd9db157ca4)

### Describe the behavior you expected

As it's working fine, fractions should be accepted without error message.

### Steps to reproduce the issue

1. Add a new card to the dashboard
2. Select History Graph
3. Enter a fraction to the duration

### What version of Home Assistant Core has the issue?

2024.9.0b2

**Comment by karwosts** [comment] 2024-08-31 14:01
duplicate of #15933

**Closed by karwosts** 2024-08-31 14:01 UTC
