### ISSUE TITLE
History_graph: reverting back to all data after striking out some items

### ISSUE THREAD

**Issue by PetersPGM** [home-assistant/frontend#9559] opened 2021-07-13 19:35 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I deselect items in the history graph the corresponding lines disappear as intended. But after a few seconds, the lines reappear while the items in the legend still show a strikethrough.

### Describe the behavior you expected

The deselected data lines should not be in the graph.

### Steps to reproduce the issue

1. Click one of the items in the legend
2. Watch the line disappear
3. Wait a few seconds
4. De line appears again and the item is still shown as strikethrough.
![Screenshot 2021-07-13 211650](https://user-images.githubusercontent.com/17383213/125511891-cadfb18f-6d15-418d-ab7f-5e34114f8830.png)

### What version of Home Assistant Core has the issue?

core-2021.7.2

### What was the last working version of Home Assistant Core?

core-2021.6

### In which browser are you experiencing the issue with?

Different versions of Chrome on different operating systems

### Which operating system are you using to run this browser?

Windows 10, Android 10

### Problem-relevant frontend configuration

```yaml
- type: history-graph
          title: Temperatures
          refresh_interval: 3600
          hours_to_show: 48
          entities:
          - entity: sensor.xiaomi_mijia_1_temperature
            name: Livingroom
          - entity: sensor.lywsd03mmc_1_temperature
            name: Livingroom (2)
          - entity: sensor.xiaomi_mijia_2_temperature
            name: Serverroom
          - entity: sensor.da4035_bme680_temperature
            name: Library
          - entity: sensor.l2_libary_th_temperature
            name: Server room
          - entity: sensor.netatmo_boterkorfhoek_innie_temperature
            name: Kitchen
          - entity: sensor.netatmo_boterkorfhoek_sleepie_temperature
            name: Bedroom
          - entity: sensor.netatmo_boterkorfhoek_outtie_temperature
            name: Garden
          - entity: sensor.lywsd03mmc_2_temperature
            name: Bathroom
```

**Comment by mat1990dj** [comment] 2021-07-20 04:34
Reproducing exact same behaviour since color change https://github.com/home-assistant/frontend/releases/tag/20210630.0

**Comment by Petro31** [comment] 2021-07-25 12:50
Very easy to reproduce.  Was just about to write this up.  This still exists in the nightly 7/25.

**Comment by oz9els** [comment] 2021-07-28 12:04
Same issue, reported here: https://github.com/home-assistant/core/issues/52788

**Comment by oz9els** [comment] 2021-08-04 12:54
Issue still exist in 2021.8

**Comment by chairstacker** [comment] 2021-09-09 22:00
Looks like it's been resolved in 2021.9.4 - maybe even sooner

**Comment by oz9els** [comment] 2021-09-10 16:20
Also works here, THANKS guys.

**Comment by spacegaier** [comment] 2021-09-11 08:46
Cannot reproduce it either => will close

**Closed by spacegaier** 2021-09-11 08:46 UTC
Labels: element: chart, bug
