### ISSUE TITLE
iOS: Keyboard closes immediately after typing first digit when editing input_datetime via entities card

### ISSUE THREAD

**Issue by rutgerkra** [home-assistant/frontend#13388] opened 2022-08-16 11:54 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I edit the hour or minute of an input_datetime inside an entities card, the keyboard closes after I type the first digit. This happens both in the iOS app as in any webbrowser.

To get the desired number, I then have to press on the text field again, after which I can type the whole thing without interruption.

I'm probably not formulating it correctly, but the keyboard seems to close every time a **new** digit is added. So say the value is 00, entering 1 closes the keyboard. Now with 01 inside, tapping and entering 1 again does **not** close it, allowing me to enter the second digit. But if I were to enter any other number with 01 inside, the keyboard will close again.

I have recorded a short video of the behavior. I hope this makes everything clear.

https://user-images.githubusercontent.com/7963187/184871645-f6d21676-0568-4ae8-872d-086f254e597d.MP4

### Describe the behavior you expected

Keyboard only closes when both digits have been entered.

### Steps to reproduce the issue

1. Create entities card in dashboard with an input_datetime
2. Open dashboard on iOS device. Does not matter if via the Home Assistant app or web browser.
3. Try to edit the hour or minute to a value that does not start with the same number that is already inside the text field.

### What version of Home Assistant Core has the issue?

2022.8.5

### Which operating system are you using to run this browser?

iOS 15.6

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: input_datetime.alarm_time
```

**Comment by steverep** [comment] 2022-08-17 00:41
Duplicate of #11861

I'll take a look at this soon. Please subscribe to the above issue.

**Closed** 2022-08-17 00:42 UTC
Labels: Duplicate
