### ISSUE TITLE
Integrations page name overflows on long names

### ISSUE THREAD

**Issue by vigonotion** [home-assistant/frontend#5806] opened 2020-05-08 08:37 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

![Screenshot_2020-05-08 Einstellungen - Home Assistant](https://user-images.githubusercontent.com/1506970/81386993-3e5fdf80-9116-11ea-99a1-38dec2f2bd5c.png)
The name of the integration overflows if the text is too long without spaces.

## Expected behavior

Text breaks or has an ellipsis.

## Steps to reproduce

1. Go to integrations page
2. Add ZHA integration and add device by path

alternatively:
1. Go to integrations page
2. Open inspector and inspect any .card-content and edit the \<h2> content to `/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01DRWR-if00-port0`

## Environment

- Home Assistant release with the issue: 0.109.5
- Last working Home Assistant release (if known):
- Browser and browser version: Chromium 81, Firefox 75
- Operating system: Arch Linux

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by Hedda** [comment] 2020-06-08 10:40
Also see https://github.com/home-assistant/frontend/issues/6120

**Comment by Hedda** [comment] 2020-09-07 07:49
Do not think this is fixed yet? And #6120 was closed only because was a duplicate of #5806 so not because this is fixed?

**Closed** 2020-10-17 20:28 UTC
Labels: bug
