### ISSUE TITLE
Blank Frame

### ISSUE THREAD

**Issue by DirtyBird667** [home-assistant/frontend#13733] opened 2022-09-14 08:30 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After update to 2022.9.3 my config/system Frame in different browsers is blank. Also in the App. 

### Describe the behavior you expected

system frame should  not blank

### Steps to reproduce the issue

1.Restart, clear Browsercache, same result
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.9.3

### Additional information

sorry for bad english

**Comment by frenck** [comment] 2022-09-14 08:31
duplicate of https://github.com/home-assistant/frontend/issues/13728

**Comment by ludeeus** [comment] 2022-09-14 08:31
Duplicate of https://github.com/home-assistant/frontend/issues/13728

**Closed** 2022-09-14 08:31 UTC
