### ISSUE TITLE
No way to check boolean states in automations UI

### ISSUE THREAD

**Issue by tannisroot** [home-assistant/frontend#8606] opened 2021-03-09 20:22 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi. Recently, I tried to create an automation with 
a state condition that would check if an attribute of an entity is false or true through UI. As state values to be checked, I typed in false. However, this did not work, because it was setting "false" as a string:
```
- condition: state
    entity_id: fan.bedroom_humidifier
    state: 'false'
    attribute: no_water
```
To make this work, I had to edit the automation through YAML editor to remove the quotes around `false`. After that, it started working properly

### Describe the behavior you expected

Ideally, you would expect the automation UI to be aware of an attribute of an entity being boolean and only allow to set boolean values for it.
However, if that is not possible or too complicated to implement, automatic conversion of "true" and "false" strings into boolean values would suffice as well, although it seems like a more dirty approach.

### Steps to reproduce the issue

1. Create an automation through UI, add any trigger with any action
2. Add a condition that checks the state of an 
entity attribute that is boolean.
3. Type in `false` as the state and save.

### What version of Home Assistant Core has the issue?

core-2021.3.3

### In which browser are you experiencing the issue with?

Home Assistant Android App

### Which operating system are you using to run this browser?

Android 11 (Galaxy S10e)

### State of relevant entities

speed_list:
  - Low
  - Medium
  - High
  - Humidity
preset_modes: []
speed: null
percentage: 0
percentage_step: 25
preset_mode: null
model: deerma.humidifier.jsq
temperature: 23
humidity: 58
mode: 1
buzzer: true
target_humidity: 0
led: true
no_water: false
water_tank_detached: false
friendly_name: Bedroom Humidifier
supported_features: 1

**Comment by tannisroot** [comment] 2021-03-09 20:24
Forgot to note, if I edit my automation that is affected by this again, Web UI changes the state back to a string.

**Comment by Skaronator** [comment] 2021-03-13 17:50
I just run into the exact same issue. When you switch to the YAML editor and change it to a bool and hit save everything works as excepted but when open the automation again it'll be converted to a string again.

**Comment by Zocker1999NET** [comment] 2021-03-17 00:04
for linking similar issues:
- this issue might be a duplicate of #7708 (or #8029)
- also #7231 describes a similar problem, but with numbers, not with booleans

**Comment by NiklasWagner** [comment] 2021-06-15 05:13
Still an issue with the latest release.

**Comment by tannisroot** [comment] 2021-09-13 06:30
Still an issue in the latest release.

**Comment by janz93** [comment] 2021-09-17 10:13
I can also confirm that this is still an issue.

While reading through the linked issues I found the following conversation:

_Originally posted by @bramkragten in https://github.com/home-assistant/frontend/issues/7231#issuecomment-813540611_
> We will probably remove attribute support from the UI editor

....

_Originally posted by @pascallj in https://github.com/home-assistant/frontend/issues/7231#issuecomment-879088385_
> The bug is still there and attribute support is still present. If attribute support is going to be removed, maybe it's better to label this and related issues as 'wontfix' and be done with it.

_Originally posted by @bramkragten in https://github.com/home-assistant/frontend/issues/7231#issuecomment-879096201_
> This should still be solved

I personally find this UI feature very useful and important for non-tech people to use HA automation.

Yet this conversation makes me unsure which direction this Problem is taking.
@bramkragten could you share some thoughts in which directions this bug should go?

**Comment by Skaronator** [comment] 2021-09-17 11:49
Possible solution could be to have a dropdown to select the data type. Node-Red does that:

![image](https://user-images.githubusercontent.com/2886913/133777669-56197cd3-7dd5-4138-a3c9-27cb7415d91d.png)

(string / number / bool would be enough)

**Comment by emontnemery** [comment] 2021-12-07 09:33
Fixed by https://github.com/home-assistant/frontend/pull/10811

**Closed by emontnemery** 2021-12-07 09:33 UTC
Labels: bug
