### ISSUE TITLE
cannot download logs from addon directly

### ISSUE THREAD

**Issue by Anto79-ops** [home-assistant/frontend#22634] opened 2024-11-02 22:59 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

hello,

running Core 2024.11.0b2, Supervisor 2024.10.4, Operating System 13.2 and Frontend 20241031.0 when i try to download addon logs from settings > addons > (addon) > logs, and selelct, for example 100 lines of logs, and try to donwload it (from Android or Chroma Local), there is no file downloaded and my browser says this:

![image](https://github.com/user-attachments/assets/ba5f94b8-f73d-48f9-8870-f22d4bd75a23)

but I'm able to download the logs when going to  settings > system > logs and then selecting the addon from the drop-down menu there.

### Describe the behavior you expected

download logs from the addons directly

### Steps to reproduce the issue

1. download logs from the addon logs
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.11.0b2

### What was the last working version of Home Assistant Core?

n/a new feature

### In which browser are you experiencing the issue with?

Google Chrome and Android App (latest)

### Which operating system are you using to run this browser?

Windows

**Comment by joostlek** [comment] 2024-11-02 22:59
cc @wendevlin

**Comment by tjorim** [comment] 2024-11-03 09:21
> There is a bug that the /boots endpoint doesn't work. I fixed (or I added a workaround in frontend) this with this PR: #22600
> 
> @tjorim with this fix `/api/hassio/core/logs/boots/0/follow` shouldn't be called anymore, please try it out after an update.

While the core logs indeed load now, it still gives an error in the dev console:
`GET https://x.y.z/api/hassio/core/logs/boots/0 400 (Bad Request)`

**Comment by tjorim** [comment] 2024-11-03 09:33
Also noticed this a few days ago except it was in settings > system > logs where the full logs were not loading. Let me see if I can still reproduce it on b2. Opening DevTools I saw this:
```
       Failed to load resource: the server responded with a status of 400 (Bad Request)
/api/hassio/core/logs/boots/0/follow?lines=100:1 

       GET https://xyz.example.com/api/hassio/core/logs/boots/0/follow?lines=100 400 (Bad Request)
fetch-with-auth.ts:20 
```

**Comment by wendevlin** [comment] 2024-11-03 09:40
Hello,

There is a bug that the /boots endpoint doesn't work. I fixed this with this PR: https://github.com/home-assistant/frontend/pull/22600

@tjorim with this fix `/api/hassio/core/logs/boots/0/follow` shouldn't be called anymore, please try it out after an update.

@Anto79-ops Since supervisor has it's own frontend, the issue still exists at the addons. The PR to fix this is here but not merged and released yet: https://github.com/home-assistant/supervisor/pull/5383

**Comment by tjorim** [comment] 2024-11-03 09:44
@wendevlin Great, thanks for the feedback. Will that PR also resolve the issue I just created #22641?

**Comment by tjorim** [comment] 2024-11-03 11:18
> There is a bug that the /boots endpoint doesn't work. I fixed (or I added a workaround in frontend) this with this PR: #22600
> 
> @tjorim with this fix `/api/hassio/core/logs/boots/0/follow` shouldn't be called anymore, please try it out after an update.

While the core logs indeed load now, it still gives an error in the dev console:
`GET https://x.y.z/api/hassio/core/logs/boots/0 400 (Bad Request)`

**Comment by wendevlin** [comment] 2024-11-06 09:26
Hi @tjorim,
With supervisor 2024.11.0 the issue should be solved.

**Closed by wendevlin** 2024-11-06 09:26 UTC
