### ISSUE TITLE
Z-Wave configuration value text is truncated

### ISSUE THREAD

**Issue by kpine** [home-assistant/frontend#17412] opened 2023-07-27 05:23 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For config values with select inputs (at least), if the text is too long it's truncated from the display. Thus I can't see what the full meaning of the setting is.

- If the HA browser window is too wide, it's truncated
- If the HA browser window is too narrow, it's truncated
- My mobile device screen is too narrow, so  it's truncated
- For this particular example, there is an exact window width that does show the fully text

The full text is:

> Garage door mode (momentary mode) for relay and door sensor (open/close) for input

All that is visible is:

> Garage door mode (momentary mode) for relay and door sens

### Describe the behavior you expected

The full text should be readable for all window sizes.

### Steps to reproduce the issue

1. Go to the Z-Wave configuration page for a Z-Wave device
2. Look at a config value that has long text, so it's truncated

Occurs in both Chrome and Firefox.

### What version of Home Assistant Core has the issue?

2023.7.3

### In which browser are you experiencing the issue with?

Google Chrome 115.0.5790.110

### Which operating system are you using to run this browser?

Windows 10

### Additional information

This specific device is a [ZEN17](https://devices.zwave-js.io/?jumpTo=0x027a:0x7000:0xa00a:0.0).

Screenshot examples:

![image](https://github.com/home-assistant/frontend/assets/791794/73a2eaf2-b7dc-49a9-9461-60ed7ee37b3f)

![image](https://github.com/home-assistant/frontend/assets/791794/438bbf54-6ab8-431d-b2ff-28f4cdbad157)

Compare to Z-Wave JS UI, which doesn't have an issue.

![image](https://github.com/home-assistant/frontend/assets/791794/1abe18d7-6f26-4283-9fa1-7a0e635040a5)

![image](https://github.com/home-assistant/frontend/assets/791794/321bd4f0-0dee-49e2-a844-f36b70c0af77)

**Comment by karwosts** [comment] 2024-04-21 15:09
Duplicate of #13070

**Closed by karwosts** 2024-04-21 15:09 UTC
