### ISSUE TITLE
Lightwave change switch after reboot

### ISSUE THREAD

**Issue by sven41** [home-assistant/frontend#11661] opened 2022-02-11 17:36 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when I restart HA the switches change to 2 buttons.... When I press 1 time on the switch, it is back on the screen.

### Describe the behavior you expected

when I restart HA the switches change to 2 buttons.... When I press 1 time on the switch, it is back on the screen.

### Steps to reproduce the issue

when I restart HA the switches change to 2 buttons.... When I press 1 time on the switch, it is back on the screen.

### What version of Home Assistant Core has the issue?

core-2022.2.5

### In which browser are you experiencing the issue with?

Firefoxx

### Which operating system are you using to run this browser?

Windows 11

### Additional information

![Schermafbeelding 2022-02-11 183321](https://user-images.githubusercontent.com/60574634/153640496-e915a369-59ea-47b7-880f-67fcb4c98f32.png)

**Comment by kpfleming** [comment] 2022-03-15 18:49
This appears to be a duplicate of https://github.com/home-assistant/core/issues/67545.

**Closed** 2022-03-15 22:21 UTC
Labels: Bug
