### ISSUE TITLE
Several text boxes don't appear when using the iOS 16.4 public beta

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#15496] opened 2023-02-19 03:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After installing the iOS 16.4 public beta (20E5212g), some text boxes don't appear in the UI.  In particular, the template dev tool doesn't show the editable text box, but does show the template output, and the States dev tool doesn't show the attributes at the top after tapping on an entity.  This happens both in a Safari browser session and in the companion app.  Same behavior occurs on both iPhone and iPad running a 16.4 build, and text boxes appeared normally in iOS 16.3.

![640D2884-2308-4683-A6A4-2DD2CBCDDC33_1_201_a](https://user-images.githubusercontent.com/860888/219910302-30f8c62b-2db3-476e-8bb9-fdf561d23729.jpeg)

![0F130872-E9C6-48E0-9CA6-3F8DD8FEB71B_1_201_a](https://user-images.githubusercontent.com/860888/219910311-b4151be5-33a3-45a3-a160-a24dd94aa423.jpeg)

It also affects the "Edit as YAML" text boxes, which also don't appear onscreen, and there are probably others. My guess is that it affects all CodeMirror boxes.

### Describe the behavior you expected

I expect editable text boxes to appear in the UI as they did in iOS 16.3 and on other platforms.  The exact same Home Assistant instance displays properly on all non-iOS platforms, and iOS platforms running iOS 16.3.

### Steps to reproduce the issue

1. Install the iOS 16.4 public beta
2. Go to the template dev tool
3. See if the editable text box appears
4. Go to the states dev tool
5. Click on an entity
6. See if the attributes appear at the top

### What version of Home Assistant Core has the issue?

core-2023.2.5

### In which browser are you experiencing the issue with?

Safari in iOS 16.4

### Which operating system are you using to run this browser?

iOS 16.4 public beta (20E5212g)

**Comment by rccoleman** [comment] 2023-02-21 18:35
As mentioned in https://github.com/home-assistant/frontend/issues/15513, I can also reproduce the same in Safari in MacOS Ventura 13.3.  No problem with Chrome.

**Comment by piitaya** [comment] 2023-02-22 09:26
I can reproduce the problem on Safari Developer Preview.
`ha-code-editor` relies on `codemirror` package and `codemirror` relies on `style-mod` package.

In `style-mod` we have these lines : 

```js
this.sheet = new CSSStyleSheet;
root.adoptedStyleSheets = [this.sheet].concat(root.adoptedStyleSheets);
adoptedSet = this;
```
https://github.com/marijnh/style-mod/blob/5a66833b514807e7e23328d46406835b68aa672a/src/style-mod.js#L92-L94

`[CSSStyleSheet].contact([])`  should return `[CSSStyleSheet]` but return `[CSSStyleSheet, []]`

**Comment by fightingmajor** [comment] 2023-02-23 15:29
This started with the latest betas for MacOS as well as IOS.  This affects the companion app for Mac as well as IOS.  This also prevents you from editing yaml inside of the ui.
<img width="987" alt="Screenshot 2023-02-21 at 12 20 06 PM" src="https://user-images.githubusercontent.com/17260650/220953283-ba9bb60b-fd99-41c1-955f-4c642fcc086f.png">

**Comment by mb695** [comment] 2023-02-26 08:23
I am using macos 13.3 beta and us homeassistant with mariadb addon.  I could only configure mariadb using chrome or firefo due to the issue above.  But whenever I try and restart homeassistant using safari then recorder, history etc cant load.  Can only restart using chrome or firefox.

**Comment by jblsd** [comment] 2023-03-01 04:14
I just updated my iPad to iPad OS 16.4 Developer Beta 2 with no change in functionality.

**Comment by fightingmajor** [comment] 2023-03-07 21:11
OSX and IOS Beta's that came out today and the issue remains.

**Comment by HybridRCG** [comment] 2023-03-07 21:35
Super annoying. Hope Apple or HA fixes it.

**Comment by jblsd** [comment] 2023-03-08 03:59
No difference with 16.4 beta 3 that was just released.

**Comment by piitaya** [comment] 2023-03-13 10:47
It will be fixed with https://github.com/home-assistant/frontend/pull/15805

**Closed** 2023-03-13 10:48 UTC
