### ISSUE TITLE
Login and registration password fields incorrectly defined - apple keychain doesn't recognize these correclty

### ISSUE THREAD

**Issue by rtheron** [home-assistant/frontend#15148] opened 2023-01-20 06:58 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

this one is browser specific to safari - but at both registration and login, the password fields have incorrect metadata, so keychain does not a) suggest a password correctly at registration, and b) input the registered password for login credentials

### Describe the behavior you expected

at registration, password fields should be auto populated with keychain suggested password (this may have been corrected as I only registered once using a previous version)

at login, keychain should populate user/password fields with biometric authentication - this does not currently happen

### Steps to reproduce the issue

registration:
1. register a user on new homeassistant instance using safari browser

login:
1. log in to a homassistant instance with a keychain registered user/pwd on the homassistant sign in page (local)

### What version of Home Assistant Core has the issue?

2023.1.6

### In which browser are you experiencing the issue with?

safari 16.2

### Which operating system are you using to run this browser?

Mac OS Ventura 13.1

**Comment by pomeloy** [comment] 2023-01-20 14:18
Duplicate of #10274

**Comment by steverep** [comment] 2023-01-20 15:12
Duplicate of #10274

**Closed by steverep** 2023-01-20 15:12 UTC
