### ISSUE TITLE
Energy dashboard desktop layout is using  half of the screen browser

### ISSUE THREAD

**Issue by Youngemmy5956** [home-assistant/frontend#18522] opened 2023-11-03 01:22 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All the cards in the energy dashboard is using a 50% width of the viewport.

### Describe the behavior you expected

The energy dashboard should use all the space in the viewport width-wise.

### Steps to reproduce the issue

1.Open the energy dashboard in desktop view.

2. View them with different browser.
![qws](https://github.com/home-assistant/frontend/assets/85987314/6f27651e-cb38-46da-9ba1-f796e853fd3e)

### What version of Home Assistant Core has the issue?

2023.11.0

### What was the last working version of Home Assistant Core?

2023.10.x

### In which browser are you experiencing the issue with?

Chrome, edge

### Which operating system are you using to run this browser?

win10

**Comment by ildar170975** [comment] 2023-11-03 02:07
Do you have card-mod installed?

**Comment by karwosts** [comment] 2023-11-03 05:01
Duplicate of #18514

**Closed** 2023-11-03 05:13 UTC
