### ISSUE TITLE
Light/Dark Theme mode not working as expected

### ISSUE THREAD

**Issue by kaizersoje** [home-assistant/frontend#12260] opened 2022-04-08 11:35 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have got `Backend-selected` on my profile page.

![image](https://user-images.githubusercontent.com/54566217/162336121-65c1dc9f-f215-46ef-a91d-be5a51249465.png)

Calling the service from Developer Tools does not do anything.

```
service: frontend.set_theme
data:
  mode: dark
  name: Github Dark Theme
```

Also, the theme stays either on Light or Dark mode. It does not seem to switch between the modes or themes. I have an automation that sets the theme but it does not seem to switch.

```
automation:

  - alias: Set Day/Night Theme
    id: set_daynight_theme
    initial_state: true
    trigger:
      - platform: state
        entity_id: sun.sun
        to: above_horizon
      - platform: state
        entity_id: sun.sun
        to: below_horizon
      - event: start
        platform: homeassistant
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: sun.sun
                state: above_horizon
            sequence:
              - service: frontend.set_theme
                data:
                  name: oxfordblue
          - conditions:
              - condition: state
                entity_id: sun.sun
                state: below_horizon
            sequence:
              - service: frontend.set_theme
                data:
                  mode: dark
                  name: Github Dark Theme
        default: []
```

### Describe the behavior you expected

I expect the themes to switch based on the automation. 

### Steps to reproduce the issue

1. Set theme to `Backend-selected` in profile page
2. Call `frontend.set_theme` service for a theme with dark mode. Before doing so, use a light theme.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.4.1

### What was the last working version of Home Assistant Core?

core-2022.3.5

### In which browser are you experiencing the issue with?

Chrome Version 99.0.4844.84 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10 Enterprise 20H2

**Comment by einschmidt** [comment] 2022-04-08 11:57
To add further information for this ticket:

The selected theme has a `dark` mode only. 

According to the documentation, the selected theme should behave like described here:
https://www.home-assistant.io/integrations/frontend/#dark-mode-support

Especially:
```
Since this example theme only has a `dark` mode defined, this mode will automatically be used.
```

Now, independent of the `dark only` mode, it seems the OS light mode overwrites some of these behaviors.

By the way, in my testing, everything worked fine once the OS light setting has been changed to `Dark`.

**Comment by kaizersoje** [comment] 2022-07-08 06:40
Has this been addressed?

**Comment by snickers2k** [comment] 2022-07-26 23:22
same problem here

**Comment by victorvcunha** [comment] 2022-08-20 14:35
same problem here.

**Comment by kaizersoje** [comment] 2022-11-23 07:02
same problem here.

**Comment by cdemi** [comment] 2022-12-18 21:27
I have this same issue. It looks like the theme mode preference is always overridden by the Personal Profile theme mode (which cannot be disabled)

**Comment by irovder** [comment] 2023-01-25 22:00
Still same problem with theme mode setting.

**Comment by gmarchett** [comment] 2023-06-13 21:48
Same problem here

**Comment by karwosts** [comment] 2023-06-14 22:10
I think this is likely duplicate of #11405. I did try to explain a bit there how I believe that this works, it was not intuitive to me at first. Perhaps we can keep all the discussion on one thread.

**Comment by karwosts** [comment] 2023-07-01 14:45
Duplicate of #11405

**Closed** 2023-07-01 19:50 UTC
