### ISSUE TITLE
Entity history flatlines/freezes

### ISSUE THREAD

**Issue by tombadog99** [home-assistant/frontend#14388] opened 2022-11-15 16:29 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Climate entity history graph freezes/flatlines. This seems to be caused by a caching issue as refreshing the browser page or completely closing and reopening the HA Android app causes the entity graph to be reloaded properly. 

### Describe the behavior you expected

Climate entity graph loads and displays correct graph information.

### Steps to reproduce the issue

1. Open climate entity history on a specific entity
2. Leave browser window open/don't force close Android app
3. Return to Android app/browser window, graph reloads but has flatlined.
...
![Screenshot_20221113-075002](https://user-images.githubusercontent.com/70843749/201973289-5fe4c2fd-21c7-4919-a67d-b91a6df56d9a.png)

### What version of Home Assistant Core has the issue?

2022.11.2

### In which browser are you experiencing the issue with?

Google Chrome Version 107.0.5304.107 / latest HA Android companion app

### Which operating system are you using to run this browser?

Windows 11/Android 13

**Comment by PierreAronnax** [comment] 2022-12-11 11:06
I am having the same issue, so I looked at the websocket messages and it looks like the history is correctly requested, but nothing is received from the server.

Opening History the first time at 10:13:41
Request:
`{"type":"history/history_during_period","start_time":"2022-12-10T10:13:41.870Z","end_time":"2022-12-11T10:13:41.870Z","significant_changes_only":false,"include_start_time_state":true,"minimal_response":true,"no_attributes":false,"entity_ids":["climate.otgw"],"id":34}`
Received:
`{"id":34,"type":"result","success":true,"result":{"climate.otgw": ***`

Opening History the second time at 10:43:34
Request:
`{"type":"history/history_during_period","start_time":"2022-12-11T10:13:41.870Z","end_time":"2022-12-11T10:43:34.002Z","significant_changes_only":false,"include_start_time_state":false,"minimal_response":true,"no_attributes":false,"entity_ids":["climate.otgw"],"id":35}`
Received:
`[{"id":35,"type":"result","success":true,"result":{}},{"id":36,"type":"result","success":true,"result":[{"id":"7f3517c495a54672b733428fe719364d","username": ***`

Opening History the third time at 10:50:33
Request:
`{"type":"history/history_during_period","start_time":"2022-12-11T10:47:27.480Z","end_time":"2022-12-11T10:50:33.181Z","significant_changes_only":false,"include_start_time_state":false,"minimal_response":true,"no_attributes":false,"entity_ids":["climate.otgw"],"id":42}`
Received:
`{"id":42,"type":"result","success":true,"result":{}}`

Full log:
[climate.otgw.txt](https://github.com/home-assistant/frontend/files/10201993/climate.otgw.txt)

**Comment by lubosjerabek** [comment] 2022-12-19 11:54
I think this is a duplicate of https://github.com/home-assistant/frontend/issues/13214

**Comment by tombadog99** [comment] 2022-12-19 12:29
Yes, think that may be the case - didn't find that issue before posting this issue.

**Comment by bdraco** [comment] 2023-01-22 07:45
fixed in 2022.2.x via #15112

**Closed by bdraco** 2023-01-22 07:45 UTC
