### ISSUE TITLE
type: energy-distribution card not updating on wall tablets

### ISSUE THREAD

**Issue by Vinisz** [home-assistant/frontend#16604] opened 2023-05-23 16:59 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hi,

The energy card of type type: energy-distribution is not updating on wall panels/always on tablet devices.
I'm using an always on android tablet with the companion app but this card is the only card that does not update during the day

### Describe the behavior you expected

I expect the card to update normally like any other card (so no need to reload the app all the time)

### Steps to reproduce the issue

1. Open home assistant companion app on android tablet displaying normal dashboard which show this card 
2. Leave it running for couple of hours
3. Noted that the card did not update over time, showing old values.
...

### What version of Home Assistant Core has the issue?

2023.5.3

### What was the last working version of Home Assistant Core?

never worked

### In which browser are you experiencing the issue with?

None, companion app (but saw the same when used in "kiosk" browser mode)

### Which operating system are you using to run this browser?

latest Android

**Comment by criticallimit** [comment] 2023-06-05 07:01
Same here with iPad/Safari

**Comment by regan-a** [comment] 2023-06-05 12:50
I am having the same issue. Running the Home Assistant Companion app on an always-on Amazon Fire HD 10. All other sensors/cards update appropriately except for the Energy Distribution Card.

**Comment by jeroenj1989** [comment] 2023-06-09 09:13
I have the same issue, running on a Raspberry Pi with Firefox, both Firefox and Home Assistant in **kiosk mode**.

**Comment by HAuser2019** [comment] 2023-07-05 09:13
Mine is crashing the app withing 24hours when using one of these energy cards. Cannot show because the log stops when app crashes. With crash I mean flickering dasboard with parts scrabling trough eachother. problem excists since launch. Alwas Using latest > HA, companion app android, android 10, latest webview.

**Comment by brunob45** [comment] 2023-08-08 01:22
Same issue here, on the android companion app

**Comment by hallonstedt** [comment] 2023-08-27 09:55
I have the exact same issue with an always-on android tablet and HA companion 2023.7.5-full.
Manually switching to the Energy dashboard and back to my normal panels forces an update to the energy-distribution card but it  then stays showing the same numbers.

**Comment by karwosts** [comment] 2023-08-28 17:27
Does anyone here claiming to have an issue have any more information to share and more details about how it is not working? Like specific timeframes where they watched it not update for multiple hours, versus what they expected to see?

I checked in a regular web browser and everything seems to be working fine for me. Statistics are generated every hour, and the dashboard auto-refreshes new data at 20 minutes past each hour. Not sure how 20 was decided but that's what it is. 

So if I, e.g., open the panel at 9:50 am, wait until 10:20, then all cards auto refresh to add the 9-10 am data at 10:20am (including distribution card). If you ever refresh the page between X:00 and X:20, then yes you will see the new data before it auto-refreshes, but if you wait, it should show up.

I look at the code for distribution card and it seems to be exactly the same as all the other cards for handling the refresh, I can't see anything that would indicate why it would not work in the same way.

Can anyone observe this issue in a regular web browser, or does that always work? I see lots of comments that companion app doesn't work, but I haven't heard much about what _does_ work, if anything.

**Comment by HAuser2019** [comment] 2023-08-28 17:59
For me problem is not in a browser. Problem is with companion app. Just leave the app open on your tablet for a day. And the next day the (type: energy-distribution) does not refresh OR the whole dashboard is crashed (e.g. scrambled image, flickering, mixedup etc. complete chaos). When I remove the the energy graph from may (custom) dasboard. Then the problem is gone.
Sometimes the app is quit over night (when having a custom dasboard open with (type: energy-distribution)on it) 
With custom dashboard, i mean not the automatically generated one from Home Assistant. But one I fitted together with the only the cards i want to see.
U use no special HACS card or whatever strange things installed. Problem only happens when using the energy cards. The one with the drawing of enery flows. But I als had this same issue with energy-usage-graph card.
**I don't use the Energy date picker. -card**

**Comment by HAuser2019** [comment] 2023-08-28 20:28
Sorry I thought is could be related to the non-refreshing issue. 
We’ll maybe check the CPU load after 24h on Android, and also see if it actually updates to the next day as a test. And not use the additional  datepicker card on the dashboard like I did, assuming it can auto update itself the next day. 
I removed the card from my dashboard so it doesn’t crash every day. I will re-add it now and if I have anything meaningful to say i about it I’ll let ya know. For now I’ll 🤐


Op 28 aug. 2023 om 20:03 heeft karwosts ***@***.***> het volgende geschreven:

﻿
OR the whole dashboard is crashed (e.g. scrambled image, flickering, mixedup etc. complete chaos)

I will look into issues about the card not refreshing as intended. "Crashing" dashboards is off topic for this issue. Feel free to make your own separate issue for that.

**Comment by karwosts** [comment] 2023-08-28 20:31
Hm, again I tested this with android companion app. Plugged it into charger at 11:10am, turned off screen sleep, and just let it sit there. 

Right at 12:20pm all energy cards updated as expected, including the energy-distribution card. 

So far as I can tell, everything is functioning as intended. 

I'll also just remind that "Kiosk mode" is not a supported HA feature, so if you are having issues that can be isolated to using that, they are not tracked here. (Not saying this is due to kiosk mode, but just something to be aware of). 

If anyone has new information (including finding any relevant error messages in logs or console), please share.

**Comment by HAuser2019** [comment] 2023-08-28 20:53
I never turn the screen off. Tablet is on 24/7 Android 10, Allnet Tablet. Displaying only one dashboard page.Op 28 aug. 2023 om 22:31 heeft karwosts ***@***.***> het volgende geschreven:﻿
Hm, again I tested this with android companion app. Plugged it into charger at 11:10am, turned off screen sleep, and just let it sit there.
Right at 12:20pm all energy cards updated as expected, including the energy-distribution card.
So far as I can tell, everything is functioning as intended.
I'll also just remind that "Kiosk mode" is not a supported HA feature, so if you are having issues that can be isolated to using that, they are not tracked here. (Not saying this is due to kiosk mode, but just something to be aware of).
If anyone has new information (including finding any relevant error messages in logs or console), please share.

**Comment by karwosts** [comment] 2023-11-28 06:01
Does anyone notice this problem when observing the Energy dashboard directly, or is it only when placing energy cards on a custom dashboard?

**Comment by HAuser2019** [comment] 2023-11-28 06:07
I never watch the energy dashboard. It’s about the cards in my customized dashboard.

**Comment by karwosts** [comment] 2023-11-28 15:23
I'm curious does your custom dashboard have an energy-date-selection card on it? I found what might be a bug in that card that could possibly be related to this, but it's complicated logic and not easy to test.

**Comment by criticallimit** [comment] 2023-11-28 15:36
mine has the energy-date-selector in my custom dashboard

**Comment by regan-a** [comment] 2023-11-28 20:13
@karwosts, I'm only using the energy-distribution card - no energy-date-selection cards. The Energy dashboard appears to periodically update throughout the day when left open. The energy-distribution card does not automatically update.

**Comment by karwosts** [comment] 2023-11-28 20:52
> The Energy dashboard appears to periodically update throughout the day when left open. The energy-distribution card does not automatically update.

@regan-a Sorry to be pedantic but I really want to get exactly what you mean:
 
Do you mean the energy-distribution card _on the energy dashboard_ does not update, but all the other cards do?

Or do you mean the energy-distribution card on the dashboard does update throughout the day, but it does not update when placed on a custom dashboard?

**Comment by regan-a** [comment] 2023-11-28 22:35
No problem at all.

The energy-distribution card on the energy dashboard seems to periodically update throughout the day (hourly?) when the energy dashboard is left open.

The energy-distribution card on a custom dashboard does not update when the custom dashboard is left open.

**Comment by karwosts** [comment] 2023-11-28 22:37
> (hourly?)

Yep, the cards should be expected to automatically update once an hour at the :20 minute mark.

**Comment by karwosts** [comment] 2023-12-01 01:22
I do think I've observed the issue now and I think I am honing in on the problem, it's some pretty ugly looking asynchronous race condition though and I don't understand it fully yet. (not fixed in 2023.12)

What I think I do know is that if you have a custom dashboard view with energy cards, if you refresh your browser, and navigate to that view for **the first time after refreshing**, and if you leave it on that view and never leave, it will update correctly. 

However I also believe that once you leave that view and go to something else (for 5+ seconds), if you come back to that view again without refreshing, it will fetch data once but no longer continue to update after that. 

If anyone wants to confirm that, would be appreciated.

**Closed** 2023-12-02 22:33 UTC
Labels: panel: energy
