### ISSUE TITLE
 Translation error: INVALID_ARGUMENT_TYPE

### ISSUE THREAD

**Issue by Teddydm71** [home-assistant/frontend#23203] opened 2024-12-07 22:01 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Automation trigger and condition descriptor, specifically entity status, gives Translation error: "INVALID_ARGUMENT_TYPE" when system language is set to Italian.

![image](https://github.com/user-attachments/assets/bdb0193f-0b33-4126-b54f-1e5b8168c36e)

### Describe the behavior you expected

I see the description of condition

### Steps to reproduce the issue

1. Open every automation task
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.12.1

### What was the last working version of Home Assistant Core?

2024.11.4

### In which browser are you experiencing the issue with?

Google Chrome 131.0.6778.109

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment] 2024-12-08 00:27
Duplicate of #23194 (and fixed)

**Closed by karwosts** 2024-12-08 00:27 UTC
