### ISSUE TITLE
Automation: Translation error: INVALID_ARGUMENT_TYPE

### ISSUE THREAD

**Issue by engal89** [home-assistant/frontend#23255] opened 2024-12-11 11:20 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the automation's detail pages, conditions gives - Translation error: "INVALID_ARGUMENT_TYPE" - when system language is set to Italian.
I think is related to issue [https://github.com/home-assistant/core/issues/126222](url)

![image](https://github.com/user-attachments/assets/3ed7e8f1-fd05-4e28-babd-2297331004e9)

### Describe the behavior you expected

Correct translation of the condition

### Steps to reproduce the issue

1. Language set to Italian
2. Go in Settings > Automations
3. Go to an automation's detail page

### What version of Home Assistant Core has the issue?

2024.12.1

### What was the last working version of Home Assistant Core?

2024.12.1

### In which browser are you experiencing the issue with?

Chrome 131.0.6778.109

### Which operating system are you using to run this browser?

Windows 11

**Comment by karwosts** [comment] 2024-12-11 16:28
Duplicate of https://github.com/home-assistant/frontend/issues/23194

**Closed by karwosts** 2024-12-11 16:28 UTC
