### ISSUE TITLE
Blueprint boolean selectors not prompting to save and also not saving in blueprint editor

### ISSUE THREAD

**Issue by aderusha** [home-assistant/frontend#13206] opened 2022-07-15 12:33 UTC
### The problem

There are two issues I've noticed with boolean selectors in blueprints:

1) If you edit a blueprint with one or more booleans, toggling the state of the boolean does not bring up the "save" button.  You have to edit some other selector in order for the "save" button to be presented.
2) If you save a blueprint after toggling the state of a boolean selector, the updated selector state is not persisted to disk.

Here is an example, dummy blueprint that offers a text selector and two booleans: https://gist.github.com/aderusha/e4348da4790af6d0875d2b3baa1762ac

## Process to replicate
1. Import and deploy blueprint: [![Open your Home Assistant instance and show the blueprint import dialog with a specific blueprint pre-filled.](https://my.home-assistant.io/badges/blueprint_import.svg)](https://my.home-assistant.io/redirect/blueprint_import/?blueprint_url=https%3A%2F%2Fgist.github.com%2Faderusha%2Fe4348da4790af6d0875d2b3baa1762ac)
2. Create automation from blueprint
3. Toggle one of the booleans, observe that the "save" button appears.
4. Press "save" and exit out of automation editor
5. Go back to the new automation in the automation editor
6. Toggle one of the booleans, observe that the "save" button does **not** appear.
7. Change the text field
8. Observe that the "save" button now appears
9. Press save and exit out of automation editor.
10. Go back to the automation in the automation editor and observe that the new value for the boolean you changed has not been saved, while the value for the text selector has been saved.
11. Open `automations.yaml` and observe that the updated boolean has not been saved, while the value for the text selector has been saved.

### What version of Home Assistant Core has the issue?

Home Assistant 2022.7.5

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yaml
blueprint:
  name: "Test blueprint toggle saving"

  domain: automation
  input:
    text:
      name: "Text 01"
      default: "Text to save"
      selector:
        text:
    toggle1:
      name: "Toggle 01"
      default: false
      selector:
        boolean:
    toggle2:
      name: "Toggle 02"
      default: false
      selector:
        boolean:

variables:
  text: !input text
  toggle1: !input toggle1
  toggle2: !input toggle2

trigger: []

action: []
```

**Comment by SteveRMann** [comment] 2022-07-23 18:37
Same issue here. In addition, when I use the "click on another parameter" to get the "save" button, the automation is saved as a new automation.  So now the automation is saved two times in automations.yaml

**Comment by aderusha** [comment] 2022-07-23 20:39
@SteveRMann do you see the same issue using the example blueprint from the issue above?  It's a dummy blueprint with no trigger or action to test the basic function.  Curious to see if this stripped-down blueprint is problematic for you.

**Comment by SteveRMann** [comment] 2022-07-23 22:03
"Curious to see if this stripped-down blueprint is problematic for you.
Yes, same results.

**Comment by YAMLcase** [comment] 2022-09-06 00:38
I'm seeing this too with:
```
Home Assistant 2022.8.7
Frontend 20220802.0 - latest
```

**Comment by puzon** [comment] 2022-09-29 21:18
Issue is still present
``` Home Assistant 2022.9.7
Supervisor 2022.09.1
Operating System 9.0
Frontend 20220907.2 - latest ```

**Comment by cymone-smart** [comment] 2022-10-11 20:59
Issue is still present

Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Comment by chjohans** [comment] 2022-10-31 00:33
And still present in release 2022.10.5 - could this please get some attention? It actually breaks automation with templates that use boolean variables - for users that don't know how to manually edit automations.yaml

This issue was driving me nuts as I was creating a template with quite a few boolean variables, until I found this bug report. Please fix someone. :)

**Comment by Tanjohnson99** [comment] 2022-12-03 17:17
Same issue here. Save automation created from blueprint diseapear in the list of automation.

**Comment by karwosts** [comment] 2022-12-24 05:47
I was going to look at this since I've fixed similar things for other automation elements, but I cannot reproduce the original problem. Can anyone confirm it's still an issue in 2022.12.6+?

Every time I toggle a boolean (on->off or off->on) I get the save button, and the yaml correctly reflects the state of the visual editor. 

Am I missing something?

![blueprint](https://user-images.githubusercontent.com/32912880/209423271-0f480b18-2828-48a8-8d1e-45ff50911963.gif)

**Comment by karwosts** [comment] 2023-06-28 21:02
Closing as this appears to be fixed. If you still have an issue, please leave a comment.

**Closed by karwosts** 2023-06-28 21:02 UTC

**Comment by cherryontopknife** [comment] 2023-09-29 14:13
Blueprints do not save correctly for me. Issue persists.

**Comment by cherryontopknife** [comment] 2023-09-29 14:13
I should say, they just don't save at all. The YAML is updated, and the visual editor reflects my changes, but if I leave the page then go back, nothing was saved.

**Comment by cherryontopknife** [comment] 2023-09-29 14:19
I'm stupid, didn't realize that blueprints are saved as automations. Woops.
