### ISSUE TITLE
Browser / App freezing when open Calendar with IOS

### ISSUE THREAD

**Issue by jschinke1067** [home-assistant/frontend#15378] opened 2023-02-07 06:19 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Anytime i open the Calendar in IOS, Safari and also Home-Assistant App freezes immediately.
So it is not possible to see / enter Calendar entries using a Iphone…

### Describe the behavior you expected

I klick „Calendar“ from main menu on the left side…
The calendar starts up and show‘s actual month and the freezes up immediately. I have to kill the Browser to get out, refresh does not help.

### Steps to reproduce the issue

1. Start Calendar
2. Calendar shows up empty snd freezes
3.
4.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.2

### In which browser are you experiencing the issue with?

Safari with ios 16.3

### Which operating system are you using to run this browser?

Ios 16.3

### State of relevant entities

```txt
I have one Google Calendar and 5 local calendars active…
```

### Additional information

calendar freezes in this view:

![Uploading 9375F070-D96A-4668-844D-A5641115B516.png…]()

**Comment by steverep** [comment] 2023-02-07 14:28
Duplicate of #15094

**Closed by steverep** 2023-02-07 14:28 UTC
