### ISSUE TITLE
On any touchscreen device, when dragging a page that contains history graphs with your finger, tip labels will toggle on until they are tapped again in the same spot.

### ISSUE THREAD

**Issue by del13r** [home-assistant/frontend#18670] opened 2023-11-15 20:54 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This has been annoying me since it's introduction in 2023.10
Only now have I been bothered enough to investigate if anyone else noticed it.

This issue is the same as
https://github.com/home-assistant/frontend/issues/18016
however they were on Android, and I am on Apple iOS, hence why I am raising a seperate issue to flag that multiple touchscreen devices on mulitple platforms are affected.

Issue started with 2023.10
Issue occurs in both iOS app and chrome for iOS.

Here is what happens when I use my finger to scroll a page with multiple graphs on it:

![image](https://github.com/home-assistant/frontend/assets/86141523/5022de3c-cddb-49eb-b36e-3b9c4ef10ba9)

Then when I actually want to tap through to a particular graph, the tips shown on the previous page are carried over to the new page and are still visible making it very cluttered and confusing as they are not relevant to the isolated graph being shown.

![image](https://github.com/home-assistant/frontend/assets/86141523/7a4d28de-422c-4457-8611-bf1952af739f)

### Describe the behavior you expected

In 2023.9, I used to be able to drag my finger over graphs and the tip label would dissappear as soon as i released my finger, even when scrolling up and down a multiple graph page.
Now it seems to toggle on the tip label on while I am scrolling with my finger and then it will stay on the screen persistently, even carrying over to the next page.

### Steps to reproduce the issue

1. open a scrollable page with multiple graphs
2. use finger to scroll the page
3. observe tip labels toggling/locking on and persistently displaying where my finger was used to scroll the page.
4. unintentionally tap into detailed view of a graph just by tapping somewhere on the graph.
5. observe the persistent labels from previous page have still carried over to the new page.
...

### What version of Home Assistant Core has the issue?

2023.10 and 2023.11

### What was the last working version of Home Assistant Core?

2023.9

### In which browser are you experiencing the issue with?

Google Chrome for iOS 119.0.6045.109

### Which operating system are you using to run this browser?

Apple iOS 17.1.1

### Additional information

Video here 

https://github.com/home-assistant/frontend/assets/86141523/637ecdeb-30e8-409c-8a04-6330227d7508

**Comment by karwosts** [comment] 2023-11-17 14:28
Duplicate of #18016.

I'll close this as a duplicate so we can keep all the discussion in one spot, I believe that issue now clearly documents that this affects both android and ios, so I think one issue ticket is sufficient.

**Closed by karwosts** 2023-11-17 14:28 UTC
