### ISSUE TITLE
Several Custom weather Cards not showing correctly in Ipad app

### ISSUE THREAD

**Issue by oyvindth** [home-assistant/frontend#21725] opened 2024-08-17 20:12 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating to 2024.8.2, the custom Card Platinum Weather Card is not displayed in the Ipad app. It displays normaly in browsers, and on Iphone, but not on my two Ipads

### Describe the behavior you expected

The Dashboard to be displayed the same on all apps and browsers

### Steps to reproduce the issue

1. Add Platinum Weather custom card from HACS
2.create a card
3.
...

### What version of Home Assistant Core has the issue?

2024.8.2

### What was the last working version of Home Assistant Core?

2024.7.4

### In which browser are you experiencing the issue with?

Ipad app

### Which operating system are you using to run this browser?

Ios 17.6.1

**Comment by oyvindth** [comment] 2024-08-18 09:44
UI in Edge:
![Skjermbilde 2024-08-18 113748](https://github.com/user-attachments/assets/2dd1f25e-0f96-445d-bb61-5909bd8fae47)

UI on iPhone:
![IMG_1555](https://github.com/user-attachments/assets/192fe038-8b83-435a-b338-cc8dc52b7112)
UI on iPAD

![IMG_0001](https://github.com/user-attachments/assets/e55f591d-0902-4a31-8bfe-ff61fd5384c6)

**Comment by steverep** [comment] 2024-08-18 17:22
Duplicate of https://github.com/home-assistant/iOS/issues/2908

**Closed by steverep** 2024-08-18 17:22 UTC

**Comment by steverep** [comment] 2024-08-18 17:25
This is a complicated issue.  For most people, fixes are already in and just need to be merged and/or released.  Please see details in the duplicate.
