### ISSUE TITLE
Editing Icon in helper results in Unresponsive Page

### ISSUE THREAD

**Issue by alexruffell** [home-assistant/frontend#14365] opened 2022-11-11 16:18 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating/editing helpers it is quite easy to cause the page to become unresponsive. My latest instance was when I was trying to change the icon for an input_select from `mdi:calendar-today` to `mdi:calendar-today-outline`. What caused the page to become unresponsive was be selecting the existing icon, and pasting the other one over it which I had just copied from another similar helper. 

<img width="530" alt="image" src="https://user-images.githubusercontent.com/4006944/201382924-5cf10d29-a370-4b63-a4fd-573bf77dd1af.png">

Hitting wait does nothing other than show the same dialog again some time later. Hitting the other button caused several tabs to die which also lead to work loss in node-red.

After refreshing all the "Oh Snap" pages in Chrome, I went back to edit the icon only to find that the helper saved the edit BUT the icon itself did not change !?! in the helper view:

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4006944/201383010-eb0d55c4-7ffe-45c4-9bf2-2a2a711aefbf.png">

And at this point while I can change the icon by typing or picking, it won't change in the helper view. I am therefore forced to delete the helper and create it again which is what I often need to do when I run into issues with helpers (they get 'stuck').

### Describe the behavior you expected

No crash...

### Steps to reproduce the issue

1. Open helper, copy icon
2. Open other helper, paste icon over existing icon
3. Crash...

### What version of Home Assistant Core has the issue?

core-2022.10.2

### In which browser are you experiencing the issue with?

Google Chrome 107.0.5304.89

### Which operating system are you using to run this browser?

Windows 11

**Comment by steverep** [comment] 2022-11-21 20:28
Duplicate of #14147

**Comment by steverep** [comment] 2022-11-21 20:29
Currently being worked but this seems to be a tough bug.

**Closed by steverep** 2022-11-21 20:28 UTC
