### ISSUE TITLE
New Tile card shows color as - color in the raw configuration editor if color is selected in card.

### ISSUE THREAD

**Issue by Kertz1954** [home-assistant/frontend#14208] opened 2022-10-27 08:51 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the raw configuration editor, if a color is selected in the Tile card, I see the following.

      - color: amber
        type: tile
        entity: sensor.sun_next_setting
        show_entity_picture: false

### Describe the behavior you expected

I was expecting to see this

      - type: tile
        entity: sensor.sun_next_setting
        color: amber
        show_entity_picture: false

### Steps to reproduce the issue

1. Create a new Tile card with any entity and save.
2. Check the raw configuration editor. It will show correct syntax.
3. Edit the Tile card and select any color and save.
4. Check the raw configuration editor. It will show incorrect syntax.
...

### What version of Home Assistant Core has the issue?

2022.11.0b0

### In which browser are you experiencing the issue with?

Not an browser issue

### Which operating system are you using to run this browser?

Not an OS issue

### Problem-relevant frontend configuration

```yaml
color: amber
type: tile
entity: sensor.sun_next_setting
show_entity_picture: false
```

**Comment by piitaya** [comment] 2022-12-20 14:58
The order doesn't matter in yaml. However, the issue is fixed in `2022.12`.

**Closed by piitaya** 2022-12-20 14:58 UTC
