### ISSUE TITLE
Statistics card ignore days to show when some data is missing

### ISSUE THREAD

**Issue by luzik** [home-assistant/frontend#15573] opened 2023-02-23 16:14 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have sensor that was unavailable for few weeks and chart shows few months now instead of week

<img width="974" alt="Zrzut ekranu 2023-02-23 o 17 12 08" src="https://user-images.githubusercontent.com/6113774/220965515-3eeaea59-8294-41d1-a2c3-7eef28ccbfea.png">

### Describe the behavior you expected

Card should always show selected number of days, or less than that if values are unavailable

### Steps to reproduce the issue

1. Make some entity record it's statistics
2. Make this statistics unavailable for few days
3. Make entity back again
4. Create statistics card with number of days to show that more than entity working days but not before it was working
5. Statistics should show more days than expected
...

### What version of Home Assistant Core has the issue?

2023.2.5

**Comment by karwosts** [comment] 2023-02-23 16:40
Sounds like duplicate of #15438

**Comment by luzik** [comment] 2023-02-23 16:45
Oh, I missed that !
Hope my use case can help.

**Closed** 2023-02-23 16:45 UTC

**Comment by Lectere** [comment] 2023-02-25 09:38
> Oh, I missed that ! Hope my use case can help.

I sure does Luzik, this confirms that something is in fact wrong with Home Assistant, and that it's not specific to my installation.
