### ISSUE TITLE
Autofill does not pop up on login page

### ISSUE THREAD

**Issue by BH1SCW** [home-assistant/frontend#11001] opened 2021-12-22 06:36 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am using safari and Autofill to login every page.
I found two bugs :

1. when I first type user name and password to login home assistant, it should pop up to ask me if I want to save password,
but nothing happen.

2. After I manually to save password, I reopen page, I focus mouse pointer to user field nothing pop up, it should display user name to let me select.

### Describe the behavior you expected

1, Pop up to ask to save password
2, Pop up user name to let me select.

### Steps to reproduce the issue

1. Open home assistant, input user name and password
2. save user name and password to Safari Autofill
3. reopen home assistant again
...

### What version of Home Assistant Core has the issue?

Newest version
2021.12.4
### What was the last working version of Home Assistant Core?

unkonwn

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

macOS mojave

**Comment by spacegaier** [comment] 2021-12-22 10:52
Please fill out the issue template, especially the HA version. There were some changes made recently, so potentially you are using an old version.

**Comment by BH1SCW** [comment] 2021-12-23 00:54
I am using Newest version 2021.12.4 from docker-compose.
Thanks

**Comment by inferusvv** [comment] 2022-01-05 19:53
It not works, because  login form handled by JS events. It should handle "submit" event on form, then browser will understand that form submit and will ask you about saving credentials

**Comment by merchako** [comment] 2022-02-20 02:33
I'm experiencing this same issue. 

Server:
Home Assistant Core 2022.2.8 on macOS

Client:
Safari 15.2 (17612.3.6.1.6) on macOS Monterey 12.1 and
Safari on iOS 14.8.1

I wasn't prompted to suggest a password or save a password, and even after manually adding login Info to my Keychain, I wasn't prompted to insert it. I'm wondering if this might have something to do with Home Assistant over HTTP.

**Comment by nbakker** [comment] 2022-02-23 21:16
I've experienced this across multiple versions of macOS, Safari, and HA as well, including latest. I think I managed to con Safari into saving the password as far back as 2020 but autofilling those saved credentials stopped working not long after.

**Comment by blakek** [comment] 2022-04-22 12:22
This also happens in Brave browser when using the latest stable version (2022.4.6) of Home Assistant. Like mentioned above, it does not prompt to save the password. In Brave, manually adding the password causes the prompt only for password but not username.

The issue occurs when accessing using an IP address, local hostname, and an HTTPS external address.

The input elements should use the [HTML autocomplete attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete). I don't know Polymer very well, but I _believe_ if the autocomplete attribute were accepted [here](https://github.com/home-assistant/frontend/blob/4f13db317854a9483e09e0a54e6a510045c4c4f1/src/components/ha-form/ha-form-string.ts#L50) and the autocomplete type provided by the forms (don't know where to find that) that'd fix this issue.

---

Related to this issue, I've found that iOS _does_ prompt for the password and fills it in. However, the form fails to log in (verified credentials are correct in iOS Settings). If I press the icon to show the password, the form clears the username/password. Again, I don't know Polymer, but my guess is there's an issue with the forms trying to manage the input values and not storing the entire change caused by autofilling the values.

**Comment by nbakker** [comment] 2022-07-21 13:15
This is still an issue and it's causing difficulty for family members having to periodically re-enter everything manually.

**Comment by bsacharski** [comment] 2022-07-22 18:17
Same thing happens with login form when one uses MFA (TOTP) - the form doesn't use `autocomplete="one-time-code"` so the code generator doesn't kick in.

**Comment by steverep** [comment] 2022-08-31 02:21
Duplicate of #10274

**Closed by steverep** 2022-08-31 02:21 UTC
Labels: Bug
