### ISSUE TITLE
Editing a lovelace card selects wrong entity-id

### ISSUE THREAD

**Issue by dfsx1** [home-assistant/frontend#16179] opened 2023-04-14 01:48 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I edit a lovelace card it suddenly has the wrong entity-id selected in the UI dropdown.

### Describe the behavior you expected

I expect the UI dropdown keep the same entity-id selected as when I saved the card.

### Steps to reproduce the issue

I have 2 entities:
- input_text.xyz
- button.xyz

I add a button card to lovelace, select entity-id **button**.xyz and save it.
When I edit the card it still has **button**.xyz selected.
But as soon as I click the entitity drowdown in the UI editor it suddenly has **input_text**.xyz selected.

Looks like the UI editor always selects the first entity in the dropdown with name .xyz not checking the part before the dot.
This happens not only with a button card, also with a regular entity card and probably all cards.

### What version of Home Assistant Core has the issue?

2023.4.3

**Comment by ildar170975** [comment] 2023-04-14 19:41
> I add a button card to lovelace, select entity-id **button**.xyz and save it.
> When I edit the card it still has **button**.xyz selected.
> But as soon as I click the entitity drowdown in the UI editor it suddenly has **input_text**.xyz selected.

I do not observe this, but I only tested it once:

There are 3 entities with same name `testing_device_class_problem`:
![image](https://user-images.githubusercontent.com/71872483/232135926-f78333e2-4017-4043-8943-f572f60fb65d.png)

Selected `input_boolean.testing_device_class_problem`
![image](https://user-images.githubusercontent.com/71872483/232140062-276da1b4-09ff-4495-b0d6-158b72aad4b9.png)

Saved, opened again - same entity is still selected:
![image](https://user-images.githubusercontent.com/71872483/232140366-c5f7b8ec-6903-4962-b3dc-1e1d51c4d56f.png)

**Comment by karwosts** [comment] 2023-04-14 22:06
I think I can reproduce this:

![same-name-entities](https://user-images.githubusercontent.com/32912880/232162618-0af0a954-cc27-4b8d-b153-40df5f479047.gif)

**Comment by dfsx1** [comment] 2023-04-15 07:17
> I do not observe this, but I only tested it once:

@ildar170975 
Because you saved with already the first item in the dropdown list.
The problem is that when editing it always selects the first item so you have to choose the second item to see it.

When you save a card with the second item **binary_sensor**.testing_device_class_problem
It then unexpectedly changes to the first item **input_boolean**.testing_device_class_problem

**Comment by dfsx1** [comment] 2023-04-15 07:19
> I think I can reproduce this:
> 
> ![same-name-entities](https://user-images.githubusercontent.com/32912880/232162618-0af0a954-cc27-4b8d-b153-40df5f479047.gif) [ ![same-name-entities](https://user-images.githubusercontent.com/32912880/232162618-0af0a954-cc27-4b8d-b153-40df5f479047.gif) ](https://user-images.githubusercontent.com/32912880/232162618-0af0a954-cc27-4b8d-b153-40df5f479047.gif) [ ](https://user-images.githubusercontent.com/32912880/232162618-0af0a954-cc27-4b8d-b153-40df5f479047.gif)

@karwosts yes this is exactly my issue, thank you for reproducing 👍

**Comment by ildar170975** [comment] 2023-04-15 11:44
> Because you saved with already the first item in the dropdown list.
> The problem is that when editing it always selects the first item so you have to choose the second item to see it.

No, here is a case when I selected the 2nd item - it still has has it selected after reopening:
![image](https://user-images.githubusercontent.com/71872483/232216040-298f8863-ee2b-4158-81a1-b801a5e2abe2.png)

**Comment by dfsx1** [comment] 2023-04-15 18:06
@ildar170975 

I don't see another `*.testing_device_class_problem` above that `binary_sensor.testing_device_class_problem` in your example.
So you still selected a 1st item from the list.

> No, here is a case when I selected the 2nd item - it still has has it selected after reopening:
> 
> ![image](https://user-images.githubusercontent.com/71872483/232216040-298f8863-ee2b-4158-81a1-b801a5e2abe2.png)
> 

> 
> Regarding "why `testing_device_class_problem` everything worked fine". 
When testing with domain starting with same letters - `input_number` & `input_boolean` - we see the issue.

I don't think the starting letters are related because [karwosts](https://github.com/karwosts) and me have reported the issue with domains starting with different letters:
- input_text.xyz
- button.xyz

**Comment by dfsx1** [comment] 2023-04-15 18:09
I havent dived into the code enough, but I suspect the html `<select>` element gets multiple `<option>`'s with attribute selected.
The code that selects these options probably doesn't check the entity part before the dot, only the (duplicate) name's.
When a `<select>` element has multiple `<option>` elements with attribute selected, the browser will only select the first one. Except with a `<select multiple>` element offcourse but that is also not what we want here.

**Comment by karwosts** [comment] 2023-04-15 21:14
Seems like maybe a Vaadin issue. I stepped through the initial setup a bit, and at some point it tries to lookup the intiial focused index based on the label/friendly name (the value shown in the textbox), not the selected entity id. 

It just admits it focuses the first item that matches the label. 

```
    /** @private */
    _filteredItemsChanged(filteredItems, oldFilteredItems) {
      // Store the currently focused item if any. The focused index preserves
      // in the case when more filtered items are loading but it is reset
      // when the user types in a filter query.
      const focusedItem = oldFilteredItems ? oldFilteredItems[this._focusedIndex] : null;

      // Try to sync `selectedItem` based on `value` once a new set of `filteredItems` is available
      // (as a result of external filtering or when they have been loaded by the data provider).
      // When `value` is specified but `selectedItem` is not, it means that there was no item
      // matching `value` at the moment `value` was set, so `selectedItem` has remained unsynced.
      const valueIndex = this.__getItemIndexByValue(filteredItems, this.value);
      if ((this.selectedItem === null || this.selectedItem === undefined) && valueIndex >= 0) {
        this.selectedItem = filteredItems[valueIndex];
      }

      // Try to first set focus on the item that had been focused before `filteredItems` were updated
      // if it is still present in the `filteredItems` array. Otherwise, set the focused index
      // depending on the selected item or the filter query.
      const focusedItemIndex = this.__getItemIndexByValue(filteredItems, this._getItemValue(focusedItem));
      if (focusedItemIndex > -1) {
        this._focusedIndex = focusedItemIndex;
      } else {
        this.__setInitialFocusedIndex();
      }
    }
    
     /** @private */
    __setInitialFocusedIndex() {
      const inputValue = this._inputElementValue;
      if (inputValue === undefined || inputValue === this._getItemLabel(this.selectedItem)) {
        // When the input element value is the same as the current value or not defined,
        // set the focused index to the item that matches the value.
        this._focusedIndex = this.__getItemIndexByLabel(this.filteredItems, this._getItemLabel(this.selectedItem));
      } else {
        // When the user filled in something that is different from the current value = filtering is enabled,
        // set the focused index to the item that matches the filter query.
        this._focusedIndex = this.__getItemIndexByLabel(this.filteredItems, this.filter);
      }
    }
    
 
    /**
     * Returns the first item that matches the provided label.
     * Labels are matched against each other case insensitively.
     *
     * @private
     */
    __getItemIndexByLabel(items, label) {
      if (!items || !label) {
        return -1;
      }

      return findItemIndex(items, (item) => {
        return this._getItemLabel(item).toString().toLowerCase() === label.toString().toLowerCase();
      });   
 
 ```

**Comment by ildar170975** [comment] 2023-04-17 00:51
> I don't see another `*.testing_device_class_problem` above that `binary_sensor.testing_device_class_problem` in your example.
> So you still selected a 1st item from the list.

If you read [my post](https://github.com/home-assistant/frontend/issues/16179#issuecomment-1509133492) you could have noticed that there were 2 entities with same name & different domains. I do not know what is "above" or "below" - but the main point is that a selected entity was still selected after save/reopen.

> with domains starting with different letters:
>     * input_text.xyz
>     * button.xyz

Not exactly. The 2nd entity is `input_button`. Check it yourself.

**Comment by dfsx1** [comment] 2023-04-17 08:03
@ildar170975 

> I do not know what is "above" or "below" - but the main point is that a selected entity was still selected after save/reopen.

With 2nd entity I mean the ordering in the entity selector dropdown.
1. whatever.xyz (1st, above)
2. whatever.xyz (2nd, below)

> No, here is a case when I selected the 2nd item - it still has has it selected after reopening:

You claim that you had selected the 2nd item but your screenshot proves otherwise.
The issue is not visible when you save a card with a 1st item from the list.
Domains or different starting letters as you mentioned have nothing to do with this.

**Comment by ildar170975** [comment] 2023-04-17 09:23
> You claim that you had selected the 2nd item but your screenshot proves otherwise.

Please point me to my screenshot which you consider as wrong.
Do you really think I may confuse myself with two different entities? )))
For me everything I did with "testing_device_class_problem" entities is obvious, do not want to hijack the thread with proving it.

**Comment by dfsx1** [comment] 2023-04-17 10:39
> Please point me to my screenshot which you consider as wrong.

Already pointed out that to you [2 replies ago](https://github.com/home-assistant/frontend/issues/16179#issuecomment-1509917231).
I'll try one more time:

> No, here is a case when I selected the 2nd item - it still has has it selected after reopening:
> 
> ![image](https://user-images.githubusercontent.com/71872483/232216040-298f8863-ee2b-4158-81a1-b801a5e2abe2.png)
> 

I see in your dropdown:
- sensor.testing_device_class_**pressure** (unrelated other name)
- binary_sensor.testing_device_class_problem (1st, selected)

I don't see another `*.testing_device_class_problem` above that `binary_sensor.testing_device_class_problem` in your example.
So you never selected the 2nd item from the list as you claimed.

> Do you really think I may confuse myself with two different entities?

I think I can trust my own eyes, yes 🤓

**Comment by ildar170975** [comment] 2023-04-17 10:42
> I think I can trust my own eyes, yes

Yet you missed this probably.
https://github.com/home-assistant/frontend/issues/16179#issuecomment-1509133492

**Comment by dfsx1** [comment] 2023-04-17 10:58
@ildar170975 

> > Yet you missed this probably.

No I did not missed.

> ![image](https://user-images.githubusercontent.com/71872483/232135926-f78333e2-4017-4043-8943-f572f60fb65d.png)

For that one I initially already told you here: https://github.com/home-assistant/frontend/issues/16179#issuecomment-1509605624 that you selected a 1st item.
You even claim there yourself you selected the first:

> Selected `input_boolean.testing_device_class_problem`:

2nd item is the binary_sensor, not the input_boolean you selected

**Comment by ildar170975** [comment] 2023-04-17 11:01
1st, 2nd, above, below - these is not important from a user's point of view.
User expectation: "I select item A - it is still selected after reopen", and this absolutely works in my `testing_device_class_problem` case whatever entity is selected. Period.

**Comment by dfsx1** [comment] 2023-04-17 11:04
Yes it is because this issue is only visible when you select anything except a 1st item (with same name).
And you made a false claim it also works fine with a 2nd item, which is not true.

**Comment by ildar170975** [comment] 2023-04-17 11:08
OK )))
Here are 2 items I have - "input_boolean" & "binary_sensor", same name.
Tell me what test should I perform instead mine to demonstrate the issue.

**Comment by dfsx1** [comment] 2023-04-17 11:13
Save a card with the 2nd item from those 2 items (based on ordering in the entity dropdown list).
Then after saving edit it again and you see that the 1st item is selected instead of the 2nd item you saved it with.

**Comment by ildar170975** [comment] 2023-04-17 11:14
> Save a card with the 2nd item

I do not understand you. Please be more precise. Which entity shall I select?

**Comment by ildar170975** [comment] 2023-04-17 11:25
I am telling you the same the 100th time: it DOES NOT depend which item (input_boolean.testing_device_class_problem, binary_sensor.testing_device_problem) you select first - it always have same item selected after reopen:
-- start creating a new card
-- select itemA
-- save
-- reopen
-- tap on a dropdown field (great "thanks" to Dev team who began displaying useless names instead on precise entity_ids on ~2021)
-- see that the itemA is still selected
-- close the card
-- delete the card
-- now repeat same - but with itemB

Is it enough?

**Comment by dfsx1** [comment] 2023-04-17 11:44
> I am telling you the same the 100th time: it DOES NOT depend which item (input_boolean.testing_device_class_problem, binary_sensor.testing_device_problem)

testing_device_**_class_**_problem
testing_device_problem

are different names?!

**Comment by ildar170975** [comment] 2023-04-17 11:55
Was a typo from my side, cool down, was already posted above.
![image](https://user-images.githubusercontent.com/71872483/232476980-4bda4c32-390d-43fd-9b49-2cd9f27476d2.png)

**Comment by dfsx1** [comment] 2023-04-17 12:20
In your screenshot I notice the name of the input_boolean is missing the underscores.
![problem_underscore](https://user-images.githubusercontent.com/60702962/232482055-5ddd439d-4314-4ead-8e77-ad54ff124d5d.png)

Change the name of the input_boolean "testing device class problem" to "testing_device_class_problem", 
so that it exactly matches the binary sensor.

If you then save a card with the binary_sensor:

![problem_save](https://user-images.githubusercontent.com/60702962/232481351-0e1decc3-aeba-4441-b492-901070365d92.png)

You will see the input_boolean suddenly selected on the next edit:

![problem_edit](https://user-images.githubusercontent.com/60702962/232481397-b958dd2d-f75b-4a41-a304-2efec202d576.png)

**Comment by dfsx1** [comment] 2023-04-17 12:45
> Back to our issue: as I demonstrated several times, if I select `input_boolean.a_b_c` - same entity is selected after reopen; if I select `binary_sensor.a_b_c` - same entity is selected after reopen. And as a user I do not care which of them is "first", which is "second".

Yes because you tested with non identical names.
If you did your test correct from the start with identical names (without underscores missing) that would saved me 25 messages and time.
But I'm cool, as long as you can finaly confirm/reproduce the issue now.

**Comment by ildar170975** [comment] 2023-04-17 12:50
> that would saved me 25 messages and time.

This is not about saving your personal time. I do not care about your time, sorry.
If you are trying to force a user to define names manually, if you think that it is normal to select items based on names instead of unique ids - well, I got your point...

**Comment by dfsx1** [comment] 2023-04-17 13:26
@ildar170975 

I don't care how you created these entity names in such way that they were not identical.
You disqualified your test by claiming they were identical.

> There are 2 entities with same name `testing_device_class_problem`:

They clearly had a difference in underscores.

> if you think that it is normal to select items based on names instead of unique ids

Why you think I posted this issue in the first place 🙄

**Comment by ildar170975** [comment] 2023-04-17 13:52
@dfsx1 
Either you do not understand or trying to play a troll.
Stop wasting other user's time.
I spend too much time for explaining my test - that was useless finally.

**Comment by ildar170975** [comment] 2023-07-21 14:24
Since some recent updates it became worse - none entity is selected in a dropdown list.

![11111Untitled Project](https://github.com/home-assistant/frontend/assets/71872483/8e4a4a04-2e17-413c-adab-65a473317bcb)

**Comment by karwosts** [comment] 2023-07-23 15:05
Closing this as a duplicate of https://github.com/home-assistant/frontend/issues/13692, will try to consolidate this issue there.

**Closed by karwosts** 2023-07-23 15:05 UTC
