### ISSUE TITLE
Condition menu in Automation Editor is not visible

### ISSUE THREAD

**Issue by AJStubbsy** [home-assistant/frontend#5986] opened 2020-05-22 15:58 UTC
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

The **Menu** is not visible for the **Conditions** section of the "Automation Editor". I am able to select and use the **Menu**, just can't see it.

![image](https://user-images.githubusercontent.com/10088946/82685547-49555c80-9c4c-11ea-90e6-bce2992bbde4.png)

## Expected behavior

As with the **Trigger** and **Action** sections, there's usually the 3 dots to show the **Menu**

![image](https://user-images.githubusercontent.com/10088946/82685697-8588bd00-9c4c-11ea-94c6-40d32ce83a0d.png)

## Steps to reproduce

Have a look in the "Automation Editor".

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

Home Assistant 0.110.1
Frontend version: 20200519.1 - latest
I'm using **Chrome** but this was reproduced with **edge**
Win10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment] 2020-05-22 16:09
Duplicate of https://github.com/home-assistant/frontend/issues/5980

**Closed by bramkragten** 2020-05-22 16:09 UTC
Labels: bug
