### ISSUE TITLE
Keyboard closes on single digit date/time input

### ISSUE THREAD

**Issue by wmaillard** [home-assistant/frontend#13005] opened 2022-06-23 19:47 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The keyboard closes on mobile web (Android, Chrome) (and xbox (edge)) when you enter one digit in the date/time ha-base-time-input.ts selector.

E.g. if I am trying to set the time to 12, the keyboard will close when I type 1 (unless you type very quickly).

I can reproduce this on Desktop (Chrome) by clicking on the input, moving the mouse outside of the input, and type 1.  If I try to type another digit, the input is no longer focused.

Probable fix: 
Change `@input` to `@change` here: https://github.com/home-assistant/frontend/blob/535fe2686b145ed99c8a913ae1a7700f3678b7a6/src/components/ha-base-time-input.ts#L186

Ref: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

> Note: The input event is fired every time the value of the element [change](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event)s. This is unlike the change event, which only fires when the value is committed, such as by pressing the enter key, selecting a value from a list of options, and the like.

### Describe the behavior you expected

I should be able to type 12 then hit enter on the mobile keyboard.

### Steps to reproduce the issue

1.  Create a card with a date time picker
2. Try to enter a time on an Android mobile device on Chrome

### What version of Home Assistant Core has the issue?

core-2022.4.3

### In which browser are you experiencing the issue with?

Chrome idk

### Which operating system are you using to run this browser?

Android 11

**Comment by sergeolkhovik** [comment] 2022-07-28 17:42
I cannot enter 2-digit value into time entry as well on desktop, even didn't try mobile yet. 2022.6.7 at the moment.

**Comment by steverep** [comment] 2022-08-17 20:53
Duplicate of #11861 

Please subscribe to the duplicate.  I should have this fixed soon.

**Closed by steverep** 2022-08-17 20:53 UTC
Labels: Duplicate
