### ISSUE TITLE
entities card

### ISSUE THREAD

**Issue by userMak** [home-assistant/frontend#5682] opened 2020-05-01 07:14 UTC
## The problem
Entities Card?

I have set up an entities card for my covers. (tuya)
After the update to 0.109.0 the particular card is not working as it was.
The covers has up and down arrows and a stop sign.
When the covers are completely opened or closed these arrows are working fine (as in preview versions. 

However if the covers are half opened the arrows turned grayed and are working at all.

**I think this has to do with their state which at the time is known.**

If I manually (physical button) close or open the cover (state open or close) after a while the arrows can move up or down again.
Please notice that even if the these arrows are grayed the automation of the cover is working.

## Environment
Home Assistant (hassio) 0.109.0 in Ubuntu
last working: all versions until 0.108.9 

- Home Assistant Core release with the issue: 
- Last working Home Assistant Core release (if known): 
- Operating environment (Home Assistant/Supervised/Docker/venv): 
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by bramkragten** [comment] 2020-05-01 09:36
Duplicate of https://github.com/home-assistant/frontend/issues/5664

**Closed by bramkragten** 2020-05-01 09:36 UTC
