### ISSUE TITLE
Unable to remove device tracker from Person

### ISSUE THREAD

**Issue by Midnitte** [home-assistant/frontend#13351] opened 2022-07-07 09:32 UTC
### The problem

When viewing a person and clicking the "x" to remove a device and clicking update, the device is not removed when viewing the person again.

### What version of Home Assistant Core has the issue?

core-2022.6.7

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Person

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/person/

### Diagnostics information

[homeassistant_companion_log_6-7-2022_5-14-7.txt](https://github.com/home-assistant/core/files/9062208/homeassistant_companion_log_6-7-2022_5-14-7.txt)

### Anything in the logs that might be useful for us?

```txt
2022-07-07 05:21:02 INFO (MainThread) [hass_nabucasa.google_report_state] Connected
2022-07-07 05:21:18 DEBUG (MainThread) [homeassistant.components.person] Subscribe to device trackers for person.chris
2022-07-07 05:21:23 DEBUG (MainThread) [homeassistant.components.person] Subscribe to device trackers for person.chris
```

### Additional information

Others also seem to have the same issue:
https://community.home-assistant.io/t/cannot-delete-tracked-devices-for-person-anymore/400348/22

I've recorded a video of the behavior as well:
https://user-images.githubusercontent.com/49769850/177741747-3fefbbf4-821c-4fb6-b07e-fd6557fc4ac9.mp4

Full device info:
## System Health

version | core-2022.6.7
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.12
os_name | Linux
os_version | 5.15.45
arch | aarch64
timezone | America/New_York

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.25.5
Stage | running
Available Repositories | 1070
Downloaded Repositories | 10

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 18, 2022 at 8:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | us-east-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | failed to load: timeout
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 8.2
-- | --
update_channel | stable
supervisor_version | supervisor-2022.06.2
agent_version | 1.2.1
docker_version | 20.10.14
disk_total | 113.9 GB
disk_used | 8.9 GB
healthy | true
supported | true
board | odroid-n2
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS (0.1.64), File editor (5.3.3), Git pull (7.13.1), Terminal & SSH (9.6.0), Node-RED (12.0.2), Glances (0.16.0), Home Assistant Google Drive Backup (0.108.2), Mosquitto broker (6.1.2), InfluxDB (4.5.0), Samba share (10.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 5
views | 2
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 27, 2022 at 12:26 AM
-- | --
current_recorder_run | July 7, 2022 at 5:20 AM
estimated_db_size | 123.62 MiB
database_engine | sqlite
database_version | 3.34.1

</details>

**Comment by smarthomejunkie** [comment] 2022-08-07 15:57
> > But, it returns after a while and is connected to that person again.
> > At first it seems that it is saved correctly on desktop, but after a while the old state returns.
> 
> Hi Smarthomejunkie, I wonder if your report could be conflating two separate issues. The issue reported here is when a device is removed from a `Person` using a touch device (like the App), the device returns immediately (as it is never actually removed).
> 
> There is another issue/feature that people have experienced (myself included in the past), that when an App is logged in for the first time (or it has to re-authenticate), the App’s `device` is automatically added to the `Person` that logged in.
> 
> This is documented in a [feature request](https://community.home-assistant.io/t/allow-disabling-of-automatic-gps-device-tracker-being-associated-with-user-upon-login-via-ios-mac-app/378309/) and Issue [home-assistant/core#63876](https://github.com/home-assistant/core/issues/63876).
> 
> Could that be the issue you are having? How long after you remove the device, does it return for you?

Hi @Daneish,
I see that my device is connected to my son (being the person). I indeed tested something and logged in as my son on my phone, so that might be the reason why my phone is connected to him (as a person). But, after I remove my phone from his person entity, it seems to be removed. Then, after a while, my phone is again connected to his person entity.

I'm not sure after how much time this occurs. I am trying to create a reproduction path so that it can be reproduced every time, but I did not find it yet. As soon as I find a reproduction path I will let you know.

**Comment by smarthomejunkie** [comment] 2022-08-07 16:03
Ah! I found the reproduction path!

1. Log in with another person's username than yourself on your phone (HA companion app)
2. Your phone is added to that person's entity
3. Log out with the other person's username from your phone
4. Log in with your own username on your phone
5. Close the Home Assistant Companion app
6. Go to Desktop and log into Home Assistant with your own username
7. Check the other person's entity
8. You will see that your phone is connected to this other person's entity
9. Remove your phone from the other person's entity
10. Update the person's entity
11. Your phone is now removed from the other person's entity.
12. Go back to your phone
13. Open the HA Companion app
14. At that moment your phone is again added to the other person's entity <= THIS SHOULD NOT HAPPEN

**Comment by smarthomejunkie** [comment] 2022-08-07 16:04
I will create another issue for this.

**Comment by Daneish** [comment] 2022-08-12 15:17
> Ah! I found the reproduction path!

Nice, glad to hear you were able to pin it down further! Thanks for raising the new issue.

**Comment by dunxd** [comment] 2022-08-16 09:34
Still seeing this behaviour with 2022.8.4 - cannot remove any device tracker from a person using the Android app.

**Comment by bschatzow** [comment] 2022-08-16 17:43
What I don't understand is why devices are added automatically to the person.  I should be able to click on the person and say track this device.  I was told in the forum that that is how it was designed.

**Comment by Daneish** [comment] 2022-08-19 05:53
> What I don't understand is why devices are added automatically to the person.

I agree it would be nice if it was optional instead of mandatory. That said, to keep the conversation in this Issue focused on original bug, we should continue the conversation of Automatic devices being added to a Person over on [this feature request.](https://community.home-assistant.io/t/allow-disabling-of-automatic-gps-device-tracker-being-associated-with-user-upon-login-via-ios-mac-app/378309)

**Comment by bschatzow** [comment] 2022-08-20 08:42
@Daneish I read the feature request that you linked to and am not sure how my comment is not related to this issue "Unable to remove device tracker from Person #13351". Of course I voted on the feature but not sure that that forum is the right place either.  I understand the original logic making it mandatory for mobile apps to add to the person tracker, but there are many times when this does not work and it should be easy to remove them.  The way it works now is I can't track my tablet and phone.  If I leave my tablet home HA believes I am home as my tablet is connected to my router.  
If I loan someone one of my devices (tablet / phone) I can't remove it from the person. I don't want the same tracking on a person I loaned it to as I do to me.
Maybe there is another GitHub discussion about system design?  If there is, I can't find it.

**Comment by smarthomejunkie** [comment] 2022-08-20 08:58
> @Daneish I read the feature request that you linked to and am not sure how my comment is not related to this issue "Unable to remove device tracker from Person #13351". Of course I voted on the feature but not sure that that forum is the right place either. I understand the original logic making it mandatory for mobile apps to add to the person tracker, but there are many times when this does not work and it should be easy to remove them. The way it works now is I can't track my tablet and phone. If I leave my tablet home HA believes I am home as my tablet is connected to my router.
> If I loan someone one of my devices (tablet / phone) I can't remove it from the person. I don't want the same tracking on a person I loaned it to as I do to me.
> Maybe there is another GitHub discussion about system design? If there is, I can't find it.

You can remove it from the person but Uninstalling and installing the companion app. See my other issue that I linked to in the discussion above.

**Comment by dunxd** [comment] 2022-08-20 10:13
The issue I see is inability to remove _any_ devices for a person using the Android app. Most of the people in my household have more than one device associated with them - I'm not having an issue with removing the _only_ one. I am having an issue removing _any_ of them whether they are related to companion app or an IP address tracker etc. It doesn't have anything to do with automatic association of devices with people.

This is only with the Android app. The workaround is to use a desktop browser.

**Comment by bschatzow** [comment] 2022-08-20 14:57
@dunxd 
My issue with all the customization allowed in HA how the mobile app has a mandatory condition to add it to the person. I like adding tracker to all my devices so I can always see where they are.  I do not want them attached to a person.

**Comment by Daneish** [comment] 2022-08-21 07:14
> I read the feature request that you linked to and am not sure how my comment is not related to this issue "Unable to remove device tracker from Person #13351".

> If I loan someone one of my devices (tablet / phone) I can't remove it from the person.

@bschatzow reading your additional comments I may have misunderstood your issue. 

To recap the Issue we are tracking here, as @dunxd mentioned, this occurs when trying to remove any device from a `Person` using a touchscreen. This can be Android, iOS, or Windows, as long as the action is done performed via the touchscreen. There appears to be a bug in the frontend when a user tries to remove a device from a `Person`, the frontend appears like the device has been removed, however it does not actually remove it. Opening the `Person` entity again, shows the device has not been removed.

If this is the same issue you are having, apologies on sending you over to the feature request, this issue is the right place, and the workaround of using a mouse/touchpad to remove the device should get things working again for you, until the bug is patched. 

However, if the app is reinstalled, or needs to re-authenticate, the device may get added to the `Person` again. I had this issue a few months ago with my tablet being assigned to my ‘Person’ but after removing it, in the few months since, it hasn’t re-added itself again. 

According to https://github.com/home-assistant/core/issues/63876, this appears to be designed behaviour.

To request a change be made to this behaviour, again, the [Feature Request to make it optional](https://community.home-assistant.io/t/allow-disabling-of-automatic-gps-device-tracker-being-associated-with-user-upon-login-via-ios-mac-app/378309) would probably be the best place to discuss.

**Comment by bschatzow** [comment] 2022-08-21 17:20
My device kept re-adding when removed via either my phone or tablet.  Seems to work from my computer.  All devices are using Chrome.

**Comment by Stooovie** [comment] 2022-09-06 14:10
Same issue with 2022.8.7 and iOS devices. I don't have any non-Apple ones.

**Comment by wire67** [comment] 2022-09-10 05:04
Same all up-to-date 

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

**Comment by anthonws** [comment] 2022-09-12 23:05
Broken to eternity. We get a while Bluetooth native stack, but a delete button doesn't work via touch... Sad... :(

**Comment by mikkelzzz3** [comment] 2022-09-28 04:52
I am experiencing the same. Sony Xperia 1 IV, newest app update, running newest Home Assistant OS and Core.

**Comment by dunxd** [comment] 2022-09-28 10:44
Are there other places in the UI where the X button works as expected on touchscreens (i.e. deletes the entity rather than clears the text)?  Unfortunately I have broken my phone screen and won't be able to tell until I get a replacement.

From inspecting the code in Chrome, I note that the X button for the image in the Person editing UI handles only the `click` event whereas the X button for devices handles both `click` and `mousedown`.  Is it possible that removing the entity is only handled by mousedown which may not be triggered on touchscreens?

**Comment by Daneish** [comment] 2022-09-28 11:09
> Are there other places in the UI where the X button works as expected on touchscreens (i.e. deletes the entity rather than clears the text)?

Yes, I haven’t tested in great detail, but it appears that when the field can only have one value, like an entity’s icon or area, it clears fine with touchscreen.

I also found another situation that has the bug—clearing member entities from a group.

This is a form that allows multiple values. This can be replicated by navigating to Settings > Devices & Services > Helpers > Create Helper > Group > select any option > enter a Name > select a Member > tap the X with a touchscreen > Submit > open the newly treated group > Group Options. The cleared member should still be there. Performing the action with a touchpad/mouse clears the value successfully.

I’m on mobile at the moment, so can’t checkout DevTools, but would you be able to check that the Group Members also has both `click` and `mousedown`?

**Comment by dunxd** [comment] 2022-09-28 11:24
@Daneish - yes the X for the UI you described also has both `click` and `mousedown` as registered handlers.

**Comment by dunxd** [comment] 2022-09-28 11:36
I note that the UI for selecting Devices in the new Automation UI only uses the `click` event for the X button.

Settings > Automations & Scenes > Create Automation > Start with an empty automation > Add trigger > select Device > choose a device.

Once a device is selected, the X button is only listening for the `click` event.

Perhaps the Person UI is using legacy code?

**Comment by Stooovie** [comment] 2022-09-28 11:41
Also the underlying design assumption is wrong - it auto-adds all devices that use the HA app as trackers, without an user intervention, throwing location-based automations out of whack. Nobody tracks location with an iMac - MAYBE an iPad but probably not.

**Comment by dunxd** [comment] 2022-09-28 11:46
This is mentioned [only a few comments above](https://github.com/home-assistant/frontend/issues/13351#issuecomment-1221485864) - it is a different issue to this one.

**Comment by Daneish** [comment] 2022-09-28 12:41
> I note that the UI for selecting Devices in the new Automation UI only uses the `click` event for the X button.

I can confirm its working for me too. It looks like the reason that one is working, and perhaps the reason it only has the click event, as it can only have one value. 

In testing I found another place where it is broken. The new Automations UI make it easy to see when a change takes effect. In Automations > Add Trigger > State > select an Entity > Tap X with a Touchscreen. The automatically generated Alias at the top of the Trigger card will not update when clearing with a touchscreen, but does update using a touchpad/mouse. Flipping into YAML mode also shows the entity does not get removed using touchscreen, but does with mouse.

Now that’s three separate sections of the UI that allow multiple values where the bug occurs. So it seems more likely that any input that allows multiple values has the bug, and any input that only allows for one value does not have the bug.

**Comment by dunxd** [comment] 2022-09-28 16:06
For the Entities card for dashboards, in the UI where you can select multiple entities, the X also has click and mousedown.

In the Button card, where you can only select a single entity the X also uses both click and mousedown.

**Comment by Daneish** [comment] 2022-09-28 16:39
They both update fine for me using a touchscreen, so there goes my theory on all multi-value fields being bugged.

**Comment by dunxd** [comment] 2022-09-28 16:53
And mine about the presence of mousedown being related since you are seeing both these working with a touchscreen (Android or iOS?).  Oh well.

I did find the code for the ha-entity-picker being used: https://github.com/home-assistant/frontend/blob/dev/src/components/ha-combo-box.ts

I don't see any clues in there, but I am a humble user rather than an experienced developer with the frontend...

**Comment by Daneish** [comment] 2022-12-29 03:39
I just checked on HA 2022.12.6 and I could successfully remove a Device from a Person using touch on an iPhone and an iPad. Can anyone test on Android?

**Comment by jgverweij** [comment] 2022-12-29 06:24
Just checked on Android mobile with HA 2022.12.8 also works ok now 👍

**Comment by Midnitte** [comment] 2022-12-29 10:07
Seems to be working for me on 2022.12.6 (Android app 2022.12.0-full).

Closing ticket since it seems to be solved, Thank you!

**Closed** 2022-12-29 10:07 UTC
Labels: Bug, integration: person
