### ISSUE TITLE
Onboarding and zone setting does not locate correctly - needs address/pluscode support

### ISSUE THREAD

**Issue by canerdianeh** [home-assistant/frontend#15699] opened 2023-03-03 21:36 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When onboarding, location only presents a map and a locate tool which returns incorrect location. No option presented to enter address or plus code for correct geolocation. When attempting to edit location after onboarding with incorrect location, it only presents a map. Still no address or pluscode input, and it's not readily apparent how to edit the location. Dragging the zone across large regions is not useful, and there is no option to adjust the size of the zone, which covers entire neighborhoods. 

### Describe the behavior you expected

Expected the ability to enter an address for location. This option is never presented anywhere. Only option for location is a query to a "service" that returns bad information. 

### Steps to reproduce the issue

1. Start Onboarding
2. Attempt to set location
3. Attempt to correct location within zone editor. 
...

### What version of Home Assistant Core has the issue?

2023.3.1

### In which browser are you experiencing the issue with?

Edge 110.0.1587.57

**Comment by steverep** [comment] 2023-03-05 03:47
Duplicate of #5991

**Comment by steverep** [comment] 2023-03-05 03:57
I marked this as a duplicate mainly because the ability to enter an address has been brought up many times and is being tracked at the linked issue.  It's not impossible, but it's a big task and involves each user having to integrate with a geocoding service, which of course has privacy and API limit considerations.

The part about editing the size of the zone is also widely requested.  It's actually possible to do that in your yaml configuration for the home zone, but not the UI yet.  Ironically, you can edit the radius via the UI for any other zone.

**Closed** 2023-03-05 03:58 UTC
