### ISSUE TITLE
Suggestion: Change default action type in automation UI

### ISSUE THREAD

**Issue by koying** [home-assistant/frontend#9739] opened 2021-08-07 08:13 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a new automation using the Automation GUI, the default action type selected is "Device".
That leads newcomers to HA to use that action type *much* more often than it should, with some undesirable side-effects leaving them puzzled.

Not a bug per se, but I think it should be desirable to have another default, likely "Service Call", which is more in-line with the philosophy of HA.

@balloob @frenck Sorry to tag you, but i's more a "philosophical" suggestion than a pure frontend one.
Sorry to have bothered you if that was thought off, already.

### Describe the behavior you expected

Have "Service Call" as default action in the Automation GUI.

### Steps to reproduce the issue

1. Create an new empty Automation
2. See the "Device" is the default action type

### What version of Home Assistant Core has the issue?

2018.8.3

**Comment by bramkragten** [comment] 2021-08-07 09:59
First of all, this not a bug, so I will close this.

Second, a service call is much harder to understand for a new user of Home Assistant than a device trigger/condition/action.

So I don't agree with you on that.

**Closed by bramkragten** 2021-08-07 09:59 UTC
Labels: bug
