### ISSUE TITLE
Auto login for password managers (like Safari and key chain)

### ISSUE THREAD

**Issue by dawiinci** [home-assistant/frontend#12162] opened 2022-03-30 17:03 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.

### Describe the issue you are experiencing

Password cannot be saved at login using Safari and iCloud key chain.

### Describe the behavior you expected

Passwort should be saved to auto login with password manager - like any other page on the internet...

### Steps to reproduce the issue

1. Fill in user name and password manually 
2. click login
3. logout
4. there is no saved login

### What version of Home Assistant Core has the issue?

2022.3.8

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

macOS monterey 12.3

### Additional information

https://github.com/home-assistant/frontend/issues/3133

I don't understand why the above was closed. The problem is clearly still there.

It works to auto fill IF I add the password manually to the key chain. But even then after the page has loaded, if I click somewhere to cancel the auto login it doesn't come back when I click in the username field. I have to reload the page.

**Comment by fsfikke** [comment] 2022-06-05 22:39
Indeed strange that this still doesn’t work. Given how complicated it is to even figure out what the username is it would be a great help if at least tools like keychain can help manage this.

**Comment by steverep** [comment] 2022-08-31 01:42
Duplicate of #10274

**Closed by steverep** 2022-08-31 01:42 UTC
