### ISSUE TITLE
First Camera stream in the dashboard not starting automarically

### ISSUE THREAD

**Issue by edomasca** [home-assistant/frontend#19799] opened 2024-02-14 12:45 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When loading a specific dashboard in Lovelace with multiple cameras to stream, the first one do not starts automatically while the others do.
Changing the order of the devices causes always the first one to fail doing autoplay. (E.g. it is not an issue related to an entity but only to the first entity in the dashboard whatever it is).
The dashboard has only cameras to steam from UNIFI protect.
If I switch to another dashboard and then I go back to the one with the cameras, then all streams start normally. 
the issue happens then only when loading the page directly to the specific dashboard 
It happens to all browsers and app too.

### Describe the behavior you expected

All cameras should start streaming when opening the specific dashboard (Autoplay)

### Steps to reproduce the issue

1. Create a dashboard with more than one camera to stream (live)
2. Load that specific page directly without switching between dashboards

### What version of Home Assistant Core has the issue?

Core 2024.2.1

**Comment by acshef** [comment] 2024-02-14 23:21
I'm experiencing the same thing. I have a `picture-glance` card with `camera_view: live` and the stream never starts (though it appears to fall back to camera thumbnails as I have those defined for RTSP and Frigate cameras I've tested)

Additional findings:
I receive a JS error in the Chrome DevTools console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'KeySystemFormats')
    at 96996 (96996.w7vKRby48d0.js:1:283711)
    at Function.c (bootstrap:19:32)
    at async a.value (ha-hls-player.ts:112:11)
```

And sure enough this part of the frontend bundle doesn't seem to play well. The offending bundle file "96996.w7vKRby48d0.js" is attempting the following near its end:

```js
var oi = $.KeySystemFormats
  , li = $.KeySystems
  , di = $.SubtitleStreamController
  , hi = $.TimelineController
```

But above that, `$` is initialized to `undefined`:

```js
var $ = void 0
  , G = s($);
```

I'm fairly certain this code comes from https://github.com/video-dev/hls.js, but due to being minified and lacking sourcemaps I'm unable to locate exactly where in `hls.js` these offending lines map to.

**Comment by sdotter** [comment] 2024-02-17 00:20
yeah I am experiencing the same problem

**Comment by nomonkeynodeal** [comment] 2024-02-21 00:04
Came here for this issue.

**Comment by b0mbays** [comment] 2024-02-26 15:14
Experiencing the same issue after updating to 2024.2.x

**Comment by sebastian-bugajny** [comment] 2024-02-26 15:26
Same problem for me since version 2024.2.x

**Comment by bramkragten** [comment] 2024-02-28 21:29
There have been multiple bumps of hls.js in 2024.3, can anyone check if this issue is still there in the beta of 2024.3?

**Comment by sdotter** [comment] 2024-02-28 21:32
Gonna check it

**Comment by bramkragten** [comment] 2024-02-28 21:42
Reproduced the issue in dev 👍

**Comment by sdotter** [comment] 2024-02-28 22:04
Think you already know... but just in case:

`
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'KeySystemFormats')
    at 96996 (96996.w7vKRby48d0.js:1:283711)
    at Function.c (bootstrap:19:32)
    at async a.value `(ha-hls-player.ts:112:11)
`

**Comment by bramkragten** [comment] 2024-02-28 22:15
Yeah, we use the light package of hls, and they replace some packages with `undefined`... and then they import stuff from it 🙃

**Comment by postaccountgh** [comment] 2024-02-29 06:24
Same issue here! I'm back to 2024.1.6 and everythig works fine.

**Comment by alphasixtyfive** [comment] 2024-03-01 20:16
I've noticed that every time I'm opening  `more-info` dialog of any camera, live via never starts and image is just frozen. If I open this or any  other camera again, streaming starts just fine. If I refresh the page it happens again.  The error I'm seeing in dev tools:

![image](https://github.com/home-assistant/frontend/assets/55880648/e0e39ff7-600d-4923-b084-2be2fc2ffd6b)


Belive it is related.

**Comment by woempiej** [comment] 2024-03-01 22:11
Same issue 2024.2.5
See:
https://github.com/dermotduffy/frigate-hass-card/issues/1368

**Comment by DaWheelz** [comment] 2024-03-06 15:01
I'm experiencing the same since 2024.2 and above.

**Comment by woempiej** [comment] 2024-03-07 08:15
Hi all,

The issue is fixed in HA 2024.3.0

**Comment by b0mbays** [comment] 2024-03-07 10:26
2024.3.0 is working for me 👍

**Comment by kenni** [comment] 2024-03-07 10:37
Ditto, 2024.3.0 also seems to work here.

**Comment by crhass** [comment] 2024-03-09 08:17
Ok for me now in 2024.3.0

**Comment by sdotter** [comment] 2024-03-09 09:52
Yep confirm in 2024.3 it's working again.. all streams are loading and playing

**Comment by XBigTK13X** [comment] 2024-03-14 15:47
Adding my vote that upgrading from 
```
Core 2024.2.5
Frontend 20240207.1
```
to 
```
Core 2024.3.0
Frontend 20240306.0
```

Resolved this issue for me on both Firefox and Android.

**Closed** 2024-04-11 11:58 UTC
