### ISSUE TITLE
Safari - Can't Scroll Through Entities

### ISSUE THREAD

**Issue by fishcharlie** [home-assistant/frontend#11584] opened 2022-02-06 23:43 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Can't scroll through entities.

### Describe the behavior you expected

Scrolling to work.

### Steps to reproduce the issue

1. Use Safari Version 15.4 (17613.1.14.1.7)
2. Navigate to Configuration tab
3. Click Devices & Services
4. Click a integrations entries link that has a lot of entries
5. Try to scroll down

### What version of Home Assistant Core has the issue?

core-2022.2.2

### In which browser are you experiencing the issue with?

Safari Version 15.4 (17613.1.14.1.7)

### Which operating system are you using to run this browser?

macOS Monterey 12.3 Beta (21E5196i)

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

The following integration has 67 entities, but only a handful are visible and scrolling doesn't work.

https://user-images.githubusercontent.com/860375/152706552-ca8c5b23-45c7-4323-a0ad-563b273b3ad3.mp4

The same behavior on Brave [Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (arm64)](https://brave.com/latest/):

https://user-images.githubusercontent.com/860375/152706628-34535a54-324b-4d96-874b-031822a9d1a4.mp4

**Comment by BNoiZe** [comment] 2022-02-07 16:48
I can confirm this bug. Same problem on the devices tab.

**Comment by jedisct1** [comment] 2022-02-13 21:34
Same here with Safari 15.4, latest macOS 15.3 beta.

**Comment by bramkragten** [comment] 2022-02-14 19:14
Duplicate of https://github.com/home-assistant/frontend/issues/11495

**Closed by bramkragten** 2022-02-14 19:14 UTC
Labels: bug
