### ISSUE TITLE
Entity picker automatically selects another entity after re-selecting a field (at least in Entities card, history-graph, statistics-graph)

### ISSUE THREAD

**Issue by ildar170975** [home-assistant/frontend#16902] opened 2023-06-13 20:34 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing
This may be reproduced if you have several entities with similar entity_ids (or names).

Start adding a new Entities card.
Select some ONE entity:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/41e0c824-637a-43c9-9ea2-4ed145ba61ba)

Switch to YAML mode, seems OK - the right entity is selected:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/0b621edc-6a1b-4ab0-a5ff-0a8c460878a3)

Save the card.

Reopen the card and select the "entity" field - see that ANOTHER entity is selected:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/b353b93b-3262-49f6-a811-89836e98e458)

DO NOT SELECT this wrong entity, just leave this field.
Switch to YAML - this is brilliant:

![изображение](https://github.com/home-assistant/frontend/assets/71872483/74164c24-a43e-41f0-aa9a-8f95a718b142)

Same for `history-graph`, `statistics-graph` (checked only these).

### Describe the behavior you expected

as above

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.6.0

### In which browser are you experiencing the issue with?

Chrome 114.0.5735.110 

### Which operating system are you using to run this browser?

Win10

**Comment by dfsx1** [comment] 2023-07-17 03:36
This looks like a duplicate of issue #16179

**Comment by karwosts** [comment] 2023-07-23 15:05
Closing this as a duplicate of https://github.com/home-assistant/frontend/issues/13692, will try to consolidate this issue there.

**Closed by karwosts** 2023-07-23 15:05 UTC
