### ISSUE TITLE
Date range picker not respecting locale

### ISSUE THREAD

**Issue by larena1** [home-assistant/frontend#12635] opened 2022-05-08 22:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

https://github.com/home-assistant/frontend/blob/dev/src/components/ha-date-range-picker.ts

The date range picker does not respect client locale. First day of week is Sunday when it should be Monday, according to the locale. This is also an issue when using the quick ranges this week and last week because these will begin Sunday then.

Locale data can be passed through attribute `locale-data`

https://innologica.github.io/vue2-daterange-picker/#usage=

### Describe the behavior you expected

Should respect locale

### Steps to reproduce the issue

1. Use date range picker
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.5.0

**Comment by spacegaier** [comment] 2022-05-09 19:06
I implemented a local solution, but the problem is that no globally usable API exists yet to automatically detect the first day of the week, because Firefox still does not support it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/weekInfo

Some work seems to be ongoing, but nothing final yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1693576

So we would need to add a new user profile setting where users have to manually set it (at least on Firefox).

**Comment by slovdahl** [comment] 2022-06-05 18:07
How is this done for the Energy dashboard? Date+time pickers get this wrong for me (shows Sunday as first day, but it should be Monday), but the Energy dashboard correctly has Monday-Sunday when the "Week" view is selected.

**Comment by slovdahl** [comment] 2022-06-05 18:07
Is this a duplicate of #10970 btw?

**Comment by koying** [comment] 2022-06-06 14:45
> Is this a duplicate of #10970 btw?

I guess ;)

> How is this done for the Energy dashboard

It seems to be hardcoded to ISO (i.e. Monday)
https://github.com/home-assistant/frontend/blob/91cd584b4b5dd57392f42aac7ee2fe9b5b7255c7/src/panels/lovelace/components/hui-energy-period-selector.ts#L197

**Comment by larena1** [comment] 2022-07-10 08:31
@spacegaier do you think on the date range picker on the history panel or elsewhere, it can just be fixed to Monday as on the energy dashboard for a more consistent UX?

**Comment by larena1** [comment] 2022-07-23 13:08
@bramkragten do you think the date range picker in the history panel or elsewhere can just be fixed to Monday as start of week similar to the energy dashboard for a more consistent UX?

**Closed** 2022-10-10 14:58 UTC
