### ISSUE TITLE
home assistant dashboard depends on icons loaded from brands.home-assistant.io

### ISSUE THREAD

**Issue by unclehack** [home-assistant/frontend#21929] opened 2024-09-09 08:59 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Home Assistant is supposed to be usable offline without relying on servers on the Internet. This is one of the reasons why people avoid other platforms and products which can't be used exclusively offline.

https://brands.home-assistant.io/ [1] is used to load the icons of the various integrations and other components. This breaks when using Home Assistant offline on a network without Internet access or the dashboard is opened on a device on which it hasn't been opened before.
There are dependencies on services run by Nabu Casa in a local Home Assistant installation. The Home Assistant installation stops working properly. In this case, the icons stop working.

This isn't reasonable because the integrations shipped with Home Assistant change when Home Assistant is upgraded. It really doesn't make sense to do this.

It's something I've observed when the icons of integrations weren't loading from time to time and when I had to open the Home Assistant dashboard on a machine I didn't use it on before while the Internet connection was down.

Blocking brands.home-assistant.io at the DNS level blocks all of these requests. It also breaks the icons of all integrations.

[1] https://github.com/home-assistant/brands

### Describe the behavior you expected

I expect Home Assistant, its dashboard and all the local integrations to work without Nabu Casa's servers. I expect the icons to be loaded from the Home Assistant instance without any requests to servers on the Internet.

### Steps to reproduce the issue

1. Install Home Assistant
2. Open the web browser's developer toolbar in the network requests section
3. Navigate to the integrations page or to the media browser
4. Observe how the browser makes requests or reuses cached images loaded from brands.home-assistant.io, not from the local Home Assistant

### What version of Home Assistant Core has the issue?

2024.9.1

### In which browser are you experiencing the issue with?

ALL

### Which operating system are you using to run this browser?

doesn't matter

**Comment by karwosts** [comment] 2024-09-09 12:45
Duplicate of #18549

**Closed by karwosts** 2024-09-09 12:45 UTC
