### ISSUE TITLE
Device association with multiple integrations arbitrarily displays primary and deleted integrations

### ISSUE THREAD

**Issue by GitHubGoody** [home-assistant/frontend#15491] opened 2023-02-18 12:08 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Devices that are connected to more than one integration seem to arbitrarily set the integration icon to one that was not used for device adoption or even one that has been deleted.

For example, the Unifi Network integration is also connected to devices like my Apple TV or ESP8266 boards brought in through ESPHome.

### Describe the behavior you expected

In these screenshots, the Apple TVs should depict Apple TV as the primary integration and all of the ESP boards should depict ESPHome.

![8062E1BD-6CF6-47CA-BE12-3E44F3D904A2](https://user-images.githubusercontent.com/46235745/219864817-d13bf0c7-fd97-4d81-b324-7672d1c51f83.jpeg)
![10E6108B-0351-49B4-AA3E-263BD44AE705](https://user-images.githubusercontent.com/46235745/219864818-b88531c6-55f4-4b34-9e1c-3308597e64a9.jpeg)

### Steps to reproduce the issue

N/A

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

HA Companion App 2023.2

**Comment by sagaland93** [comment] 2023-02-20 10:26
In my case I have replaced an integration, but the old integration still shows up.

I’m using ZHA, but deCONZ still pops up - even though the addon and integration is removed.

![image](https://user-images.githubusercontent.com/93126880/220079503-2e1fb733-ebdf-4a9a-a413-7aabed46c730.png)

**Comment by sagaland93** [comment] 2023-02-28 11:41
It seems I may have fooled myself here. Found deCONZ as disabled.
Deleted the integration and now it looks normal.

**Comment by steverep** [comment] 2023-03-06 21:09
If I'm understanding your expectation correctly, this is a duplicate of #14620.  Please confirm.

**Comment by steverep** [comment] 2023-03-07 04:18
Duplicate of #14620

**Closed by steverep** 2023-03-07 04:18 UTC
