### ISSUE TITLE
Thermostat cards not fully working

### ISSUE THREAD

**Issue by mhschmall** [home-assistant/frontend#15672] opened 2023-03-02 05:39 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

2023.3 seems to have broken lovelace thermostat cards, the one with the curved slider. The curved slider no longer functions as a slider.

### Describe the behavior you expected

The curved slider functions like a slider.

### Steps to reproduce the issue

1. install core 2023.3
2. restart
3. try to adjust values on curved thermostat slider, watch while nothing happens.
...

### What version of Home Assistant Core has the issue?

2023.3

### What was the last working version of Home Assistant Core?

2023.2.3

### In which browser are you experiencing the issue with?

firefox

### Which operating system are you using to run this browser?

windows 7 & 11

**Comment by karwosts** [comment] 2023-03-02 05:44
duplicate of #15662, fix just went in

**Closed** 2023-03-02 09:43 UTC
