### ISSUE TITLE
Workday country not configurable via UI

### ISSUE THREAD

**Issue by rgerhards** [home-assistant/frontend#16550] opened 2023-05-16 10:55 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I had the workday sensor configured in YAML and the integration was automatically added on update. When I try to configure from the UI, I cannot edit the country (but the subdivision). See screenshot below.

In `.storage/core.config_entries`, the country is properly configured and I guess (not tested) I could change it there.

![image](https://github.com/home-assistant/frontend/assets/1482123/26caea69-ea35-4a8d-bb31-3352f7e42c45)

### Describe the behavior you expected

Country can be configured via UI.

### Steps to reproduce the issue

1. Have workday sensor configured on older HA version without workday UI
2. update to current version

### What version of Home Assistant Core has the issue?

docker

### What was the last working version of Home Assistant Core?

2023.3

### In which browser are you experiencing the issue with?

Version 113.0.5672.93 (Offizieller Build) (64-Bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by messiuw** [comment] 2023-05-18 16:27
Can confirm that this is also true when using the most recent version of homeassistant and configuring the workday integration via the UI. After the initial setup, the country cannot be changed anymore. Would suggest to show a dropdown above the „Subdivision of Country“ dropdown with the initially selected value

**Comment by gjohansson-ST** [comment] 2023-05-18 16:49
It's by purpose made like this as if you want to change country you should remove this and create a new one. 
I can't even think of a reason why you would like to change country as you can have multiple workday integrations for different countries if for some reason you need to alternate between. 

Anyhow it's by design so will close this.

**Comment by rgerhards** [comment] 2023-05-19 07:01
Thanks for the explanation. While I understand the reasoning, I admit I personally do not think it is sound. But for sure I can live with that. Just let me explain my concerns:

1. It is surprising for a user not at least to see the counter. Especially if the config is auto-upgraded from YAML to GUI. That was the path I took and I wanted to verify that everything was taken over properly (workdays is very important in my config). I was deeply puzzled not to see the country any longer. So I resorted to "the `.storage` path" to see everything was indeed converted correctly. I assume most users do not know they can check the text files for GUI components, so there will remain a doubt. The story is definitely different if you configured via the GUI and configured the country manually.

2. I think the argument that there is no need to change the country is weak as the country sub-division is kept configurable. If the algorithm assumes that the HA installation remains on the same geolocation, there is also no need to change the sub-division and it could also be left out. If one assumes the geolocation can change, then the country can change as easily as the subdivision - at least in Europe. We have some spots where moving a couple of hundred meters changes the sub-divisions, but a similar move can also change the country.

I am fine with keeping things as-is, but I would suggest to consider my argument. I would at least suggest to **show the country**, even if is not configurable (just to remove any doubt, e.g. also when troubleshooting).

**Comment by rgerhards** [comment] 2023-05-19 07:03
> This should also have been reported in core rep and not here in frontend as configuration is all backend.

sry about this, but that's not clear to a non-insider. I went away from core (where I went to first) because I thought this is an GUI issues.

I would appreciate if you could move the issue over to core. I have no permissions here to do that (I regularly do this on my OSS projects, so I know it is possible).

**Closed** 2023-05-21 08:53 UTC

**Comment by simonlbn** [comment] 2023-06-17 14:47
One problem with the current status is that there is no way (that I can see) to verify it's set to the correct country.

For reasons to change it - the holiday Python module has at least once been broken for one country (Ireland) which meant I had to temporarily set it to another country until that got fixed.

**Comment by gjohansson-ST** [comment] 2023-06-17 14:50
If you open options for the entry it should say in the description at the top of the page which country has been configured. 
You can't change but you can see which it is.

**Comment by rgerhards** [comment] 2023-06-20 13:18
> If you open options for the entry it should say in the description at the top of the page which country has been configured.

I do not see this (see screenshot in my initial posting). Where should it be visible exactly?

**Comment by gjohansson-ST** [comment] 2023-06-20 22:23
> I do not see this (see screenshot in my initial posting). Where should it be visible exactly?

Probably some ghosts on this 😆
I apparently did not set it when configuring options so I will add a pr now to add that.
It will then look like this:
![image](https://github.com/home-assistant/frontend/assets/62932417/ff973d57-8c00-4b1e-b641-29d10aadcabf)
