### ISSUE TITLE
When deleting a snapshot, the gui loads 2 sidebars.

### ISSUE THREAD

**Issue by Evers72** [home-assistant/frontend#9025] opened 2021-04-28 17:29 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When deleting a snapshot, the gui loads 2 sidebars.

### Describe the behavior you expected

When i delete the snapshot, the page reloads within the frame and not in total.

### Steps to reproduce the issue

1.Create a snapshot
2.buy me a coffee or a beer while waiting
3.Check the snapshot is ready
4.Delete the snapshot
5.Page reloads including a sidebar (now you got to sidebars)
...

### What version of Home Assistant Core has the issue?

core-2021.4.6

### What was the last working version of Home Assistant Core?

dont know.

### In which browser are you experiencing the issue with?

Edge, Chrome

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
none
```

### Problem-relevant frontend configuration

```yaml
none
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

No

**Comment by Misiu** [comment] 2021-04-28 19:11
Duplicate of https://github.com/home-assistant/frontend/issues/8926. 
P. S.
already fixed

**Closed** 2021-04-29 13:55 UTC
Labels: bug
