### ISSUE TITLE
"A new version of the frontend is available. RELOAD" button is missing in android app

### ISSUE THREAD

**Issue by mib1185** [home-assistant/frontend#21542] opened 2024-08-01 16:27 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

after updating to current beta 2024.8.0b0 in the android app i do not get shown the "A new version of the frontend is available. RELOAD" overlay. Even clearing the app cache via system settings did not fix this. Further on the android app the about screen still shows the old frontend version, while on my pc the correct version is shown

| android app | pc |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/f52fec4e-1673-4f58-ac59-609ac3772fd5) | ![image](https://github.com/user-attachments/assets/a8786f60-0d83-4595-aaef-6c8080e43097) |

unfortunately i'm not such familiar with these deep insides of the frontend, but maybe it is a regrssen of #21177 :thinking: 

### Describe the behavior you expected

The "A new version of the frontend is available. RELOAD" overlay is reliable shown on every frontend update

### Steps to reproduce the issue

1. HA core 2024.7.4 running
2. android app 2024.7.3-full up and running
3. update to current beta 2024.8.0b0
4. expect to see the "A new version of the frontend is available. RELOAD" overlay, but it did not show up

### What version of Home Assistant Core has the issue?

2024.8.0b0

### In which browser are you experiencing the issue with?

android app 2024.7.3-full

### Which operating system are you using to run this browser?

android 14

**Comment by bramkragten** [comment] 2024-08-02 12:13
The file name of the service worker changed, but it should still load the new one, it might be that the old one can not be loaded anymore (as it doesnt exist anymore) and that causes an error somewhere. Do you see any errors in your log?

**Comment by Anto79-ops** [comment] 2024-08-02 16:19
it seems on b1 this is not fixed for me.  https://github.com/home-assistant/frontend/issues/21533
Anyone confirm its fixed for them? At least then I can try to troubleshoot more on my end if its fixed for others thanks.

**Comment by mib1185** [comment] 2024-08-02 19:51
For me it is also not fixed with 2024.8.0b1 on my android app.

**Comment by steverep** [comment] 2024-08-02 23:16
I'll do some research to fix this, but in the meantime...

If the new service worker is not being registered, I'd expect some sort of error in the browser console.  I'm not sure how to access that while running the app, but you can try turning on debug logging for the frontend integration.  That will send any errors to the core log (as long as they occur after the core connection, which may or may not be the case).

Also, does the problem occur only in the app or in the browser on android too?

**Comment by bschatzow** [comment] 2024-08-02 23:22
Browser works fine on my android device.  Only the app.

**Comment by Anto79-ops** [comment] 2024-08-03 00:24
Sure I'd be happy to get logs for you. Can you please tell me how to turn on logging for the front end? I don't think I've ever done that before.

And yes like others have said it's only the Android app that's giving the issue everything else is fine

**Comment by steverep** [comment] 2024-08-03 02:58
> Sure I'd be happy to get logs for you. Can you please tell me how to turn on logging for the front end? I don't think I've ever done that before.

```yaml
logger:
  default: info
  logs:
    homeassistant.components.frontend: debug
```

**Comment by Anto79-ops** [comment] 2024-08-03 18:37
@steverep i added that to configuration.yaml and restarted, After, I made a change the dashboard on Chrome so that it will force a refresh on the app  while I had the dashboard open ( that was log at 12:30 pm). Unfortuantly, there is nothing in the log. I'd be happy to send you the entire log, privately as there are some things in the log with names etc.. My discord handle is Anto79-ops.

**Comment by steverep** [comment] 2024-08-03 18:57
@Anto79-ops no need to send logs if there is nothing in there from the frontend.  You would see an unhandled exception or rejection with a stack trace if there was something to help here.

Let's try something else:
1. Confirm you have the beta installed, and that you are still seeing the old frontend (go to Settings > About and what's the frontend version).
2. Manually refresh. On iOS this can be done just by trying to scroll up past the top of the page, but I'm not sure if that works on android or if there's another way.
If that works and updates the frontend version, then that tells me that the registration is successful but something is stopping the toast message.  If it doesn't work, then android is refusing to register the new service worker for some reason.

Unfortunately I don't have an android device with HA to diagnose this myself, so thanks for bearing with me on the instructions.

**Comment by Anto79-ops** [comment] 2024-08-03 19:12
Oh, check this out. It looks like the app is NOT on beta.

![Screenshot_20240803_130930_Home Assistant.jpg](https://github.com/user-attachments/assets/b6e36a48-7d79-42a6-a190-2e26fb8bda67)

But, on PC Chrome, it's on 20240802.0

This looks like the problem. I'm tempted to delete the app and start all over again, but I don't know if that's a good solution if others are going to run into the same issue.

Yeah, I'm not able to refresh the screen manually on Android. Does anybody know how?

**Comment by steverep** [comment] 2024-08-03 19:21
Don't delete the app - that's what is expected.  Your core version is on beta, but your frontend hasn't updated because a page refresh is needed.  The toast message you see on other browsers is doing nothing but telling you to reload the page (and clicking the refresh button does exactly that).

**Comment by Anto79-ops** [comment] 2024-08-03 19:25
ok, i just have to figure out how to refresh the app. let me ask in the android channnel and report back....thanks

**Comment by steverep** [comment] 2024-08-03 21:55
AFAICT from searching, there's no way to do it unless built-in by the app developer.

If you haven't done so already, can you close the app (not just putting it in the background) and also close all HA tabs in browsers on the same device.  Then reopen the app and check the frontend version again.

**Comment by Anto79-ops** [comment] 2024-08-03 22:16
Thanks, Steve. 

I  "Force Stop" the app, cleared the cache, and opened it again, and it's still at the older frontend version.

**Comment by steverep** [comment] 2024-08-04 04:46
Okay I think I understand **what** is happening, and will submit a probable fix shortly.  I just don't know enough about android web view to say **why** it's behaving like that when other browsers do not.

**Comment by tsvi** [comment] 2024-08-04 05:55
Might this explain why I can't access any of the add-ons in the android app with the beta installed?

**Comment by bschatzow** [comment] 2024-08-04 15:05
Why close before a release of the proposed fix?

**Comment by mib1185** [comment] 2024-08-04 15:30
it is automatically closed because of a merged bugfix PR, the next release will contain this fix

**Comment by steverep** [comment] 2024-08-04 15:56
Actually I'm going to reopen because only the core change was merged.  I ran out of time last night and still need to submit the frontend change.

**Comment by Anto79-ops** [comment] 2024-08-04 16:00
> Might this explain why I can't access any of the add-ons in the android app with the beta installed?

Yes, that is correct.

**Comment by steverep** [comment] 2024-08-04 17:57
I submitted a change that just needs to be reviewed and merged, but should make it into the next beta.  As I said, I don't have an android device setup to fully test, but fairly confident it will solve it. 🤞🏻

**Comment by bschatzow** [comment] 2024-08-04 19:08
@steverep If you want me to test something prior, let me know where I can download the change (s) and I will test it.  Thanks as always to the team for the quick action to resolve issues.

**Comment by steverep** [comment] 2024-08-05 02:50
> @steverep If you want me to test something prior, let me know where I can download the change (s) and I will test it. Thanks as always to the team for the quick action to resolve issues.

I'd expect the next beta tomorrow so that's not worth the trouble to set up.  Thanks for the offer though.

**Comment by tsvi** [comment] 2024-08-05 14:17
Still not working with 2024.8.0b2.
I tried clearing the cace from the all. Nothing. I still get the old UI.

**Comment by mib1185** [comment] 2024-08-05 14:37
can confirm, it is unfortunately still not providing the update/reload button

![image](https://github.com/user-attachments/assets/e2efb334-66ce-4f93-bb44-17c1cc799b96)

**Comment by mib1185** [comment] 2024-08-05 14:41
now i see that the new frontend [20240805.0](https://github.com/home-assistant/frontend/releases/tag/20240805.0) did not get it into 2024.8.0b2, therefor the fix is just not released yet.

**Closed** 2024-08-05 14:45 UTC

**Comment by bschatzow** [comment] 2024-08-05 15:00
Not sure why an untested fix is automatically closed prior to any testing? Doesn't make sense to me.

**Comment by bramkragten** [comment] 2024-08-05 15:10
If a fix has been merged the issue is closed, as we assume the issue was fixed by the fix. If it is not fixed the issue can be reopened or you can open a new issue. Otherwise issues will never get closed, because people often will not close them to report it was fixed, but will report it wasnt fixed.

**Comment by steverep** [comment] 2024-08-05 15:12
> Not sure why an untested fix is automatically closed prior to any testing? Doesn't make sense to me.

The change was tested, just not on the android app, and there is high confidence it solves the problem as it just becomes like any other update in the past.  It can also be reopened at the click of a button.

**Comment by bdraco** [comment] 2024-08-05 15:43
We use GitHub for tracking development, and it does not operate like a traditional ticket system/support desk.  Issues are closed when the PR merges.

**Comment by bschatzow** [comment] 2024-08-05 19:03
Thanks for the clarification. I understand that a new issue can be opened, I don't realize any user could open a closed issue ? I was never able to do this and many times useful information is lost when opening a new issue for the same issue.  Anyway we should know shortly if it is fixed

**Comment by Anto79-ops** [comment] 2024-08-05 19:33
Thanks @steverep and frontend team. All is working for me in b3 now. Cheers!

**Comment by bschatzow** [comment] 2024-08-05 21:32
All good for me as well.
