### ISSUE TITLE
ERROR [frontend.js.latest.202112290] core.360c502d.js:1:9840 3

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#11079] opened 2022-01-03 11:39 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

not even experiencing an issue, but this keeps showing I the log. Really sorry I havent been able to connect it to a user action, but there's no true clue how to go about debugging this further without instructions

### Describe the behavior you expected

no error....

### Steps to reproduce the issue

1. as said, not sure
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.2.0.dev20220103

### What was the last working version of Home Assistant Core?

not sure but at least the last week of dev

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

MacOS 12.0.1 12.0.1 Monterey 12.0.1 

### Javascript errors shown in your browser console/inspector

```txt
2022-01-03 10:06:14 ERROR (MainThread) [frontend.js.latest.202112290] https://mydomain/frontend_latest/core.360c502d.js:1:9840 3
```

**Comment by tempus2016** [comment] 2022-01-03 22:39
I too am getting this error.

```
Logger: frontend.js.latest.202112290
Source: components/system_log/__init__.py:189
First occurred: 22:35:12 (1 occurrences)
Last logged: 22:35:12

https://XXX/frontend_latest/core.360c502d.js:1:9840 3
```

**Comment by Mariusthvdb** [comment] 2022-01-27 10:03
still seeing this in 2202.2.0b0 so not a dev install fluke, purposely updated to the beta to check.

**Comment by spacegaier** [comment] 2022-01-27 11:06
> still seeing this in 2202.2.0b0 so not a dev install fluke, purposely updated to the beta to check.

Can you please provide the exact error location now with the beta. I should have the same, so perhaps we can narrow down the error based on the code location, even though the coding is minified.

**Comment by Mariusthvdb** [comment] 2022-01-27 11:16
it moved to:
```
frontend_latest/core.9023daf4.js:1:9840 3
```
in my setup

**Comment by spacegaier** [comment] 2022-01-27 11:27
So that means it is that green line here, which I think is from `home-assistant-js-websocket`.

![grafik](https://user-images.githubusercontent.com/114137/151349793-1cc28087-8403-4c39-a68b-2eeabe9d1198.png)

**Comment by Mariusthvdb** [comment] 2022-01-27 12:49
tbh, I dont understand where you see that? But, now I check inspector again, I see the error being listed again. Could it be this happens upon loading Inspector??

**Comment by spacegaier** [comment] 2022-01-27 13:48
I just looked in the coding of that JS file at the location specified in the error message (line 1, position 9840) and then "prettied" the coding.

**Comment by Mariusthvdb** [comment] 2022-01-27 14:05
not sure what you're saying now, do you mean you have a 'fix'? or do you want me to do anything?

also, which dashboard it 19 referring to? how can I count my dashboards?

**Comment by balloob** [comment] 2022-02-03 15:56
@Mariusthvdb the "Verzoek" bit, is that from an addon called logviewer served via ingress? I can't see the full URL.

And did you re-open the dashboard before this error occurred ?

**Comment by Mariusthvdb** [comment] 2022-02-04 07:36
yes it is, https://github.com/hassio-addons/addon-log-viewer and is up to date 0.12.2

but it has become way more sporadic... I've only seen it once since this mornings update to latest dev build, and it moved to `core.25b6fb5a.js:1:9840 3`

even tried with 2 windos now, both on Logviewer didnt make it happen. so a bit of a mystery.

**Comment by Mariusthvdb** [comment] 2022-02-04 09:15
right, so this is odd, I see logviewer:

```
2022-02-04 10:04:38 ERROR (MainThread) [frontend.js.latest.202202030] http://hassio.local:port/frontend_latest/core.9a12ab6a.js:1:9840 3
```

but also:
<img width="569" alt="Schermafbeelding 2022-02-04 om 10 09 38" src="https://user-images.githubusercontent.com/33354141/152502765-95674adb-ebc1-4b50-a494-df640c6001c0.png">

note 9840 is now 9841?

clicking that results in:

<img width="573" alt="Schermafbeelding 2022-02-04 om 10 10 45" src="https://user-images.githubusercontent.com/33354141/152502840-6b9ac563-b1e8-4ffd-921e-6396c8555034.png">

full text of that section is enclosed
[frontend_error.txt](https://github.com/home-assistant/frontend/files/8001504/frontend_error.txt)

**Comment by bramkragten** [comment] 2022-02-04 10:01
It means that something (browser-mod?) was sending a message to the backend, but the connection was closed.

It looks like this is from a custom card, and not core frontend.

**Comment by Mariusthvdb** [comment] 2022-02-04 10:58
yes, this one indeed, the others were from logviewer though.

**Comment by bramkragten** [comment] 2022-02-04 12:01
Could this be happening when the HA tab is hidden/inactive for 5 minutes? Can you maybe turn off "auto close connection" option and see if it is gone then?

![image](https://user-images.githubusercontent.com/5662298/152525756-0562d688-a7b8-4404-9374-9d978894ee36.png)

**Comment by Mariusthvdb** [comment] 2022-02-04 13:05
sure, will try.
this is a per browser setting isnt it? as is the error probably?

**Comment by Mariusthvdb** [comment] 2022-02-09 22:02
not really sure the issue @zacwest linked above it the issue at hand here. As Ive been trying to narrow down the source, I disabled Kiosk Node plugin, and havent seen the error since.
Would be nice if people that responded with a +1 here could check/confirm they also use Kiosk mode, and if yes, when disabled see the error gone?

**Comment by skynet01** [comment] 2022-02-10 06:26
@Mariusthvdb I think you are right, I have Kiosk Mode plugin installed and removing it solved this issue for me

**Comment by tempus2016** [comment] 2022-02-10 07:06
I do not use kiosk mode and have the error.

**Comment by Mariusthvdb** [comment] 2022-02-10 07:47
I am afraid you're right... just updated to todays nightly and see 
```
2022-02-10 08:42:47 ERROR (MainThread) [frontend.js.latest.202202030] http://mydomain/frontend_latest/core.9a12ab6a.js:1:9840 3
```

in the startup log again. too bad. it has become less frequent, but now we can say for sure Kiosk mode doesnt cause it. thats a good thing ;-)

**Comment by skynet01** [comment] 2022-02-10 18:08
Hahah yea.. same for me. It came back today even with kiosk uninstalled.

**Comment by maddeuce** [comment] 2022-02-16 05:52
Logger: frontend.js.latest.202202030
Source: components/system_log/__init__.py:190
First occurred: 9:26:21 PM (7479 occurrences)
Last logged: 9:51:26 PM

:0:0 Script error.

This is the same error?

**Comment by maddeuce** [comment] 2022-02-16 05:58
I have this error for couple months now no one can tell me what wrong.  Everyone say is frontend intergradion.  Will guess what I turn off all off and still happen.  Usually it happen once or twice for 2 to 10 minutes per day but log up to 200k errors.   But I just notice 3hrs ago it been reoccurring non stop.  It slow down about 10 error per sec.  Before I seem up to 5000 error per sec.

**Comment by Mariusthvdb** [comment] 2022-02-16 08:12
its still a bit of a mystery indeed. I recently discovered it even happens when all  front-end device are closed, so no HA interface is showing anywhere.
How could a frontend error fire at all.
I then, accidentally, noticed the error happening when I called 'Hey google, do..'  Thought I had found the issue, because ofc we do that also when all devices are closed. But, unfortunately, it didnt reproduce reliably after that...

so still at a loss as for the reason this keeps happening.

**Comment by Mariusthvdb** [comment] 2022-04-23 08:55
```
Logger: frontend.js.latest.202204200
Source: components/system_log/__init__.py:190 
First occurred: 10:31:46 (647 occurrences) 
Last logged: 10:47:56

http://hassio.local:42938/frontend_latest/core.8ff2e18e.js:1:10023 3
:0:0 Script error.

```

**Comment by pedolsky** [comment] 2022-05-23 05:01
I get a bunch of errors of the same `source` after editing automations:

```
Logger: frontend.js.latest.202205041
Source: components/system_log/__init__.py:190 
First occurred: 22. Mai 2022, 22:00:27 (99 occurrences) 
Last logged: 06:45:42

:0:0 Script error.
```

**Comment by maxistviews** [comment] 2022-05-23 12:59
Im getting the following errors:


```
Logger: frontend.js.latest.202205041
Source: components/system_log/__init__.py:190
First occurred: May 22, 2022 at 7:30:38 AM (19 occurrences)
Last logged: 8:25:13 AM

http://192.168.1.118:8123/frontend_latest/core.a0afd420.js:1:9430 Uncaught Error: Suspend promise not set
https://home.maxistviews.com/frontend_latest/core.a0afd420.js:1:10014 Uncaught 3
```

**Comment by fenty17** [comment] 2022-05-23 20:30
My logs are plagued by this sort of error. Tried removing cards with more complex cofigs but didn't work. Seems to happen when opening the app or browser reload (but not when cached). 

```

Logger: frontend.js.latest.202205041
Source: components/system_log/__init__.py:190 
First occurred: 20:10:58 (7 occurrences) 
Last logged: 21:24:46

http://192.168.1.120:8123/frontend_latest/core.a0afd420.js:1:10024 3

```

**Comment by phiberoptick** [comment] 2022-06-04 07:14
I'm a little late to the party but am having the same issue.  I finally noticed it when I decided to try to look into why my Eufy integration stopped working recently and came across this in my logs.

```
Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 10:47:43 (7 occurrences)
Last logged: 23:28:56

https://ha.devnulls-bitbucket.com:8123/lovelace:0:0 Uncaught
https://ha.devnulls-bitbucket.com:8123/lovelace/0:0:0 Uncaught
https://ha.devnulls-bitbucket.com:8123/developer-tools/yaml:0:0 Uncaught
https://ha.devnulls-bitbucket.com:8123/config/dashboard:0:0 Uncaught
```

**Comment by cplagz** [comment] 2022-06-09 03:29
I had a similar issue when trying to edit cards on Lovelace UI
`Logger: frontend.js.latest.202206010
Source: components/system_log/__init__.py:190
First occurred: 10:35:08 AM (13 occurrences)
Last logged: 10:35:08 AM

http://HA.URL:8123/frontend_latest/core.446aadfa.js:1:10014 Uncaught 3`

![image](https://user-images.githubusercontent.com/46581655/172758062-8b5ea09a-34af-4d64-ab72-f05e1593b30d.png)

ending up needing to remove BrowserMod integration and problem went away.

**Comment by Mariusthvdb** [comment] 2022-08-01 21:08
currently in beta 2022.8 and seeing the same error, but now also on the Nabucasa link:
```
Logger: frontend.js.latest.202207280
Source: components/system_log/__init__.py:227 
First occurred: 18:36:08 (3 occurrences) 
Last logged: 23:03:41

https://t97redacted3o.ui.nabu.casa/frontend_latest/core.6ade3ee1.js:1:10024 3
http://hassio.local:myport/frontend_latest/core.6ade3ee1.js:1:10024 3
```

**Comment by Mariusthvdb** [comment] 2022-11-16 13:50
ive gotten tired of all of these unexplained Frontend errors, I started filtering them in the home assistant log:
```
logs:
  frontend.js.latest: fatal
```

and be done with it.

**Comment by steverep** [comment] 2023-01-17 22:48
Is this not a duplicate of #9022?

**Comment by Mariusthvdb** [comment] 2023-01-20 07:51
No that is about the ResizeObserver explicitly ?

**Comment by halsafar** [comment] 2023-05-27 19:20
Happening still in [frontend.js.latest.202305033].

**Comment by steverep** [comment] 2023-05-27 19:44
Source maps have been improved since this was first reported.  Browser console should have a full stack trace now.  Someone please paste it here.

**Comment by bcutter** [comment] 2023-11-07 15:34
Seing similar errors massively in HA log (starting with HA Core 2023.4.6):

```
Logger: frontend.js.latest.202304111
Source: components/system_log/__init__.py:257
First occurred: 6. November 2023 um 16:27:12 (1193 occurrences)
Last logged: 16:29:25

:0:0 ResizeObserver loop completed with undelivered notifications.
:0:0 Script error.
http://my-home-assistant:8123/frontend_latest/core--AdzVoB_i-0.js:1:9860 Uncaught Error: Suspend promise not set
```

Not sure what causes this or how to track down the root cause. Seing this old issue (and there are even older ones like https://github.com/home-assistant/core/issues/58567) doesn't really look well tbh.

**Comment by bcutter** [comment] 2024-02-06 11:25
Not stale :-(

**Comment by silamon** [comment] 2024-05-12 08:08
I just found these errors coming from the quickbar. Opening quickbar and then remove the ">" will trigger them both.

**Comment by steverep** [comment] 2024-05-12 17:23
> I just found these errors coming from the quickbar. Opening quickbar and then remove the ">" will trigger them both.

Which errors exactly?  This issue thread has a mixed bag of errors, and the OP was filed before stack traces were significantly improved.  IMO, this one should be closed unless the original can be reproduced with a full stack from the core entrypoint.

The `ResizeObserver` errors are harmless and covered by #9022 which we can reopen if needed.  If we converted all observers to use `@lit/observers` for better tear down, I'd bet most of them would go away.

**Comment by silamon** [comment] 2024-05-12 17:33
I should have specified further, but talking about the ResizeObserver error and Script 0:0 error. I did investigate further and indeed harmless, caused by changing increasing height of the items in the list. (For example, a one line item would become a two line item and then causes the height to increase causing a resize and the error.)

**Closed** 2024-06-23 14:35 UTC
Labels: Bug

**Comment by bcutter** [comment] 2024-06-23 16:35
Closed, okay -.-

**Comment by silamon** [comment] 2024-06-23 20:18
> Closed, okay -.-

If you encounter these errors and you can reproduce them on a specific page, feel free  to open a new issue.
