### ISSUE TITLE
Scrolling Graphs by day when TZ client ne TZ server

### ISSUE THREAD

**Issue by RobWills** [home-assistant/frontend#20185] opened 2024-03-25 20:15 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am currently in US with server in UK. In my profile I set to display data in the server TZ.
When I view Energy Management Graphs for current day they display correctly.
However, when I try to scroll to the previous day, it jumps two days.

### Describe the behavior you expected

When scrolling to previous day, it should scroll exactly 24 hours. Currently it seems to take the  initial date in the graph USING THE LOCAL TZ and then subtracts a day so scrolls 2 days.
It should use the date/time in the display TZ defined in the profile.

### Steps to reproduce the issue

1. Set client time zone to be four hours ahead of server time zone
2. Within the HA client profile, set the display time to be in the server TZ rather than local TZ
3. View the Energy Dashboard which should show the current day starting midnight in the TZ of the server
4. Attempt to scroll back one day and observe that the system scrolls back two days
...

### What version of Home Assistant Core has the issue?

2024.3.3

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.40

### Which operating system are you using to run this browser?

Android OxygenOS 13

**Comment by karwosts** [comment] 2024-03-26 04:22
Duplicate of #20004

**Closed by karwosts** 2024-03-26 04:22 UTC

**Comment by karwosts** [comment] 2024-03-26 14:08
Will be fixed by https://github.com/home-assistant/frontend/pull/20191

**Comment by RobWills** [comment] 2024-03-26 15:12
Fantastic work! Thanks
