### ISSUE TITLE
Loading screen shows white background in dark mode

### ISSUE THREAD

**Issue by mountainsandcode** [home-assistant/frontend#6607] opened 2020-08-12 23:10 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

- Using default theme, dark mode
- Reloading the page in browser or the mobile app, the reloading screen is fully white, while the app is in dark mode, which creates a kind of “flash”

![E5BDA20F-E216-4DF7-A403-C19510E2B50A](https://user-images.githubusercontent.com/26942220/90077144-af102c80-dd01-11ea-8f04-164a0efce0af.png)
![5D83218D-13A3-49C3-8FAB-1502A4BBD87A](https://user-images.githubusercontent.com/26942220/90077147-b0d9f000-dd01-11ea-9926-3524fa428637.png)

## Expected behavior

Background of the page to be black/ gray if the theme is set to dark mode

## Steps to reproduce

- Activate dark mode
- Pull-to-refresh or refresh the page in browser
- See white “flash” 

## Environment

- Home Assistant release with the issue: 0.114.0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Safari on iPad, iOS App
- Operating system: iPadOS, iOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment] 2020-08-14 07:06
Is your device in dark mode or have you manually set dark mode?

**Comment by mountainsandcode** [comment] 2020-08-14 08:13
> Is your device in dark mode or have you manually set dark mode?

The device is in dark mode (iPhone/iPad)

**Comment by balintkozma** [comment] 2020-08-15 08:06
The same for me on Windows 10 and Android 10 on Samsung. Dark mode enabled on both operating systems.

**Comment by ludeeus** [comment] 2020-08-15 09:47
I'm not able to reproduce this
![image](https://user-images.githubusercontent.com/15093472/90309921-07575200-deed-11ea-8eae-7006bbe7b50d.png)

**Comment by spacegaier** [comment] 2020-08-28 14:01
@ludeeus The flash happens for me before that loading screen is shown (Firefox on Win 10). Once I see the "Loading data" text and the progress ring, it has the proper black background.

**Comment by spacegaier** [comment] 2020-08-28 14:11
I played around a bit with manually triggering a page refresh in Firefox and then immediately pressing stop in Firefox. I then ended up on the following white page ("ha-init-page"), but not sure if that is just because I stopped the proper loading of the page or whether that is actually the white flash that can be seen.

**Note**: The text "Unable to connect to Home Assistant" is in the DOM, but is rendered white, which leads me to believe that it is attempting to sue the dark theme, where text is white, but just not consistently across the whole init page.
![image](https://user-images.githubusercontent.com/114137/91577484-0db3e800-e949-11ea-8ecd-5bd377ee95d3.png)

**Comment by bramkragten** [comment] 2020-08-28 22:45
It is because we add our default styles before we load the selected user theme/dark theme.

<https://github.com/home-assistant/frontend/blob/dev/src/entrypoints/app.ts#L3>

**Comment by spacegaier** [comment] 2020-08-28 23:06
Yes, I had played around a bit by setting `background-color: var(--primary-background-color)` in the `ha-init-page.ts`, but that is still resolving to the normal white background at runtime, since the adjusted `darkStyles` colors are not yet applied.

**=>** So is that something that falls in the category "cannot / won't solve" or do you see an option to adjust here something?

**Comment by spacegaier** [comment] 2020-08-29 09:10
I found a way how to prevent the white flashes. PR is coming in the next minutes.

**Comment by spacegaier** [comment] 2020-09-07 19:21
This PR https://github.com/home-assistant/frontend/pull/6815 fixes the flashing for the main content area.

**Closed** 2020-09-07 22:03 UTC
Labels: bug, dark-theme, ux
