### ISSUE TITLE
Name of discovered devices is truncated in the integrations page

### ISSUE THREAD

**Issue by chrisceska** [home-assistant/frontend#7200] opened 2020-10-02 14:14 UTC
## Checklist

- [ x] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [x ] I have tried a different browser to see if it is related to my browser.

## The problem

![image](https://user-images.githubusercontent.com/53413705/94932849-9caba700-0497-11eb-90b1-63935a40612d.png)

Multiple homekit devices discovered, I have no idea what they are because the names are truncated.

## Expected behavior

I would expect to see the entire name of the device so I can figure out what it is

## Steps to reproduce

1) have a discovered device
2) look at the name
3) scratch your head when you try to figure out what is is

## Environment

Home Assistant 0.115.6
Frontend version: 20200918.2 - latest

**Comment by zsarnett** [comment] 2020-10-02 14:18
Duplicate of https://github.com/home-assistant/frontend/issues/6989

**Closed by zsarnett** 2020-10-02 14:18 UTC
Labels: bug
