### ISSUE TITLE
Moving items in f.i. entity-list does not work in Firefox

### ISSUE THREAD

**Issue by pjannink** [home-assistant/frontend#13335] opened 2022-08-04 07:44 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Moving entities to a new row does not work in browser Firefox (Windows 11), All software latest versions.
It does work OK in Edge-browser

### Describe the behavior you expected

Ability to move entities to another row in Firefox browser

### Steps to reproduce the issue

1.Open HA in Firefox
2.Select edit dashboard
3.Try to move an entity in an entity-list to another row.

![image](https://user-images.githubusercontent.com/85283776/182792366-6b7393d7-c287-4016-9e9b-1cde4454f2dd.png)

### What version of Home Assistant Core has the issue?

2022.8

### In which browser are you experiencing the issue with?

Firefox 103.0.1

### Which operating system are you using to run this browser?

Windows 11

**Comment by spacegaier** [comment] 2022-08-10 08:01
Duplicate of https://github.com/home-assistant/frontend/issues/12562.

**Closed by spacegaier** 2022-08-10 08:01 UTC
