### ISSUE TITLE
Energy - Monitor individual devices - device names disappear when scrolling dates

### ISSUE THREAD

**Issue by isuee94** [home-assistant/frontend#9841] opened 2021-08-18 21:42 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Add individual devices to the new energy monitoring section of home assistant.  Go to the energy tab on the left side.  Scroll backward one day and the devices names will disappear and the graph will not be shown correctly.  Hover your mouse over the graph and it will redraw correctly and the devices names will appear.

![Screen Shot 2021-08-18 at 4 37 41 PM](https://user-images.githubusercontent.com/69063765/129975653-1d7c6499-1fb6-4568-a139-4b39d3e9e777.png)

![Screen Shot 2021-08-18 at 4 38 13 PM](https://user-images.githubusercontent.com/69063765/129975746-645f5bd0-4977-4634-ad9b-a260f09e5c72.png)

![Screen Shot 2021-08-18 at 4 39 14 PM](https://user-images.githubusercontent.com/69063765/129975787-fb05b186-e2f0-4ac8-a177-c0fd62f21a27.png)

### Describe the behavior you expected

Devices descriptions should show up when scrolling between dates and the graph should draw correctly without needing to hover over the graph.

### Steps to reproduce the issue

1. Add devices to the energy monitoring section.
2. Scroll to a previous date - the device description will be missing and if you have multiple devices, the graph will be incorrectly drawn.
3. Hover mouse over graph and it will redraw correctly and device names will then appear.
...

### What version of Home Assistant Core has the issue?

2021.8.4

### In which browser are you experiencing the issue with?

Chrome 92.0.4515.107, Safari Version 14.1.1 (16611.2.7.1.4)

### Which operating system are you using to run this browser?

macOS Big Sur 11.4

**Comment by bramkragten** [comment] 2021-08-19 15:12
duplicate of #9722

**Closed by bramkragten** 2021-08-19 15:12 UTC
Labels: bug
