### ISSUE TITLE
button template helper entity page not reachable from helpers view

### ISSUE THREAD

**Issue by CFenner** [home-assistant/frontend#21642] opened 2024-08-09 07:46 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I click on *show settings* on a button template helper, I get directly into the *automation editor*.

<img width="1372" alt="Bildschirmfoto 2024-08-09 um 09 42 51" src="https://github.com/user-attachments/assets/465e7c60-fed9-406f-ba77-2cbc1543481f">
<img width="467" alt="Bildschirmfoto 2024-08-09 um 09 43 52" src="https://github.com/user-attachments/assets/25959f22-1e5f-42c2-9eda-d68e037234c0">

So from this page, I cannot change the name or icon. For other helpers, I get the entity page first.

### Describe the behavior you expected

I would expect that I can change the icon, name, etc. when clicking on a button template helper (as for other helpers) and have here the *template options* button to adjust the template.
<img width="584" alt="Bildschirmfoto 2024-08-09 um 09 30 12" src="https://github.com/user-attachments/assets/28aef8d1-fc15-4e90-9dd1-d0de9080f45a">

### Steps to reproduce the issue

1. to do helpers
2. create a new template helper
3. select *button template*
4. save
5. select created helper
...

### What version of Home Assistant Core has the issue?

core-2024.8.0

**Comment by CFenner** [comment] 2024-08-09 08:35
Interestingly this fixed itself after time. I noticed that the icons changed as well.

<img width="524" alt="Bildschirmfoto 2024-08-09 um 10 34 23" src="https://github.com/user-attachments/assets/0d12ad6f-60cd-44b3-84e1-33566d2982fb">

<img width="824" alt="Bildschirmfoto 2024-08-09 um 10 33 39" src="https://github.com/user-attachments/assets/e8b662ef-eeda-4022-a4a4-eb3de480d65b">

**Comment by ildar170975** [comment] 2024-08-09 13:57
You are talking about a "button template helper" - but I see a template "binary_sensor" entity.

**Comment by karwosts** [comment] 2024-08-09 14:04
Might be a duplicate of this: https://github.com/home-assistant/frontend/issues/20486

For some reason in helpers table I think if the entity is disabled (or maybe unavailable?) the settings go straight to the options flow instead of showing the entity registry settings.

**Comment by dougiteixeira** [comment] 2024-08-11 17:02
This is a problem with the helpers page, not the template integration.

As @karwosts said, when an entity is in an unavailable/unknown state, the click opens the integration options flow.

When creating a button in the template integration, the normal behavior is for the initial state to be unknown. This makes it impossible to access the entity via the helpers page with the current behavior.

By accessing the entity in another way (through a dashboard or through the template integration page) you can confirm that everything is fine with the button template entity.

**Closed** 2024-11-09 23:40 UTC
