### ISSUE TITLE
Lovelace Gauge UI Bugs

### ISSUE THREAD

**Issue by weitheng** [home-assistant/frontend#10910] opened 2021-12-14 01:05 UTC
### The problem

Gauge card UI bug. Needle doesn't display correctly, entire UI is just buggy.
![Screenshot 2021-12-14 at 01 03 09](https://user-images.githubusercontent.com/34220268/145913621-fac077ad-baf7-403d-9ffd-bd76e67d6563.png)
![Screenshot 2021-12-14 at 01 02 29](https://user-images.githubusercontent.com/34220268/145913629-cea22a7c-2d29-4554-843a-6e588cf6e88b.png)
y

### What version of Home Assistant Core has the issue?

core-2021.12.1

### What was the last working version of Home Assistant Core?

core-2021.11.7

### What type of installation are you running?

Home Assistant OS

**Comment by mchangsp** [comment] 2021-12-14 12:40
I have similar problems.
In my setup with Safari it works fine in iOS 15.1 and the needles disappear in iOS15.2.
More details: https://community.home-assistant.io/t/gauge-card-no-needle-in-ha-2021-12-1/366753

**Comment by spacegaier** [comment] 2021-12-14 12:52
We have a reported issue for Safari. Only seems to appear on Apple devices. Is that the case here as well?

https://github.com/home-assistant/frontend/issues/10766

**Comment by mchangsp** [comment] 2021-12-14 13:43
In my case (https://community.home-assistant.io/t/gauge-card-no-needle-in-ha-2021-12-1/366753) I am having problems with Safari on iPhone 11 Pro and iPad pro devices running iOS 15.2

**Comment by mchangsp** [comment] 2021-12-14 13:44
I found another issue which may be related: https://github.com/home-assistant/frontend/issues/10766

**Comment by smeg1** [comment] 2021-12-14 15:29
same on Mac Pro desktop as per top image been like it for 2 weeks or more, cannot say when it went wrong but was working fine for a long time

**Comment by ciottomate** [comment] 2021-12-15 09:21
> In my case (https://community.home-assistant.io/t/gauge-card-no-needle-in-ha-2021-12-1/366753) I am having problems with Safari on iPhone 11 Pro device running iOS 15.2

I do confirm same setup and problem.
Issue reported on the same topic as well.

**Comment by eblekkenhorst** [comment] 2021-12-15 20:33
Apart from iOS 15.2, I'm also seeing this on Mac OS Monterey 12.1 in both Safari and the HA Companion App. But not in Chrome or FireFox.
Looks like a change in Apple’s WebKit is causing this.

**Comment by bcutter** [comment] 2021-12-15 20:59
I am seeing this only on Apple devices.
- I can confirm it started after updating iOS to 15.2.
- HA Companion App or browser (tested with Firefox) doesn't make any difference. Therefore I guess it's in some core Safari components (?)

![image](https://user-images.githubusercontent.com/13799156/146264059-6921a17f-6b2e-403b-95a3-99e9f092a5c2.jpeg)

![image](https://user-images.githubusercontent.com/13799156/146264073-3056b122-cad4-4a8c-9b97-95420c3e803d.jpeg)

Not seeing this issue on Android and Windows powered devices.

**Comment by DolfLund** [comment] 2021-12-15 22:44
Same here just checking in - updated to ios 15.2 and immediately my iphone matches everyone's screen shots above.

**Comment by wzaatar** [comment] 2021-12-16 00:05
+1. Confirming that I also am in an iEnvironment similar to the rest of the folks. Discussed it with the community at https://community.home-assistant.io/t/lovelace-gauge-bug-ha-2021-12-1/366934 and doesn't seem to impact Android. I believe @eblekkenhorst nailed the cause as this started with me as soon as I went to IOS15.2 and equivalent.

**Comment by andreasfranz** [comment] 2021-12-21 07:55
I switched the user agent to "Google Chrome - macOS" in the "Develop | User Agent" menu in Safari and everything looks good. I guess the `isSafari` logic in `src/components/ha-gauge.ts` isn't needed anymore for the latest Safari.

**Comment by ciottomate** [comment] 2021-12-21 17:27
> I switched the user agent to "Google Chrome - macOS" in the "Develop | User Agent" menu in Safari and everything looks good. I guess the `isSafari` logic in `src/components/ha-gauge.ts` isn't needed anymore for the latest Safari.

Thanks for this finding but any hint on how to solve it on IOS devices? Can’t found same setting on IOS safari’s preferences .

**Comment by Friedi1970** [comment] 2021-12-21 19:12
👍 
Same here on IOS devices.

**Comment by andreasfranz** [comment] 2021-12-21 21:19
> > I switched the user agent to "Google Chrome - macOS" in the "Develop | User Agent" menu in Safari and everything looks good. I guess the `isSafari` logic in `src/components/ha-gauge.ts` isn't needed anymore for the latest Safari.
> 
> Thanks for this finding but any hint on how to solve it on IOS devices? Can’t found same setting on IOS safari’s preferences .

My comment about switching the user agent is just a workaround not a fix. I think overhauling the "isSafari" detection, so it doesn't apply on the latest iOS and macOS versions for this component, might be the resolution.

**Comment by ciottomate** [comment] 2021-12-23 05:38
> > > I switched the user agent to "Google Chrome - macOS" in the "Develop | User Agent" menu in Safari and everything looks good. I guess the `isSafari` logic in `src/components/ha-gauge.ts` isn't needed anymore for the latest Safari.
> > 
> > 
> > Thanks for this finding but any hint on how to solve it on IOS devices? Can’t found same setting on IOS safari’s preferences .
> 
> My comment about switching the user agent is just a workaround not a fix. I think overhauling the "isSafari" detection, so it doesn't apply on the latest iOS and macOS versions for this component, might be the resolution.

I got your point. 
thanks 😊

**Comment by rhoddan** [comment] 2021-12-26 11:18
I have same problem

**Comment by slvwolf** [comment] 2021-12-26 11:46
PR for this issue: #10992

**Comment by norfolkmustard** [comment] 2021-12-26 12:12
FYI this is still a bug in iOS15.3 and HomeAssistant app 2021.12.1

**Comment by rhoddan** [comment] 2021-12-26 22:05
Not only in safari. This is the ms egde browser in IOS 15.2

![2A59A7E8-1BBB-4A71-A172-2D5E2453A130](https://user-images.githubusercontent.com/33499995/147421009-671f515b-2583-4bd7-8680-591d86af93ce.jpeg)

**Comment by Wh1terat** [comment] 2021-12-26 22:38
> Not only in safari. This is the ms egde browser in IOS 15.2
> 
> 
> 
> ![2A59A7E8-1BBB-4A71-A172-2D5E2453A130](https://user-images.githubusercontent.com/33499995/147421009-671f515b-2583-4bd7-8680-591d86af93ce.jpeg)
> 
> 
> 
>  

On iOS every browser uses Safari WebKit behind the scenes, a limitation placed by apple for 3rd party browsers.

**Comment by rhoddan** [comment] 2021-12-26 22:40
> > Not only in safari. This is the ms egde browser in IOS 15.2
> > ![2A59A7E8-1BBB-4A71-A172-2D5E2453A130](https://user-images.githubusercontent.com/33499995/147421009-671f515b-2583-4bd7-8680-591d86af93ce.jpeg)
> 
> On iOS every browser uses Safari WebKit behind the scenes, a limitation placed by apple for 3rd party browsers.

Aha ok, thanks for the clarification.

**Comment by DolfLund** [comment] 2021-12-28 18:06
12.6 seems to have fixed it wonderfully! Thank you

**Comment by bcutter** [comment] 2021-12-28 18:31
> 12.6 seems to have fixed it wonderfully! Thank you

Please specify on which system with which version on which browser so your response is helpful.

**Comment by ciottomate** [comment] 2021-12-28 18:37
> 12.6 seems to have fixed it wonderfully! Thank you

Yes confirmed problem Fixed with Safari IOS 15.2
Issue still present on Chrome IOS 15.2 and the home assistant APP for  IOS

**Comment by scns** [comment] 2021-12-28 18:43
On the latest iOS app 2021.12.1 with  ha 2021.12.6 and iOS 15.3 beta the problem still exists

![image](https://user-images.githubusercontent.com/7148071/147596889-cee7b02f-1690-49ef-aad2-d7598319b1a5.jpeg)

**Comment by rhoddan** [comment] 2021-12-28 19:12
The needle is still not correct (IOS app)
    	Vänligen Peter
    
  

 Från: Maarten Schmeitz ***@***.***>Skickat: tisdag, december 28, 2021 7:43 emTill: home-assistant/frontendKopia: rhoddan; CommentÄmne: Re: [home-assistant/frontend] Lovelace Gauge UI Bugs (Issue #10910) 
On the latest iOS app 2021.12.1 with  ha 2021.12.6 and iOS 15.3 beta the problem still exists

**Comment by ciottomate** [comment] 2021-12-28 19:38
> On the latest iOS app 2021.12.1 with ha 2021.12.6 and iOS 15.3 beta the problem still exists
> 
> ![image](https://user-images.githubusercontent.com/7148071/147596889-cee7b02f-1690-49ef-aad2-d7598319b1a5.jpeg)

Try with Safari (not the home assistant  app).
It’s ok for me now (ng the home assistant  ios app or either chrome).

**Comment by ciottomate** [comment] 2021-12-28 19:39
> The needle is still not correct (IOS app) Vänligen Peter  Från: Maarten Schmeitz ***@***.***>Skickat: tisdag, december 28, 2021 7:43 emTill: home-assistant/frontendKopia: rhoddan; CommentÄmne: Re: [home-assistant/frontend] Lovelace Gauge UI Bugs (Issue #10910)  On the latest iOS app 2021.12.1 with ha 2021.12.6 and iOS 15.3 beta the problem still exists —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

Try with Safari (not the home assistant app).
It’s ok for me now (ng the home assistant ios app or either chrome).

**Comment by rhoddan** [comment] 2021-12-28 20:00
Yes you are right. It’s fine in safari 🙂👍👍
    	Vänligen Peter
    
  

 Från: ciottomate ***@***.***>Skickat: tisdag, december 28, 2021 8:39 emTill: home-assistant/frontendKopia: rhoddan; CommentÄmne: Re: [home-assistant/frontend] Lovelace Gauge UI Bugs (Issue #10910) 



The needle is still not correct (IOS app) Vänligen Peter  Från: Maarten Schmeitz @.>Skickat: tisdag, december 28, 2021 7:43 emTill: home-assistant/frontendKopia: rhoddan; CommentÄmne: Re: [home-assistant/frontend] Lovelace Gauge UI Bugs (Issue #10910)  On the latest iOS app 2021.12.1 with ha 2021.12.6 and iOS 15.3 beta the problem still exists —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.>



Try with Safari (not the home assistant app).

It’s ok for me now (ng the home assistant ios app or either chrome)

**Comment by jdwhite** [comment] 2021-12-30 06:00
Core 2012.12.7
works: Safari on iOS 15.2, iPadOS 15.2, macOS Monterey 12.1
doesn't work: Home Assistant Companion 2021.12.1 (2021.327) on iOS/iPadOS and 2021.12 (2021.322) on macOS Monterey. Tried resetting front-end cache with companion app.

**Comment by raducotescu** [comment] 2021-12-30 22:24
Based on the comments, this is a duplicate of #10766 (which addressed Safari only) and #11041 (which concerns the companion apps on iOS/macOS). #11052 should make the fix for #10766 more reliable, while also addressing the bug in the companion apps.

**Comment by nmajin** [comment] 2021-12-31 03:19
> Based on the comments, this is a duplicate of #10766 (which addressed Safari only) and #11041 (which concerns the companion apps on iOS/macOS). #11052 should make the fix for #10766 more reliable, while also addressing the bug in the companion apps.

lol wut? So #10766 fixes the issue**s**?

**Comment by raducotescu** [comment] 2021-12-31 06:37
> lol wut? So #10766 fixes the issues?

The comments mention both browsers and the Home Assistant companion app. #10766 addressed Safari via its PR, #11041 will handle the companion apps via its PR.

What doesn’t yet work (and have no idea how to reliably fix) are other browsers than Safari on iOS - see https://github.com/home-assistant/frontend/pull/11052#issuecomment-1003205065.

**Comment by bcutter** [comment] 2021-12-31 15:32
> > What doesn’t yet work (and have no idea how to reliably fix) are other browsers than Safari on iOS - see [#11052 (comment)](https://github.com/home-assistant/frontend/pull/11052#issuecomment-1003205065).
> 
> 
> 
> I believe it broke my iOS Companion App on the 2nd or 3rd to last update, sorry I can’t recall accurately, but it was very recent for me that a HA update broke it for me, so wondering if the most recent HA updates can be reviewed.
> 
> 

No it didn't. It's iOS 15.2 that changed.

**Comment by adriederegt** [comment] 2021-12-31 22:27
Problem came with upgrading to iOS15.2, With 2021.12.7 it is solved in the browser (Safari) but not in the app

**Comment by TomBrien** [comment] 2022-01-13 13:40
Just a small clarification on the above, it is currently fixed in Safari on iOS but not in any WebKit app which includes Chrome on iOS for example

**Comment by raducotescu** [comment] 2022-01-13 13:45
Yes, this was already mentioned in https://github.com/home-assistant/frontend/issues/10910#issuecomment-1003285909.

**Comment by Wh1terat** [comment] 2022-01-13 17:28
Would be nice to see [#11052](https://github.com/home-assistant/frontend/pull/11052) merged sometime soon.

The issue has been ongoing for a month and for some the companion app on iOS devices is a primary means accessing HA.

**Comment by credulous67** [comment] 2022-01-21 19:14
I was running Home Assistant 2021.12.10 when I upgraded my Iphone IOS 15.2.1 and that broke it for me.

**Comment by AmoebeLabs** [comment] 2022-01-23 14:21
I was able to fix the positioning problems (scaling/rotating) in the Companion App with my own custom-cards:

**Working on iOS 15.2, and a mess on iOS 15.2.1**
```
style="transform-origin:center;"
```
**Working on iOS 15.2 _AND_ on iOS 15.2.1**
```
style="transform-origin:center; transform-box:fill-box;"
```

So adding the `transform-box:fill-box`, which I also use on the Chromium renderpath seems to fix the problem for me 😄 

I still have separate renderpaths for Safari and any other browser, but the Safari renderpath does currently **NOT** depend on the Safari/iOS version 14.x or 15.x.

Maybe the above helps in solving the Gauge problem...

My logic to detect Safari / iOS is:
```javascript
    this.isSafari = !!navigator.userAgent.match(/Version\/[\d\.]+.*Safari/);
    this.iOS = (/iPad|iPhone|iPod/.test(navigator.userAgent) ||
                (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)) &&
                !window.MSStream;

```

**Comment by Maxym77** [comment] 2022-01-24 09:40
> I was able to fix the positioning problems (scaling/rotating) in the Companion App with my own custom-cards:
> 
> **Working on iOS 15.2, and a mess on iOS 15.2.1**
> 
> ```
> style="transform-origin:center;"
> ```
> 
> **Working on iOS 15.2 _AND_ on iOS 15.2.1**
> 
> ```
> style="transform-origin:center; transform-box:fill-box;"
> ```
> 
> So adding the `transform-box:fill-box`, which I also use on the Chromium renderpath seems to fix the problem for me 😄
> 
> I still have separate renderpaths for Safari and any other browser, but the Safari renderpath does currently **NOT** depend on the Safari/iOS version 14.x or 15.x.
> 
> Maybe the above helps in solving the Gauge problem...
> 
> My logic to detect Safari / iOS is:
> 
> ```js
>     this.isSafari = !!navigator.userAgent.match(/Version\/[\d\.]+.*Safari/);
>     this.iOS = (/iPad|iPhone|iPod/.test(navigator.userAgent) ||
>                 (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1)) &&
>                 !window.MSStream;
> ```
> 
> This mess in 15.2.1: ![image](https://user-images.githubusercontent.com/7996307/150683174-ea3188ea-ab47-4ed1-8be9-e1f00be82027.png)
> 
> Is back to as it should be again in both 15.2 and 15.2.1: ![image](https://user-images.githubusercontent.com/7996307/150683228-eb8aa1f4-5a62-42f0-b9dc-873e9dc0e693.png)

can you share your component?

**Comment by bramkragten** [comment] 2022-01-24 20:05
FIxed in dev by #10992

**Closed by bramkragten** 2022-01-24 20:05 UTC
Labels: safari

**Comment by norfolkmustard** [comment] 2022-02-03 19:38
Fixed for me now, thanks all. 

iOS15.4, HA iOS app 2022.2, HA2022.2.0

**Comment by ciottomate** [comment] 2022-02-04 05:14
Same for me now it’s ok 
thanks all.

iOS15.3
HA iOS app 2022.2
HA2022.2.0
IOS SAFARI as well ok
