### ISSUE TITLE
Energy dashboard graph cut off at 1am

### ISSUE THREAD

**Issue by TheJulianJES** [home-assistant/frontend#17766] opened 2023-08-31 23:16 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When it's 1am, (so only one energy graph is showing in the energy dashboard), the first bar gets cut off slightly depending on screen/window size:
![Bildschirmfoto 2023-09-01 um 01 10 03](https://github.com/home-assistant/frontend/assets/6409465/f3ed85e5-3eef-435f-845f-3b1fa51a331c)
(notice the "outline" missing on the left and the bar being wider than usual)
This problem goes away if a second bar is showing (so after 2am).

Here's a video comparing two dates:

https://github.com/home-assistant/frontend/assets/6409465/453d85e5-d0dd-4038-a438-dd4213aa0f7f

### Describe the behavior you expected

That the one bar isn't cut-off and has the same width as when two or more bars are present.

### Steps to reproduce the issue

1. Have only one "energy bar" in the energy dashboard, so it needs to be ~1am (new day)
2. Open energy dashboard
3. Resize window a bit back and forth until the bar gets cut off

### What version of Home Assistant Core has the issue?

core-2023.9.0b1

### In which browser are you experiencing the issue with?

Google Chrome 116.0.5845.140

### Which operating system are you using to run this browser?

macOS Sonoma (14.0) Dev Beta 7

**Comment by karwosts** [comment] 2023-09-02 04:15
Same for the first date of the month in monthly view. It's especially noticible if you turn on compare data. 

Since there's only one datapoint in the series, chart.js doesn't really understand how to space the bars appropriately. 

![image](https://github.com/home-assistant/frontend/assets/32912880/67c290fa-4bff-4119-ba26-aa2e75f3ea3a)

**Comment by karwosts** [comment] 2023-09-02 12:40
Found this is a duplicate of #14950

**Closed** 2023-09-26 20:49 UTC
