### ISSUE TITLE
Automation editor treats true/false as a string

### ISSUE THREAD

**Issue by avshalog** [home-assistant/frontend#12634] opened 2022-05-08 21:16 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when I create or change automation using the editor and I want it to be triggered by state change from "false" to "true".
the editor will treats the "true" as a string and will add an apostrophes to it in the YAML code - 'true'
of course the automation wont work like that. the only way to make it work is to change the YAML manually what will make the automation uneditable by the editor.
<img width="380" alt="Screen Shot 2022-05-08 at 23 46 58" src="https://user-images.githubusercontent.com/73798369/167315737-41692bad-8780-4499-97cd-06a5adf9aeff.png">

after I change it manually from 'true' to true:
<img width="804" alt="Screen Shot 2022-05-09 at 0 05 51" src="https://user-images.githubusercontent.com/73798369/167315797-e3d976f3-c4e0-496c-a558-84914cf2cbe5.png">

### Describe the behavior you expected

when using "true" & "false" in the editor, it should not add Apostrophes to the true in the YAML

### Steps to reproduce the issue

1. create a new automation
2. triggered it by state change from false to true
3. look at the YAML that was generated by the editor
4. change it manually to "true" without the apostrophes
5. go back to the editor and see the alert.
...

### What version of Home Assistant Core has the issue?

core-2022.4.7

**Comment by frenck** [comment] 2022-05-09 06:17
Duplicate of #7708

**Closed by frenck** 2022-05-09 06:18 UTC
