### ISSUE TITLE
attributes in developer-tools/state displays json errors

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#8478] opened 2021-02-27 11:19 UTC
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

when entering 'attic' in the attributes filter  this error is displayed:
added to that, the filter doesnt work at all, and still show anything without the search term. se below screenshot.

**Describe the behavior you expected**

nothing, and filter on 'attic' (or anything really...)

**Steps to reproduce the issue**

1.
2.
3.
...

**What version of Home Assistant Core has the issue?**

2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Safari / Chrome 

**Which operating system are you using to run this browser?**

macOS Big sur 11.2

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'JSON.stringify(s).toLowerCase')
```

<img width="753" alt="Schermafbeelding 2021-02-27 om 12 14 09" src="https://user-images.githubusercontent.com/33354141/109385638-98c06b80-78f5-11eb-8a49-4e825f2187a8.png">

and Chrome

<img width="525" alt="Schermafbeelding 2021-02-27 om 12 18 39" src="https://user-images.githubusercontent.com/33354141/109385693-0a98b500-78f6-11eb-9174-074cc512e3e0.png">

<img width="767" alt="Schermafbeelding 2021-02-27 om 12 20 09" src="https://user-images.githubusercontent.com/33354141/109385720-43d12500-78f6-11eb-81c5-7657c958bc53.png">

**Comment by spacegaier** [comment] 2021-02-27 11:37
I assume the error is raised here: https://github.com/home-assistant/frontend/blob/f44d505b4196aef1a08b794afe05330726eb5de3/src/panels/developer-tools/state/developer-tools-state.js#L411

I cannot reproduce the issue plus there was no coding change, so I assume it only appears in certain situations, but that would require an attribute value that is not null but still cannot be stringified.

Can you try to narrow it down to a certain entity e.g. by filtering out some entities and states?

**Comment by Mariusthvdb** [comment] 2021-02-27 11:41
no sorry, it seems no matter what I enter in the attributes field, the filter isnt working correctly at all. see:
<img width="773" alt="Schermafbeelding 2021-02-27 om 12 40 47" src="https://user-images.githubusercontent.com/33354141/109386154-189c0500-78f9-11eb-9019-209764204b0e.png">

**Comment by spacegaier** [comment] 2021-03-05 21:18
> 
> 
> btw, when using inspector in Chrome, the attributes column isn't displayed at all......

It has to be there, otherwise it would not be rendered.
But no matter what I try, I cannot reproduce the issue. Works fine for me. Did you enforce cache disabling in the Chrome dev tools network tab to rule out any caching issues?

**Comment by Mariusthvdb** [comment] 2021-03-09 09:47
this is another related issue, now on the state column:
<img width="864" alt="Schermafbeelding 2021-03-09 om 10 45 32" src="https://user-images.githubusercontent.com/33354141/110451559-98c62580-80c4-11eb-9699-b6ea8a7da62c.png">

but when I enter the full state 'Window/door is closed' (selected and copied from the state column itself...) this happens:

<img width="808" alt="Schermafbeelding 2021-03-09 om 10 46 14" src="https://user-images.githubusercontent.com/33354141/110451720-c612d380-80c4-11eb-87ba-e72937e0cd1e.png">

**Comment by Mariusthvdb** [comment] 2021-03-23 15:59
getting back to this, I still have a failing states page. Only way  I can make the attributes filter behave some, is my first filtering the states, though as shown above that too has its oddities..

meanwhile on 2021.3.4, so yes, all possible cache issues are ruled out. And no, no difference between Safari and Chrome on Mac

**Comment by spacegaier** [comment] 2021-03-23 18:14
I was finally able to reproduce and I think I found the root cause as well.

**Comment by Mariusthvdb** [comment] 2021-03-23 21:35
o wow, that would be so great. can I help in a test of somekind?

**Comment by spacegaier** [comment] 2021-03-23 22:10
If you have a frontend dev environment you can locally test my linked PR to confirm the fix, but that one is trivial so I think should be merged soon-ish anyway.

**Comment by Mariusthvdb** [comment] 2021-03-24 08:08
ok, ill await that then. thanks!

**Closed** 2021-03-24 08:48 UTC
Labels: bug

**Comment by Mariusthvdb** [comment] 2021-04-06 09:44
supposing this is in 2021.4.0 beta, I can confirm the state filter on 'window' to work as expected now. However, the original issue on the attributes in the attribute filter column still persists.



<img width="611" alt="Schermafbeelding 2021-04-06 om 11 42 37" src="https://user-images.githubusercontent.com/33354141/113691907-41b86e00-96cd-11eb-93f0-6fe3504a4f9f.png">

**Comment by spacegaier** [comment] 2021-04-06 10:08
Cannot reproduce that neither in current beta nor dev.

**Comment by Mariusthvdb** [comment] 2021-04-06 10:20
no I am doing nothing of the sorts, just enter a filter in the attributes column like 'afval'. If I do so, nothing happens. If I enter a filter in the state column, like 'on' , it immediately shows the entities, in this case a couple of 'afval' automations.

**Comment by Mariusthvdb** [comment] 2021-04-13 08:03
Hi Philip,
please let me get back on this.
I have 3 instances all of which have my custom-ui loaded. Only my product system suffers the issue, indicating it is not (only) custom-ui causing this. On the contrary, after all experiments I did, it seems to be an _indicator_ for this issue, instead of a root cause.

Thats why I ask you to have a second look why the error posted above could happen, like it did before for the states column.
After all you found a code error there, and you were able to fix that fortunately. Maybe there's still something left for the attributes column.

If I enter more than 2 characters in the attributes column, the error shows, and no filtering is applied at all (not even after waiting some time, because I have a large system with many entities):

<img width="607" alt="Schermafbeelding 2021-04-13 om 09 53 08" src="https://user-images.githubusercontent.com/33354141/114516894-1d651000-9c3e-11eb-9f4e-31c7da153a80.png">

consequently, if I then enter a state in the state filter column, filtering _Is_ applied, and it is immediate.

If I reverse the order, so first a filter in the state column, and then an attribute filter, all is well, no error shows at all, and filtering is correctly done, and very immediate.

Would certainly appreciate your second check.

**Comment by Mariusthvdb** [comment] 2021-05-04 13:15
still happening on 2021.5b07 now, but here's another thought: 

could it be the _number of entities_ the states has to check? My test system holds only a couple hundred maybe (it merely serves as a Zwave add-on instance and entities that registers. My production system however holds over 3000 entities.

If there is some sort of limitation, it would explain why the error is happening only when entering in the attributes first, and immediately gone when entering anything in the state or entity column?

**Comment by bramkragten** [comment] 2021-05-04 13:34
You have an entity with an attribute that has the value `undefined`. Normally this should not be possible, so I guess you have some custom stuff doing things we don't support 😉

**Comment by Mariusthvdb** [comment] 2021-05-04 14:12
thanks for you explanation, will check that. And thanks for the guard you added in the #9089 
so appreciated!

**Comment by Mariusthvdb** [comment] 2021-05-05 07:14
Bram, is this in b08 now?
because the errors persist...

**Comment by Mariusthvdb** [comment] 2021-05-15 10:16
SOLUTION:
after testing each and every customization, comparing between the 3 instance I use, in various iterations of custom-ui, (which proofed it wasn't Custom-ui perse) I finally found the culprit!

As it turned out, I had used a single line comment in one of my templates:
```
        icon_color: >
          if (state == 'on') return 'purple'; //'red'
          return 'steelblue';
```
and the system doesn't error on that, at least, doesn't state there is a templating/javascript error. 

I still don't understand why it behave like it does, choking in only filtering the attributes, but fine filtering when first adding a character in the entity, or state column.

Also, I am not sure where the catch should be added for this. 

I do thank you guys for your support, and even adding/changing the guard in the PR above.

**Comment by bramkragten** [comment] 2021-05-15 10:26
That PR is not released yet.

**Comment by bramkragten** [comment] 2021-05-15 10:28
That is custom-ui? as we don't support javascript templates...

**Comment by Mariusthvdb** [comment] 2021-05-15 10:35
Yes Bram, it is, I hope I didn't give you the impression it was HA, I purposely stated it here: https://github.com/home-assistant/frontend/issues/8478#issuecomment-814006837

and I know you don't support that, that's why I was/am so grateful you made the PR after all. I think it will benefit anyone, and hope it might guard the issue I created myself, using a faulty template (or rather, make an error in JS)

Anyways, the opening part (on the state) of this issue was HA, as Philip was able to reproduce and fix ;-) Since the second part (on the attributes) looked identical, this issue evolved quite naturally.
