### ISSUE TITLE
Unable to enter Color and Color Temperature values in Dev Tools, Services, UI Mode for Light: Turn on

### ISSUE THREAD

**Issue by danielbrunt57** [home-assistant/frontend#14343] opened 2022-11-09 09:54 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Unable to enter Color and Color Temperature values in Dev Tools, Services, UI Mode for Light: Turn on

### Describe the behavior you expected

The entry fields should be available

### Steps to reproduce the issue

1.
2.
3.

### What version of Home Assistant Core has the issue?

core-2022.11.2

### In which browser are you experiencing the issue with?

Microsoft Edge - latest

### Which operating system are you using to run this browser?

Windows 11

### Additional information

![image](https://user-images.githubusercontent.com/49846893/200798138-652334ea-7217-4884-8881-9362cc2ad935.png)

**Comment by basnijholt** [comment] 2022-11-09 19:30
Duplicate of https://github.com/home-assistant/frontend/issues/14314.

**Comment by steverep** [comment] 2022-11-12 03:51
Duplicate of #14314

**Closed by steverep** 2022-11-12 03:51 UTC
