### ISSUE TITLE
No Grouping in Logbook Card for old entries when many  exists

### ISSUE THREAD

**Issue by admeno** [home-assistant/frontend#9544] opened 2021-07-11 17:39 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The logbook card does not group the entries if they are in the past and there are many.
Tested this in Chrome and Firefox.

Example:
I have a card with many entries in it and for the first group it works fine:
![GroupingOk](https://user-images.githubusercontent.com/61088677/125204714-ed4dfd00-e27e-11eb-9351-b4f55fe8a15b.PNG)

But every entry after this group is not grouped:
![noGrouping](https://user-images.githubusercontent.com/61088677/125204751-1c646e80-e27f-11eb-8fbc-bdfaf6fff66a.PNG)

### Describe the behavior you expected

I expected that all the entries are grouped for each day.

### Steps to reproduce the issue

1. Add a logbook-card so that are many entries in it.

### What version of Home Assistant Core has the issue?

core-2021.7.1

### In which browser are you experiencing the issue with?

Google Chrome 91.0.4472.124
Firefox 89.0.2

### Which operating system are you using to run this browser?

Windows 10
_

**Comment by spacegaier** [comment] 2021-09-06 20:13
Duplicate of https://github.com/home-assistant/frontend/issues/9371

**Closed by spacegaier** 2021-09-06 20:13 UTC
Labels: bug
