### ISSUE TITLE
Mis-Spelled Word in UI

### ISSUE THREAD

**Issue by Colorado4Wheeler** [home-assistant/frontend#8069] opened 2021-01-02 16:12 UTC
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

Automations interface has a grammatical error.  It says "Use automations to bring your home to live.", it should say "Use automations to bring your home to life.

## Expected behavior

See problem, it contains the expectation.

## Steps to reproduce

1. Go to Configuration
2. Go to Automations
3. Create or Edit an Automation
4. Read the test on the first section

## Environment

- Home Assistant release with the issue: 2020.12.2
- Last working Home Assistant release (if known):
- Browser and browser version: Browser agnostic issue
- Operating system: OS agnostic issue

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment] 2021-01-02 16:43
Duplicate of https://github.com/home-assistant/frontend/issues/7958.

**Closed by spacegaier** 2021-01-02 16:43 UTC
Labels: bug
