### ISSUE TITLE
Admin GUI for input field date/time/datetime

### ISSUE THREAD

**Issue by ChrLipp** [home-assistant/frontend#5565] opened 2020-04-18 11:22 UTC
![gui](https://user-images.githubusercontent.com/1706324/79636408-b8382500-8177-11ea-961b-d4541d2f0606.jpg)

## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When I create an date/time/datetime input field via the (German) GUI I am not able to select Date (Datum) / Time (Uhrzeit) / Date and Time (Datum und Uhrzeit). When I press Create (Erstellen) I receive the error "Entity needs at least a date or a time. Got {'name': 'elias_alarm_time', 'icon': 'mdi:alarm', 'has_time': False, 'has_date': False}" (of course).

 

## Expected behavior

The date / time /datetime options should be available.

## Steps to reproduce

1. Go to options - helper
2. Choose to add a new helper (+)
3. Select "Date and/or time"
4. Try to choose the type

## Environment

- Home Assistant release with the issue: 0.108.6
- Last working Home Assistant release (if known): -
- Browser and browser version: Version 80.0.3987.163 (Offizieller Build) (64-Bit), tested also with firefox
- Operating system: Windows 10 64bit

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.114-v7l
python_version | 3.7.7
timezone | Europe/Vienna
version | 0.108.6
virtualenv | false

## Javascript errors shown in your browser console/inspector

none

**Comment by ludeeus** [comment] 2020-04-18 11:26
Duplicate of https://github.com/home-assistant/frontend/issues/5540

**Closed by ludeeus** 2020-04-18 11:26 UTC
Labels: bug
