### ISSUE TITLE
Missing Raspberry Pi 3 image in hardware

### ISSUE THREAD

**Issue by scop** [home-assistant/frontend#13204] opened 2022-07-16 10:37 UTC
What about PI 3 logo?
It`s not loading, because the call results in 404.

`GET https://brands.home-assistant.io/hardware/boards/raspberry_pi_3.png`

Relevant HTML is:

`<img slot="graphic" src="https://brands.home-assistant.io/hardware/boards/raspberry_pi_3.png">`

Would be great to add this also. It`s still broken :(.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/14962205/179187095-78a73c2d-f272-43b7-916c-c6f174c39a8d.png">

_Originally posted by @osyrixx in https://github.com/home-assistant/frontend/issues/13040#issuecomment-1185320457_

**Comment by iosoft** [comment] 2022-07-29 03:57
Yes, I also face the same issue since few weeks!
**It is NOT yet fixed!**

The URL is -
https://brands.home-assistant.io/hardware/boards/raspberry_pi_3.png

**Comment by frenck** [comment] 2022-07-29 09:56
duplicate of https://github.com/home-assistant/brands/issues/3515

**Closed by frenck** 2022-07-29 09:56 UTC

**Comment by iosoft** [comment] 2022-07-29 12:19
Pls upload this Raspberry Pi 3 image

![raspberry_pi_3](https://user-images.githubusercontent.com/349968/181757016-eebca287-51c6-4a88-9b00-73adcf94b887.png)
.
