### ISSUE TITLE
Datepicker not visible

### ISSUE THREAD

**Issue by vincedh** [home-assistant/frontend#14630] opened 2022-12-08 10:55 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a input_datetime helper which is visible in my frontend, but the calender option is not visible (only the time is visible)

![image](https://user-images.githubusercontent.com/17254729/206429126-1b5ead79-6cab-407d-a695-1bc84fac154d.png)
![image](https://user-images.githubusercontent.com/17254729/206429260-5024b2fe-6d5a-4700-b3e5-1c3a51ba6d31.png)

### Describe the behavior you expected

a calendar popup where i can choose the date

### Steps to reproduce the issue

1. create a input_datetime helper with a time & date option
2. add it to the frontend
3. try to change the date

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.0

### What was the last working version of Home Assistant Core?

Home Assistant 2022.11.X

### In which browser are you experiencing the issue with?

Chrome and the App

### Which operating system are you using to run this browser?

Windows, iOS

**Comment by bramkragten** [comment] 2022-12-08 10:59
I can not reproduce this, what is the state of the entity?

**Comment by vincedh** [comment] 2022-12-08 11:17
in chrome, i see this error in the developer tools:

![image](https://user-images.githubusercontent.com/17254729/206433535-dcb926d4-7eaf-4cc7-996d-04998a5a5ecd.png)

**Comment by spacegaier** [comment] 2022-12-08 11:58
Duplicate of https://github.com/home-assistant/frontend/issues/14616 and already fixed.

**Closed by spacegaier** 2022-12-08 11:58 UTC
