### ISSUE TITLE
Automations: sorting by alphabet only works the first time

### ISSUE THREAD

**Issue by Ruud2702** [home-assistant/frontend#5338] opened 2020-03-25 12:21 UTC
Hello together,
in the list of automations, sorting by alphabet only works the first time you create it. if automation is renamed afterwards, the sorting does not change accordingly.

regards,
daniel

**Comment by Misiu** [comment] 2020-03-25 14:09
Duplicate of https://github.com/home-assistant/frontend/issues/4897

**Closed** 2020-03-25 14:16 UTC
Labels: bug
