### ISSUE TITLE
cannot adjust numeric value due to decimal separator setting

### ISSUE THREAD

**Issue by santiagozky** [home-assistant/frontend#20515] opened 2024-04-14 13:17 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In iOS, if the locale settings uses comma as a decimal separator and hass uses a dot, it becomes impossible to enter numeric data in some fields.

### Describe the behavior you expected

I can enter numeric data no matter my locale.

### Steps to reproduce the issue

1. have an ios device that uses comma es decimal separator
2. try to edit a numeric field. many of them open a numeric only keyboard
3. since the numeric keyboard will only have a comma available, if hass expects a dot as decimal separator, it becomes impossible to enter a decimal number  since the field validation will fail.
![IMG_1438](https://github.com/home-assistant/frontend/assets/1405393/818b65e7-3a59-4ffe-a9fa-09e6d96e3e55)

### What version of Home Assistant Core has the issue?

2024.4.0

### In which browser are you experiencing the issue with?

safari

### Which operating system are you using to run this browser?

ios 17.4.1

**Comment by karwosts** [comment] 2024-04-22 02:36
Duplicate of #19490

**Closed by karwosts** 2024-04-22 02:36 UTC
