### ISSUE TITLE
0.112.0: Template checker first lines not visible anymore

### ISSUE THREAD

**Issue by Moonbase59** [home-assistant/frontend#6321] opened 2020-07-03 10:54 UTC
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When using the template checker, the first few lines are hidden since upgrade to Home Assistant Core 0.112.0. This happens with several browsers, on different machines (tried Firefox, Opera, Chromium).

This behaviour is absolutely bad, because all error messages (usually top right) can’t be seen anymore!

## Expected behavior

Nothing should be hidden, especially not error messages.

## Steps to reproduce

Open template checker, empty it, type a number in each line. You’ll see lines 1..4 can’t be seen.

## Environment

- Home Assistant release with the issue: 0.112.0
- Last working Home Assistant release (if known): 0.111.4 (not sure about the .4)
- Browser and browser version: Firefox 66.0.3, Chromium 65.0.3325.181, Opera 67.0.3575.137
- Operating system: Ubuntu Studio 14.04.5, Linux Mint 19.3, Linux Mint 17.3

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information
![Screenshot_2020-07-03 Entwicklerwerkzeuge - Home Assistant](https://user-images.githubusercontent.com/3706922/86462719-59bd2480-bd2c-11ea-9baa-aaa151856f48.png)

**Comment by bramkragten** [comment] 2020-07-03 12:07
Duplicate of #6298

**Closed by bramkragten** 2020-07-03 12:07 UTC
Labels: bug
