### ISSUE TITLE
Wrong brand displayed when a device have multiple integration

### ISSUE THREAD

**Issue by BenoitAnastay** [home-assistant/frontend#14163] opened 2022-10-22 20:03 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

- When a device have multiple integrations for example an ESP device which have presence sensing with a router integration might have the router logo on it's brand.

It's a minor issue that need to have integration hiearchy to fix it

![brand-esp](https://user-images.githubusercontent.com/45088785/197360274-49767e8a-bad6-4a25-8341-bdacb9fbb231.PNG)

### Describe the behavior you expected

The brand of the device to be displayed

### Steps to reproduce the issue

Having a device with multiple integrations

### What version of Home Assistant Core has the issue?

core-2023.1.6

**Comment by BenoitAnastay** [comment] 2023-01-21 19:42
The issue is still present

**Comment by steverep** [comment] 2023-03-06 21:11
Duplicate of #14620

**Closed by steverep** 2023-03-06 21:11 UTC

**Comment by steverep** [comment] 2023-03-06 21:15
Normally I'd mark the others as duplicates since this one is older, but that one has a linked PR with some discussion.  Please subscribe or comment on that duplicate to get notifications.  Sorry about that.
