### ISSUE TITLE
Safari  browser shows blank page on login 

### ISSUE THREAD

**Issue by NicholasHaupt** [home-assistant/frontend#20719] opened 2024-05-03 20:49 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have an old iPad (iOS 10.1) that cannot be upgraded anymore. It was perfect for showing my custom built solar dash with guages and switches, etc.
Since this big update of yesterday it  now shows a blank page thus making the iPad totally useless...
Any others have the same problem after the update? Any help on how to fix....

### Describe the behavior you expected

It worked fine in previous versions 

### Steps to reproduce the issue

1. Use Safari browser on old iPad 
2. Login to HA
3.
...

### What version of Home Assistant Core has the issue?

2024.5.0/1

### What was the last working version of Home Assistant Core?

2024.4.x

### In which browser are you experiencing the issue with?

Safari

**Comment by karwosts** [comment] 2024-05-03 23:57
Duplicate of #20697

**Closed by karwosts** 2024-05-03 23:57 UTC
