### ISSUE TITLE
Entities data table text overflow

### ISSUE THREAD

**Issue by snapsl** [home-assistant/frontend#20700] opened 2024-05-02 10:01 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Ordering the entities data table by status causes text to overflow.

https://github.com/home-assistant/frontend/assets/32878439/c78b1dac-d4a1-4c7f-8d86-ce6269a69bf4

### Describe the behavior you expected

Move the text so it fits on the screen.

### Steps to reproduce the issue

...

### What version of Home Assistant Core has the issue?

2024.5.0

**Comment by ildar170975** [comment] 2024-05-02 11:47
duplicate of https://github.com/home-assistant/frontend/issues/15666

**Closed** 2024-05-02 12:26 UTC
