### ISSUE TITLE
Area card: Temperature shown 10 °C too high

### ISSUE THREAD

**Issue by AleXSR700** [home-assistant/frontend#21049] opened 2024-06-09 16:52 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The area card is showing the temperature sensor value 10 °C higher than actual value.

Card:
<img width="371" alt="image" src="https://github.com/home-assistant/frontend/assets/57034871/9fdea071-59df-4fe3-b170-3c5399cada38">

Sensor entity value:
<img width="524" alt="image" src="https://github.com/home-assistant/frontend/assets/57034871/f173daf4-6515-4b63-aaaf-663d2d9b08ce">

### Describe the behavior you expected

Displayed value = sensor value

### Steps to reproduce the issue

1. Install temperature sensor
2. Add sensor to area
3. Add area card
...

### What version of Home Assistant Core has the issue?

2024.6.1

**Comment by karwosts** [comment] 2024-06-09 17:10
You've certainly got a second temperature sensor somewhere in that area, that's reporting a higher value. The area card will _average_ together all temperature sensors in the area.

**Comment by AleXSR700** [comment] 2024-06-09 19:01
Interesting idea. 
There is no other sensor that is part of a climate device. There are temperature entities in the power sockets which of course have higher values.

Is there a way then to select which sensor is being used?

**Comment by karwosts** [comment] 2024-06-09 19:50
No for area card there's not currently a way to select entities. That may change someday in the future. 

It's somewhat simplistic card that isn't going to be appropriate for everyone's usecase.

If you want an entity to not be used for Area card, the best you can do is mark that entity as Hidden, and then it will not be considered for calculations.

**Comment by AleXSR700** [comment] 2024-06-09 20:10
thank you for your support :)

Hiding entities that are useful is not really a good solution just because of a broken card.
I will just remove the card until it is fixed :)

**Comment by karwosts** [comment] 2024-06-09 20:26
Sure that's fine. Though "hiding" is not as severe as it sounds, I think the only difference is they don't show up on autogenerated dashboards. They're still fully useable and visible everywhere else.

**Comment by karwosts** [comment] 2024-06-10 18:38
Closing for now as the card is operating as intended. Certainly additional functionality could be desired, but those desires are probably well covered by existing feature requests, or you can make a new one if you wish.

**Closed by karwosts** 2024-06-10 18:38 UTC

**Comment by AleXSR700** [comment] 2024-06-10 18:46
No, that is fine, thank you.

This is one of the cases where a feature is actually a bug declared as a feature to make it look like it is working as intended 😄

So, since it is a nice-to-have card rather than must-have card, I will keep my fingers crossed and wait :)
