### ISSUE TITLE
Persistent Notification Count on Restart

### ISSUE THREAD

**Issue by woodmj74** [home-assistant/frontend#17137] opened 2023-07-01 18:19 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When HA is restarted, the count of Persistent Notifications is not reset without a page refresh - this is different behavior to earlier releases

### Describe the behavior you expected

The bell icon counter should represent the actual number of persistent notifications without the need to refresh the page

### Steps to reproduce the issue

1: System running with 3 persistent notifications, the bell icon shows a count of 3
2: Restart HA (existing persistent notifications are cleared as part of this)
3: HA now shows a count of 3 but sliding the notification panel out no persistent notifications are present
4: Add a persistent notification, count increases to 4 but the panel only shows 1

### What version of Home Assistant Core has the issue?

2023.7.0b3

### What was the last working version of Home Assistant Core?

2023.5.x

### In which browser are you experiencing the issue with?

Chrome Version 114.0.5735.199 (Official Build) (64-bit), Edge Version 114.0.1823.67 (Official build) (64-bit)

### Which operating system are you using to run this browser?

W11

**Comment by Kisty** [comment] 2023-07-01 18:38
Same issue but upgraded from 2023.5.x to 2023.6.2

**Comment by henkhoekema** [comment] 2023-07-09 14:50
I have exactly the same issue. 
Version  2023.07.1

**Comment by Petro31** [comment] 2023-07-13 12:25
It's not updating the count when you dismiss them via an automation and the page hasn't refreshed in a while.  If the page has refreshed in the past ~5 minutes, the automation will clear the count.

**Comment by woodmj74** [comment] 2023-07-13 13:29
> It's not updating the count when you dismiss them via an automation and the page hasn't refreshed in a while. If the page has refreshed in the past ~5 minutes, the automation will clear the count.

There's no automation in play here. Its a straight forward restart - all PN's are cleared as part of this process but the visual counter doesn't update this.

> Refreshing the page updates to the proper count.

Fully agree it does. I was raising the change in behavior since persistent notifications were changed in 2023.06 (I think).

**Comment by Petro31** [comment] 2023-07-13 13:38
> There's no automation in play here. Its a straight forward restart - all PN's are cleared as part of this process but the visual counter doesn't update this.

I'm adding to the issue.  I'm saying that this is also an issue.  It's all related.  I have an automation and this is occurring.

**Comment by Mariusthvdb** [comment] 2023-07-21 08:23
has been on/off since a long time (not saying this is the exact same thing) and when I filed this over a year ago, it was said maybe not Frontend? https://github.com/home-assistant/frontend/issues/17137

**Comment by Kisty** [comment] 2023-07-27 12:15
I think this is a browser cache issue. When I tried in an incognito tab, I didn't see the problem

**Comment by domolys** [comment] 2023-08-05 14:46
Tried to clear browser data/cache, same issue with "Steps to reproduce" as described.

**Comment by woodmj74** [comment] 2023-11-03 16:50
Issue retested on 2023.11 and still present

**Comment by finity69x2** [comment] 2024-01-17 15:09
It's still happening to me on 2023.12 as well.

**Comment by VDRainer** [comment] 2024-04-16 17:03
Still an issue!

**Comment by henkhoekema** [comment] 2024-07-15 20:39
Keep +1

**Comment by karwosts** [comment] 2024-07-16 00:06
Will be fixed by #21405

**Closed** 2024-07-18 18:53 UTC
