### ISSUE TITLE
statistic graph card has a wrong min hight on classic dashboards

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#21322] opened 2024-07-06 16:40 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

since 2024.7.0 the statistic graph card is using half the hight of before the update, when it is placed on a classic dashboard.
![grafik](https://github.com/home-assistant/frontend/assets/26391061/d1653337-5a8a-4249-83d5-6135d939815f)

in a horizontal Stack card:
![grafik](https://github.com/home-assistant/frontend/assets/26391061/d2cb766a-30d3-4511-a776-d28883838e49)

on the sections dashboard, the hight cannot be set lower than two rows:
![grafik](https://github.com/home-assistant/frontend/assets/26391061/66c8cf6b-1b6d-4b91-9c64-dd6faaf6f520)
![grafik](https://github.com/home-assistant/frontend/assets/26391061/f2ca84a7-09c6-4747-be12-32c3e98d2836)

Compared with an 2024.8.dev on a classic Dashboard (auto-generated)
![grafik](https://github.com/home-assistant/frontend/assets/26391061/e15e2ede-8e1b-4e98-88fa-08b4cf1ee0aa)

### Describe the behavior you expected

the graph card should have the correct size on a standard dashboard than previously (before 2024.7.x)

### Steps to reproduce the issue

1. create a statistic graph card on a regular dashboard
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.7.1

### What was the last working version of Home Assistant Core?

2024.6.x

**Comment by karwosts** [comment] 2024-07-06 18:13
You sure you're not talking about sensor card, not statistics graph card?

If so, that is duplicate of #21317

**Comment by ChristophCaina** [comment] 2024-07-06 18:15
thanks,
then it is a duplicate

**Closed** 2024-07-06 18:19 UTC
