### ISSUE TITLE
Helpers

### ISSUE THREAD

**Issue by fordemon92** [home-assistant/frontend#16991] opened 2023-06-22 03:11 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I Go to Devices then helpers then to create helper it no longer does anything I do not get a overlay for creating a helper nor can I delete old unused helpers.

### Describe the behavior you expected

When I Go to Devices then helpers then to create helper I should get the overlay to setup the helper.

### Steps to reproduce the issue

1. go to settings
2. go to devices
3. go to helpers on top bar
4. click create helper on bottom right
...

### What version of Home Assistant Core has the issue?

2023.6.2

### In which browser are you experiencing the issue with?

Google Chrome version 114.0.5735.134 and Microsoft Edge Version 114.0.1823.51  

### Which operating system are you using to run this browser?

Windows 10 Pro Version 22H2

**Comment by ildar170975** [comment] 2023-06-22 09:11
Please search for existing issues before creating a new one.
https://github.com/home-assistant/frontend/issues/16896

**Comment by karwosts** [comment] 2023-06-23 13:21
Closing as duplicate of #16896

**Closed by karwosts** 2023-06-23 13:21 UTC
