### ISSUE TITLE
Strings to reboot core and supervisor are no longer built correctly when interface is in Dutch language

### ISSUE THREAD

**Issue by tvennekens** [home-assistant/frontend#8569] opened 2021-03-06 14:49 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Strings to reboot core and supervisor are no longer built correctly when interface is in Dutch language (Nederlands).
Suspect translation has been done and variable "name" has been translated as well to "naam".

Errors seen:
- Core: Translation Error: The intl string context variable "naam" was not provided to the string "Weet u zeker dat u {naam} opnieuw wilt starten?"
- Supervisor: Translation Error: The intl string context variable "naam" was not provided to the string "Weet u zeker dat u {naam} opnieuw wilt starten?"

### Describe the behavior you expected

Strings built as follows:
"Weet u zeker dat u Core opnieuw wilt starten?"
"Weet u zeker dat u Supervisor opnieuw wilt starten?"

### Steps to reproduce the issue

1. Change language to Dutch (Nederlands)
2. Open [Supervisor] >> [Syste(e)m]
3. Check reboot message for Core and Supervisor

### What version of Home Assistant Core has the issue?

core-2021.3.2

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.190

### Which operating system are you using to run this browser?

Win10 2004

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment] 2021-03-06 18:01
Duplicate of https://github.com/home-assistant/frontend/issues/8550.

**Closed by spacegaier** 2021-03-06 18:01 UTC
Labels: bug
