### ISSUE TITLE
Can't re-enable disabled template sensors from helpers view

### ISSUE THREAD

**Issue by Jarru8** [home-assistant/frontend#20486] opened 2024-04-09 21:15 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have made few helpers using template sensor, i disabled the sensors and after disabling the Settings link from sensor takes me to wrong view, it goes directly to template editing so i cannot re-enable the sensor from UI
![Screenshot_20240409_234613_Home Assistant](https://github.com/home-assistant/frontend/assets/22845411/34501a13-93f9-4d0d-9f1a-b44dbbbcdfee)
the link goes directly to this view:
![Screenshot_20240410_000436_Home Assistant](https://github.com/home-assistant/frontend/assets/22845411/65c25c3d-f52c-42ee-9b3c-528649581e9a)

### Describe the behavior you expected

I expect that it would go to the general view like this:
![Screenshot_20240410_000734_Home Assistant](https://github.com/home-assistant/frontend/assets/22845411/d604f72d-4d68-437a-bb5f-8fc5918d4690)

### Steps to reproduce the issue

1. Make a template sensor using helpers view
2. Disable a template sensor by going to setting and disable the sensor
3. Try to go to setting and re-enable the sensor
4. You are now in template editing view and unable to re-enable the sensor

### What version of Home Assistant Core has the issue?

core-2024.4.2

**Comment by RonaldRegister** [comment] 2024-05-07 17:57
I'm having this exact same issue, on 2024.4.4

**Comment by karwosts** [comment] 2024-05-08 02:58
You can delete entities (including helpers) from the `Config/Entities` tab. You may have to change the filters to show disabled entities.

**Comment by Jarru8** [comment] 2024-05-08 03:49
>

**Comment by Jarru8** [comment] 2024-05-08 04:34
Sorry, i accidently closed and opened the issue on mobile 😅, but i think this was closed as duplicate?

**Comment by karwosts** [comment] 2024-05-08 04:35
This was not closed as duplicate. 

There is an inbound link from another issue ticket that was closed as a duplicate of this one, maybe that is what you are seeing.

**Comment by RonaldRegister** [comment] 2024-05-08 07:50
thank you @karwosts!

I did not think of that! From here I'm also able to re-enable the helper, and delete it the regular way.

**Comment by kevinhaas** [comment] 2024-06-23 01:47
It's still a bit confusing you can't do it from the helpers screen directly, and more confusing that when you go to the settings and hit submit, it says "success" but doesn't work.

**Comment by fumantsu** [comment] 2024-10-04 08:44
still exist in 2024.9

**Closed** 2024-11-09 23:40 UTC
