### ISSUE TITLE
Inputting or editing text via code editor or yaml mode not possible on IOS devices

### ISSUE THREAD

**Issue by pedolsky** [home-assistant/frontend#8896] opened 2021-04-11 22:07 UTC
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I’m using iPad Air 3. Gen. with the latest iPadOS.
When I try to insert yaml code into a card, existing code cannot be deleted; furthermore, the cursor cannot be positioned. 
The same happens when I try to change code in the raw config editor or edit automations in yaml mode.

***Edit: Dev tools (Services and Template) are also affected.

### Describe the behavior you expected

The cursor should be able to be positioned at the desired place without any problems; code should be able to be deleted or changed.

### Steps to reproduce the issue

1. Use an iPad or iPhone

2. Open Companion App or your HA instance in a browser

3. Choose a type of card on your dashboard / raw config editor / automation in the config section 

4. Try to fill in / past / edit / delete text at the desired position
.

### What version of Home Assistant Core has the issue?

core-2021.4.3

### In which browser are you experiencing the issue with?

Companion App 2021.3; Google Chrome for iPad 87.0.4280163; Safari (don‘t know version - latest I think)

### Which operating system are you using to run this browser?

iPadOS 14.4.2; iOS 14.5 Beta 6

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by emufan** [comment] 2021-04-15 19:07
I second this. Editing is completely destroyed with 2021.4. Before is was already bad (copy and paste) was only possible line by line and not for selected blocks, but now nothing is possible anymore. Backspace results in nothing. Entering characters enter them always at the beginning from the whole yaml file currently in editor. Etc etc.

**Comment by glassbase** [comment] 2021-04-16 12:20
Me as well. 
v2021.4.1

**Comment by bramkragten** [comment] 2021-04-16 14:33
Duplicate of https://github.com/home-assistant/frontend/issues/8542

**Closed by bramkragten** 2021-04-16 14:33 UTC
Labels: bug, code-editor

**Comment by pedolsky** [comment] 2021-05-09 09:39
Please reopen.

With HA 21.5 editor was working again - til HA version 21.5.1. Now everything is as it was before 21.5.

**Comment by spacegaier** [comment] 2021-05-09 10:08
Version 2021.5.1 does contain the same frontend version as 2021.5.0 did, so there cannot be a frontend regression there.

**Comment by pedolsky** [comment] 2021-05-17 07:55
After reverting via snapshot and re-installing I can use the editors. No offence.
