### ISSUE TITLE
Error while loading page lovelace on 2024.6.0

### ISSUE THREAD

**Issue by LFernandoHA** [home-assistant/frontend#21024] opened 2024-06-07 14:42 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Home Assistant (app and web) show a behavior just like exposed in #20697, now on version 2024.6.0:
- does not show the content of its pages at all, showing only the menu sidebar and a message "Error while loading page..." at the center of the display,
- the menu sidebar appears with some icons missing and options names in an unusual format, like "media_browser" and  "developer_tools".
Issue exists on:
the HA Companion app (2023.12.1) on an old ipad running iOS 12.5.7 (max for the iPad)
Safari and Google Chrome (92.0.4515.90 - newest for the iOS version) on an old iPad running iOS 12.5.7 (max for the iPad)

Issue does not exist in Android (Samsung S20 and tablets Samsung Tab 4, Tab 5 and Tab 6) and Windows 11 (Dell notebook) devices.

Details:
Pages related to the Google Drive Backup integration is working (except for "Logs" page, which gives a 401 Error), appears to be ok.
Page from Dock Wyze Bridge integration works fine, showing a snapshot and able to call the webpage that shows the stream. 
Home Asssistant components versions:
Core: 2024.6.0
Supervisor: 2024.06.0
Operating System: 12.3
Frontend: 20240605.0

### Describe the behavior you expected

The app and Chrome instances of Home Assistant should work normally on the iPad Air running  iOS 12.5.7 (max for the iPad).

### Steps to reproduce the issue

1.Upgrade to 2024.6.0
2. Try to login and use HA on an old iOS version or any Chrome browser on iOS 12.5.7
3.The UI will fail to display dashboards, Energy, Logbook, History, Developer Tools, HACS, ESPHome, Settings (but will display addons such as Backups and Dock Wyze Bridge).

### What version of Home Assistant Core has the issue?

2024.6.0

### What was the last working version of Home Assistant Core?

2024.5.5

### In which browser are you experiencing the issue with?

Chrome 92.0.4515.90 and and Home Assistant Companion (can't find the version, Settings page is not opening)

### Which operating system are you using to run this browser?

iOS 12.5.7

**Comment by karwosts** [comment] 2024-06-07 15:20
duplicate of #21004

**Closed by karwosts** 2024-06-07 15:20 UTC
