### ISSUE TITLE
Climate entity ignores 'precision' in UI

### ISSUE THREAD

**Issue by andriej** [home-assistant/frontend#7308] opened 2020-10-11 10:55 UTC
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have "generic thermostat" climate.* domain devices with `precision: 0.1`.
When I open those entities in UI view, I can only set the target temperature with step of 0.5, nothing in between.
![image](https://user-images.githubusercontent.com/6303489/95676708-5c97a300-0bc0-11eb-8097-1ad13bff61b3.png)

Click of up or down arrow marked yellow on screenshot would make it either 19.5 or 18.5, not 19.1 and 18.9 as desired.

## Expected behavior

Respect `precision`

## Steps to reproduce

1. Add climate generic thermostat 
2. Set it's precision to 0.1
3. Add the entity to 'entities' UI lovelace card
4. Open the entity
5. Try to set temperature with 0.1*C higher value than shown

## Environment

- Home Assistant release with the issue: 0.116.2
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome latest (no matter browser)
- Operating system: Win 10

## State of relevant entities

```yaml

heat 
hvac_modes: heat, off 
min_temp: 10 
max_temp: 26 
preset_modes: none, away 
current_temperature: 20.7 
temperature: 19 
hvac_action: idle 
preset_mode: none 
friendly_name: Garaż 
supported_features: 17
```

## Problem-relevant configuration

```yaml
- platform: generic_thermostat
  name: Garaż
  heater: group.co_parter_garaz
  target_sensor: sensor.temperature_garaz
  min_temp: 10
  max_temp: 26
  precision: 0.1
  away_temp: 16
  hot_tolerance: 0
  cold_tolerance: 0.3
  min_cycle_duration:
    minutes: 30
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by biga85** [comment] 2020-10-16 19:41
The same problem for me. I have fresh install of HA and did not understand what happening. Previously I was using ~0.96.x version and everything was fine.

**Comment by spacegaier** [comment] 2020-10-16 20:56
It is actually a backend issue, since the `generic_thermostat` is not properly exposing the temperature step size and therefore the frontend cannot read it. The `climate` platform that I am using is for example properly exposing the step size, which is why it always worked for me.

I fixed `generic_thermostat` on my dev machine already and will prepare a PR for [home-assistant/core](https://github.com/home-assistant/core). Let's leave this issue open until confirmed that my PR works.

**Comment by milanvo** [comment] 2020-11-24 12:48
Hit this issue too. Until core PR will be merged, I have workaround - configure `target_temp_step` via `customize.yaml`:

```
climate.garaz:
  target_temp_step: 0.1
```
Customization should be enabled first: https://www.home-assistant.io/docs/configuration/customizing-devices/

**Closed** 2020-11-25 17:45 UTC
Labels: bug
