### ISSUE TITLE
Deleting snapshots duplicates the core-menu

### ISSUE THREAD

**Issue by mcnovy** [home-assistant/frontend#8993] opened 2021-04-24 15:02 UTC
### Describe the issue you are experiencing

Everytime I delete an old snapshot, it open home assistant core page inside the supervisor frame, rather than only the supervisor page.
![image](https://user-images.githubusercontent.com/6799500/115963012-32834e00-a51e-11eb-8b31-5831f43f2578.png)

### What is the used version of the Supervisor?

supervisor-2021.04.0

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

5.13

### What version of Home Assistant Core is installed?

core-2021.4.6

### Steps to reproduce the issue

1. go to supervisor
2. click snapshots
3. click a snapshot you wish to delete
4. delete it
...

### Anything in the Supervisor logs that might be useful for us?

None

### Additional information

Since the introduction of creating snapshot after updating any add-on or the core, a "delete selected" could be beneficial.

**Comment by spacegaier** [comment] 2021-04-26 09:53
Duplicate of https://github.com/home-assistant/frontend/issues/8926.

**Closed by spacegaier** 2021-04-26 09:53 UTC
