### ISSUE TITLE
Helper Workflows inconsistent

### ISSUE THREAD

**Issue by muddro1** [home-assistant/frontend#19148] opened 2023-12-26 19:18 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Depending on the helper you choose to create, some have a back button to go back to the main list of helpers, and others you just have to cancel out. IE: Adding a utility meter does not have a back, while creating a button does.

From quickly going through, the following helper workflows do not have a back button:
- Change devise type of a switch
- Combine State
- Derivative
- Group
- Integration
- Random
- Template
- Threshold
- Times of day
- Utility meter

### Describe the behavior you expected

All helper workflows should have a back button to go back to the main helper list

### Steps to reproduce the issue

Described above

### What version of Home Assistant Core has the issue?

core-2023.12.3

**Comment by karwosts** [comment] 2023-12-26 20:23
Duplicate of #12275

**Closed by karwosts** 2023-12-26 20:23 UTC
