### ISSUE TITLE
Opening dropdown changes selected entity

### ISSUE THREAD

**Issue by Hootie81** [home-assistant/frontend#13670] opened 2022-09-09 01:23 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Several entities may have the same name, however they have a unique entity_id. some entities share the same name as they are added automatically or via 2 integrations, ie the device itself and the tracker for the device via the router integrations

part of the problem, once selected you cannot see enough info about the entity selected - only its friendly name, not the ID which also needs to be displayed.

the bug! once an entity is selected and you have no idea which one unless you change to yaml edit mode, only its friendly name is visible. if you select the dropdown and close it by clicking somewhere else a different entity is selected - the first one with that friendly name

this happens in the automation builder and the dashboard editor

### Describe the behavior you expected

once an entity is selected, clicking the dropdown and closing it again should leave the same entity in the automation/dashboard

once an entity is selected display its friendly name and entity ID in small text below

 

### Steps to reproduce the issue

1. add an entity card, select one entity where you have mode than one with the same name - i.e. uptime sensor, or something thats got device tracker assosiated, select the second or 3rd with the same name
2.switch to yaml and check which entity is actually selected
3. select the deopdown and select out of the dropdown
4. switch to yaml and check which entity is actually selected

### What version of Home Assistant Core has the issue?

noticed in 2022.8, still in 2022.9.0

### In which browser are you experiencing the issue with?

chrome 105.0.5195.53 + androud app beta-2646-84aa4454-full

### Which operating system are you using to run this browser?

win 10 / android 13

### Additional information

![names](https://user-images.githubusercontent.com/7753214/189252470-277d5ac7-f271-4070-ac1b-e660a3a64253.png)
this shows some entities that have the issue, all auto-generated

**Comment by ildar170975** [comment] 2022-09-09 12:38
Seems to be same https://github.com/home-assistant/frontend/issues/12889
Described as fixed.
Probably will be added in the next release.

**Comment by emontnemery** [comment] 2022-09-09 12:41
Closing, duplicate of #12889

**Closed by emontnemery** 2022-09-09 12:41 UTC

**Comment by spacegaier** [comment] 2022-09-09 13:57
That mentioned fix that I had made was already part of the 2022.9.0 release, so if the issue is still appearing there (as reported above), then we might have a different issue here.

**Comment by Hootie81** [comment] 2022-09-09 14:22
confirmed still happening in the automation builder in 2022.9.0, looks to be fixed when editing things in an entities card in lovelace.

exactly the same issue, just in another place!

**Comment by ildar170975** [comment] 2022-09-09 14:38
Checked in History page, Dev-tools -> Set state.
Seems to be fixed.

**Comment by Hootie81** [comment] 2022-09-09 14:41
yes i had noticed it in a few places before, but it still exists in the automation builder.

steps in the first post to reproduce.
