### ISSUE TITLE
context variable "naam"was not provided..

### ISSUE THREAD

**Issue by stresskiller** [home-assistant/frontend#8617] opened 2021-03-11 12:10 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

probably a translation error in Dutch version "language Nederlands" when i switch to English the problem no longer excist.
mouse over mentions a translation error

### Describe the behavior you expected

expect to see clickable text like "herstart / restart core"

### Steps to reproduce the issue

1.http://homeassistant.local:8123/profile
2.select language "nederlands"
3.http://homeassistant.local:8123/hassio/system
4.underneath Core is should show restart core in dutch "herstart core ?" instead it shows context variable "naam" was not provided to the string "herstart
...

### What version of Home Assistant Core has the issue?

core-2021.3.3

### In which browser are you experiencing the issue with?

brave 1.21.74 chromium:89.0.4389.72

### Which operating system are you using to run this browser?

win 10

### State of relevant entities

Versie
supervisor-2021.03.4
Nieuwste versie
supervisor-2021.03.4
Core
Versie
core-2021.3.3
Nieuwste versie
core-2021.3.3
Besturingssysteem
Home Assistant OS 5.12
Implementatie
production

### Problem-relevant frontend configuration

translation error

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

looks like a translation error to me

**Comment by spacegaier** [comment] 2021-03-11 13:21
Is no one searching if a bug has already been reported before? It's now the fifth time that someones raises this...

Duplicate of https://github.com/home-assistant/frontend/issues/8616 and many others.

**Closed by spacegaier** 2021-03-11 13:21 UTC
Labels: bug
