### ISSUE TITLE
Group Switch Button missing in 20230411.0 - latest

### ISSUE THREAD

**Issue by jlong23** [home-assistant/frontend#16171] opened 2023-04-13 13:41 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After the latest release, all 'Group Lights' are missing from the UI Dashbords

The Entity for the groups still show in developer --> States
The groups still function with 'She who shall not be named' (Alexa)

Just do not render on the UI nor on the Android UI

**_Environment:_**
Home Assistant 2023.4.3
Supervisor 2023.04.0
Operating System 9.5
Frontend 20230411.0 - latest

**_Card Configuration Yaml:_**
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-light-card
        name: Utility Room Light
        entity: light.utility_room_light
      - type: custom:mushroom-light-card
        name: Utility Overhead Light
        entity: switch.utility_overhead
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-light-card
        name: B1
        entity: light.basement_bathroom_light_1
      - type: custom:mushroom-light-card
        name: B2
        entity: light.basement_bathroom_light_2
      - type: custom:mushroom-light-card
        name: 3
        entity: light.basement_bathroom_light_3
      **- show_name: false
        show_icon: true
        type: button
        tap_action:
          action: toggle
        show_state: false
        name: Lights
        entity: light.basement_bathroom**
  - type: grid
    square: true
    columns: 5
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.bedtime_group
        name: Bedtime
      - type: button
        tap_action:
          action: toggle
        entity: light.basement_kitchen_group
        name: Kitchen
      - type: button
        tap_action:
          action: toggle
        entity: light.family_room
        name: Family Room
      - type: button
        tap_action:
          action: toggle
        entity: light.stairs_group
        name: Stairs
      - type: button
        tap_action:
          action: toggle
        entity: light.laundry_group
        name: Laundry
  - type: horizontal-stack
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: input_boolean.office_dark_mode
        name: Dark Mode
      - type: custom:button-card
        entity: scene.office_lighting
        name: Office Scene
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.office_lighting
      - type: custom:button-card
        entity: scene.family_room_night_light
        name: Night Light
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.bedtime_scene
      - type: custom:button-card
        entity: scene.bunny_scene
        name: Bunny
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.bunny_scene

![Screenshot from 2023-04-13 08-31-32](https://user-images.githubusercontent.com/12409196/231776137-d68061e1-328d-427e-b248-27132e537771.png)

### Describe the behavior you expected

UI Group buttons to function

### Steps to reproduce the issue

See description

### What version of Home Assistant Core has the issue?

2023.4.3

### What was the last working version of Home Assistant Core?

2023.4.2

### In which browser are you experiencing the issue with?

Version 112.0.5615.49 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux blackberry 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### State of relevant entities

```txt
Does not matter
```

### Javascript errors shown in your browser console/inspector

```txt
mushroom.js?hacstag=444350375263:1328 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at Dl (mushroom.js?hacstag=444350375263:1328:10226)
    at lc.render (mushroom.js?hacstag=444350375263:2496:2276)
    at lc.update (mushroom.js?hacstag=444350375263:23:298)
    at lc.performUpdate (mushroom.js?hacstag=444350375263:11:5089)
    at lc.scheduleUpdate (mushroom.js?hacstag=444350375263:11:4736)
    at lc._$Ej (mushroom.js?hacstag=444350375263:11:4644)
Dl @ mushroom.js?hacstag=444350375263:1328
render @ mushroom.js?hacstag=444350375263:2496
update @ mushroom.js?hacstag=444350375263:23
performUpdate @ mushroom.js?hacstag=444350375263:11
scheduleUpdate @ mushroom.js?hacstag=444350375263:11
_$Ej @ mushroom.js?hacstag=444350375263:11
await in _$Ej (async)
requestUpdate @ mushroom.js?hacstag=444350375263:11
set @ mushroom.js?hacstag=444350375263:11
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1380
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1380
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
(anonymous) @ hui-view.ts:151
value @ hui-view.ts:149
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hui-root.ts:929
(anonymous) @ hui-root.ts:671
setTimeout (async)
(anonymous) @ render-status.ts:2
requestAnimationFrame (async)
i @ render-status.ts:2
value @ hui-root.ts:671
_$AE @ reactive-element.ts:1380
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1871
_$AI @ lit-html.ts:1813
p @ lit-html.ts:1181
$ @ lit-html.ts:1528
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ partial-panel-resolver.ts:112
value @ hass-router-page.ts:139
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1871
_$AI @ lit-html.ts:1813
p @ lit-html.ts:1181
$ @ lit-html.ts:1528
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1871
_$AI @ lit-html.ts:1813
p @ lit-html.ts:1181
$ @ lit-html.ts:1528
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
t @ home-assistant.ts:92
(anonymous) @ home-assistant.ts:102
i @ fire_event.ts:76
s @ navigate.ts:43
value @ hui-root.ts:821
value @ hui-root.ts:875
handleEvent @ lit-html.ts:2006
fire @ legacy-element-mixin.js:577
_itemActivate @ iron-selectable.js:391
_activateHandler @ iron-selectable.js:383
_activateHandler @ iron-menu-behavior.js:415
_activateHandler @ paper-tabs.js:407
(anonymous) @ template-stamp.js:183
B @ gestures.js:676
V @ gestures.js:1072
click @ gestures.js:1031
M @ gestures.js:464
14mushroom.js?hacstag=444350375263:1328 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at Dl (mushroom.js?hacstag=444350375263:1328:10226)
    at lc.render (mushroom.js?hacstag=444350375263:2496:2276)
    at lc.update (mushroom.js?hacstag=444350375263:23:298)
    at lc.performUpdate (mushroom.js?hacstag=444350375263:11:5089)
    at lc.scheduleUpdate (mushroom.js?hacstag=444350375263:11:4736)
    at lc._$Ej (mushroom.js?hacstag=444350375263:11:4644)
Dl @ mushroom.js?hacstag=444350375263:1328
render @ mushroom.js?hacstag=444350375263:2496
update @ mushroom.js?hacstag=444350375263:23
performUpdate @ mushroom.js?hacstag=444350375263:11
scheduleUpdate @ mushroom.js?hacstag=444350375263:11
_$Ej @ mushroom.js?hacstag=444350375263:11
await in _$Ej (async)
requestUpdate @ mushroom.js?hacstag=444350375263:11
set @ mushroom.js?hacstag=444350375263:11
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1380
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hui-stack-card.ts:63
_$AE @ reactive-element.ts:1380
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
(anonymous) @ hui-view.ts:151
value @ hui-view.ts:149
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hui-root.ts:598
_$AE @ reactive-element.ts:1380
performUpdate @ reactive-element.ts:1345
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1871
_$AI @ lit-html.ts:1813
p @ lit-html.ts:1181
$ @ lit-html.ts:1528
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ partial-panel-resolver.ts:112
value @ hass-router-page.ts:93
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1871
_$AI @ lit-html.ts:1813
p @ lit-html.ts:1181
$ @ lit-html.ts:1528
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
j @ lit-html.ts:1871
_$AI @ lit-html.ts:1813
p @ lit-html.ts:1181
$ @ lit-html.ts:1528
_$AI @ lit-html.ts:1375
G @ lit-html.ts:2172
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1331
scheduleUpdate @ reactive-element.ts:1263
_$Ej @ reactive-element.ts:1235
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1210
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:52
_updateHass @ context-mixin.ts:86
(anonymous) @ connection-mixin.ts:190
s @ store.js:19
(anonymous) @ entities.js:74
e.subscribeMessage.type @ entities.js:76
(anonymous) @ connection.js:23
_handleMessage @ connection.js:15
```

**Comment by bramkragten** [comment] 2023-04-13 13:59
duplicate of #16172

**Closed by bramkragten** 2023-04-13 13:59 UTC
