### ISSUE TITLE
Calendar in history is stuck in February 

### ISSUE THREAD

**Issue by ericvandamme** [home-assistant/frontend#15802] opened 2023-03-13 01:14 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The calendar for selecting date ranges is stuck displaying February. As we roll over into a new week, I always have to advanced the month to March so I can select current date ranges. 

![2A05208E-04B1-4711-81B7-933BFEA2FB77](https://user-images.githubusercontent.com/28657401/224586453-e336d825-e0e8-4ccf-8f15-cacbef506acd.png)

### Describe the behavior you expected

I would expect that it would align itself to either the start date or end date of the currently selected date.

### Steps to reproduce the issue

1. In history, select a date. 

### What version of Home Assistant Core has the issue?

Supervised

### What was the last working version of Home Assistant Core?

Believed to be 2023.2 since it was the correct month

### In which browser are you experiencing the issue with?

Firefox. Companion app (iOS) 

### Which operating system are you using to run this browser?

Windows 10; Debian 11; iOS 16.3.1

### Additional information

I believe this to be related to 2023.3 updates, but because it got stuck in February, it may have been an issue since 2023.2. 

I help manage other instances, and all seem to exhibit this behaviour. All are running 2023.3 or newer.

**Comment by ildar170975** [comment] 2023-03-13 01:58
Duplicate of https://github.com/home-assistant/frontend/issues/15800

**Closed** 2023-03-13 19:12 UTC
