### ISSUE TITLE
Missing monetary state_class in scrape sensor config 

### ISSUE THREAD

**Issue by luca-angemi** [home-assistant/frontend#19500] opened 2024-01-21 17:33 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding a scrape sensor the monetary state_class in config flow is missing

### Describe the behavior you expected

monetary should be available

### Steps to reproduce the issue

1. Add a scrape sensor through config flow

![image](https://github.com/home-assistant/frontend/assets/9977955/93b0a443-a86f-4c42-b2a4-cf6ed51acced)

### What version of Home Assistant Core has the issue?

2024.1

**Comment by karwosts** [comment] 2024-01-21 17:37
Duplicate of #18704.

Select "Balance" from the dropdown.

**Closed** 2024-01-21 17:37 UTC

**Comment by luca-angemi** [comment] 2024-01-21 17:39
Thanks!
