### ISSUE TITLE
Pasting mdi name crashes Chrome tab

### ISSUE THREAD

**Issue by snis** [home-assistant/frontend#13823] opened 2022-09-20 13:13 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Trying to change entity icon, in my clipboard I have 'mdi:globe-light-outline', when I paste it to the input field the browser-tab freezes and in Vivaldi and Chrome the tab crashes, Firefox freezes but recovers.

### Describe the behavior you expected

No browser crash

### Steps to reproduce the issue

I go via 
Integrations -> mqtt / entities -> filter on 'lights', 
selects an entity and pastes the icon name.

Immediate freeze

### What version of Home Assistant Core has the issue?

core-2022.9.5 - Frontend 20220907.2

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.125 / Vivaldi 5.4.2753.51 / Firefox 104.0.2

### Which operating system are you using to run this browser?

Linux 5.19.9-arch1-1

**Comment by Sjorsa** [comment] 2022-10-29 18:07
Same issue here. Very weird. Pasting any string that doesn't start with `mdi:` works fine.

**Comment by steverep** [comment] 2022-11-16 22:45
Duplicate of #14147

**Closed by steverep** 2022-11-16 22:45 UTC

**Comment by steverep** [comment] 2022-11-16 22:47
I would have kept this older issue and marked the new one as duplicate, but the new one has a linked PR that is in work.

cc: @piitaya
