### ISSUE TITLE
Logs page: add-on logs in log switcher not sorted alphabetically

### ISSUE THREAD

**Issue by SeanPM5** [home-assistant/frontend#20955] opened 2024-06-02 03:46 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In logs page there's a log switcher dropdown menu in top right. It shows the users installed add-ons, but these aren't sorted and makes it harder to find things in the menu.

<img width="743" alt="Screen Shot 2024-06-01 at 10 35 23 PM" src="https://github.com/home-assistant/frontend/assets/9065557/fc36346d-cde5-4738-89ba-20eb8cf69a49">

### Describe the behavior you expected

Sort add-ons alphabetically to make it easier for user to find in the dropdown

Maybe add a divider too seperating the default system logs and the users add-on logs

### Steps to reproduce the issue

[![Open your Home Assistant instance and show your Home Assistant logs.](https://my.home-assistant.io/badges/logs.svg)](https://my.home-assistant.io/redirect/logs/?)

1. Navigate to Settings → System → Logs
2. Open log switcher in top right, your installed add-ons are not listed alphabetically

### What version of Home Assistant Core has the issue?

2024.6.0b4

**Comment by karwosts** [comment] 2024-06-02 05:25
Duplicate of #20648 (which you also filed)

**Closed by karwosts** 2024-06-02 05:25 UTC
