### ISSUE TITLE
calendar display is wrong when switching from 7day view to month view

### ISSUE THREAD

**Issue by turboc1208** [home-assistant/frontend#18130] opened 2023-10-05 19:08 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When switching from the 7 day view to the month view on the calendar, the month shows up compressd into thee top left corner.  It is acting like it is trying too display the month calendar into the grid cell left behind from the 7 day view.

### Describe the behavior you expected

I expect it to display the full card view like it does if you start out in the month view.

### Steps to reproduce the issue

1. setup calendar card as default month view by editing the dashboard and the calendar card.  
2. exit edit mode
3. on the calendar card switch from month view to 7 day view
4. after 7 day view is displayed, switch back to month view.
...

### What version of Home Assistant Core has the issue?

2023.9.4

### In which browser are you experiencing the issue with?

Google Chrome Version 116.0.5845.179

### Which operating system are you using to run this browser?

macOS Ventura version 13.5.2 and others

**Comment by karwosts** [comment] 2023-10-05 21:52
I think this is probably duplicate of, or at least related to, #16848

**Comment by karwosts** [comment] 2023-10-24 17:58
Fixed by #18381

**Closed by karwosts** 2023-10-24 17:58 UTC
