### ISSUE TITLE
The "Precision" tab does not exist

### ISSUE THREAD

**Issue by RH-Dreambox** [home-assistant/frontend#15318] opened 2023-02-02 14:43 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The "Precision" tab does not exist in update 2023.2 so I cannot change the number of decimal places on my sensors.
Do I need to enable that feature or is it missing from my update?
The installation is Generic x86-64 (Dell Optiplex)

Home Assistant 2023.2.0
Supervisor 2023.01.1
Operating System 9.5
Frontend-version: 20230201.0 - latest

### Describe the behavior you expected

The "Precision" tab does not exist

### Steps to reproduce the issue

1. Select a temperature sensor
2. Open settings
3. The "Precision" tab does not exist
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.0

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
sensor.lumi_1_rum_rh_temperature
Lumi_1_Rum_RH_temperature
22.67	state_class: measurement
unit_of_measurement: °C
device_class: temperature
friendly_name: Lumi_1_Rum_RH_temperature
```

**Comment by karwosts** [comment] 2023-02-02 14:51
This feature was pulled from the beta, the devs thought it needed more work before being released. So it does not exist yet.

**Comment by frenck** [comment] 2023-02-02 15:58
Closing this, as this is not a bug. The precision features were there during beta and removed from beta as we have found potential issues with them. It has thus not been released. It might return in the future.

../Frenck

**Closed by frenck** 2023-02-02 15:58 UTC

**Comment by nikito7** [comment] 2023-02-02 23:21
But changes are permanent.

Precision set in beta continues in final
