### ISSUE TITLE
Suggested areas are not suggested in UI after config flow

### ISSUE THREAD

**Issue by allenporter** [home-assistant/frontend#11407] opened 2022-01-22 16:17 UTC
### The problem

I recently added suggested area support to Nest, and show do show up in the devices panel for example:

<img width="915" alt="Screen Shot 2022-01-22 at 8 13 42 AM" src="https://user-images.githubusercontent.com/6026418/150646718-b5796226-61a6-4c30-be45-9ee03b97b27b.png">

However, they do not show up suggested at the end of the config flow when adding these same devices:

<img width="592" alt="Config Flow Missing Suggestions" src="https://user-images.githubusercontent.com/6026418/150646773-413628a2-cc12-40f6-b387-f225f6466a6d.png">

### What version of Home Assistant Core has the issue?

dev

### What type of installation are you running?

Home Assistant Core

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/nest/

**Comment by balloob** [comment] 2022-01-23 04:57
Transferring this to the frontend as I am pretty sure the issue is here.

**Comment by allenporter** [comment] 2022-01-23 05:25
Yeah good point, I believe I did confirm they are returned over the websocket last time I checked, but need to confirm again.

**Comment by balloob** [comment] 2022-01-23 05:52
My initial gut feeling is that the data is not propagated properly to the area picker. It probably assumes no area was ever set.

**Closed** 2022-11-15 14:09 UTC
