### ISSUE TITLE
Missing translation text in automatisation

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18893] opened 2023-12-04 18:58 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing translation text in automatisation (screeenshots attached)

![1701698828650](https://github.com/home-assistant/frontend/assets/61636045/678ff4f7-1057-4f81-8b78-ffea66c3538b)

![1701698828658](https://github.com/home-assistant/frontend/assets/61636045/c48e5e64-5ea2-4bb6-8a18-6a62fa05de12)

### Describe the behavior you expected

Please add missing text to translation

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment] 2024-01-05 01:19
First screenshot is duplicate of #18356, bottom screenshot (confirm condition) is now localized, closing.

**Closed by karwosts** 2024-01-05 01:19 UTC
Labels: localization
