### ISSUE TITLE
Sensor graph card issues with Hours to Show

### ISSUE THREAD

**Issue by Uriziel01** [home-assistant/frontend#8228] opened 2021-01-24 22:36 UTC
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

After changing `Hours to show` options in my graphs from 24 to 72 hours I get glitches where my card shows values from before the 24 period as just a flat line with latest value from default 24 hours period.

The only fixes I've came up with is to eighter refresh the entire HA page or edit the card, change anything and click `save`, it regenerates the card and fixed the graph for a moment.

Also **not sure if this is a bug or intended behavior** but after clicking on the graph detailed graph shows up in a modal window and it just ignores the `Hours to Show` setting showing me just the default 24 hours? This is of no use for me so for now I just use `History` tab to review actual values 🤔 

Data for all the graphs I have custom periods for come from MQTT if that is of any importance.

![image](https://user-images.githubusercontent.com/568207/105645814-65c12d00-5e9c-11eb-9b82-a24de4639859.png)

![image](https://user-images.githubusercontent.com/568207/105645817-6b1e7780-5e9c-11eb-978e-c3cd9305ab09.png)

## Expected behavior

Graph should show correct values for custom periods of more than 24 hours all the time.

## Steps to reproduce

1. Create a graph card from a sensor with some historical data od at least 72 hours
2. Customize the card's `Hours to Show` to 72 hours
3. Leave the browser card opened untill the value in the graph changes (different value from the last one recorded!)
4. Observe as the cards have no correct data from period before the default 24 hours just a flat line

## Environment

- Home Assistant release with the issue: 2021.1.5
- Last working Home Assistant release (if known): - 
- Browser and browser version: Chrome 87 / Opera 73
- Operating system: Linux Debian 10

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by spacegaier** [comment] 2021-01-24 22:51
Duplicate of https://github.com/home-assistant/frontend/issues/8055.

The graph in the more-info popup is by design currently fixed to 24 hours.

**Closed by spacegaier** 2021-01-24 22:51 UTC
Labels: bug

**Comment by Uriziel01** [comment] 2021-01-24 22:54
@spacegaier Thank you, didn't find the old one. Sorry for the duplicate.
