### ISSUE TITLE
Roller Shutter Automation cannot be saved

### ISSUE THREAD

**Issue by mstoffel-sag** [home-assistant/frontend#8351] opened 2021-02-08 13:43 UTC
## Checklist

- [ x ] I have updated to the latest available Home Assistant version.
- [ x] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

When I try to configure my roller shutter automation like that:

![image](https://user-images.githubusercontent.com/29426188/107226633-a8e1db00-6a1a-11eb-9b32-0039b132089d.png)

I get the following error on saving:

![image](https://user-images.githubusercontent.com/29426188/107226980-1beb5180-6a1b-11eb-894e-ec1d156a217e.png)

Message malformed: value must be one of ['close', 'close_tilt', 'open', 'open_tilt', 'stop'] for dictionary value @ data['type']

The generated yaml code is:

![image](https://user-images.githubusercontent.com/29426188/107227049-345b6c00-6a1b-11eb-8b44-805ef4fc212f.png)

## Expected behavior

Successfully created the  automation 

## Steps to reproduce

    1. Add a automation
    2. Action type device
    3. Select a roller shutter
    4. select position 0
    5. hit save

## Environment

- Home Assistant release with the issue: core-2021.2.1
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome  88.0.4324.150
- Operating system: Windows 10

**Comment by cchristofr** [comment] 2021-02-19 22:20
Hi
I have the same error when I try to control shutter (fibaro) with MQTT (and zwavejs2mqtt).
Before using MQTT, I've used the addon "ZWAVE" and it was possible to do the automation by indicating the position (with the action "set shutter position" and a numeric value). 
But now, with MQTT, the action "set shutter position" seems not to be the correct one (the action wait for a numeric value but the error indicates that a string has to be put).

**Comment by spacegaier** [comment] 2021-02-19 23:35
Sounds like a duplicate of https://github.com/home-assistant/frontend/issues/7531 and if so, this PR (core not frontend, since the validation happens in the backend) should fix that. Since "position" is marked as mandatory and the initial cover slider position "0" is not taken into account, the schema validation fails.

https://github.com/home-assistant/core/pull/45670

Can you double check that if you add a `position: 1` in the service data or set the slider to something other than 0, you can save the automation? If yes, then I think that is fixed.

**Comment by mstoffel-sag** [comment] 2021-02-22 15:09
You're right, using 1 as value let me save the Automation. When will this core version be released?

Thanks Marco

**Comment by spacegaier** [comment] 2021-02-22 16:42
Releases are always on the first Wednesday of each month, with a beta period starting one week earlier.

**Closed by spacegaier** 2021-02-22 16:42 UTC
Labels: bug
