### ISSUE TITLE
Starting a script from the info dialog no longer works after entity id was changed

### ISSUE THREAD

**Issue by EDelsman** [home-assistant/frontend#21600] opened 2024-08-06 09:40 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I press the run button for a script in the info dialog of that script, I get an error. "Action script xxx not found. If I run it from the script itself, it runs fine.

### Describe the behavior you expected

Script runs when I press the run button

### Steps to reproduce the issue

1. Rename a scripts entity id through the cog dialog
2. Search for that script
3. Open the dialog
4. Press the Run script button
5. Watch the error in the bottom corner
![IMG_0844](https://github.com/user-attachments/assets/c0336f0f-f69d-4ef0-a4e0-61bf020ddf17)

### What version of Home Assistant Core has the issue?

2024.8.b03

### In which browser are you experiencing the issue with?

Safari

### Which operating system are you using to run this browser?

iPadOS

**Comment by tjorim** [comment] 2024-08-06 09:56
Is there anything in the logs?

**Comment by frenck** [comment] 2024-08-06 10:06
I'm not able to reproduce this on the current beta either

![CleanShot 2024-08-06 at 12 05 53](https://github.com/user-attachments/assets/895e724c-c8d6-4a13-83bf-3424f0984d7f)

**Comment by silamon** [comment] 2024-08-06 10:42
Is it like this issue? https://github.com/home-assistant/frontend/issues/14140

**Comment by karwosts** [comment] 2024-09-04 14:33
Will be fixed by #21880

**Closed** 2024-09-10 07:35 UTC
