### ISSUE TITLE
Multiple Sidebars

### ISSUE THREAD

**Issue by flixlix** [home-assistant/frontend#8989] opened 2021-04-25 18:18 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I noticed that, in the last two versionsof HA Core: 2021.3 and 2021.4, there might be a bug in the Supervisor panel.
When I, for example, start a new Add-on, a new Sidebar appears. I was able to temporarily fix this issue, by reloading the page.

### Describe the behavior you expected

I expect no new Sidebar to appear

### Steps to reproduce the issue

1. Supervisor Panel
2. Open a Add-on
3. Do anything
4. A second Sidebar appears

### What version of Home Assistant Core has the issue?

2021.4

### What was the last working version of Home Assistant Core?

2021.2

### In which browser are you experiencing the issue with?

Google Chrome v.90.0.4430.85

### Which operating system are you using to run this browser?

Windows

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

### Additional information

[
![Screenshot](https://user-images.githubusercontent.com/61006057/116004507-e2c68480-a5fa-11eb-9975-9217ece4303f.jpeg)
](url)

**Comment by spacegaier** [comment] 2021-04-25 19:19
Duplicate of https://github.com/home-assistant/frontend/issues/8926

**Closed by spacegaier** 2021-04-25 19:19 UTC
Labels: bug
