### ISSUE TITLE
Left side bar gets duplicated

### ISSUE THREAD

**Issue by kfir-bar** [home-assistant/frontend#9058] opened 2021-04-30 18:31 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I delete a snapshot, after the snapshot been deleted, the left sidebar is getting duplicated.

### Describe the behavior you expected

No duplication of the sidebar

### Steps to reproduce the issue

At the superviser -> snapshots -> delete an existing snapshot

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

Chrome - 90.0.4430.93

### Which operating system are you using to run this browser?

Windows 10

### Additional information

![image](https://user-images.githubusercontent.com/42117135/116738558-4980df00-a9fb-11eb-9d81-4f45ea481f8a.png)

**Comment by spacegaier** [comment] 2021-04-30 22:10
Duplicate of https://github.com/home-assistant/frontend/issues/8926 and already fixed...and reported about 5 times :wink:.

**Closed by spacegaier** 2021-04-30 22:10 UTC
Labels: bug
