### ISSUE TITLE
text overlay on statistics card

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#21828] opened 2024-08-28 21:57 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

With some settings, the text on the X Axis of the Statistic-Graph card will be overlayed and is not clearly readable.
![grafik](https://github.com/user-attachments/assets/1d8da76f-c85c-43f1-bc66-807a12be4202)

This happens especially, when the time span of the graph is set to one day.
Here, compared the same sensor - one time with one day, and the second graph with two days.
![grafik](https://github.com/user-attachments/assets/6ed75224-fa82-47f2-aaf8-8d1f97e9059a)

### Describe the behavior you expected

the text on the axis should always be clearly readable.

### Steps to reproduce the issue

1. create a statistic graph card with bars
2. play around with the amount of days the card should show

### What version of Home Assistant Core has the issue?

2024.9.0b0

### In which browser are you experiencing the issue with?

chrome 128.0.6613.114

**Comment by ildar170975** [comment] 2024-08-28 22:11
Duplicate of https://github.com/home-assistant/frontend/issues/9815

**Comment by karwosts** [comment] 2024-08-29 04:00
> Duplicate of #9815

**Closed by karwosts** 2024-08-29 04:00 UTC
