### ISSUE TITLE
Missing translation in lokalise - pipeline words

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19244] opened 2024-01-02 18:41 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found missing words in translation for lokalise (screenshot attached).

![AssistPipeline](https://github.com/home-assistant/frontend/assets/61636045/0aff3838-9672-4a64-bc55-c2d89a77e04c)

### Describe the behavior you expected

Please add missing words to translation in lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.0b3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment] 2024-01-03 01:25
Please try to review your previously filed issues before opening new ones. You reported this exact same thing a few weeks ago, and I don't believe this is your first time making duplicated reports. 

I don't mind if you open several issues for localization issues but you should not be opening the same issues repeatedly, that is borderline spam. 

Duplicate of #18926

**Closed by karwosts** 2024-01-03 01:25 UTC
