### ISSUE TITLE
Gauge needle missig in mobile app

### ISSUE THREAD

**Issue by capralest** [home-assistant/frontend#10724] opened 2021-11-29 11:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Hello

Missing gauge needle mobile app. in pc is ok and show.
![260472834_757376865660781_8563087468926919206_n](https://user-images.githubusercontent.com/91413067/143858774-ed70aa89-aec6-492c-9a9e-c3629a86e309.jpg)
![123456](https://user-images.githubusercontent.com/91413067/143858777-34fef015-b767-434c-819e-8b3f9e57ab03.png)

### Describe the behavior you expected

Missing gauge needle mobile app. in pc is ok and show.

### Steps to reproduce the issue

1.in pc is show needle 
2.mobile app not show gauge needle.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.11.5

### What was the last working version of Home Assistant Core?

core-2021.11.5

### In which browser are you experiencing the issue with?

opera,mozilla

### Which operating system are you using to run this browser?

win10

### State of relevant entities

```txt
Missing gauge needle mobile app. in pc is ok and show.
```

### Additional information

Missing gauge needle mobile app. in pc is ok and show
![260472834_757376865660781_8563087468926919206_n](https://user-images.githubusercontent.com/91413067/143859133-ba7a20ff-ea04-40f9-a51d-5e918c31a37e.jpg)
![123456](https://user-images.githubusercontent.com/91413067/143859134-45ede5e7-6e5f-49cf-a340-397450cd3c58.png)
.

**Comment by spacegaier** [comment] 2021-12-02 09:38
Which mobile OS are you using? You only mentioned Win 10 in the ticket.

Are you using a custom theme?

**Comment by capralest** [comment] 2021-12-02 18:27
Ios15.2 use and no use custom theme.

**Comment by rccoleman** [comment] 2021-12-03 18:35
I'm using the latest iOS 15.2 beta and can confirm that I see the issue.  I don't use a theme at all, just plain Dark mode.

Desktop:

![image](https://user-images.githubusercontent.com/860888/144654882-c4f65c4a-a49e-4260-9241-260c273dda88.png)

iOS 15.2:

![image](https://user-images.githubusercontent.com/860888/144654906-0091d6bf-1b8f-4ad6-b2ac-343114deeeb6.png)

Code (pretty much just added the card in the UI and gave it a dummy entity and some thresholds):

```
type: gauge
entity: input_number.test2
min: 0
max: 100
needle: true
severity:
  green: 10
  yellow: 20
  red: 40
```

**Comment by stevesamnow** [comment] 2021-12-14 23:15
Exact Same problem here, my system had been working perfectly for many months.

**Comment by spacegaier** [comment] 2021-12-14 23:21
And just double-check: This issue did appear only once you updated to 2021.12 or was it caused by going to iOS 15.2?

And I assume you all see the same issue here on the demo page? https://demo.home-assistant.io/#/energy

**Comment by stevesamnow** [comment] 2021-12-14 23:53
Hi 

Well I’m now not sure if IOS update broke it or 2021.12 as I upgraded it all about the same time.

Just did a full restore  of Home-assistant  back to core: 2021.10.6.

The needle has re-appeared and on my old Ipad Air running IOS 12.5.5 it looks perfect

The needle on my 2 new IOS 15.2 devices is now also showing BUT is in the wrong place?? see enclosed image



Cheers
Steve Manchester

Computer Tech Services Pty Ltd
Phone:  07 5515 0225 <tel:0755150225>
Mobile:  0488 444 366 <tel:0488%20444%20366>
Helpdesk/Support:  0488 811 747 <tel:0488811747>

www.computertechservices.com.au <http://www.computertechservices.com.au/>

**Comment by raducotescu** [comment] 2021-12-30 22:33
#10766 which was fixed in HA 2021.12.6 handled Safari only, but the companion apps still have an issue that should be soon fixed. See #11041.

**Comment by vittorio1968** [comment] 2022-01-31 10:03
Still no solution? To date it only works fine on Safari on iPhone iOS 15.3.

This is how it is seen on Crome.
![BD9C20BB-43D9-437C-B44E-23C2AD8411FE](https://user-images.githubusercontent.com/75095867/151773027-ab482207-5ca1-4c71-82d1-943f6b56edf3.png)

This is Safari, perfect.
![F268572A-188F-4971-A2AF-894B0421B5DD](https://user-images.githubusercontent.com/75095867/151773034-c8bb8e70-2a78-4dbe-b715-0e7601aeffe2.png)

This is the Nabu Casa app, identical problem, same as Crome.
![0D3DF535-C368-4AF5-A79E-9125FD1E5679](https://user-images.githubusercontent.com/75095867/151773042-6715cefb-e890-45a3-b43b-8c3b9b93c61e.png)

**Comment by raducotescu** [comment] 2022-01-31 12:31
This issue duplicates https://github.com/home-assistant/frontend/issues/11041, which is already fixed. The release providing the fix should be made available on Wednesday. If you're in a hurry, just update your frontend to at least `20220127.0`.

**Comment by vittorio1968** [comment] 2022-01-31 12:40
Okay, thanks a lot for the tip. I did not realize that the solution had been made available.

**Closed** 2022-01-31 17:20 UTC
Labels: iOS, bug
