### ISSUE TITLE
Integration settings dialog should be scrollable (option are displayed below dialog)

### ISSUE THREAD

**Issue by Misiu** [home-assistant/frontend#5253] opened 2020-03-18 11:21 UTC
## The request

Currently when changing integration settings (via gear icon), when there are a lot of options some of them are not visible and displayed below the dialog:
![image](https://user-images.githubusercontent.com/1741838/76955310-38b5fc80-6912-11ea-8703-392c7942fd89.png)
As you can see some options are not visible, same with the save button.
I'd like to ask for adding a scrollbar if options don't fit on the screen so that we always have the `SUMBIT` button visible.

## The alternatives

I must change the zoom to 80% in Chrome to see all the options:
![image](https://user-images.githubusercontent.com/1741838/76955564-b4b04480-6912-11ea-911b-b0b22b4be131.png)

## Additional information
This is easy to reproduce in ShellyForHass 0.1.7-beta.2

**Comment by hakana** [comment] 2020-03-18 11:47
Would it also be possible to compact the dialog, now there is a lot of extra space between rows?

**Comment by Misiu** [comment] 2020-03-18 11:57
![image](https://user-images.githubusercontent.com/1741838/76958166-82551600-6917-11ea-9f10-ff96d726d494.png)
each paper-checkbox has `padding: 22px 0px;`
thats the reason for extra space.

view editor dialog is using `paper-dialog-scrollable`. Is should be used here to allow scrollbar when needed

**Comment by bramkragten** [comment] 2020-03-18 13:31
@hakana you locked the other issue, so I could not respond. But HA does have multi select for settings. Check for example plex: <https://github.com/home-assistant/core/blob/dev/homeassistant/components/plex/config_flow.py#L287> or Unifi <https://github.com/home-assistant/core/blob/dev/homeassistant/components/unifi/config_flow.py#L210>

**Comment by Misiu** [comment] 2020-03-18 13:57
@chemelli74 could you reopen https://github.com/StyraHem/ShellyForHASS/issues/209?

**Comment by chemelli74** [comment] 2020-03-18 15:19
> @chemelli74 could you reopen [StyraHem/ShellyForHASS#209](https://github.com/StyraHem/ShellyForHASS/issues/209)?

Done

Simone

**Comment by hakana** [comment] 2020-03-18 15:28
I will check!

**Comment by bramkragten** [comment] 2020-03-19 11:41
duplicate of https://github.com/home-assistant/frontend/issues/5103

**Closed by bramkragten** 2020-03-19 11:41 UTC
Labels: feature request
