### ISSUE TITLE
statistic cards don't show all bars

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#15970] opened 2023-03-29 14:53 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using the statistics graph card with the option "bars" - does not show all bars for the selected period.
The first and last entries are cut-off.

![image](https://user-images.githubusercontent.com/26391061/228575270-392c73ab-c02f-469e-b884-667854745b1a.png)

Opening the card editor (without changing anything) seems to fixed the issue for of the graphs - but I don't know what exactly has caused this.
The second statistics card remained unchanged...
![image](https://user-images.githubusercontent.com/26391061/228577345-06be799b-4b2c-4937-9440-4ba132c638fc.png)

card parameters / configuration for the second chart:
- days to show: 365
- period: month

### Describe the behavior you expected

the statistic graph should ALWAYS show all bars that have been configured

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.3.6

**Comment by karwosts** [comment] 2023-06-24 13:15
Close as duplicate of #14375

**Closed by karwosts** 2023-06-24 13:15 UTC
