### ISSUE TITLE
Save last changed state in glance 

### ISSUE THREAD

**Issue by d3m3trius** [home-assistant/frontend#6602] opened 2020-08-12 12:33 UTC
## The request

Using show_last_changed in glance shows the time since last changed. However, at HA restart the value reports the time since HA restart and not the time elapsed since last state change.

## The alternatives
The value of last change should be saved during restart, or at least it should show unknown if reporting previous state is not possible and there hasn't been changes since last restart.

**Comment by bramkragten** [comment] 2020-08-12 13:13
Duplicate of https://github.com/home-assistant/architecture/issues/230

**Closed by bramkragten** 2020-08-12 13:14 UTC
Labels: feature request
