### ISSUE TITLE
codemirror  set to tab 4 chars in raw config editor

### ISSUE THREAD

**Issue by scooper1** [home-assistant/frontend#8486] opened 2021-02-28 01:26 UTC
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

codemirror  set to tab 4 chars in raw config editor  i am convinced this used to be 2 chars         

**Describe the behavior you expected**

it would be much better to restore original behaviour of two char tab when in  yaml editing mode as most spacing indents by two 
i not sure but also think there maybe another change that tabs are not converted to spaces - but cant remember if that was true for last version of codemirror it mabe just the 4 char tab making us use tabs and spaces 
  

**Steps to reproduce the issue**

1.
2.
3.
...

**What version of Home Assistant Core has the issue?**

core-2021.3.0b3

**What was the last working version of Home Assistant Core?**

2021.2.0

**In which browser are you experiencing the issue with?**

_No response_

**Which operating system are you using to run this browser?**

windows 10

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment] 2021-02-28 01:29
Duplicate of https://github.com/home-assistant/frontend/issues/8460 and I already fixed that three days ago, but that frontend version is not part of the current betas yet.

**Closed by spacegaier** 2021-02-28 01:29 UTC
Labels: bug
