### ISSUE TITLE
Hamburger icon is not displayed on Configuration page.

### ISSUE THREAD

**Issue by tdejneka** [home-assistant/frontend#6314] opened 2020-07-02 14:16 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Hamburger icon is missing from the Configuration page.

![Screenshot from 2020-07-02 09-44-33](https://user-images.githubusercontent.com/44732909/86369888-088a3380-bc4d-11ea-8b85-fc341e1a6c56.png)

NOTE:
The following option is enabled: "Always hide the sidebar". Nevertheless, normally there's a means of accessing the side-menu.

## Expected behavior

Should display the icon in order to be able to access the side-menu.
## Steps to reproduce

Click `Configuration` menu option in side-menu. Resulting page lacks the hamburger icon.
## Environment

- Home Assistant release with the issue: 0.112.0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Firefox 78.9.1
- Operating system: Ubuntu 18.04.4

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment] 2020-07-02 15:12
Duplicate of #6300

**Closed by bramkragten** 2020-07-02 15:12 UTC
Labels: bug

**Comment by SeanPM5** [comment] 2020-07-02 16:10
Until the fix rolls out, here's a way to access it still (without turning off the "Always hide the sidebar" option). 

If you're familiar with the swipe gestures on a mobile device, you'd basically be emulating that gesture with your mouse.

![image](https://i.imgur.com/XqMaquo.png)
