### ISSUE TITLE
System tab stays blank 

### ISSUE THREAD

**Issue by Roald28** [home-assistant/frontend#13735] opened 2022-09-14 08:46 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After updating to Release 2022.9.3 the system tab stays blank (/config/system)

- Did a restart of HA
- Cleared cache
- Did this with Chrome, Edge and android app. 

### Describe the behavior you expected

The page stays blank

### Steps to reproduce the issue

1. Just update to Release 2022.9.3
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.3

### What was the last working version of Home Assistant Core?

Release 2022.9.1  or Release 2022.9.2 (don't know if I skipped one)

### In which browser are you experiencing the issue with?

Chrome, Edge and Android phoneapp

### Which operating system are you using to run this browser?

MacOs Big sur or android

### State of relevant entities

```txt
- Just a blank page
```

### Problem-relevant frontend configuration

```yaml
- Just a blank page
```

### Javascript errors shown in your browser console/inspector

```txt
companion-bubble.js:1452 
        
       Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at companion-bubble.js:1452:20487
    at Generator.next (<anonymous>)
    at An (companion-bubble.js:1452:19905)
(anonymous) @ companion-bubble.js:1452
An @ companion-bubble.js:1452
Promise.then (async)
In @ companion-bubble.js:1452
An @ companion-bubble.js:1452
Promise.then (async)
In @ companion-bubble.js:1452
(anonymous) @ companion-bubble.js:1452
ar @ companion-bubble.js:1452
(anonymous) @ companion-bubble.js:1452
(anonymous) @ companion-bubble.js:1452
K1 @ companion-bubble.js:1347
r.unstable_runWithPriority @ companion-bubble.js:1354
To @ companion-bubble.js:1343
_s @ companion-bubble.js:1347
Al @ companion-bubble.js:1345
(anonymous) @ companion-bubble.js:1343
r.unstable_runWithPriority @ companion-bubble.js:1354
To @ companion-bubble.js:1343
Md @ companion-bubble.js:1343
ls @ companion-bubble.js:1343
wf @ companion-bubble.js:1345
Bc @ companion-bubble.js:1347
r.render @ companion-bubble.js:1347
(anonymous) @ companion-bubble.js:1452
Promise.then (async)
(anonymous) @ companion-bubble.js:1452
t @ companion-bubble.js:1
(anonymous) @ companion-bubble.js:1436
t @ companion-bubble.js:1
(anonymous) @ companion-bubble.js:1
(anonymous) @ companion-bubble.js:1
typography.js:181 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-card.ts:5:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
i @ typography.js:181
value @ ha-card.ts:5
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-card.ts:5
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-list-item.ts:7
E @ typography.js:181
t @ typography.js:181
window.CustomElementRegistry.define @ typography.js:181
finisher @ styles.ts:370
runClassFinishers @ ha-list-item.ts:7
(anonymous) @ ha-list-item.ts:7
(anonymous) @ ha-list-item.ts:7
u.a @ styles.ts:370
99417 @ ha-list-item.ts:7
u @ styles.ts:370
Promise.then (async)
load @ 312c80d9.js:1
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
r @ hass-loading-screen.ts:11
s @ 312c80d9.js:1
E @ typography.js:181
t @ typography.js:181
(anonymous) @ VM578:1
value @ hass-loading-screen.ts:11
value @ hass-loading-screen.ts:11
_currentLoadProm.l.then._currentLoadProm @ hass-loading-screen.ts:11
Promise.then (async)
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
value @ styles.ts:370
(anonymous) @ styles.ts:370
s @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
Promise.then (async)
d @ core.79519174.js:1
u @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
subscribe @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
Promise.then (async)
(anonymous) @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
(anonymous) @ core.79519174.js:1
ha-config-system-navigation.ts:140 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at HTMLElement.value (ha-config-system-navigation.ts:140:1)
```

**Comment by ludeeus** [comment] 2022-09-14 08:46
Duplicate of https://github.com/home-assistant/frontend/issues/13728

**Closed by ludeeus** 2022-09-14 08:46 UTC
