### ISSUE TITLE
Reconnecting loop if connection is broken after 30 minutes

### ISSUE THREAD

**Issue by chriss158** [home-assistant/frontend#7732] opened 2020-11-19 13:02 UTC
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Every now and then i can't get a reconnection to my home assistant after the connection is broken (ex. duo to a home assistant restart) with the android app. The frontend just shows the message "Connection lost. Reconnecting..." for ever. I had never problems with HA releases  before this PR #7236.

Did some debugging the last couple of days and tracked down the problem to this PR #7236. 

While HA is restarting the frontend tries to reconnect in background.

1. `RefreshAccessToken`is called 
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L69

2.  `RefreshAccessToken`calls `getExternalAuth`
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L92

3. `getExternalAuth` triggers the `onGetExternalAuth` of the android app 
https://github.com/home-assistant/android/blob/6e13b162144cfeed69d0d37f050098d2b16ebf6c/app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt#L82

4. The method call `view.setExternalAuth` will fail because Home assistant is not yet restarted.

5. The catch block is triggered and calls the following method:
https://github.com/home-assistant/android/blob/6e13b162144cfeed69d0d37f050098d2b16ebf6c/app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt#L88

6. Now the `_tokenCallbackPromise` is trigged 
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L81
with success = false. Meaning the _tokenCallbackPromise is in a rejected state.

7. Now after one second the next try for a reconnect starts.  
https://github.com/home-assistant/home-assistant-js-websocket/blob/1836b3ae57309a969627fc993619cfd40b47204c/lib/socket.ts#L84

8. Again `RefreshAccessToken` is called because of expired session token. This time from the reconnection instead of the app https://github.com/home-assistant/home-assistant-js-websocket/blob/1836b3ae57309a969627fc993619cfd40b47204c/lib/socket.ts#L87

9. Then this check is called:
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L70  `_tokenCallbackPromise` is not undefined and force is undefined because the parameter is not defined by the caller.  Then the `_tokenCallbackPromise` is called. And here is the **culprint**: `tokenCallbackPromise` is in a rejected state with undefined data.   The rejected promise triggers an exception.

10. The exception is then handled here:
https://github.com/home-assistant/home-assistant-js-websocket/blob/1836b3ae57309a969627fc993619cfd40b47204c/lib/socket.ts#L90
This triggers that the websocket will be closed again.

11. Then the reconnection process is beginning from the start. And we are in a reconnect loop.

On the home assistant side there are following messages. Which explains this process above.

```txt
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Connected from ipaddress
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Sending {'type': 'auth_required', 'ha_version': '0.117.6'}
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Disconnected
```
I hope i could describe the problem understandable. 

## Expected behavior

Reconnecting should also work if  connected longer than 30 minutes.

## Steps to reproduce

I think this is reproducible with following steps:

1. Deactivate "Close connection automatically" in the profile settings of HA.
2. Open the android app and let it connect to home assistant
3. Lock the phone/tablet leaving the app open and in foreground
4. Wait around 30 minutes (I think this is the session timeout for the token)
5. Restart HA and wait till it is running fully again
5. Unlock the phone/tablet.

## Environment

- Home Assistant release with the issue: 0.117.6
- Last working Home Assistant release (if known): I think this should be 0115.6, because since 0.116 this PR is included
- Browser and browser version: Latest chrome/ android webview
- Operating system: Intel NUC - HASS OS

## Problem-relevant configuration

Disabled Close connection automatically in the profile settings.
This also happens on my samsung tablet with enabled close connection automatically, but i think this is a problem with the android app which doesnt pause the webview. I'm unsure on that one.

## Javascript errors shown in your browser console/inspector

Connection refused errors are shown as soon as the HA connection is broken

## Additional information

Maybe here
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L70

should be a check if the promise is rejected. If it is reject then do not return the reject promise. Instead do the stuff below (call getExternalAuth etc.) If the promise is resolved, then return the promise.

**Comment by manuelo1983** [comment] 2020-11-19 19:49
I have exactly the same problem as described. This happens very often, so that the only solution is to restart the app again. It would be very helpful when this issue will be fixed. Thanks a lot

**Comment by manuelo1983** [comment] 2020-12-02 11:34
Sorry to ask again, but is it somehow foreseeable if this error will be corrected, because the aborts are currently daily on my tablet. Means I have to close and reopen the app again and again. Only then I can use Home Assistant correctly again. Thank you very much.

**Comment by Erriez** [comment] 2020-12-31 09:58
What is the status of this issue?

**Problem:**
* `Connection lost. Reconnecting...` is displayed when reopening Android Homeassistant app version `3.0.2-full`. 
* Android Homeassistant app never reconnects automatically.
* The only way to reconnect is to completely close the app and reopen it.

**The problem is 100% reproducible:**
* With HTTP and SSL
* Battery optimizations disabled does not matter
* Samsung Galaxy Tab S4 Android
* Samsung Galaxy Tab S3 Android
* Galaxy S10 Android

**Screenshot:**

![Screenshot_20201231-101145_Home Assistant](https://user-images.githubusercontent.com/8849873/103404728-f5e9ac00-4b54-11eb-89d2-c64dea6dba6c.jpg)

**Comment by Erriez** [comment] 2021-01-01 12:00
I found a temporary _last resort_ workaround to avoid "Connection lost. Reconnecting...":

1. Uninstall the Homeassistant app from Android.
2. Open the Homeassistant web page in Android Chrome browser.
3. Create a shortcut on the desktop and use this instead of the Homeassistant app.

I look forward to a bugfix which is highly appreciated.

**Closed** 2021-01-29 12:40 UTC
Labels: bug
