### ISSUE TITLE
Lovelace card layout incorect size at startup - column problem

### ISSUE THREAD

**Issue by dolenec** [home-assistant/frontend#5655] opened 2020-04-29 06:49 UTC
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When you make restart of Home Assistant the problem is that lovelace cards position is in incorect size. The main problem is that position is not set as should be.

## Expected behavior

[https://www.vseznalec.si/public/1.jpg](https://www.vseznalec.si/public/1.jpg)
(incorect position)

[https://www.vseznalec.si/public/2.jpg](https://www.vseznalec.si/public/2.jpg)
(show / hide menu)

[https://www.vseznalec.si/public/3.jpg](https://www.vseznalec.si/public/3.jpg)
**(this is correct cards position and cards size)**

## Steps to reproduce

1. Restart Home Assistant (lovelace cards position in incorect position)
[https://www.vseznalec.si/public/1.jpg](https://www.vseznalec.si/public/1.jpg)
2. Show menu
[https://www.vseznalec.si/public/2.jpg](https://www.vseznalec.si/public/2.jpg)
3. Hide menu
[https://www.vseznalec.si/public/3.jpg](https://www.vseznalec.si/public/3.jpg)
4. Now it's OK..

## Environment

- Home Assistant release with the issue: 0.108.9
- Last working Home Assistant release (if known): (probably newer)
- Browser and browser version: Google Chrome, MS Edge, Firefox (all up-to-date)
- Operating system: Windows OS - 10, Android OS 7, 8, 9

## Problem-relevant configuration

There should be many cards, so that lovelace make 4 columns instead of 3.

## Additional information

Probably the solution would be to mark every card with column number and with order number under column.

**Comment by bramkragten** [comment] 2020-05-24 08:31
Duplicate of https://github.com/home-assistant/frontend/issues/5321

**Closed by bramkragten** 2020-05-24 08:31 UTC
Labels: bug
