### ISSUE TITLE
iOS 16.4 1Password autofill cannot login

### ISSUE THREAD

**Issue by matt-oakes** [home-assistant/frontend#16617] opened 2023-05-24 16:55 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When signing in to Home Assistant on iOS 16.4.1(a) login will always fail when 1Password prefills the username and password in Safari. When looking at the login request that is made the `username` and `password` properties of the request are an empty string.

To work around this, you can manually edit the uername and password and then the request includes the correct details and login is successful.

### Describe the behavior you expected

It should be possible for 1Password to autofill the username and password and login to be successful when pressing the login button without needing to edit the contents of the text field manually.

### Steps to reproduce the issue

1. Open the login screen on iOS Safari.
2. Open the 1Password password manager
3. Select the password item so the details are prefilled
4. Press the login button or keyboard return

### What version of Home Assistant Core has the issue?

2023.5.2 / Frontend 20230503.3

### In which browser are you experiencing the issue with?

iOS Safari 16.4.1(a)

### Which operating system are you using to run this browser?

iOS 16.4.1(a)

### Additional information

Screen recording:

https://github.com/home-assistant/frontend/assets/97068/6dd1dc21-4c37-4370-97bf-2955a6451202

Auth request:

```
:method: POST
:scheme: https
:authority: SNIP
:path: /auth/login_flow/SNIP
Content-Type: text/plain;charset=UTF-8
Accept: */*
Sec-Fetch-Site: same-origin
Accept-Language: en-GB,en;q=0.9
Accept-Encoding: gzip, deflate, br
Sec-Fetch-Mode: cors
Host: SNIP
Origin: https://SNIP
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 16_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1
Referer: SNIP
Content-Length: 81
Connection: keep-alive
Sec-Fetch-Dest: empty

{
    "username": "",
    "password": "",
    "client_id": "https://SNIP/"
}
```

**Comment by steverep** [comment] 2023-08-08 19:53
Duplicate of #16976 

Please subscribe and track this there.

**Closed by steverep** 2023-08-08 19:53 UTC
