### ISSUE TITLE
Hassio Energy Dashboard does not show first number of Grid Usage

### ISSUE THREAD

**Issue by Chaosflori25** [home-assistant/frontend#19315] opened 2024-01-07 13:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the Energy Dashboard of Hassio the first digit of the Grid Consumption is nearly unreadable.
![grafik](https://github.com/home-assistant/frontend/assets/44469989/bbc5bad8-ce54-4180-9b97-56a3a6ea6fdf)
Especially in the winter months with 2 EVs my Energyconsumption is quite high so i'd like to read this a bit better.
![grafik](https://github.com/home-assistant/frontend/assets/44469989/a0b8b6bd-4240-44db-963d-20b47f938e95)

### Describe the behavior you expected

The Digits could go 1 Size smaler or the Unit "kWh" could be (re)-moved elsewhere.

### Steps to reproduce the issue

0. Probably change the Language to German/Unit to kWh
1. Go to the Energy Configuration Dashboard
2. Add Solar and Grid Usage and Increase the Grid Usage till it reads something like 169,9 kWh
3.  Go to the Energy Dashboard.

### What version of Home Assistant Core has the issue?

core-2023.12.2 and core-2024.1.2

### In which browser are you experiencing the issue with?

Firefox 121.0 (64-Bit)

### Which operating system are you using to run this browser?

Windows 11 22H2

**Comment by karwosts** [comment] 2024-01-07 14:22
Duplicate of #19114

**Closed by karwosts** 2024-01-07 14:22 UTC
