### ISSUE TITLE
graphs in the monitor individual devices (energy pane) not showing properly when changing date.

### ISSUE THREAD

**Issue by zadigre** [home-assistant/frontend#10007] opened 2021-09-10 13:37 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

when switching to day, week, month, year or changing date, graphs for monitor individual devices do not show properly. 
reloading the page will reload the current date and graphs will be ok... but changing the date again will "break" the graphs.
This is in Safari on the latest macOS Monterey beta. 
Edge works fine. 

see attached screen recording... first browser is Safari, second is Edge.

### Describe the behavior you expected

show graphs the same way in Safari compared to Edge.

### Steps to reproduce the issue

1. go to energy pane
2. change date or select a different range (today, week, month, year).

https://user-images.githubusercontent.com/4810599/132861929-e6d5aede-211d-4c11-be6e-bd6ae728b966.mov

### What version of Home Assistant Core has the issue?

core-2021.9.5

### In which browser are you experiencing the issue with?

Safari 15.0 (17612.1.28.5)

### Which operating system are you using to run this browser?

macOS Monterey 12.0 (21A5506j)

**Comment by zadigre** [comment] 2021-09-10 14:23
I discovered something... if I slightly resize my safari window when I get this bug, the graphs will be fine. but as soon I as change date, problem will be back. 

it might be a rendering issue specific to safari... but I do not have any other problem elsewhere on Internet.

**Comment by zadigre** [comment] 2021-09-11 10:44
I also have the same problem in the iOS app and safari on my iPhone running the latest iOS 15 beta

**Comment by zadigre** [comment] 2021-12-10 11:12
This issue is still present 
![AE34C5D3-C88A-4D50-AB40-5BE94838250A](https://user-images.githubusercontent.com/4810599/145565287-a3cc140e-2288-49ed-9ecb-11afb49a1186.jpeg)
![48957436-A896-4EC1-836D-4AD3F9990546](https://user-images.githubusercontent.com/4810599/145565292-cce0433e-69e0-4238-9c7f-1970c1412c48.jpeg)
![5F328282-23A4-4842-BEC6-2DBC572C3330](https://user-images.githubusercontent.com/4810599/145565295-d8373686-618a-4cf2-bd3d-3447807be6d8.png)

**Comment by zadigre** [comment] 2021-12-10 11:13
![3EEE1C9E-34D3-4CA5-B27F-E91E200FDAC2](https://user-images.githubusercontent.com/4810599/145565450-b0ce4de0-3e7d-4779-8367-9fe4960e56d3.png)

**Comment by thomas-svrts** [comment] 2021-12-21 10:09
I've the same on iOS and on my Mac (Safari), resizing the window does indeed solve it.
Works fine in Edge on Mac.

tested on 2021.12.4 with frontend 20211220

**Comment by Irming1109** [comment] 2022-01-09 18:43
i have the same problem. will this be fixed someday maybe ?

**Comment by JurajNyiri** [comment] 2022-02-04 20:50
Same issue here in the iOS app on iPad.

Replication steps:

<details>
  <summary>- Open energy</summary>
  
  ![image](https://user-images.githubusercontent.com/5785999/152600885-a7cb488b-dcb6-4801-a010-2fff3c88b7d6.png)
</details>

- Click week (at this moment it is also bugged


- Click day

<details>
  <summary>- Observe incorrect graph for individual devices</summary>
  
  ![image](https://user-images.githubusercontent.com/5785999/152601061-cc96e450-339a-43f7-9e41-8e61d033b6d7.png)
</details>

It fixes itself when the single orange lane is clicked.

**Comment by emufan** [comment] 2022-03-29 16:01
Problem is still there with 2022.3.8. Interesting thing, where I'm not sure if it was already the case in the past: If I click on the single bar in the last screenshot of the last post today, the chart is loaded/displayed afterwards correctly (as far as I can see). So only an UI refresh/update problem?

Additionally, for Sources card in energy view there is now a horizontal scroll bar, which is not the case in any other card in this view. Don't think that it is wanted or expected behavior.

Thir topic: The name in the view above is right aligned. I would suggest to align it left, so it is more probable that the name to distinguish the bars is at the beginning not the end of the name, esp. if you have such suffixes as above.

**Comment by zadigre** [comment] 2022-03-29 17:33
> Problem is still there with 2022.3.8. Interesting thing, where I'm not sure if it was already the case in the past: If I click on the single bar in the last screenshot of the last post today, the chart is loaded/displayed afterwards correctly (as far as I can see). So only an UI refresh/update problem?

@emufan I've found on my computer (Mac + Safari) that just moving the mouse cursor over the bar will refresh the bars properly.

**Comment by emufan** [comment] 2022-04-27 20:04
Is there anything I can test or provide to get it fixed in any of the next releases?

**Comment by zrhutto** [comment] 2022-05-03 21:56
I wonder if this is a regression or a different issue than what was fixed in #9722. FWIW, this bug still exists on 2022.4.7

**Comment by emufan** [comment] 2022-05-04 13:58
At least every description and behavior look like exactly the same. I'm not sure if the fix from Bram (https://github.com/home-assistant/frontend/pull/9806) is still in place or if there was another reason.

**Comment by nickdos** [comment] 2022-06-14 23:31
> I discovered something... if I slightly resize my safari window when I get this bug, the graphs will be fine. but as soon I as change date, problem will be back.
> 
> it might be a rendering issue specific to safari... but I do not have any other problem elsewhere on Internet.

My experience mirrors this - seems to be Safari related and resizing window forces the graphs to be regenerated. On iOS HA app, this is not possible so the graphs are broken there.

**Comment by grudyjsy** [comment] 2022-06-19 11:11
Tested on iPad iOS 15.5 -  safari, HA app, chrome and Firefox. I can confirm issue affects all browsers. If you click on and off the graph a few times it forces it to refresh.

**Comment by emufan** [comment] 2022-09-17 16:14
Unfortunately, still the case. Not usable on Apple devices.

**Comment by nickdos** [comment] 2022-09-18 02:50
Still not working for me, including on Home Assistant iOS app (latest versions).

**Comment by Irming1109** [comment] 2022-09-18 06:42
Still not working for me.. using newest version. Problem occurs across all platforms (PC – Android App, IOS App)

 

Fra: github-actions[bot] ***@***.***> 
Sendt: 17. september 2022 18:02
Til: home-assistant/frontend ***@***.***>
Cc: Irming1109 ***@***.***>; Manual ***@***.***>
Emne: Re: [home-assistant/frontend] graphs in the monitor individual devices (energy pane) not showing properly when changing date. (#10007)

 

There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.
Please make sure to update to the latest Home Assistant version and check if that solves the issue. Let us know if that works for you by adding a comment 👍
This issue has now been marked as stale and will be closed if no further activity occurs. Thank you for your contributions.

**Comment by zadigre** [comment] 2022-09-18 09:55
Working fine for me on iOS 16 and latest beta of macOS Ventura.
I guess rendering issue has been fixed on latest versions of iOS and probably safari 16 (included in the latest macOS Monterey)

**Comment by thomas-svrts** [comment] 2022-09-18 11:26
Yes I can confirm: also works on my iPhone with Safari iOS16

**Comment by knudsvik** [comment] 2022-11-03 19:17
I can confirm it is also fixed with MacOS Ventura (and iOS 16).

**Comment by karwosts** [comment] 2023-06-28 20:55
Closing as this is quite stale and there are multiple reports that it is fixed. If you still experience an issue, please leave a comment.

**Closed by karwosts** 2023-06-28 20:55 UTC
Labels: Bug
