### ISSUE TITLE
Geocoded location no longer compatible with MapCard

### ISSUE THREAD

**Issue by hofst** [home-assistant/frontend#14099] opened 2022-10-15 18:12 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It looks like the MapCard in the dashboard is no longer compatible with the HomeAssistant Geocoded-Location-Sensor after upgrading the app. We have two phones connected and the older version still works while the newer HomeAssistant app no longer works. I have a strong suspicion of what is the root cause:
The older HomeAssistant app reported "lattitude and longitude" as separate attributes. The newer version only reports a single "location" attribute that contains both values.

Note: I have also opened an issue against the core since it is unclear to me whether this is a core or a frontend bug: https://github.com/home-assistant/core/issues/80416

### Describe the behavior you expected

Geocoded location devices should display on MapCard in dashboard.

### Steps to reproduce the issue

1. Enable geocoded location on latest homeassistant app version
2. Add MapCard to your dashboard and add your device as entity.
3. Check if the device displays. Older versions of the app will display correctly but the latest version will not.
...

### What version of Home Assistant Core has the issue?

2022.9.4 (this is the latest available snap version)

### In which browser are you experiencing the issue with?

Latest Edge and latest Firefox

### Which operating system are you using to run this browser?

Windows 11

**Comment by dshokouhi** [comment] 2022-10-16 15:13
Duplicate of https://github.com/home-assistant/frontend/issues/11970

**Closed** 2022-10-16 16:10 UTC
