### ISSUE TITLE
Data tables don't use font-family CSS-variable

### ISSUE THREAD

**Issue by nagtegaal** [home-assistant/frontend#21569] opened 2024-08-03 08:44 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you override the font-family in your theme/config, there is currently no way to override/adjust the way the text is presented inside the newly introduced data tables. The Roboto font seems to be hard coded, instead of the introduction of a new CSS variable, or relying on the main CSS font variable.

### Describe the behavior you expected

Another CSS variable, which could be overridden/adjusted where it's default value fallback to the main font-family variable.
It would also be nice, to get these (newly created) CSS variables documented somewhere..

### Steps to reproduce the issue

1. Change the font
2. See the data tables inside Settings
4.
...

### What version of Home Assistant Core has the issue?

2024.7.4

### In which browser are you experiencing the issue with?

Safari/IE/Chrome/Firefox on MacOS, and the Companion app on iOS

### Which operating system are you using to run this browser?

MacOS/iOS

**Comment by silamon** [comment] 2024-11-01 08:59
Duplicate of #22361. Since #22361 has more information and clearer descriptions, I'll close this one.

**Closed by silamon** 2024-11-01 08:59 UTC
