### ISSUE TITLE
#8353 breaks zoom in Fully Kiosk Browser 

### ISSUE THREAD

**Issue by scstraus** [home-assistant/frontend#9251] opened 2021-05-25 18:57 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Pinch to zoom in Fully Kiosk Browser was working great on 2021.1.5, but due to [#8353](https://github.com/home-assistant/frontend/pull/8353), from 2021.3.x, it stopped working. This seriously limits accessability on Fully Kiosk and as that's a very important feature for my wall panels, being that my eyesight is not what it once was, I'm now stranded on 2021.1.5. 

Is there any way that I could get this feature back on new versions? I'd be happy to edit the source code if that's what it takes. I just can't figure out what I'd need to do to bring it back.

### Describe the behavior you expected

Working pinch to zoom on Fully Kiosk Browser

### Steps to reproduce the issue

1. Upgrade from 2021.1.x to 2021.3.x
2. Attempt pinch to zoom in Fully Kiosk
3. Cry
...

### What version of Home Assistant Core has the issue?

all versions since 2021.3

### What was the last working version of Home Assistant Core?

2021.1.x

### In which browser are you experiencing the issue with?

Fully Kiosk Browser latest version

### Which operating system are you using to run this browser?

FireOS latest version

**Comment by scstraus** [comment] 2021-05-25 18:57
Any suggestion for a potential workaround would be very much appreciated.

**Comment by spacegaier** [comment] 2021-05-25 18:59
Isn't this here a duplicate of your own issue https://github.com/home-assistant/frontend/issues/9069 😉?

**Comment by scstraus** [comment] 2021-05-25 19:02
Sorry you beat me to the punch of closing it by 5 seconds (you are fast!). I wanted to create something more focused around this which didn't involve cameras and the discussion about what the core issue was so I moved it to a new issue which gets straight to the heart of the matter. Sorry about that.

**Comment by scstraus** [comment] 2021-05-25 19:07
I went back to the #8353, could you confirm that if I [reversed this edit](https://github.com/home-assistant/frontend/pull/8353/commits/d601e99e96149fdc74b2d40c066e0ff124526955), I could undo this? 

Though honestly I think that completely sacrificing accessibility on some devices to make the mobile experience slightly nicer for people without accessibility issues is completely the wrong thing to do. This should have been solved in the iOS app, not by disabling zoom across the board.

**Comment by bramkragten** [comment] 2021-05-25 21:55
Yes, that would fix it. You can also very easily create a custom js snippet that enables it.

Put this in a file and load it with <https://www.home-assistant.io/integrations/frontend/#extra_module_url>

```js
document.querySelector("meta[name=viewport]").setAttribute("content", "width=device-width, viewport-fit=cover");
```

**Comment by scstraus** [comment] 2021-05-25 23:56
Cool, would that survive upgrades?

**Comment by scstraus** [comment] 2021-06-01 20:36
It works! Thank you, this was causing me big stress.

**Comment by bramkragten** [comment] 2021-06-01 20:37
> It works! Thank you, this was causing me big stress.

Great! :-)

**Closed** 2021-06-01 20:37 UTC
Labels: bug
