### ISSUE TITLE
Tracking screen opens a new screen instead value display

### ISSUE THREAD

**Issue by eibdoktor** [home-assistant/frontend#20442] opened 2024-04-06 09:05 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a problem with the display of histories of values. It occurs when I want to specify the time range. After that, when I want to read the values on a certain point on the curve, by clicking on it, instead of the normal reaction in previous version, the same page is opened over this page again. Without a specific time range, but the default one. Then I can click on the curve to see the value on a spot, but this is surely not the intention! 

### Describe the behavior you expected

The spot values on the curve must be shown like in the previous versions of HA - it makes no sense at all like it behaves now.

### Steps to reproduce the issue

1. select a value
2. Open the „further details“ page
3. Click on the curve: another line diagram will open instead of displaying the spot value

### What version of Home Assistant Core has the issue?

2024.4.1

### What was the last working version of Home Assistant Core?

That one before the recent update as from April 5th

### In which browser are you experiencing the issue with?

It happens in all browsers i have, Chrome, Firefox, Safari, Edge and in the APP! So the versions don‘t seem to be relevant

### Which operating system are you using to run this browser?

Windows 10 Pro 22H2, iPad OS 15.8.2, iPhoneOS 17.3.1

### State of relevant entities

```txt
I think this is not relevant, unless it is caused by KNX entities. I use HA mainly for KNX.
```

### Problem-relevant frontend configuration

```yaml
I really think it is not important, because the error occurs on all numerical value entities!
```

### Additional information

You ask for a lot of information which is only browser related. But I am using the HA App, and I use this both on an iPhone and on an iPad. I have the latest versions of the Apple iOS, the HA App as well.

**Comment by eibdoktor** [comment] 2024-04-06 09:08
As this issue occurs whereever I open my HA, it seems strongly to be related to its recent update, and not to any specific browser or operating system.

**Comment by karwosts** [comment] 2024-04-07 01:12
This is an iOS issue, duplicate of https://github.com/home-assistant/frontend/issues/20081

**Closed by karwosts** 2024-04-07 01:12 UTC
