### ISSUE TITLE
Dashboard Freezes on load if BitWarden Extension is Enabled

### ISSUE THREAD

**Issue by canselcik** [home-assistant/frontend#21101] opened 2024-06-16 18:42 UTC
Today I noticed the dashboard was freezing. Tried updating to latest version, tried clearing all site data for the frontend on the browser. Nothing helped, it would load only with Incognito, which meant it was either interaction the installed extensions or site data.

Since site data was ruled out, it must be the extensions. All of the content filtering / ad blocking extensions were ruled out.

Disabled BitWarden, it loads fine, no freezing. Enabled BitWarden, it freezes.

There is no other website at which I have this issue. Would appreciate more eyes on this.

_Originally posted by @canselcik in https://github.com/home-assistant/frontend/issues/17947#issuecomment-2171804341_

Running the `ghcr.io/home-assistant/home-assistant:stable` image but also tried `ghcr.io/home-assistant/home-assistant:latest`.

**Comment by canselcik** [comment] 2024-06-16 18:48
If it is some weird interaction breaking the page, not a big deal. What's more concerning would be if some rogue obfuscated code made it into the frontend that's looking for unlocked password manager contexts trying to exfiltrate secrets.

**Comment by cryd-s** [comment] 2024-06-17 04:59
Same problem here!

**Comment by MartinKuhl** [comment] 2024-06-17 05:25
Update to the latest version 2024.6.1 fixed my issue.

**Comment by cryd-s** [comment] 2024-06-17 05:26
I have updated yesterday and for me it isnt a fix

**Comment by MartinKuhl** [comment] 2024-06-17 05:30
> I have updated yesterday and for me it isnt a fix

on the detailed extension site they mentioned that this version (2024.6.1) was released today. If you updated already yesterday maybe the rereleased this version?

**Comment by cryd-s** [comment] 2024-06-17 05:33
> > I have updated yesterday and for me it isnt a fix
> 
> on the detailed extension site they mentioned that this version (2024.6.1) was released today. If you updated already yesterday maybe the rereleased this version?

![image](https://github.com/home-assistant/frontend/assets/47699362/ded739fd-4b47-40eb-8830-024ad35c6713)

**Comment by MartinKuhl** [comment] 2024-06-17 05:35
> > > I have updated yesterday and for me it isnt a fix
> > 
> > 
> > on the detailed extension site they mentioned that this version (2024.6.1) was released today. If you updated already yesterday maybe the rereleased this version?
> 
> ![image](https://private-user-images.githubusercontent.com/47699362/340188485-ded739fd-4b47-40eb-8830-024ad35c6713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDI3NjYsIm5iZiI6MTcxODYwMjQ2NiwicGF0aCI6Ii80NzY5OTM2Mi8zNDAxODg0ODUtZGVkNzM5ZmQtNGI0Ny00MGViLTg4MzAtMDI0YWQzNWM2NzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA1MzQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNGQ2NWViODcyYzgzYmIwYzcwNTcxYTcyZTg3ODc4NTc0NzI2MmNkYzZkOWIwNzlmZjlkM2I3YWRmMWQxOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvwhVIFQHMkd9-7sgYXaXyReQkaSnCS9aqsMB-1izzI)

I was refering to the bitwarden chrome extension, not home assistant!
https://chromewebstore.google.com/detail/bitwarden-passwortmanager/nngceckbapebfimnlniiiahkandclblb?hl=de&utm_source=ext_sidebar

**Comment by cryd-s** [comment] 2024-06-17 05:52
> > > > I have updated yesterday and for me it isnt a fix
> > > 
> > > 
> > > on the detailed extension site they mentioned that this version (2024.6.1) was released today. If you updated already yesterday maybe the rereleased this version?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/47699362/340188485-ded739fd-4b47-40eb-8830-024ad35c6713.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDI3NjYsIm5iZiI6MTcxODYwMjQ2NiwicGF0aCI6Ii80NzY5OTM2Mi8zNDAxODg0ODUtZGVkNzM5ZmQtNGI0Ny00MGViLTg4MzAtMDI0YWQzNWM2NzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA1MzQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNGQ2NWViODcyYzgzYmIwYzcwNTcxYTcyZTg3ODc4NTc0NzI2MmNkYzZkOWIwNzlmZjlkM2I3YWRmMWQxOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VvwhVIFQHMkd9-7sgYXaXyReQkaSnCS9aqsMB-1izzI)
> 
> I was refering to the bitwarden chrome extension, not home assistant! https://chromewebstore.google.com/detail/bitwarden-passwortmanager/nngceckbapebfimnlniiiahkandclblb?hl=de&utm_source=ext_sidebar

Perfekt it works !!!!

**Comment by MartinKuhl** [comment] 2024-06-17 06:40
with updating the bitwarden extension, this issue is solved

**Comment by MartinKuhl** [comment] 2024-06-17 06:41
> Today I noticed the dashboard was freezing. Tried updating to latest version, tried clearing all site data for the frontend on the browser. Nothing helped, it would load only with Incognito, which meant it was either interaction the installed extensions or site data.
> 
> Since site data was ruled out, it must be the extensions. All of the content filtering / ad blocking extensions were ruled out.
> 
> Disabled BitWarden, it loads fine, no freezing. Enabled BitWarden, it freezes.
> 
> There is no other website at which I have this issue. Would appreciate more eyes on this.
> 
> _Originally posted by @canselcik in [#17947 (comment)](https://github.com/home-assistant/frontend/issues/17947#issuecomment-2171804341)_
> 
> Running the `ghcr.io/home-assistant/home-assistant:stable` image but also tried `ghcr.io/home-assistant/home-assistant:latest`.

with updating the bitwarden extension, this issue is solved

**Comment by silamon** [comment] 2024-06-17 12:14
Duplicate of #21085

**Closed by silamon** 2024-06-17 12:14 UTC

**Comment by c11umw** [comment] 2024-06-19 09:18
It was an issue with all the extension used on all Chromium based browsers.
Firefox didn't have the issue ( https://github.com/home-assistant/operating-system/issues/3419 )
