### ISSUE TITLE
Automation Editor failing to open correctly

### ISSUE THREAD

**Issue by andylether** [home-assistant/frontend#8628] opened 2021-03-13 10:22 UTC
### The problem

An automation correctly opens for editting in core version 2021.3.2 fails in later versions.

### What is version of Home Assistant Core has the issue?

2021.3.3 and 2021.3.4

### What was the last working version of Home Assistant Core?

2021.3.2

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Automation editor

### Example YAML snippet

```yaml
# Put your YAML below this line
- id: '1611235384705'
  alias: Evening Curtains with cloud cover
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '-0.8'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '-0.5'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '0.1'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '0.4'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '0.8'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '1.2'
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '-1.2'
  condition:
  - condition: template
    value_template: '{{ not state_attr(''sun.sun'', ''rising'') }}'
  - condition: state
    entity_id: input_boolean.notify_curtain
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_cloud_coverage
        below: '10'
        value_template: '{{ states("sensor.openweathermap_cloud_coverage") }}'
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '-0.8'
      sequence:
      - service: script.evening_curtain_and_lights
        data: {}
      - service: logbook.log
        data:
          message: elevation, {{states.sun.sun.attributes.elevation}}, weather {{states.sensor.openweathermap_cloud_coverage.state}}
            , weather {{states.sensor.openweathermap_condition.state}}.
          name: Evening test 10
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_cloud_coverage
        below: '25'
        value_template: '{{ states("sensor.openweathermap_cloud_coverage") }}'
        above: '9'
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '-0.4'
      sequence:
      - service: script.evening_curtain_and_lights
        data: {}
      - service: logbook.log
        data:
          message: elevation, {{states.sun.sun.attributes.elevation}}, weather {{states.sensor.openweathermap_cloud_coverage.state}}
            , weather {{states.sensor.openweathermap_condition.state}}.
          name: Evening test 25
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_cloud_coverage
        below: '33'
        above: '24'
        value_template: '{{ states("sensor.openweathermap_cloud_coverage") }}'
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '0.1'
      sequence:
      - service: script.evening_curtain_and_lights
        data: {}
      - service: logbook.log
        data:
          message: elevation, {{states.sun.sun.attributes.elevation}}, weather {{states.sensor.openweathermap_cloud_coverage.state}}
            , weather {{states.sensor.openweathermap_condition.state}}.
          name: Evening test 33
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_cloud_coverage
        value_template: '{{ states("sensor.openweathermap_cloud_coverage") }}'
        below: '50'
        above: '30'
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '0.4'
      sequence:
      - service: logbook.log
        data:
          message: elevation, {{states.sun.sun.attributes.elevation}}, weather {{states.sensor.openweathermap_cloud_coverage.state}}
            , weather {{states.sensor.openweathermap_condition.state}}.
          name: Evening test 50
      - service: script.evening_curtain_and_lights
        data: {}
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_cloud_coverage
        above: '45'
        below: '66'
        value_template: '{{ states("sensor.openweathermap_cloud_coverage") }}'
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '0.8'
      sequence:
      - service: script.evening_curtain_and_lights
        data: {}
      - service: logbook.log
        data:
          message: elevation, {{states.sun.sun.attributes.elevation}}, weather {{states.sensor.openweathermap_cloud_coverage.state}}
            , weather {{states.sensor.openweathermap_condition.state}}.
          name: Evening test 66
    - conditions:
      - condition: numeric_state
        entity_id: sensor.openweathermap_cloud_coverage
        below: '101'
        value_template: '{{ states("sensor.openweathermap_cloud_coverage") }}'
        above: '66'
      - condition: numeric_state
        entity_id: sun.sun
        attribute: elevation
        below: '1.2'
      sequence:
      - service: script.evening_curtain_and_lights
        data: {}
      - service: logbook.log
        data:
          message: elevation, {{states.sun.sun.attributes.elevation}}, weather {{states.sensor.openweathermap_cloud_coverage.state}}
            , weather {{states.sensor.openweathermap_condition.state}}.
          name: Evening test 101
    default:
    - service: logbook.log
      data:
        message: elevation, {{states.sun.sun.attributes.elevation}}, weather {{states.sensor.openweathermap_cloud_coverage.state}}
          , weather {{states.sensor.openweathermap_condition.state}}.
        name: Evening test default
  mode: parallel
  max: 7
```

### Anything in the logs that might be useful for us?

```txt
# Put your logs below this line
No errors found in the logs
```

try's to open the automation in yaml mode but fails.
2021.3.3 shows around 21 lines.
2021.3.4 just shows "Choose"

**Comment by frenck** [comment] 2021-03-13 12:04
This is a frontend issue, not a core issue. Transferred this report to the correct location.

**Comment by bramkragten** [comment] 2021-03-13 14:22
Click inside the editor, that should show it.

**Comment by andylether** [comment] 2021-03-13 15:07
Clicking in the editor loads some more of the file but still some missing. The uieditor worked correctly in 2021.3.2.
Screen shot of the error message attached
![Screenshot from 2021-03-13 15-00-03](https://user-images.githubusercontent.com/43098184/111034445-a0136900-840d-11eb-91de-553684f86668.png)

**Comment by andylether** [comment] 2021-03-13 15:11
Closed in error

**Comment by andylether** [comment] 2021-03-13 15:27
Screen shot from 2021.3.2
![Screenshot from 2021-03-13 15-24-35](https://user-images.githubusercontent.com/43098184/111035080-8de6fa00-8410-11eb-88ef-40dc0980c65a.png)

**Comment by andylether** [comment] 2021-04-09 09:03
The new automations trace function also fails to display all the lines.

**Comment by bramkragten** [comment] 2021-04-09 10:51
Duplicate of https://github.com/home-assistant/frontend/issues/8557

**Closed by bramkragten** 2021-04-09 10:51 UTC
