### ISSUE TITLE
Slider value label cut off

### ISSUE THREAD

**Issue by zepfietje** [home-assistant/frontend#7560] opened 2020-10-30 19:02 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Slider value labels are being cut off in various places.
<img width="97" alt="image" src="https://user-images.githubusercontent.com/44533235/97746310-6db24080-1aea-11eb-8440-68da5b5b8e57.png">

## Expected behavior

Label doesn't get cut off and is fully visible, even the part outside of cards.

## Steps to reproduce

1. Add a number helper to a Lovelace entities card, or just open a light's details (e.g. brightness).
2. Drag the slider and see the slider value label being cut off at the top.

## Environment

- Home Assistant release with the issue: 0.117.1
- Last working Home Assistant release (if known): -
- Browser and browser version: latest version of the Home Assistant Android and Mac apps
- Operating system: -

**Comment by spacegaier** [comment] 2020-11-01 15:09
I can confirm that, as I had noticed the same a few days ago. Fix is on its way.

**Comment by zepfietje** [comment] 2020-11-19 21:51
@bramkragten, https://github.com/home-assistant/frontend/pull/7651 fixed this issue only partly.
For (number helper) range sliders in a Lovelace entities card, the label still gets cut off.

**Comment by spacegaier** [comment] 2020-11-19 22:21
@zepfietje This is how it looks for me. Not sure if there is a missing pixel on top or not. Looks the same to me compared to the light brightness slider.
![image](https://user-images.githubusercontent.com/114137/99731196-d70bea80-2abd-11eb-81ad-37168e54d4a4.png)

**Comment by zepfietje** [comment] 2020-11-19 22:23
@spacegaier, I'm talking about the Lovelace entities card, not the details card.

**Comment by spacegaier** [comment] 2020-11-19 22:25
That was what I tested first and there it was fine on my end, so I moved on to the more-info 😄 .

![image](https://user-images.githubusercontent.com/114137/99731592-6a452000-2abe-11eb-94de-9a8620971cbf.png)

Can you post a screenshot to illustrate the scenario you found? Does the number helper need to be at the top or something along those lines for the issue to appear?

**Comment by zepfietje** [comment] 2020-11-19 22:27
@spacegaier, if you move the number helper to be the first entity in the card, the issue should occur. 😉

**Comment by spacegaier** [comment] 2020-11-19 22:29
Please post a screenshot, because I cannot reproduce it.

**Comment by zepfietje** [comment] 2020-11-19 22:32
<img width="502" alt="image" src="https://user-images.githubusercontent.com/44533235/99732251-75e51680-2abf-11eb-97ab-3aeebbb105b2.png">

**Comment by spacegaier** [comment] 2020-11-19 22:35
Ah, an entities card without title 😄. No ideas, how to properly fix that. @bramkragten or other CSS wizards need to chime in here.

**Comment by zsarnett** [comment] 2020-11-19 22:36
The reason it happens is that overflow is hidden on the ha-card element... But it's there for a reason.. I can take a look later potentially

**Comment by zepfietje** [comment] 2021-02-18 21:09
This is still a relevant issue.

**Comment by zepfietje** [comment] 2021-05-22 19:51
This is still a relevant issue.

**Comment by zepfietje** [comment] 2021-08-20 21:03
I believe this hasn't been solved yet.

**Comment by davekrijgsman** [comment] 2021-10-16 12:32
Fix yet?

**Comment by spacegaier** [comment] 2021-10-16 15:22
> 
> 
> Fix yet?

Not yet, otherwise this issue would be closed?! This PR might solve it: https://github.com/home-assistant/frontend/pull/10250

**Comment by Raul-7-7** [comment] 2021-11-03 23:27
Anyone wondering, issue is not yet fixed, he PR has not been approved to be merged yet.

**Comment by robertkalinowski** [comment] 2021-11-08 09:05
in my case it is completely not visible
![Screenshot 2021-11-08 at 10 04 38](https://user-images.githubusercontent.com/20813438/140713840-6991bdc1-6c3d-4857-beb3-e85c51528f10.png)

**Comment by bramkragten** [comment] 2021-11-08 09:13
Fixed in https://github.com/home-assistant/frontend/pull/10250

**Closed by bramkragten** 2021-11-08 09:13 UTC
Labels: bug

**Comment by robertkalinowski** [comment] 2021-11-08 12:50
Thanks, I would like to correct the .ts file before fix will be available in new release. Can you let me know where this file is located in docker installation version?
