### ISSUE TITLE
Calendar Card: can't select initial_view in UI editor

### ISSUE THREAD

**Issue by mamoel666** [home-assistant/frontend#12093] opened 2022-03-22 12:11 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The dropdown for the parameter "initial_view" only shows three empty items and they have no effect on the configuration. So it's not only a visual problem.

![image](https://user-images.githubusercontent.com/45948842/159478398-1bca49b5-14b1-43de-a0dd-31fb2951311f.png)

### Describe the behavior you expected

I'd like to have the option to select from

- Month View
- Day View
- List View

### Steps to reproduce the issue

1. Add calendar card to UI
2. Select entity
3. Try to change initial view

### What version of Home Assistant Core has the issue?

2022.3.6

**Comment by sniper6661991** [comment] 2022-03-29 03:40
Same issue
On 2022.3.5 
Tired chrome and edge
![image](https://user-images.githubusercontent.com/57074288/160528291-65ee7222-8cf8-4756-8626-652e1edb65ea.png)

Tried Code editor with following and just blanks the card.
type: calendar
initial_view:  (dayGridMonth, dayGridDay, or listWeek)
  - calendar.qwertyuiop
  - calendar.abcdefghijk

**Comment by atkjedi** [comment] 2022-04-08 06:30
I have the same issue

**Comment by jugla** [comment] 2022-04-12 20:46
Same issue.
The problem seems to be within `src/panels/calendar/ha-full-calendar.ts` .
As a workaround, you can create a calendar card and select code. E.g. : 
```yaml
initial_view: dayGridMonth
type: calendar
entities:
  - calendar.royan_tides
title: Next tide
```
In initial view you can put : 
`dayGridMonth`
`dayGridWeek`
`dayGridDay`
`list`
(value given by `const viewButtons`)

NB : as you can notice there is 4 possible values, whereas 3 seems to be wanted to be shown

When set initial view, it seems that all calendar card shared the same initial view. I don't think it's the wanted behaviour.
If some one can confirm or not .

**Comment by jugla** [comment] 2022-04-12 21:29
Don't know if it can help: #9993 may solve it.

**Comment by jantoney** [comment] 2022-04-21 15:39
@jugla workaround confirmed working and also confirmed still a fault in HA 2022.4.6

#9993 seems to be stuck waiting for #9193 which has now been marked stale and closed... So I don't think it's going to go anywhere

**Comment by jugla** [comment] 2022-04-22 21:39
@[spacegaier](https://github.com/spacegaier) , do you know how to handle this PR #12093 ?

**Comment by thoemmi** [comment] 2022-09-05 11:12
This issue still exists in 2022.8.7

**Comment by devedsmith** [comment] 2022-09-22 12:03
Yes, this is still an issue. 
![image](https://user-images.githubusercontent.com/34871257/191741644-9fa10c6b-6e81-48ef-b89e-964280b91e85.png)

**Comment by spacegaier** [comment] 2022-12-05 11:33
That is already fixed in the current stable release.

**Closed by spacegaier** 2022-12-05 11:33 UTC
