### ISSUE TITLE
Thermostat Card Configuration cannot change temperature

### ISSUE THREAD

**Issue by domerich** [home-assistant/frontend#15676] opened 2023-03-02 11:36 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the normal theromstat I cannot change the tempature anymore since the last update to Home Assistant 2023.3.0

### Describe the behavior you expected

Usually I could grab the slider on the round bar and change it, now this is not possible anymore.

### Steps to reproduce the issue

Usually I could grab the slider on the round bar and change it, now this is not possible anymore.

### What version of Home Assistant Core has the issue?

Home Assistant 2023.3.0

### What was the last working version of Home Assistant Core?

 2023.3b

**Comment by spirit8000** [comment] 2023-03-02 12:01
I have the same issue after updating to Home Assistant 2023.3.0 this morning but this only affects the iOS app for me on both my and my wife's iPhones. Desktop browser (Chrome) is fine. I've also tried different themes. App has been restarted.

It manifests like the dot, which you would usually drag around the circle, is missing.

**Comment by crsprsp** [comment] 2023-03-02 12:23
Same here. Since the update to 2023.3.0 today, the control "dot" is missing in the Thermostats. Due to this, the Thermostats are not controlable via the GUI or App anymore.

<img width="453" alt="thermostatdotmissing" src="https://user-images.githubusercontent.com/16636402/222427670-fccc1187-2dbc-4c0d-b5e2-6b943db96cfb.png">

**Comment by piitaya** [comment] 2023-03-02 12:25
Duplicate of #14440. It will be fixed in the next patch

**Closed by piitaya** 2023-03-02 12:25 UTC

**Comment by fibsifan** [comment] 2023-03-02 12:48
Hello @piitaya are you sure that this issue is a duplicate of #14440 - the creator of #14440 mentioned the version 2022.11.4 to be affected. This issue with the thermostat hasn't been seen before 2023.3.0. In Fact I was using the Thermostat just fine in every Version between 2022.11.4 and 2023.2.5.

@spirit8000 , @crsprsp A workaround seems to be to set the temperature via the three dots menu of the panel.

**Comment by piitaya** [comment] 2023-03-02 13:02
Oops, I referenced the wrong issue. The right one is https://github.com/home-assistant/frontend/issues/15662
