### ISSUE TITLE
"Home Assistant is starting, not everything will be available until it is finished." Blocking Profile Button

### ISSUE THREAD

**Issue by IIAIronWolf** [home-assistant/frontend#6674] opened 2020-08-22 00:16 UTC
## The problem

After Home Assistant has started, currently you have to wait until the "Home Assistant is starting, not everything will be available until it is finished." message has disappeared in order to access your user profile section that is hidden beneath the message.

## Environment

- Home Assistant Core release with the issue: 0.114.3
- Last working Home Assistant Core release (if known): NA
- Operating environment (OS/Container/Supervised/Core): Core
- Integration causing this issue: Frontend
- Link to integration documentation on our website: NA

## Problem-relevant `configuration.yaml`

```yaml
NA
```

## Traceback/Error logs

```txt
NA
```

## Additional information
Would like to see these notifications be cancellable.

**Comment by spacegaier** [comment] 2020-08-25 07:26
Duplicate of https://github.com/home-assistant/frontend/issues/6649

**Closed** 2020-08-25 09:46 UTC

**Comment by CharlesRDavis** [comment] 2020-08-27 02:35
When I removed default_config: from configuration.yaml, the message went away.
