### ISSUE TITLE
Settings -> System not loading

### ISSUE THREAD

**Issue by pezzeonline** [home-assistant/frontend#13732] opened 2022-09-14 08:06 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After latest upgrade (2022.9.3), System page in Settings is not loading because a Javascript error in Italian translation:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-card.ts:5:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
```

### Describe the behavior you expected

The page has to be shown, has before latest upgrade (2022.9.3)

### Steps to reproduce the issue

1. Set Italian language
2. Upgrade to 2022.9.3
3. Check System page

### What version of Home Assistant Core has the issue?

2022.9.3

### What was the last working version of Home Assistant Core?

2022.9.2

### In which browser are you experiencing the issue with?

Brave v1.43.89, Chrome v105.0.5195.102, Safari  15.6.1 (17613.3.9.1.16)

### Which operating system are you using to run this browser?

macOS Monterey 12.5.1

### Javascript errors shown in your browser console/inspector

```txt
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-card.ts:5:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
```

**Comment by ludeeus** [comment] 2022-09-14 08:07
Duplicate of https://github.com/home-assistant/frontend/issues/13728

**Closed by ludeeus** 2022-09-14 08:07 UTC
