### ISSUE TITLE
Using long /dev paths for ZHA integration breaks formatting in integrations UI

### ISSUE THREAD

**Issue by cannfoddr** [home-assistant/frontend#6120] opened 2020-06-08 08:53 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using path /dev/serial/by-id/<very long device description> results in text spilling outside ZHA box on the configuration -> Integrations page

## Expected behaviour

Text should wrap of be truncated

## Steps to reproduce

1. Add a ZHA (or other - not tested) integration
2. Instead of /dev/ttyACM0 set path to /dev/serial/by-id/<some very very long device description>
3. Integration works correctly
4. Go to UI configuration -> Integrations 
5. Resource name is set to long /dev/serial.... string which flows outside the ZHA integration frame

## Environment

- Home Assistant release with the issue: 0.110.5
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome (latest), Safari (latest)
- Operating system: Mac 10.15.5

## State of relevant entities

<img width="402" alt="image" src="https://user-images.githubusercontent.com/1035066/84010304-64bea800-a96c-11ea-91c0-7cc9fe981a0a.png">

**Comment by Hedda** [comment] 2020-06-08 10:40
Also see https://github.com/home-assistant/frontend/issues/5806

**Comment by bramkragten** [comment] 2020-06-08 11:19
Duplicate of #5806

**Closed by bramkragten** 2020-06-08 11:19 UTC
Labels: bug
