### ISSUE TITLE
Automation editor - Condition State mangled by UI

### ISSUE THREAD

**Issue by eode** [home-assistant/frontend#7463] opened 2020-10-23 01:30 UTC
ok, not deleting any text..

## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When editing automations in the automation editor (at configuration->automations), if editing a Condition->State, or an Actions->Condition->State, there is a: only one way to enter multiple conditions to match within the same entry -- specifically, by editing as YAML and entering a list, as in this case:

```yaml
condition: state
entity_id: sensor.whatever
state:
  - blah
  - foo
```
In the above case, if the rule is saved either of 'foo' or 'blah' are the state of `sensor.whatever`, the condition matches.  This is good.

However, if you edit that automation, it no longer shows up as YAML, but rather with the 'state' field containing the string `'blah,foo'`.  The underlying rule looks like this:

```yaml
condition: state
entity_id: sensor.classic_chargestatetext
state: 'blah,foo'
```
This also occurs if you just switch back to editing with UI, even if the rule hasn't been saved yet.

## Expected behavior

Expected behavior is:

a: changing back and forth between UI and YAML editing does not modify the YAML.
b: editing an automation does not modify portions of the automation you do not alter (although this is fixed if a: is fixed)
c: YAML that can't be handled by the UI shown as YAML, not modified to a form that the UI can handle (unless that is simply an isomorphic translation for usage in the UI, and doesn't affect the underlying YAML).

## Steps to reproduce

1: Create an automation that can be saved
2: Add a condition or action condition
3: Choose 'edit as YAML' for that condition
4: Edit the condition so that `state:` contains a list of states containing more than one item
5: Choose 'edit in UI'.
6: It is now one comma-separated string instead of a list of strings.

Alternate route:
5: Save the automation
6: Exit back to configuration->automations
7: Edit your automation again.
8: Your rule now contains one comma-separated string instead a list of strings.
9: make any unrelated change
10: save
11: your rule is broken, as any lists of states are now singular strings.

## Environment

- Home Assistant release with the issue: 0.116.4
- Last working Home Assistant release (if known): --
- Browser and browser version: Firefox 81.0.2 64-bit, Android HomeAssistant app
- Operating system: Ubuntu 20.04, Android

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

No relevant errors
```txt

```

**Comment by spacegaier** [comment] 2020-10-23 07:34
Duplicates https://github.com/home-assistant/frontend/issues/6664

**Comment by frenck** [comment] 2020-10-23 11:25
Closing as duplicate of #6664

**Closed by frenck** 2020-10-23 11:25 UTC
Labels: bug
