### ISSUE TITLE
Side bar mulitplies when canceling 

### ISSUE THREAD

**Issue by joostb9** [home-assistant/frontend#9038] opened 2021-04-29 13:19 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Getting multiple sidebar copies when canceling.

![Schermafbeelding 2021-04-29 151633](https://user-images.githubusercontent.com/52859487/116556625-ef4e2400-a8fd-11eb-9333-9dcce0d98f65.png)

### Describe the behavior you expected

expected to keep one side bar

### Steps to reproduce the issue

1.Go to the super visor. 
2.Select an exisitng add on
3.Go to the remove add on sub menu.
4.Press no/cancel

### What version of Home Assistant Core has the issue?

core-2021.4.6

### In which browser are you experiencing the issue with?

MS Edge Versie 90.0.818.49 

### Which operating system are you using to run this browser?

Windows 10 22H2

**Comment by spacegaier** [comment] 2021-04-29 13:54
Duplicate of https://github.com/home-assistant/frontend/issues/8926 and already fixed.

**Closed by spacegaier** 2021-04-29 13:54 UTC
Labels: bug
