### ISSUE TITLE
Frontend stopped loading inside an IFRAME after upgrading to 20240207.0

### ISSUE THREAD

**Issue by pedropombeiro** [home-assistant/frontend#19724] opened 2024-02-08 08:29 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After upgrading this morning, I noticed that the frontend was stuck on the loading icon, when opening it from `https://dashboard.<my-domain>`. Opening the site outside of `https://dashboard.<my-domain>` worked as expected. Looking at the Developer Tools Console shows:

```
Uncaught (in promise) SecurityError: Failed to read a named property 'name' from 'Window': Blocked a frame with origin "https://ha.<my-domain>" from accessing a frame with origin "https://dashboard.<my-domain>". Protocols, domains, and ports must match.
```

Normally, the required configuration is in place and was working as expected before the upgrade.

### Describe the behavior you expected

I should see ha.<my-domain> being loaded inside dashboard.<my-domain>.

### Steps to reproduce the issue

1. Setup Traefik as a reverse proxy
2. Setup muximux to host the Home Assistent app
3. Browse to muximux

### What version of Home Assistant Core has the issue?

2024.2.0

### What was the last working version of Home Assistant Core?

2024.1.x

### In which browser are you experiencing the issue with?

Microsoft Edge Version 121.0.2277.106 (Official build) (arm64)

### Which operating system are you using to run this browser?

macOS 14.3 (23D56)

### Javascript errors shown in your browser console/inspector

```
Uncaught (in promise) SecurityError: Failed to read a named property 'name' from 'Window': Blocked a frame with origin "https://ha.<my-domain>" from accessing a frame with origin "https://dashboard.<my-domain>". Protocols, domains, and ports must match.
```

**Comment by ImSkully** [comment] 2024-02-08 12:08
Also experiencing this issue after updating:
```
Uncaught (in promise) DOMException: Failed to read a named property 'name' from 'Window': Blocked a frame with origin "https://home.<domain>" from accessing a cross-origin frame.
```

This was previously working fine in 2024.01 as long as `use_x_frame_options: false` was set in `http` settings to allow embedding HA in an iframe.

**Comment by bramkragten** [comment] 2024-02-08 15:05
I'm not going to set this all up to reproduce:

>Setup Traefik as a reverse proxy
Setup muximux to host the Home Assistent app
Browse to muximux

Got a simple repo?

**Comment by ImSkully** [comment] 2024-02-08 15:29
@bramkragten for context, I'm using the [Home Assistant Chrome extension](https://github.com/bokub/home-assistant-extension) which simply points to your HA instance via URL and embeds an iframe in Chrome to quickly access it - that iframe is failing with this same issue that may help with reproducing.
1. Install [Chrome extension](https://chromewebstore.google.com/detail/home-assistant/hpoiflhmfklhfcfpibmdmpeonphmdbda)
2. Update `configuration.yaml` and add the following:
  ```yml
  http:
    use_x_frame_options: false
  ```
3. In extension options, set URL to any home assistant homepage
4. Preview displays page hanging and loads splash page only showing HA logo, dev console throws error

**Comment by ivanpavlina** [comment] 2024-02-09 07:45
Having the identical issue as of last update, opening Homeassistant through Organizr throws dev console error .

```
http:
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  use_x_frame_options: false
  cors_allowed_origins:
    - https://dashboard.mydomain..net/
  trusted_proxies:
    - 127.0.0.1
    - !secret http_proxy_ip
```

Setting cors_allowed_origins to Organizr's URL also does not help.

**Comment by codyc1515** [comment] 2024-02-09 09:59
Your CORS allow origins must match identically. I presume the above is an example but there are two dots before net - that would cause an exception if real.

**Comment by pedropombeiro** [comment] 2024-02-09 10:22
> Your CORS allow origins must match identically. I presume the above is an example but there are two dots before net - that would cause an exception if real.

Mine match exactly and it still fails. The truth is that something changed with the last version that caused working configurations to stop working, so it would be helpful to figure out which commit changed that behavior, so that we can try to work out a solution.

**Comment by ivanpavlina** [comment] 2024-02-09 10:33
> Your CORS allow origins must match identically. I presume the above is an example but there are two dots before net - that would cause an exception if real.

It's a copy paste error while writing comment, configuration is without extra dot.

**Comment by codyc1515** [comment] 2024-02-09 20:38
How strange. CORS is not working for me too. I will do some digging. It may well be the case that this is a core issue.

**Comment by noteventhrice** [comment] 2024-02-09 21:20
same issue here

**Comment by GazAt105** [comment] 2024-02-10 02:22
Same issue here. I rolled back to 2024.1.6 iframe working ok. Then tested with versions 2024.2.0b0, 2024.2.0b5, 2024.2.0 and 2024.2.1 all failed.

**Comment by codyc1515** [comment] 2024-02-10 06:45
> I'm not going to set this all up to reproduce:
> 
> > Setup Traefik as a reverse proxy
> > Setup muximux to host the Home Assistent app
> > Browse to muximux
> 
> Got a simple repo?

`configuration.yaml`
```
http:
  cors_allowed_origins:
    - https://www.google.com
```

You should not even be able to use HA anymore because the websocket should refuse to connect but it still works. I was able to reproduce this everytime. I cannot get any CORS headers to show.

**Comment by myopenflixr** [comment] 2024-02-11 14:24
Same issue here as soon as I upgraded to 2024.2*. Displaying HA in IFRAME has worked for the past couple of years until this update.
I use both Muximux and Organizr to display HA in IFRAME along with other services. All other services display in IFRAME as expected.
Following this thread until resolved.

**Comment by technicallyfeasible** [comment] 2024-02-11 16:34
I'm having the same issue. Looking through the homeassistant source I can find this file as the source of the error:
https://github.com/home-assistant/frontend/blob/master/src/common/dom/get_main_window.ts

However, this file hasn't been changed  in 3 months so I am not sure why this issue would crop up only now.

**Comment by wwwDESIGN-basti** [comment] 2024-02-11 17:29
same issue here

**Comment by toxic0berliner** [comment] 2024-02-12 11:29
same issue here, organizr iframe also broken, didn't touch any config, traefik middleware is already adding CORS properly, I even widened it today with a new middleware : 
```
 http:
  middlewares:
    cors:
      headers:
        accessControlAllowOriginList:
          - "*"
        customResponseHeaders:
          Access-Control-Allow-Methods: "GET,HEAD,OPTIONS"
          Access-Control-Allow-Headers: "*"
          Access-Control-Allow-Origin: "*"
          Access-Control-Max-Age: "86400"
```
No more luck, still looks broken, can't figure out what to try next...

**Comment by mesab0ogie** [comment] 2024-02-12 11:48
same issue here home assistant page not loading in organizr iframe

Uncaught (in promise) DOMException: Failed to read a named property 'name' from 'Window': Blocked a frame with origin "https://xxx.xxx.com" from accessing a cross-origin frame.

**Comment by cbailes78** [comment] 2024-02-12 20:48
Same here, still an issue in 2024.2.1

**Comment by thegame3202** [comment] 2024-02-13 02:33
+1, also using Organizr and was working fine prior to latest 2024.2.0 update.

**Comment by audifan88** [comment] 2024-02-13 02:44
Issue for me too on Organizr

**Comment by alex-LE** [comment] 2024-02-15 15:54
I've found a solution. Setting name="ha-main-window" to the iframe worked for me.
Like this:

`<iframe src="[YOUR_HA_URL]" name="ha-main-window"></iframe>`

**Comment by JiggsNephron** [comment] 2024-02-15 16:52
Any idea how to add that permanently to Organizr? If I add it via Inspector, it works until page reload.

**Comment by cbailes78** [comment] 2024-02-15 17:53
Works here too - top man!

Thanks for sharing.

**Comment by alex-LE** [comment] 2024-02-15 20:45
> Any idea how to add that permanently to Organizr? If I add it via Inspector, it works until page reload.

Unfortunately, I am not familiar with Organizr.

**Comment by JiggsNephron** [comment] 2024-02-16 11:04
I found a solution for Organizr. In settings, go to Customize, then "Custom Javascript" and add this:

```
(function() {
    var newFrameName = "ha-main-window";
    document.getElementById("frame-13").setAttribute("name", newFrameName);

})();
```

**Comment by thegame3202** [comment] 2024-02-16 12:42
> I found a solution for Organizr. In settings, go to Customize, then "Custom Javascript" and add this:
> 
> ```
> (function() {
>     var newFrameName = "ha-main-window";
>     document.getElementById("frame-13").setAttribute("name", newFrameName);
> 
> })();
> ```

Didn't work for me. Where'd you find "frame-13"? I wonder if multiple integrations are causing this error.

**Comment by thegame3202** [comment] 2024-02-16 13:05
Yeah mine are all different numbers. I bet it's whatever integration is taking frame-13 for you. I tried that same section for me (happened to be frame-5), and that didn't work either. Interesting... Thanks though!

**Comment by JiggsNephron** [comment] 2024-02-16 13:28
I'm not very familiar with Javascript, but maybe you could use getElementsByClassName("iframe") instead, and apply it to all iframes. Also, I had to "ctrl+f5" refresh for a full refresh after saving the change in Organizr.

**Comment by toxic0berliner** [comment] 2024-02-16 21:08
I can cet it working in firefox through the console, but when I add my javascript in the organizr custom js section, I get the following error...
`Uncaught (in promise) DOMException: Permission denied to access property "name" on cross-origin object`

I strongly believe someone from ha should have a look at it and fix it from hass instead of tweaking our way to get it to work from outside, not all iframes will be in the same context, custom JS might not be an option for some anyway...

**Comment by thegame3202** [comment] 2024-02-16 21:15
Just tried the .2 release that just dropped, no change. Still broken.

**Comment by codyc1515** [comment] 2024-02-16 21:26
Is there anyone here experiencing this issue _not_ using Organizr?

**Comment by toxic0berliner** [comment] 2024-02-16 21:43
well, those on organizr can show some ❤️ to the request to get an actual web frontend dev from organizr to help find a workaround in organizr itself here https://github.com/causefx/Organizr/issues/1968

**Comment by ivanpavlina** [comment] 2024-02-16 21:57
> well, those on organizr can show some ❤️ to the request to get an actual web frontend dev from organizr to help find a workaround in organizr itself here [causefx/Organizr#1968](https://github.com/causefx/Organizr/issues/1968)

This is a homeassistant issue, I don't see why would organizr dev do unnecessary workarounds to accommodate currently present bug in another app.

**Comment by shbatm** [comment] 2024-02-16 22:02
> Is there anyone here experiencing this issue _not_ using Organizr?

Yes, same issue here using HA with a MagicMirror

**Comment by pedropombeiro** [comment] 2024-02-16 22:03
> Is there anyone here experiencing this issue _not_ using Organizr?

OP here, I'm seeing this with Muximux.

**Comment by aleckxss** [comment] 2024-02-17 00:35
I have the same problem, it's easy to reproduce using https://iframetester.com/ and simply opening home assistant in the iframe, of course after setting use_x_frame_options to false.

**Comment by thegame3202** [comment] 2024-02-17 02:56
^Confirmed that site shows the same problem. Just to confirm, I also have "use_x_frame_options: false" in my HASS and this has worked for years with my setup until this release.

**Comment by seidler2547** [comment] 2024-02-17 03:51
> ^Confirmed that site shows the same problem. Just to confirm, I also have "use_x_frame_options: false" in my HASS and this has worked for years with my setup until this release.

`use_x_frame_options: false` has been required since last year already.

**Comment by mrstevefay** [comment] 2024-02-17 08:11
> > well, those on organizr can show some ❤️ to the request to get an actual web frontend dev from organizr to help find a workaround in organizr itself here [causefx/Organizr#1968](https://github.com/causefx/Organizr/issues/1968)
> 
> This is a homeassistant issue, I don't see why would organizr dev do unnecessary workarounds to accommodate currently present bug in another app.

Yes, I have the issue in a basic HTML page hosted locally on apache showing HomeAssistant on my Kitchen display.

**Comment by myopenflixr** [comment] 2024-02-17 14:07
> I found a solution for Organizr. In settings, go to Customize, then "Custom Javascript" and add this:
> 
> ```
> (function() {
>     var newFrameName = "ha-main-window";
>     document.getElementById("frame-13").setAttribute("name", newFrameName);
> 
> })();
> ```

This seems to work in Firefox, but not Chrome.
In addition, I still can't get it working in MuxiMux.

**Comment by matt-laird** [comment] 2024-02-18 07:21
Please can I ask that the core issue be discussed rather than other app solutions that use iframes, it's clear it an issue with home-assistant in an frame, simple as that. Since the last version up date something specifically is different with home-assistant opening in an iframe. Either contribute to the home-assistant solution or simply configure whatever you using to open in a new tab for now until there is a home-assistant fix.

**Comment by iamdnaran** [comment] 2024-02-19 05:53
i have hass irame in hommar dashboard and it was working until 20240207 release and with the last update still broken

**Comment by robertw** [comment] 2024-02-20 11:40
> i have hass irame in hommar dashboard and it was working until 20240207 release and with the last update still broken

I concur I also amusing Hommer and it's still not functioning

**Comment by Vansmak** [comment] 2024-02-21 05:36
I see im not alone. It used to work on homepage dashboard. I am now using homarr and can't get it working. Just the icon

**Comment by andyb2000** [comment] 2024-02-21 08:52
Just to clarify.
This issue occurs in a plain embedded iframe (no 3rd parties/app solutions, etc, needed to prove the fault)

My test:
```
<HTML>
<BODY>
<iframe src="https://home.assistant:xxxx/" width=300 height=300></iframe>
</BODY>
</HTML>
``` 

If you add name="ha-main-window" like this:
``` 
<HTML>
<BODY>
<iframe src="https://home.assistant:xxxx/" width=300 height=300 name="ha-main-window"></iframe>
</BODY>
</HTML>
``` 
It works, but this seems to be a cludge/work-around as it's allowing the JS target to hit the static name.

The issue appears to be as reported above the js reference https://github.com/home-assistant/frontend/blob/master/src/common/dom/get_main_window.ts

**Comment by JamesDAdams** [comment] 2024-02-21 10:29
same error with organizr v2

**Comment by pedropombeiro** [comment] 2024-02-21 13:53
At this point it is no longer helpful to post new environments where this happens. We know that it happens with the simplest IFRAME setup, as [pointed out above](https://github.com/home-assistant/frontend/issues/19724#issuecomment-1956164357), so the rest is just noise and doesn't help with getting to a solution.

**Comment by Vansmak** [comment] 2024-02-22 02:54
Sure is quiet in here

**Comment by thegame3202** [comment] 2024-02-22 04:50
Anyone running HA without HACS or custom integrations in here? Wonder if maybe a custom card or integration is loading something with an iframe?

**Comment by MarekWatroba** [comment] 2024-02-22 06:57
I don't know how, but today it started to work, meaning I can see HA in Home Assistant Chrome Extension. No changes were made.

**Comment by GazAt105** [comment] 2024-02-22 07:12
I just did a fresh install of HA on a RPi4 without any addons, custom cards, integrations etc. and I get the same issue.

Without the 'name="ha-main-window"' option added to iframe in a simple html page [as per above ](https://github.com/home-assistant/frontend/issues/19724#issuecomment-1956164357) it does not work, add the option and it works.

**Comment by Spoil001** [comment] 2024-02-22 08:41
> I don't know how, but today it started to work, meaning I can see HA in Home Assistant Chrome Extension. No changes were made.

The extension was updated to set the frame name.


I suspect the relevant change in homeassistant is in one of these files:
https://github.com/search?q=repo%3Ahome-assistant%2Ffrontend%20MAIN_WINDOW_NAME&type=code

I however did not have the time to check "blame" for changes and I'm not fluent in Typescript.

**Comment by alex-LE** [comment] 2024-02-22 10:53
If you compare the current with the previous release, you can see that mainWindow is now being imported on several more places like the date-range-picker, ha-drawer and ha-slider.

see https://github.com/home-assistant/frontend/compare/20240131.0...20240202.0

All 3 changed by one pull request #19586.

But i don't think the change is the issue, it has just been added to more scripts and now the error happens. It just wasn't loaded before.

The main issue here is, that "parent" is not accessible due cross origin on this line:

`parent.name === MAIN_WINDOW_NAME`

adding a check of window.frameElement might help here, like this:

`window.frameElement !== null && parent.name === MAIN_WINDOW_NAME`

or just a simple try catch. But i'm not familiar with the code and Typescript at all.

**Comment by audifan88** [comment] 2024-02-24 01:17
oh man 2 releases since this was mentioned and each time I keep hoping it'll be the fix, what do we need to do to get this addressed I mean is it even listed as a bug or how do we get someone to acknowledge this :/

**Comment by Vansmak** [comment] 2024-02-24 01:21
Out of sight out of mind. People were admonished from commenting unless they had something toward a fix.  Noise is always good.

**Comment by aleckxss** [comment] 2024-02-24 01:35
I would not consider listing the zillion ways that home assistant can function in an iframe good noise... and there is such thing as a good and a bad noise. But it sure is calm in here. I'm checking this thread every day hoping something will change, I have two wall mounted dashboards at home that are only partially working since this problem started, I'm pretty tired of seeing it full of home assistant icon sized holes!! I just wish I had the programming know-how to help with the issue.

**Comment by Vansmak** [comment] 2024-02-24 02:13
The more comments the more people involved and more likely someone with the know how. Even this is better than sitting still in silence. 

I've been using python web view frameless to open my ha dash over my homepage which is silly but hey its better than nothing.  I tried creating an html to change the window name as suggested but that didn't seem to work for me. 

What about rolling back ha?

**Comment by silamon** [comment] 2024-02-24 11:06
I've found it working in 20240104.0 and broken in 20240112.0. Bisected to #19355. It must be that the import for search-params is being done earlier somehow than the import for the main window where many of you looked at. 

Since there a lot of comments here that helps towards the fix, I've summarized the reproduction steps I followed below. 

Reproduction steps: 
> 2. Update `configuration.yaml` and add the following:
> 
> ```yaml
> http:
>   use_x_frame_options: false
> ```
From: https://github.com/home-assistant/frontend/issues/19724#issuecomment-1933981318

Then this: 
> My test:
> 
> ```
> <HTML>
> <BODY>
> <iframe src="https://home.assistant:xxxx/" width=300 height=300></iframe>
> </BODY>
> </HTML>
> ```
> 
From: https://github.com/home-assistant/frontend/issues/19724#issuecomment-1956164357
(Replace the url with development url for easy debugging http://localhost:8123/)

**Comment by Ras-Perry** [comment] 2024-02-26 17:02
I have a super-simple homepage up and running. It consists of two frames. One serves as a navigation bar and the other to display the contents of the various menu items. I don't think it could be any simpler. When I click on the Homeassistant image on the left, the dashboard appears in the right-hand window. After updating HA, it no longer does. 

I don't use any third-party apps and my homepage doesn't use iframes. The error occurs in Chrome and Firefox. "use_x_frame_options: false" is in the configuration.yaml. 

I suspect that HA generally no longer supports frames.

**Comment by jwoglom** [comment] 2024-02-27 02:21
I've made an attempt to resolve this in https://github.com/home-assistant/frontend/pull/19884 by adding a try-catch around the logic which determines the main homeassistant window.

**Closed** 2024-02-27 12:17 UTC

**Comment by erlendoyen** [comment] 2024-04-01 15:02
is this actually fixed?
in that case, should it work with

cors_allowed_origins:
    - https://dashboard.example.com

or do you have to disable x-frame options altogether? 


error
Refused to display 'https://ha.example.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by inf0rmix** [comment] 2024-04-16 13:04
I have the same problem with the most current release

**Comment by erlendoyen** [comment] 2024-04-17 00:46
> I have the same problem with the most current release

hi, is it a local setup, you could add: 

http:
  use_x_frame_options: false

and if it's a proxy setup
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.204
    
    to ha config

**Comment by le0m** [comment] 2024-05-29 14:33
A note for anyone ending up here: deregister the web worker from your browser's dev tools after you have set `use_x_frame_options: false`, otherwise it will keep using the cached request with the `x-Frame-Options: SAMEORIGIN` header and you will still have the error.

**Comment by hesham1216** [comment] 2024-12-03 23:27
> A note for anyone ending up here: deregister the web worker from your browser's dev tools after you have set `use_x_frame_options: false`, otherwise it will keep using the cached request with the `x-Frame-Options: SAMEORIGIN` header and you will still have the error.

Man!!! can't thank you enough! 👌
