### ISSUE TITLE
Missing in lokalise "discharging", "none"

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#17366] opened 2023-07-20 13:29 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing two words in lokalise for translation
![1689858543227_discharging](https://github.com/home-assistant/frontend/assets/61636045/b82043f0-ef05-4442-b33f-8be4db4e05aa)

### Describe the behavior you expected

Add missing words to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.07.1

**Comment by frenck** [comment] 2023-07-20 13:38
I'm not sure what I am looking at @misa1515. Please provide me with the steps I need to take to get to this screen (in plain English).

../Frenck

**Comment by misa1515** [comment] 2023-07-21 08:39
@frenck you can found it in this submenu
Settings/Companion application (location and notifications)/Manage Sensors/

**Comment by karwosts** [comment] 2023-07-21 13:42
May be at least partially duplicate with #17205

**Comment by MickLesk** [comment] 2023-07-22 17:33
Yes, its a duplicate of my issue. Unfortunately, I have not yet been able to find a proper solution.

**Comment by frenck** [comment] 2023-07-22 17:52
Closing as a duplicate.

**Closed by frenck** 2023-07-22 17:52 UTC
