### ISSUE TITLE
Inconsistentie found in helpers

### ISSUE THREAD

**Issue by RoadXY** [home-assistant/frontend#15692] opened 2023-03-03 11:49 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Back button seems to be missing on several, but not all, helpers.
I.e.
![image](https://user-images.githubusercontent.com/3482284/222711607-8fe5de62-cdd4-473c-99a8-20b5bbcb4b5c.png)

A list of helpers missing the back button:
- Change device type
- Combine the state of several sensors
- Derivative sensor
- Group
- Riemann sum integral sensor
- Threshold Sensor
- Times of the Day Sensor
- Utility Meter

### Describe the behavior you expected

Every helper has a back button like this one:
![image](https://user-images.githubusercontent.com/3482284/222711607-8fe5de62-cdd4-473c-99a8-20b5bbcb4b5c.png)

### Steps to reproduce the issue

1. Go to settings, helpers, create helper
2. Select one helper from the list mentioned earlier an notice the absence of button in the bottom left corner which should contain the text 'back'

### What version of Home Assistant Core has the issue?

2023.3.0

### What was the last working version of Home Assistant Core?

Unknown

### In which browser are you experiencing the issue with?

Chrome 110.0.5481.178 (Official build) (64-bits), but also tried Edge and Chrome incognito

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
Nope
```

### Problem-relevant frontend configuration

```yaml
-
```

### Javascript errors shown in your browser console/inspector

```txt
-
```

### Additional information

-

**Comment by RoadXY** [comment] 2023-06-01 13:07
Unfortunately this 'issue' hasn't been resolved.

**Comment by karwosts** [comment] 2023-08-22 04:10
Duplicate of #12275

**Closed by karwosts** 2023-08-22 04:10 UTC
