### ISSUE TITLE
Time displays incorrectly throughout Home Assistant when in 12hr clock format.

### ISSUE THREAD

**Issue by Xerig** [home-assistant/frontend#16692] opened 2023-05-31 12:03 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the global time setting in Home Assistant is set to 12-hr it displays all times of the day correctly using AM/PM, with the only exception being midday. At midday Home Assistant displays the time as 0:58:28 pm, as seen here in the logbook: 
![image](https://github.com/home-assistant/frontend/assets/74830785/c043ddff-b1e3-42e5-998c-e23a15d56e86)

### Describe the behavior you expected

Expected behaviour would be to display the time as 12:58:28 pm in the example above, and changing all midday & midnight times to display as 12 instead of 0.

### Steps to reproduce the issue

1. Change time to 12hrs (AM/PM) in Profile -> Time Format
2. View the time at midday or midnight on any screen (I used the logbook for example, but History or other places also contain the issue)

### What version of Home Assistant Core has the issue?

core-2023.5.4

**Comment by christophwen** [comment] 2023-05-31 12:25
I will have a look into this issue soon.

**Comment by karwosts** [comment] 2023-06-05 21:49
Duplicate of #11891 ?

Also see https://community.home-assistant.io/t/wth-ha-energy-graph-should-be-12-00pm-not-00-00pm-for-midday/479342

**Comment by christophwen** [comment] 2023-06-06 04:46
> Duplicate of #11891 ?
> 
> Also see https://community.home-assistant.io/t/wth-ha-energy-graph-should-be-12-00pm-not-00-00pm-for-midday/479342

Yes, they seem to be duplicates. Thank you for pointing out. I am currently working on a fix (or rather testing my fix).

**Closed** 2023-06-20 10:52 UTC
