### ISSUE TITLE
Energy-Label in Settings is broken for german translation

### ISSUE THREAD

**Issue by pschneider87** [home-assistant/frontend#9712] opened 2021-08-04 15:58 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Label of Energy is set to [%key:ui::panel::config::energy::caption%] in German Translation, works for EN

![2021-08-04_17h57_02](https://user-images.githubusercontent.com/17707309/128213909-a69c821d-d379-450f-976e-bd0c9d63867b.png)

### Describe the behavior you expected

instead of [%key:ui::panel::config::energy::caption%] I would like to see "Energie"
![2021-08-04_17h58_52](https://user-images.githubusercontent.com/17707309/128214224-38fae4c4-4c06-41a8-bd7d-5e01de0a1b58.png)

### Steps to reproduce the issue

1. Set Language to German
2. Open Configuration
3. Scroll down to Energy-Entry
...

### What version of Home Assistant Core has the issue?

core-2021.8.0

### What was the last working version of Home Assistant Core?

core-2021.8.0b10

### In which browser are you experiencing the issue with?

Chrome 92

### Which operating system are you using to run this browser?

Win10

**Comment by bramkragten** [comment] 2021-08-04 16:05
Duplicate of #9708

**Closed by bramkragten** 2021-08-04 16:05 UTC
Labels: bug
