### ISSUE TITLE
Cast

### ISSUE THREAD

**Issue by Bluhme1** [home-assistant/frontend#5292] opened 2020-03-20 16:15 UTC
Tried to use an additional dashboard to cast to my Google Nest Max. Everything works concerning the views on the default dashboard but the views on the additional dashboard don’t show as an option on the google cast manager website

**Comment by bramkragten** [comment] 2020-03-20 16:59
You can use the Lovelace row <https://www.home-assistant.io/lovelace/entities/#cast>

**Comment by zsarnett** [comment] 2020-03-20 17:01
Closing as template was removed and this is not a bug but a feature request

**Closed by zsarnett** 2020-03-20 17:01 UTC
Labels: bug
