### ISSUE TITLE
Button Card "call service" tap action links to old entity ID for scripts

### ISSUE THREAD

**Issue by talormanda** [home-assistant/frontend#20826] opened 2024-05-19 18:55 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I am trying to use a Tap action for a button card to call a script. When I do this, it only shows results for entity IDs that the scripts were originally setup with. This means if I changed my script and manually edited the entity ID, it will no longer be visible.

### Describe the behavior you expected

I expect the entity ID to match what the script entity ID is after it is changed.

### Steps to reproduce the issue

1. Create a script, save
2. Re-open script, manually change entity ID, save
3. Create button card --> Tap action --> Call service --> only old entity ID of script shows up

### What version of Home Assistant Core has the issue?

core-2024.5.4

### In which browser are you experiencing the issue with?

Google Chrome 125.0.6422.61 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Additional information

![image](https://github.com/home-assistant/frontend/assets/10092964/841b984c-e808-4345-be65-dd3f7dc3790b)

**Comment by karwosts** [comment] 2024-05-20 16:37
Script service names aren't tied to the entity id, but the unique id of the script, which does not change when the entity id is modified. 

If you want to change the unique_id of the script, you can select the duplicate option to create a new script, and delete the original. That's the only way to change it short of manually editing the generated yaml file. 

Also this is duplicate of #14140

**Closed by karwosts** 2024-05-20 16:37 UTC
