### ISSUE TITLE
Include divider into visual entity editor

### ISSUE THREAD

**Issue by Fusseldieb** [home-assistant/frontend#4217] opened 2019-11-14 11:22 UTC
**Is your feature request related to a problem? Please describe.**
The divider is not available to select in the visual entity editor, forcing me to use the code editor, which doesn't have autocomplete, making it hard to remember sensor names and stuff.
![image](https://user-images.githubusercontent.com/4715129/68852944-a8438300-06b7-11ea-8e22-adb935519c17.png)

**Describe the solution you'd like**
I would like a button or something which inserts a divider on the end of these entities, which also has order sorting, like the others.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by Misiu** [comment] 2020-09-21 11:48
Duplicate of: https://github.com/home-assistant/frontend/issues/3851

Support for GUI editor for special rows would be awesome!

**Closed** 2020-09-21 13:32 UTC
Labels: feature request
