### ISSUE TITLE
The information displayed in the Area Cards for some device classes is wrong

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#20374] opened 2024-04-03 13:45 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Area Card can show certain information provided by sensors of specific device classes.
To do this, it is calculating the sum of all sensor values and dividing it to the amount of sensors in that area.

For example the temperature and humidity information.

BUT: it does use the same logic also for Power and Energy counters - which is, in my opinion not correct - as these information should ALWAYS show the total amount...

For example:
Area: Kitchen
- energy counter fridge: 230 kWh
- energy counter coffee-machine: 150 kWh
==> total: 380 kWh

Instead, the information will show a calculated value like 190 kWh

![image](https://github.com/home-assistant/frontend/assets/26391061/96416ad3-223f-4a34-8b35-8d0f36f0500e)
![image](https://github.com/home-assistant/frontend/assets/26391061/7abb68d1-df33-47f0-8af4-e3e3f770d535)
![image](https://github.com/home-assistant/frontend/assets/26391061/4aa495b8-03a1-4cdb-9672-cf1ce32f3abb)

### Describe the behavior you expected

the information for Energy / Power should only show the total consumtion, not divided by the amount of sensors.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.4.0b7

**Comment by karwosts** [comment] 2024-04-21 13:51
Duplicate of #20014

**Closed by karwosts** 2024-04-21 13:51 UTC
