### ISSUE TITLE
You cannot access the "App configuration" if you are not administrator

### ISSUE THREAD

**Issue by jlpouffier** [home-assistant/frontend#10924] opened 2021-12-14 22:25 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have users that are not admin in my home.
Since the last release, the "App config" link is nested under the main "Configuration" tab.
Non admin users do not have access to the configuration tab....

![signal-2021-12-14-23-19-01-855](https://user-images.githubusercontent.com/5878296/146088777-5c92cba9-7199-4584-a99a-be2038963a07.png)

### Describe the behavior you expected

Being able to access the config of your app as before.

### Steps to reproduce the issue

1. Create a non admin user
2. Download the app 
3. Try to configure anything.

### What version of Home Assistant Core has the issue?

2021.12

### What was the last working version of Home Assistant Core?

Any 2021.11

### Additional information

The new version is SO FREAKING SLOW.....
The config tab is barely usable

**Comment by spacegaier** [comment] 2021-12-14 22:40
Duplicate of https://github.com/home-assistant/frontend/issues/10894.

**Closed by spacegaier** 2021-12-14 22:40 UTC
Labels: bug
