### ISSUE TITLE
Remove repo doesn't work

### ISSUE THREAD

**Issue by r3mcos3** [home-assistant/frontend#5873] opened 2020-05-14 07:54 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Removing a repository from the add-on store doesn't work. 
Confirmed by @frenck 

I see nothing in the logs.

For me it wasn't working on latest stable 0.109.6 Burt also on beta 0.110.0b0 it isn't working

## Expected behavior

That the repo got deleted when pressing the trashcan.
## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment] 2020-05-14 08:29
Duplicate of <https://github.com/home-assistant/frontend/issues/5819>
You can find a workaround in that issue ☝️

**Closed by ludeeus** 2020-05-14 08:29 UTC
Labels: bug, supervisor
