### ISSUE TITLE
Can not create new or edit existing helpers.

### ISSUE THREAD

**Issue by maxwellsmonson** [home-assistant/frontend#16984] opened 2023-06-20 17:33 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I click add new helper nothing happens. A blank popup opens when trying to edit existing ones.

### Describe the behavior you expected

I would expect a pop up to open when I click new helper or try to open existing one.

### Steps to reproduce the issue

1. Go to helper section 
2. Click add new helper
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2023.6.2

**Comment by bramkragten** [comment] 2023-06-21 21:50
Duplicate of #16896

**Closed** 2023-06-21 21:50 UTC
