### ISSUE TITLE
Energydashboard stopped working ~4 o´clock

### ISSUE THREAD

**Issue by ohkaja** [home-assistant/frontend#21278] opened 2024-07-04 08:18 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Updated HA about 9 o´clock. After restart and check all works well. After looking in the energydashboard now, there are no data. Starting 4 o´clock.
<img width="350" alt="image" src="https://github.com/home-assistant/frontend/assets/93218188/830854d1-6e29-463b-8ad3-2cc12d1d826e">
<img width="350" alt="image" src="https://github.com/home-assistant/frontend/assets/93218188/26031f68-cfd2-441d-b9fb-ffa5c30b9a76">

Seems theres no Data collected between 4 a.m. and now. I only opend the energydashboard config to see whats wrong. After that he´s collecting again?! HA was not offline.
<img width="231" alt="image" src="https://github.com/home-assistant/frontend/assets/93218188/227fb4a9-3ba6-4efd-bec6-46c71b232805">

### Describe the behavior you expected

See the Energymeterings

### Steps to reproduce the issue

1.Update to 2024.7.0

### What version of Home Assistant Core has the issue?

2024.7.0

### What was the last working version of Home Assistant Core?

2024.6.4

### In which browser are you experiencing the issue with?

Microsoft Edge Version 126.0.2592.81 // iOS App

### Which operating system are you using to run this browser?

Windows 11 23H2 // iOS

### State of relevant entities

```txt
Entities working normal
```

**Comment by silamon** [comment] 2024-07-04 09:55
It looks to me that you've gotten the same bug discussed in [117263](https://github.com/home-assistant/core/issues/117263). Since we only represent the data what is given to us, there are no further actions we can take in the frontend, I'm going to close this.

**Closed** 2024-07-04 09:55 UTC

**Comment by ohkaja** [comment] 2024-07-04 10:15
You´re right. But this comes with update to 2024.07.0 as stated her: [https://github.com/home-assistant/core/issues/121164](121164).
I now know thats not fronted after diggig a bit deeper. Have to think first before i post. sry. :)

**Comment by fideias** [comment] 2024-07-08 08:22
Have the same issue, it all started at the same time with the latest update. 2024.07.0. After the latest update. The issue is mitigated with a restart. Need to do it Every day at the moment.  the Energy Usage does not update and when it does all the previous consumptions is merged to the Hour that the restart is happening.The mitigation is restarting the HA. 



![3](https://github.com/home-assistant/frontend/assets/1420257/41bd20ba-59c8-445b-855d-0f4b63b6051c)
![2](https://github.com/home-assistant/frontend/assets/1420257/dc082eec-3c9a-4af6-83e1-eec38b0fc223)
![ok](https://github.com/home-assistant/frontend/assets/1420257/975db492-f3cb-4717-9e27-170543ef0f64)
![1](https://github.com/home-assistant/frontend/assets/1420257/a0fce28d-726c-4dc0-b73e-6d572a2b7a2c)

**Comment by oh5lep** [comment] 2024-07-09 15:16
Same here. But not just energy card but all the data; HA frontend responses fine, but no data since 4 o'clock (local) until HA restart.
