### ISSUE TITLE
Calendar and Companion App

### ISSUE THREAD

**Issue by reotto613** [home-assistant/frontend#16219] opened 2023-04-17 16:28 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the IPhone Companion App, Safari and another user confirmed the issue on the Android Companion App I experience the following issue:

I have my calendar with 7 calendars from google calendar.

By accessing the calendar from the side menu on the web it works fine, shows all 7 calendars, all appointments and I can navigate away when I am done.

In the companion app on my iphone and ipad, if I access the calendar from the side menu it does NOT show the calendars (usually they are listed where you can check and uncheck them), it shows 0 appointments, and I am unable to navigate away from it no matter what I try.

To make matters worse no matter what I can including closing the app it always opens back up to the calendar. The only resolution I have found is to delete the app and reload it.

### Describe the behavior you expected

in Edge and Chrome on a Windows Desktop the calendars show up to the left of the calendar along with the sidebar and the 3 line menu. Without the sidebar and 3 line menu you can't navigate away.

### Steps to reproduce the issue

1. In Companion App (iOS or Andrioid) or Safari on iPhone, click the calendar in the side bar
2. Unable to navigate away.
3.
...

### What version of Home Assistant Core has the issue?

2023.4.0-4.4

### What was the last working version of Home Assistant Core?

2023.3.6

### In which browser are you experiencing the issue with?

Safari and Companion Apps

### Which operating system are you using to run this browser?

iOS 16.4.1

### Additional information

Previously logged under these tickets until further debugging narrowed it down:

[https://github.com/home-assistant/iOS/issues/2343](url)

[https://github.com/home-assistant/core/issues/91053](url)

**Comment by karwosts** [comment] 2023-04-17 16:57
probably duplicate of #15094

**Comment by ikeurb** [comment] 2023-04-28 17:18
Yes, the iOS app locks up when viewing the calendar view. Confirmed that spamming the top left corner during app load-in allowed me to select another view.

**Comment by allenporter** [comment] 2023-05-29 16:23
Tracking in #15094

**Closed by allenporter** 2023-05-29 16:23 UTC
