### ISSUE TITLE
thermostat card: no "dot" to change temperature

### ISSUE THREAD

**Issue by bartplessers** [home-assistant/frontend#15686] opened 2023-03-02 22:47 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Running 
Home Assistant 2023.3.0
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230301.0 - latest

I noticed that on my thermostat card, I can NOT change the temperature anymore, because the small "dot" is missing at the end of the line indicating the selected temperature:

![2023-03-02_23-42-00](https://user-images.githubusercontent.com/10470708/222576892-9fc21a49-4d2b-4202-84b9-12109299ff32.png)

### Describe the behavior you expected

I want my dot back :-)

### Steps to reproduce the issue

running latest version

### What version of Home Assistant Core has the issue?

Home Assistant 2023.3.0

### What was the last working version of Home Assistant Core?

Home Assistant 2023.2.x

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

win10

**Comment by ildar170975** [comment] 2023-03-02 22:54
Guys, plenty of issues about same. 
Don’t you use a “search” before creating an issue?)))

**Comment by steverep** [comment] 2023-03-03 01:03
Duplicate of #15662

**Closed** 2023-03-03 01:03 UTC

**Comment by ildar170975** [comment] 2023-03-03 22:39
Probably you were to overwhelmed by these changes)))
