### ISSUE TITLE
"Related" > "Part of the following..." (for scripts) missing links

### ISSUE THREAD

**Issue by xip0rt** [home-assistant/frontend#16992] opened 2023-06-22 04:07 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the Related dialog for a script entity, under the section of "Part of the following automations," it doesn't actually list any of the automations that call the script.

### Describe the behavior you expected

The "Related" dialog of a script should link to automations which have service calls to run said script, like when you open a light entity's Related dialog and it shows which automations and scripts have service calls controlling it.

This bug also extends to automations not listing other automations that call them, though that's a less common use case

### Steps to reproduce the issue

1. create a script that does anything (example, script.lightitup with a "service: light.turn_on" action)
2. create automation.callscript with "service: script.lightitup" action to previously created script
3. go to Related dialog for script.lightitup

it should say "Part of the following automations: automation.callscript" (but it doesn't)

### What version of Home Assistant Core has the issue?

2023.6.2

### In which browser are you experiencing the issue with?

Firefox 114

### Which operating system are you using to run this browser?

Windows 11

**Comment by spacegaier** [comment] 2023-06-27 07:35
I can confirm the issue, but I think that is a backend issue.

I also noted that in my case I do see related automations, but not the one that is explicitly calling the script, but other automations (and scenes) that use the light that I switched on with my test script.

**Comment by karwosts** [comment] 2023-06-27 18:32
Yeah, as we can see when we open this tab we call the 'search/related' API in core, and we get a response for which automations are related.

![image](https://github.com/home-assistant/frontend/assets/32912880/a088d36d-3ee2-4962-b3a7-04d3905b9860)

I will close this in that case since it seems nothing can be done in frontend, but please feel free to open an issue in home-assistant/core if you still want to see improvement.

**Closed by karwosts** 2023-06-27 18:32 UTC
