### ISSUE TITLE
Missing translation in lokalise - new automation - more words

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#19240] opened 2024-01-02 18:20 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hello,
found missing words in translation for lokalise (screenshots attached).

![Screenshot_NewAutomatiosation_DeviceAction](https://github.com/home-assistant/frontend/assets/61636045/ef1e4e12-da29-4c5f-9f6f-b8da5a619142)

![Screenshot_NewAutomatiosation_Other](https://github.com/home-assistant/frontend/assets/61636045/2a9e7295-2887-4331-8547-e239dc40895c)

### Describe the behavior you expected

Please add missing words to translation in lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.12.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment] 2024-01-03 01:29
Duplicate of #18358  and others.

**Closed by karwosts** 2024-01-03 01:29 UTC
