### ISSUE TITLE
Unable to change theme using the set_theme service

### ISSUE THREAD

**Issue by adr29truck** [home-assistant/frontend#6611] opened 2020-08-13 14:10 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Since updating to 0.114 and having called `frontend.set_theme` with 
```yaml
name: slate 
mode: dark
``` 
for my light/dark themes respectively calling the service `frontend.set_theme`  with for example `name: Default` no longer changes to the default theme.

I would assume that this is due to the OS setting overriding the users theme call in Home Assistant.
Meanwhile manually changing the theme in the frontend works as expected.

## Expected behavior

Calling `frontend.set_theme` regardless of OS state should change the current theme.
## Steps to reproduce

1. Call `frontend.set_theme` with the `mode` and `name` argument for both a light and a dark theme.
2. Try calling `frontend.set_theme` with the `name` argument
3. Nothing happens
## Environment

- Home Assistant release with the issue: 0.114
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Opera 68.0.3618.206, Firefox 77.0.1
- Operating system: Windows 10, Ubuntu 20.04

## State of relevant entities
Theme is set to Backend-selected.

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by ludeeus** [comment] 2020-08-13 14:12
When you do not give a "mode", it uses the default ("light"), if your OS is not using that mode, you will not see the change, and this will only be visible to you if you have it set to "Backend-Selected" in your user profile.

**Comment by adr29truck** [comment] 2020-08-13 14:20
OK, so you are unable to override the OS current mode unless also providing the current OS state as the `mode: `
Did I get that right?

I mean it would be useful to be able to change the theme on all devices without them depending on the OS to switch in addition to it being switched by the OS.

**Comment by ludeeus** [comment] 2020-08-13 14:45
Correct, there is a open bug for that #6572 so I guess this is a duplicate

**Comment by KTibow** [comment] 2020-09-13 00:15
Duplicate of #6572
(just for github auto-link)

**Closed** 2020-09-13 09:13 UTC
Labels: bug
