### ISSUE TITLE
Cannot view Frigate recording from media browser anymore

### ISSUE THREAD

**Issue by jasonwragg** [home-assistant/frontend#23005] opened 2024-11-26 14:11 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When trying to view recording or other Frigate media the front end gives errors: 

`Failed to load resource: the server responded with a status of 404 (Not Found):8123/api/hls/h78sf7s6fs78f6s78df6/playlist.m3u8?_HLS_msn=14845&_HLS_part=3:1 `
        
        
       

### Describe the behavior you expected

Media should play.

### Steps to reproduce the issue

1. try and play soemthing from Frigate recordings in the media browser
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.11.3

### What was the last working version of Home Assistant Core?

core-2024.10.4

### In which browser are you experiencing the issue with?

Google Chrome, MS Edge

### Which operating system are you using to run this browser?

Windows / Mac

**Comment by jasonwragg** [comment] 2024-11-26 14:11
Console errors:
![image](https://github.com/user-attachments/assets/aecb3771-cf6e-4171-b9f7-0b838ca2a012)

**Comment by silamon** [comment] 2024-11-26 16:40
Duplicate of https://github.com/home-assistant/frontend/issues/22755

**Closed by silamon** 2024-11-26 16:40 UTC
