### ISSUE TITLE
History graph card no longer displaying legends since update to 2022.12.0

### ISSUE THREAD

**Issue by e10kstarfire** [home-assistant/frontend#14656] opened 2022-12-08 19:02 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have multiple history graph cards that each are displaying multiple entities.

Prior to 2022.12.0 a legend would display on the card showing the entity and its associated color.

This functionality no longer works and no legends are displayed at all.

Probably related to https://github.com/home-assistant/frontend/pull/14546

### Describe the behavior you expected

Legends to display for a card with multiple entities

### Steps to reproduce the issue

1. Create history graph card containing multiple entities
2. Look at the created graph and note no legends displayed
3.
...

### What version of Home Assistant Core has the issue?

2022.12.0

### What was the last working version of Home Assistant Core?

2022.11.x

**Comment by spacegaier** [comment] 2022-12-08 21:20
Duplicate of https://github.com/home-assistant/frontend/issues/14610

**Closed by spacegaier** 2022-12-08 21:20 UTC
