### ISSUE TITLE
logbook, entities, devices, automations, script, helpers impossible to scroll on iOS 15.4 beta and macOS 12.3 beta

### ISSUE THREAD

**Issue by zadigre** [home-assistant/frontend#11675] opened 2022-02-13 16:10 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

logbook, entities, devices, automations, script, helpers impossible to scroll in the iOS app and Safari on iOS 15.4 beta 2 and macOS 12.3 beta 2.
Problem is also present in the latest Safari Technology Preview
works fine in Microsoft Edge on macOS. 
I tried on my wife's iPhone running iOS 15.3.1. works fine in the iOS app. I didn't try in Safari... but I guess it should work fine since both are essentially using the same libraries. 

No error are shown in the inspector

### Describe the behavior you expected

should scroll as expected

### Steps to reproduce the issue

1. open logbook (...) 
2. try to scroll 

### What version of Home Assistant Core has the issue?

core-2022.2.6

### In which browser are you experiencing the issue with?

Safari on iOS 15.4 beta 2 and macOS 12.3 beta

### Which operating system are you using to run this browser?

Macos 12.3 beta and iOS 15.4 beta 2

### Additional information

if I compare with the history pane (which is working fine), it looks like the frame or list dimensions are stuck to the windows size

**Comment by bramkragten** [comment] 2022-02-14 19:17
Duplicate of #11495

**Closed by bramkragten** 2022-02-14 19:17 UTC
Labels: bug
