### ISSUE TITLE
Unable to reactivate helpers created from the UI

### ISSUE THREAD

**Issue by KristianAndersson** [home-assistant/frontend#20518] opened 2024-04-14 20:09 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing
Unable to reactivate helper created from the UI because the specific helper settings are displayed when clicking on the helper in the list, rather than the "general settings" where you can reactivate the helper

Below a screen recording from the config/helpers section:
![unable_to_activate_deactivated_helper](https://github.com/home-assistant/frontend/assets/15807372/bb214310-ba8d-43f2-a62a-a7d4c7003358)

### Describe the behavior you expected

Ive would have expected the "general settings" window to open, enabling me to activate the helper again. (The same settings that is opened when clicking an active helper before it is deactivated)

### Steps to reproduce the issue

1. From the UI in the config/helpers section, create a new helper (I have tested and reproduced the error with the group, Riemann Integral sensor and utility meter helpers)
2. In config/helpers section, click the newly created helper. The "general settings" modal should open. Scroll down and flip the switch to deactivate the helper and press update.
3. Click the helper again. Now the setting specific to the helper is shown, and not the "general settings" allowing you to activate the sensor

### What version of Home Assistant Core has the issue?

2024.4.3

### In which browser are you experiencing the issue with?

Safari Version 16.6.1 (16615.3.12.11.5, 16615) and chrome Version 123.0.6312.124 (Officiel version) (x86_64)

### Which operating system are you using to run this browser?

macOS Big Sur 11.7.10

### Javascript errors shown in your browser console/inspector

No console errors or warnings shown

**Comment by karwosts** [comment] 2024-04-14 22:08
Duplicate of #20486

**Closed by karwosts** 2024-04-14 22:08 UTC
