### ISSUE TITLE
0.114.0 - Lovelace always asks to add a card to main view

### ISSUE THREAD

**Issue by snakuzzo** [home-assistant/frontend#6604] opened 2020-08-12 14:35 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When I open lovelace from web browser or from mobile app, popup appears and asks to add a new card to main view

## Expected behavior

No popup

## Steps to reproduce

 open lovelace on browser or mobile app 

## Environment

- Home Assistant release with the issue: 0.114.0
- Last working Home Assistant release (if known): 0.113.3
- Browser and browser version: 84.0.4147.125 (Official Build) (64-bit)
- Operating system: Ubuntu 20.x

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

![image](https://user-images.githubusercontent.com/7205371/90028059-86644480-dcb9-11ea-870e-23aa0ef63da4.png)

**Comment by SeanPM5** [comment] 2020-08-12 14:41
See https://github.com/home-assistant/frontend/issues/6526

This is an issue if you have card-tools installed, I believe that Thomas released an update for it a few days ago.

**Comment by ludeeus** [comment] 2020-08-12 15:11
Duplicate of #6526

**Closed by ludeeus** 2020-08-12 15:11 UTC
Labels: bug
