### ISSUE TITLE
Trend graphs don't work and stop working after a reboot

### ISSUE THREAD

**Issue by jjtoard** [home-assistant/frontend#21304] opened 2024-07-05 10:08 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Trend graphs don't work and stop working after a reboot.
If you click on a certain value to see the trend.  The trendline is frozen at a certain value and is not updating anymore.
After a restart it started working again but hours later the same thing happened.

### Describe the behavior you expected

should just work

### Steps to reproduce the issue

can't reproduce it.  Rebooted again and for now it works fine but is just an hour ago.  Yesterday it worked for multiple hours.
Strange thing it stopped twice at 4:11 AM  Will see again this night
![Untitled](https://github.com/home-assistant/frontend/assets/24300782/c065ea1a-6731-4000-a726-f4638e760fce)

### What version of Home Assistant Core has the issue?

latest

### What was the last working version of Home Assistant Core?

2024.6.6

### In which browser are you experiencing the issue with?

doesn't matter

### Which operating system are you using to run this browser?

windows

**Comment by silamon** [comment] 2024-07-05 11:23
This is a duplicate of https://github.com/home-assistant/core/issues/117263 .

**Closed** 2024-07-05 11:25 UTC
