### ISSUE TITLE
Latest Safari 16.4 (18615.1.21.11.5) on osx 13.3 Beta (22E5219e) issue

### ISSUE THREAD

**Issue by Rrapa** [home-assistant/frontend#15513] opened 2023-02-20 18:22 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When trying to edit Yaml code getting empty page where I should see editor window .. this happens after latest OSX update 

### Describe the behavior you expected

Yaml editor window should be visible

### Steps to reproduce the issue

1.Update OSX to latest public Beta
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

2023.2.5

### In which browser are you experiencing the issue with?

Safari 16.4 (18615.1.21.11.5)

### Which operating system are you using to run this browser?

Ventura 13.3 Beta (22E5219e)

**Comment by karwosts** [comment] 2023-02-21 02:48
duplicate of #15496?

**Comment by Rrapa** [comment] 2023-02-21 06:45
That case is about iOS not OSXWiadomość napisana przez karwosts ***@***.***> w dniu 21.02.2023, o godz. 03:48:﻿
duplicate of #15496?

**Comment by Rrapa** [comment] 2023-02-21 17:46
Yes, please :) it easier for me as I'm using Continuity option quite often ..

**Comment by piitaya** [comment] 2023-02-22 09:13
Yes it's a duplicate of #15496. I can reproduce the issue with Safari Developer Preview. Let's continue the discussion on the other issue.

**Closed by piitaya** 2023-02-22 09:13 UTC
Labels: Duplicate
