### ISSUE TITLE
Automation "edit in yaml" page blank

### ISSUE THREAD

**Issue by Lampornis** [home-assistant/frontend#15740] opened 2023-03-03 17:26 UTC
### The problem

I can create and edit automations just fine using the UI but when I switch to "edit in yaml" all I get is a blank screen.  Cannot say for certian but this could have occurred beginning in either 2023.2 or 2023.3.  I have check several of my current automations and the edit in yaml page is blank in all of them.  The yaml code does exist because it is present and can be edited in the automations.yaml file.  My HA instance runs on a RPi 4B, 4GB RAM.

### What version of Home Assistant Core has the issue?

2023.3.1

### What was the last working version of Home Assistant Core?

2023.2

### What type of installation are you running?

Home Assistant Supervised

### Integration causing the issue

Automation, edit in yaml

**Comment by karwosts** [comment] 2023-03-05 15:16
Are you on mac or IOS? 

https://github.com/home-assistant/frontend/issues/15496

**Comment by Lampornis** [comment] 2023-03-05 15:56
I use both MacOS and iOS.  The problem exists on both platforms.  It also exists regardless of whether I am using the apps or web interface on either platform.

Cheers,

Don

Don & Theo Powers
24600 NE Hummingbird Ct
Newberg, OR 97132
503-550-1579
***@***.***

**Comment by karwosts** [comment] 2023-03-05 15:58
Try Chrome on your Mac, see if that works. I believe I remember the issue is in Safari and in iOS apps.

**Comment by Lampornis** [comment] 2023-03-05 17:04
Interesting.  Well, that worked.  Can see the yaml code in Chrome.  Do not like to use Chrome but that is an option when I need to work on automations.  Thanks for the help.

Cheers,

Don

Don & Theo Powers
24600 NE Hummingbird Ct
Newberg, OR 97132
503-550-1579
***@***.***

**Comment by Lampornis** [comment] 2023-03-05 17:19
Also works in Firefox so this is clearly an issue related to Safari.

Cheers,

Don

Don & Theo Powers
24600 NE Hummingbird Ct
Newberg, OR 97132
503-550-1579
***@***.***

**Comment by piitaya** [comment] 2023-03-13 10:53
I close it as it's a duplicate of https://github.com/home-assistant/frontend/issues/15496

**Closed by piitaya** 2023-03-13 10:53 UTC
