### ISSUE TITLE
input_select dropdown wont show completely or scroll down

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#9416] opened 2021-06-14 09:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

the dropdown of an input_select wont scroll down in a Safari desktop window when it touches the bottom window

Chrome behaves fine

### Describe the behavior you expected

be able to scroll up/down

### Steps to reproduce the issue

1. click dropdown
2. try and scroll
3.
...

### What version of Home Assistant Core has the issue?

2021.6.4

### What was the last working version of Home Assistant Core?

Dk

### In which browser are you experiencing the issue with?

Safari desktop Mac

### Which operating system are you using to run this browser?

Big sur 11.2.3 Safari 14.0.3 

### State of relevant entities

```txt
not relevant
```

### Problem-relevant frontend configuration

```yaml
- type: entities
    title: Theme settings
    entities:
      - input_select.set_sunrise_theme
      - input_select.set_sunset_theme
      - sensor.sun_based_theme
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

![Jun-14-2021 11-18-41](https://user-images.githubusercontent.com/33354141/121869702-9b0ed000-cd02-11eb-8405-52f53dd42630.gif)

this is the full list of available themes the scroll wont allow to select:

<img width="471" alt="Schermafbeelding 2021-06-14 om 11 13 59" src="https://user-images.githubusercontent.com/33354141/121869734-a235de00-cd02-11eb-8355-8fa49b6ac363.png">

**Comment by Mariusthvdb** [comment] 2021-07-14 07:24
recent.y discovered  this same behavior also prevents scrolling the language drop down in the account pane

<img width="626" alt="Schermafbeelding 2021-07-14 om 09 22 47" src="https://user-images.githubusercontent.com/33354141/125580541-c2a53ec1-59cd-4d4b-89f8-397f933b42c9.png">

**Comment by spacegaier** [comment] 2021-10-01 06:53
I don't own any Apple devices, so I can only try on Windows.

=> I cannot reproduce this issue in dev with neither Firefox nor Chrome. The long dropdown menus always get a scrollbar here so I can access all entries without issue.

**Comment by Mariusthvdb** [comment] 2021-10-01 07:37
just checked it once more, with all updates, HA in the new beta 10, and Apples software to the latest both Mac OS and Safari:

<img width="462" alt="Schermafbeelding 2021-10-01 om 09 35 53" src="https://user-images.githubusercontent.com/33354141/135583069-a9e62613-138a-4711-b038-a3117924ef25.png">

no scroll bar, and we can not scroll the dropdown beyond the browser window

**Comment by Mariusthvdb** [comment] 2021-12-30 11:58
still happening, most frustrating issue. Ha 2022.2.0.dev20211230

**Comment by Mariusthvdb** [comment] 2022-02-06 14:23
keeping alive just to be sure. dev 2022.3

**Comment by bramkragten** [comment] 2022-02-06 19:28
This will be fixed soon (next week) by replacing them with mwc-select

**Comment by Mariusthvdb** [comment] 2022-02-16 20:04
Fixed!

Thanks, working beautifully.

Is the select box purposely themed differently from the drop down itself?

Had to set some theme variables to reinstate the regular coloring.

**Closed** 2022-04-22 06:56 UTC
Labels: Bug, safari

**Comment by pedolsky** [comment] 2022-05-04 06:07
Can the topic be reopened or should I raise a new issue? Input select lists are jumping back / invisible (iOS):


https://user-images.githubusercontent.com/71203830/166630227-a8914270-b7f6-437a-b866-4eb13f5b90ce.MOV

**Comment by emontnemery** [comment] 2022-05-04 06:10
@pedolsky Please open a new issue where you fill in all the details about your environment in the template 👍
