### ISSUE TITLE
input_datetime entry is not working as it should

### ISSUE THREAD

**Issue by ltjessem** [home-assistant/frontend#13315] opened 2022-08-01 08:52 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This issue has been bugging me for ages, it's brought up in  #1031 from 2018!! I'm surprised this hasn't been fixed for so long.
Setting a time on mobile is almost unusable.

> Each time I enter a number a `set_datetime` service is called. This is done each time I enter a number, either in the hours or minutes while I am not ready entering the complete time yet. Also after the service call is finished the ui loses focus and I need to re-focus and finish my input...

### Describe the behavior you expected

For time input to not lose focus on every input. For example to set the time to "12" I expect to be able to type:
"12"
not:
"1", refocus, "12"

### Steps to reproduce the issue

Already described

### What version of Home Assistant Core has the issue?

all

**Comment by steverep** [comment] 2022-08-17 00:49
Duplicate of #11861

I'll take a look at this soon. Please subscribe to the above issue.

**Closed** 2022-08-17 00:50 UTC
Labels: Duplicate
