### ISSUE TITLE
Automation frontend auto-selects wrong entity

### ISSUE THREAD

**Issue by tgpaul-ha** [home-assistant/frontend#13063] opened 2022-07-02 04:26 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have only found this problem in this particular context; it may exist elsewhere.

I have an automation with an If-Then action. I select the following options from the UI:

Condition type: `Numeric state`
Entity: `proximity.home` → auto-corrected to “Home”
Above: `0`

The problem is that the entity is actually getting changed to `zone.home`. Similarly I have an entity called weather.home which is incorrectly corrected to `zone.home`.

This cause a ton of confusion because these entities evaluate their states very differently, and was not obvious why it was failing.

Work-around is to Edit in YAML.

### Describe the behavior you expected

The correct entity is selected and retained.

### Steps to reproduce the issue

1. Ensure multiple entities with the same name but with different domains exist
2. Create an automation using the UI with an If-Then action
3. Select the entity with a shared name and observe that it is auto-corrected to the wrong entity (may have to try all of the devices with the shared name)
...

### What version of Home Assistant Core has the issue?

core-2022.6.7

**Comment by spacegaier** [comment] 2022-09-05 19:53
Sounds like a duplicate of https://github.com/home-assistant/frontend/issues/12889

**Closed by spacegaier** 2022-09-05 19:53 UTC
