### ISSUE TITLE
Integration names are not localized after refreshing the "Integrations" dashboard

### ISSUE THREAD

**Issue by acshef** [home-assistant/frontend#20489] opened 2024-04-10 22:52 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When navigating to the "Integrations" dashboard (https://my.home-assistant.io/redirect/integrations/), the names of all the integrations are properly localized (picture 1). If I refresh the page, the names are no longer localized (picture 2). This issue is not present if the "Disable cache" checkbox is checked in the browser's DevTools Network tab.

Picture 1:
![image](https://github.com/home-assistant/frontend/assets/9013284/3f1354c7-702e-423d-862f-74eb9f287b6b)

Picture 2:
![image](https://github.com/home-assistant/frontend/assets/9013284/ed5401c1-bba3-4453-9470-b8c824f1605e)

### Describe the behavior you expected

I expect the integrations names to be localized even after I refresh the page.

### Steps to reproduce the issue

1. Navigate to https://my.home-assistant.io/redirect/integrations/
2. Note that the integration names are localized
3. Refresh the page (F5), *make sure browser DevTools "Disable cache" is unchecked*
4. Note that the integration names are now **NOT** localized

### What version of Home Assistant Core has the issue?

2024.4.2

### In which browser are you experiencing the issue with?

Google Chrome 123.0.6312.106 (x64)

### Which operating system are you using to run this browser?

Windows 10 (x64)

### State of relevant entities

```txt
As long as there is some config-flow integration (e.g. Sun), this issue is observable.
```

### Problem-relevant frontend configuration

```yaml
N/A
```

**Comment by acshef** [comment] 2024-04-10 22:59
Possibly related to #20299, #20110

**Comment by karwosts** [comment] 2024-04-11 13:30
Duplicate of #20110

**Closed by karwosts** 2024-04-11 13:30 UTC
