### ISSUE TITLE
Energy Dashboarg: Not showing all data. BETA 2023.2.0b3

### ISSUE THREAD

**Issue by themiskir83** [home-assistant/frontend#15241] opened 2023-01-28 07:33 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the energy dashboard not all data are showing.
![Screenshot_20230128_092555](https://user-images.githubusercontent.com/40212435/215253117-09337a66-eb46-4616-b7b7-2673595150aa.png)

Energy usage is not showing tha data and it is not showing individual devices.

The same behavior is also and in the android companion app.

### Describe the behavior you expected

Showing the data as it supposed to do just like 2023.1

### Steps to reproduce the issue

1. Just updated to the latest version

### What version of Home Assistant Core has the issue?

2023.2.0b3

### What was the last working version of Home Assistant Core?

2023.1

### In which browser are you experiencing the issue with?

Google Chrome 109.0.5414.120

### Which operating system are you using to run this browser?

Windows 11

**Comment by Mick51** [comment] 2023-01-28 08:52
![Capture d’écran 2023-01-28 095043](https://user-images.githubusercontent.com/40418405/215256728-6bed3559-43f0-40ea-9fd9-928f81a0f652.jpg)
![Capture d’écran 2023-01-28 095007](https://user-images.githubusercontent.com/40418405/215256742-6fb6459a-dfd5-4f7c-890c-d0d334d12f23.jpg)
Same problem here, since beta 1 I have nothing....
Several days without energy dashboard and no one notices anything.....

**Comment by Mick51** [comment] 2023-01-28 10:14
You must specify Beta in the title so that the error is treated as a priority.  😉

**Comment by piio** [comment] 2023-01-28 10:19
I have exactly the same problem in 2023.2.0b3

**Comment by jurriaan** [comment] 2023-01-28 11:22
It's not only the graphs in the energy dashboard though. The history graphs in the more info/sensor dialogs are also missing for me.

**Comment by themiskir83** [comment] 2023-01-28 12:35
> It's not only the graphs in the energy dashboard though. The history graphs in the more info/sensor dialogs are also missing for me (like @Mick51 shows).

I confirm this. also the history graphs are not showing on the preview tab of each sensor. you must go to the history tab select date and time to show you the graph.

**Comment by Foroxon** [comment] 2023-01-28 13:11
Same for me since 2023.2.0b2

**Comment by FrancoLoco** [comment] 2023-01-28 13:42
Same here for several days and with all beta versions.. energy graphs and history graphs when clicking empty like others

**Comment by andrey-yantsen** [comment] 2023-01-28 14:36
Same for me; see the screenshot of the dev console log below. It was working fine on 2023.2.0.dev20230112 and became broken at least in 2023.2.0b0.

<img width="804" alt="image" src="https://user-images.githubusercontent.com/629281/215272291-8c2d9270-dc2c-47ec-be46-83284d8e07e2.png">

**Comment by karwosts** [comment] 2023-01-28 15:23
This has been noted several times, and is fixed in frontend branch, but no beta yet since b0 has updated the frontend package. Looks like one is being prepared for the next beta release though, hopefully in b4.

**Comment by Mick51** [comment] 2023-01-28 17:11
I hope it won't take several days, I use all these views on a daily basis, it's already starting to get long......

**Comment by thanomichalis** [comment] 2023-01-28 18:33
Same with me. In addition, all more info ent ities are not showing eny graphs. The same in system, when you select hardware.

Home Assistant 2023.2.0b3
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230125.0 - latest

**Comment by steverep** [comment] 2023-01-28 19:48
As @karwosts mentioned, this has been fixed and just hasn't hit the release yet.

**Comment by steverep** [comment] 2023-01-28 19:49
Duplicate of #15211

**Closed by steverep** 2023-01-28 19:49 UTC

**Comment by themiskir83** [comment] 2023-01-28 19:52
> Duplicate of #15211 

It's not a duplicate cause it's for a different beta version.
