### ISSUE TITLE
Name not shown for inactive entities in device view

### ISSUE THREAD

**Issue by eikowagenknecht** [home-assistant/frontend#11343] opened 2022-01-17 09:12 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the device page the names for inactive entities are now shown. See this animation for details:

![Animation](https://user-images.githubusercontent.com/1475672/149740256-7057adca-aeb0-4ae0-9f79-f269a4f38b71.gif)

### Describe the behavior you expected

Names are shown for all entities, active or inactive

### Steps to reproduce the issue

1. Disable one or more entities
2. Refresh device view (strg+f5)
3. Expand to see inactive entities

### What version of Home Assistant Core has the issue?

core-2021.12.9

### In which browser are you experiencing the issue with?

Chrome latest

### Which operating system are you using to run this browser?

Windows 10

### Javascript errors shown in your browser console/inspector

```txt
There is a console error as well, but only sometimes and I don't know if it's related:

![image](https://user-images.githubusercontent.com/1475672/149740468-1834a5de-141d-463c-b1ab-ff5a707d7cae.png)
```

**Comment by spacegaier** [comment] 2022-01-17 10:02
Duplicate of https://github.com/home-assistant/frontend/issues/10903 and https://github.com/home-assistant/frontend/issues/11067 plus already fixed in the current dev version.

**Closed by spacegaier** 2022-01-17 10:02 UTC
Labels: bug
