### ISSUE TITLE
Energy dashboard shows nonexistent energy flows in the 'Energy distribution' card

### ISSUE THREAD

**Issue by fencepost-error** [home-assistant/frontend#21326] opened 2024-07-07 11:19 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The 'Energy distribution' card shows nonexistent power flows, best illustrated via this screen shot:

![energy_card](https://github.com/home-assistant/frontend/assets/35447717/685aaf18-5169-4244-b248-025c1ee6f13e)

This shows energy flowing from the solar panels to the grid and the house, even though it's the middle of the night and the last solar production, shown in the 'Energy usage' card next to it, was around 5pm.  This is the out-of-the-box config with no customisation done apart from setting the sensors as per the [Enphase config page](https://www.home-assistant.io/integrations/enphase_envoy/).

### Describe the behavior you expected

As a sanity-check I installed Power Flow Card Plus, again the default out-of-the-box config, which shows:

![card_plus](https://github.com/home-assistant/frontend/assets/35447717/03e21211-d2b1-41c2-927e-0dff3a3e293e)

In this case only the flow from the grid to the house is shown, there are no nonexistent flows from the solar panels to the grid or house.

### Steps to reproduce the issue

1. Go to the Energy dashboard

At the moment I'm not sure what other information would be needed since this is the out-of-the-box config, but I can provide more details on any specific issues.

### What version of Home Assistant Core has the issue?

2024.7.1

### In which browser are you experiencing the issue with?

Firefox 127.0.2 (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by karwosts** [comment] 2024-07-07 19:15
It's not intended to be a realtime display, it simply reflects the time period that was selected. 

E.g. if you select an entire year of data, there will be a flow dot displayed if there was any transfer from solar to grid during that entire year, regardless of what is happening at that current moment.

**Comment by franstempelaars** [comment] 2024-07-07 20:13
I have the same kind of problem with the same HA version. The energy dashboard stops recording the graph at about 8.15 AM and only starts after a restart of home assistant. No idea why

**Comment by ChristophCaina** [comment] 2024-07-08 00:01
> I have the same kind of problem with the same HA version. The energy dashboard stops recording the graph at about 8.15 AM and only starts after a restart of home assistant. No idea why

the problem with the recorder stopped is different from the topic mentioned here and you should consider the following forum thread: https://community.home-assistant.io/t/psa-2024-7-recorder-problems/746428/1

**Comment by fencepost-error** [comment] 2024-07-08 04:07
> For a single day time period, the animation represents the amount of energy transfer that occured over the entire displayed day.

This seems rather misleading, if I just bring up the Energy dashboard without anything selected, i.e. no specific time period chosen, it shows flows that don't actually exist.  In particular if what it's showing is any flow that happened at any point in the last 24 hours/day then it may as well just animate all connectors all the time because there's bound to be some flow somewhere in the last 24 hours/day.

**Comment by fencepost-error** [comment] 2024-10-06 08:15
This issue is still present with the latest HA release, currently showing power coming off the solar panels in pitch blackness.

**Comment by karwosts** [comment] 2024-10-06 13:00
This is not a bug and will not be fixed, as I previously explained. 

Sorry if you don't like the current behavior, but if you want to advocate a change, please open a feature request on the community forum. But everything here is working as intended, so I will close this issue.

**Closed by karwosts** 2024-10-06 13:00 UTC
