### ISSUE TITLE
fonts.googleapis always gets contacted

### ISSUE THREAD

**Issue by merinleona** [home-assistant/frontend#5756] opened 2020-05-05 14:06 UTC
## Checklist

- [x ] I have updated to the latest available Home Assistant version.
- [x ] I have cleared the cache of my browser.
- [ x] I have tried a different browser to see if it is related to my browser.

## The problem

 I cannot get hassio to stop contacting google for fonts even though I have set a theme that uses System fonts only. It still always contacts fonts.googleapi to get the Roboto font.

## Expected behavior

 If I don't use google fonts, google should not get contacted.

## Steps to reproduce

  Apply theme with a different font.
Use Developer tools in Browser to see that Roboto still gets downloaded.

**Comment by ludeeus** [comment] 2020-05-05 14:09
duplicate of https://github.com/home-assistant/frontend/issues/4165

**Closed by ludeeus** 2020-05-05 14:09 UTC
Labels: bug
