### ISSUE TITLE
Minor color error in lamp card.

### ISSUE THREAD

**Issue by KentGitIvar** [home-assistant/frontend#15368] opened 2023-02-06 15:59 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When there is a lamp that don't have any change of color only brightness, the card icon get black.

The other lamps that at least have some kind of chnage in color or temperature will light up in color near the lamp color.

The more info icon is yellow as before only the card icon itself have changed.

This have come after upade to Home Assistant 2023.2.1.

No change after update to Home Assistant 2023.2.2.

URL:
https://www.home-assistant.io/dashboards/light/

Mvh Kent

### Describe the behavior you expected

An card icon that is yellow or similar.

### Steps to reproduce the issue

1. Create lamp card with a lamp that have only brightness changes.
2. Look at Card icon when lamp is on.
3.
...

### What version of Home Assistant Core has the issue?

core_2023.2.1

### What was the last working version of Home Assistant Core?

core_2023.1.7

### In which browser are you experiencing the issue with?

Firefox 1090.1 (64-bitars) and Google Chrome Version 109.0.5414.120 (Officiell version) (64 bitar)

### Which operating system are you using to run this browser?

Windows 10 22H2

### State of relevant entities

```txt
Entitet
light.ovre_datarum_hyllan_ikea_400lm_level_on_off
Övre datarum hyllan IKEA 400lm level, on_off

state = On

Attributes
supported_color_modes: brightness
color_mode: brightness
brightness: 166
off_with_transition: false
off_brightness: null
friendly_name: Övre datarum hyllan IKEA 400lm level, on_off
supported_features: 40
```

**Comment by karwosts** [comment] 2023-02-06 20:32
Duplicate of #15319?

**Closed** 2023-02-06 20:51 UTC
