### ISSUE TITLE
Sudden UI Freezing / Performance Issues

### ISSUE THREAD

**Issue by 503Dev** [home-assistant/frontend#18726] opened 2023-11-23 09:54 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Recently after the latest upgrade I am experiencing severe performance issues on the front end. Sometimes things are fine but after navigating between menus or dashboards for a few minutes there will be a sudden and noticeable slowdown and sluggishness. Eventually it will become unresponsive and I must refresh. If using the mobile app it will crash. After opening the app or refreshing the browser it is fine again (for a while). 

### Describe the behavior you expected

Normal performance. I've used HA for over a year in this setup and prior to this last update (could have been last few and I didn't notice) it was fine. 

### Steps to reproduce the issue

1. Open HA 
2. Casually navigate between menus / settings / pages for a few minutes 

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Chrome (latest), Edge, Mobile App (Android)

### Which operating system are you using to run this browser?

Windows 11, Chrome OS, Android 

### Additional information

This occurs regardless of my browser or OS. It happens in the mobile app too. It happens in stock and custom dashboards. 

The physical service does not have any resource spikes or issues. The host server is extremely overpowered for the application (it's an actual dedicated rack server with 60G of RAM and all storage is high speed and high quality SSD which all pass SMART).

**Comment by karwosts** [comment] 2023-11-23 16:38
I think I have seen this also, we discussed it some on discord 
https://discord.com/channels/330944238910963714/1171191308480679996

Seems possibly some kind of memory leak, but haven't pinned it down.

**Comment by 503Dev** [comment] 2023-11-23 16:45
Thank you. Indeed looks to be the same. I can't figure out why it happens. I disabled all the things I could. I even did a fresh install (I did restore a backup though so maybe that didn't help). 

I could not find anything to explain why and there are no real clues. I can reproduce it regularly on my setup though if that's any help. I am a professional software dev so if anyone needs me to capture any debug info or reproduce it I know the drill.

**Comment by aslabsalbeh** [comment] 2023-11-25 05:34
I'm having some sort of a similar issues which I posted about on HA community forum.

I’m struggling to find the source of the issue or learning where to look.

I’m running HA on a virtual machine on a Synology NAS. It was running fine for over a year and recently (around maybe 2 months ago) this started happening: Every time I edit an automation and hit save, the dashboard freezes and stops updating or reloading data. After about 1 minute, HA either restarts or starts responding and loading data again.

I'm able to reproduce this since it happens the moment I click the SAVE button inside an automation.

Do you think this is similar somehow to what you were experiencing? @503Dev

**Comment by 503Dev** [comment] 2023-11-25 14:30
@aslabsalbeh It could be. My issue is not always when I bit save but it does it sometimes when I hit save. In general the freezing you describe matches my issue. 

I also have the same scenario where I ran HA for a while, a long while with no issues and then this started seemingly suddenly. Logs and console are clean.

**Comment by Danm72** [comment] 2023-12-26 23:01
I'm still experiencing this issue, is there any information we could provide that would help?

**Comment by aslabsalbeh** [comment] 2023-12-26 23:59
> I'm still experiencing this issue, is there any information we could provide that would help?

After months of not knowing what was going on, I discovered that the .config folder has 20+ copies of the .config folder nested inside each other. 

This might have been caused by an addon. I'll be keeping an eye on it in the future. 

So once I deleted all the nest folders and kept the main .config folder, the issue was resolved!

Hope that helps.

**Comment by Danm72** [comment] 2024-01-04 09:29
In my case I figured out it was a few factors:
- Misconfigured frontend components
- heaps of chrome console errors
- Too many unused frontend add-ons being loaded

I think the primary issue for me was with card mod and bubble card, I was www/community instead of hacsfiles in my paths and for some reason this caused loading issues. Even though hacsfiles is a pointer to www/community.

🤷‍♂️

**Comment by sushibagel** [comment] 2024-01-31 06:21
> In my case I figured out it was a few factors:
> - Misconfigured frontend components
> - heaps of chrome console errors
> - Too many unused frontend add-ons being loaded
> 
> I think the primary issue for me was with card mod and bubble card, I was www/community instead of hacsfiles in my paths and for some reason this caused loading issues. Even though hacsfiles is a pointer to www/community.
> 
> 🤷‍♂️

Do you mind expanding on what you believe there issue was you encountered? I was just making a dash with card mod and bubble cards and it's made everything unbearably slow.

**Comment by karwosts** [comment] 2024-01-31 22:07
I'm going to mark this as closed as I don't believe there are any frontend issue currently being tracked here. 

I believe the original issue from OP has been resolved.

**Closed by karwosts** 2024-01-31 22:07 UTC
Labels: Performance
