### ISSUE TITLE
Re-Occurance of 20697 - Error while loading page lovelace. on 2024.6.0

### ISSUE THREAD

**Issue by grahamr** [home-assistant/frontend#21015] opened 2024-06-06 18:50 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

As with 2024.5.0, there is a code change causing issues with dashboards
This was fixed in https://github.com/home-assistant/frontend/pull/20741
looking at the code for https://github.com/home-assistant/frontend/blob/master/build-scripts/webpack.cjs the impacted lines appear to be back in the main branch

### Describe the behavior you expected

Dashboards on ios 12.5.7 devices no longer work

### Steps to reproduce the issue

1. update to the new version
2. load dashboard - expereince the error

### What version of Home Assistant Core has the issue?

2024.6.0

### What was the last working version of Home Assistant Core?

2024.5.5

**Comment by steveworkman** [comment] 2024-06-06 19:58
I get this too on 2024.6.0 on the same iOS 12 device. It appears to be trying to load some files from `unknown/node_modules` - I've included a zipped HAR file of this from my iPad.

[Uploading homeassistant.local.webarchive.zip…]()

**Comment by karwosts** [comment] 2024-06-06 20:08
I think this is duplicate of #21004

**Closed by karwosts** 2024-06-06 20:08 UTC
