### ISSUE TITLE
Markdown: No display with content from template returning int / float

### ISSUE THREAD

**Issue by koying** [home-assistant/frontend#9891] opened 2021-08-27 08:04 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Ref: https://community.home-assistant.io/t/markdown-card-is-acting-up/331718?u=koying

Nothing is displayed in a markdown card if the content resulting from a template is an in or float

### Describe the behavior you expected

Numbers are displayed

### Steps to reproduce the issue

Test card:

1. Displays nothing

```yaml
type: markdown
content: '{{ 23.75 }}'
title: Test numbers
````

2. Displays as expected:

```yaml
type: markdown
content: '{{ 23.75 }} eur'
title: Test numbers
```

### What version of Home Assistant Core has the issue?

2021.8.7

### In which browser are you experiencing the issue with?

Firefox 91.0.1

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment] 2021-11-25 12:17
I cannot reproduce the issue on Win 10 + Chrome or FF in the current dev version. So if there was an issue (potentially in the backend since that is where the templates are evaluated) it is probably fixed by now.

**Comment by koying** [comment] 2021-11-25 12:22
Still there for me in 2021.11.4

![image](https://user-images.githubusercontent.com/164740/143440787-2ca1168e-4333-4727-bd62-c3b6db5c6946.png)
![image](https://user-images.githubusercontent.com/164740/143440826-245a8037-203f-4f83-8c39-5b3219ff2fde.png)

![image](https://user-images.githubusercontent.com/164740/143440867-56ac4f44-26d0-4058-aa2c-83f3c238cd6f.png)
![image](https://user-images.githubusercontent.com/164740/143440901-f41d7a1d-d8b0-424a-b17d-29dadd743bef.png)

**Comment by spacegaier** [comment] 2021-11-25 16:58
Confirmed. I had just blindly copied your YAML as input into my markdown card. Then it of course works 🤦. PR is coming up.

**Closed** 2021-11-29 09:50 UTC
Labels: bug
