### ISSUE TITLE
Missing popup “save password on this browser”

### ISSUE THREAD

**Issue by niccolobusato** [home-assistant/frontend#5269] opened 2020-03-18 21:44 UTC
## The problem 

Missing popup “save password on this browser

## Environment

- Home Assistant release with the issue: Home Assistant 0.107.0
- Last working Home Assistant release (if known): i was on 0.105.5 never tested 0.106.x
- Operating environment (Hass.io/Docker/Windows/etc.): Hass.io
- Integration causing this issue: idk
- Link to integration documentation on our website: idk

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

**Comment by bramkragten** [comment] 2020-03-18 22:30
Duplicate of #5264

**Closed by bramkragten** 2020-03-18 22:30 UTC
