### ISSUE TITLE
2024.9.0b5 Fire OS - Home Assistant App Crashing

### ISSUE THREAD

**Issue by it00x32** [home-assistant/frontend#21879] opened 2024-09-04 11:02 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

on 2024.9.0b5 the Companion App is Crashing on a Fire OS Tablet (Webview Amazon v114). It seems it s related to dashboards using the section view and the WebView version of Fire OS (Fully Kiosk: same problem, Chrome: working)

### Describe the behavior you expected

no crash 

### Steps to reproduce the issue

1. call a dashboard using the section view on the companion app or fully kiosk on a fire os device
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.9.0b5

### In which browser are you experiencing the issue with?

Fire OS 7 / Webview 114

**Comment by Tykwondo1** [comment] 2024-09-04 23:44
same here

**Comment by zamansoum** [comment] 2024-09-05 03:15
Same as well. App crashing and entering reload loop when I try to open a dashboard with the section (experimental) layout on the firetablet

**Comment by alexpfau** [comment] 2024-09-05 06:01
Same issue here

**Comment by cgilis** [comment] 2024-09-05 07:44
Same here on a NSpanel pro

- Companion app
- Fully kiosk browser

Both are crashing

**Comment by silamon** [comment] 2024-09-05 08:16
So if you have a masonry view, it works? But from as soon as you go to a view with section layout, it crashes?

**Comment by Jordenjj** [comment] 2024-09-05 11:56
> So if you have a masonry view, it works? But from as soon as you go to a view with section layout, it crashes? Does it reproduce if you have an empty section layout (no cards)?

I cannot confirm whether it happens with empty sections (at work) but yes. Masonry works, my sections dashboard is broken.

**Comment by cupertinomiranda** [comment] 2024-09-05 15:05
I also confirm this bug leaked into 2024.09.0 stable version.

**Comment by nguyenquyhy** [comment] 2024-09-06 03:06
I can confirm that the bug happens with an empty section view. All the other layouts work.

**Comment by tima2k6** [comment] 2024-09-06 06:05
Download webview beta and make sure you switch to that.

I’ve had no issues with A9 since 2024.9, but my A8 has struggled. Downloading the Webview Beta  and switching to that has helped my A8 immensely.

**Comment by Jordenjj** [comment] 2024-09-06 07:18
Is that possible for devices that can solely install apk's via ADB?

**Comment by EvanMulawski** [comment] 2024-09-06 23:41
Can confirm this is still present in 2024.9.1 w/ Fire OS 7.3.2.9 (WebView v114) - the latest version for Fire OS 7 devices. Rolled back to 2024.8.3.

**Comment by Tykwondo1** [comment] 2024-09-07 15:43
I have two fire tablets and they are on my IoT network where I block the internet so my tablets were not up to date. So I connected the tablets to my network with the internet and checked the updates, there were 24, I did the manual updates by pushing the update button several times until zero. I put my table back on my network without internet, relaunch Fully Kios Browser, AND VOILA

**Comment by silamon** [comment] 2024-09-07 16:11
I'm going to close this as a duplicate of #21900. Please subscribe there to follow updates.

**Closed by silamon** 2024-09-07 16:11 UTC
