### ISSUE TITLE
ViCare integration setup UI is broken

### ISSUE THREAD

**Issue by bmgit26** [home-assistant/frontend#10958] opened 2021-12-17 12:45 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

@oischinger
@oischinger:vicare_config_flow

The vicare integration setup UI just shows input fields without any labels.

![Screenshot from 2021-12-17 13-33-53](https://user-images.githubusercontent.com/3626088/146546587-f1e52e57-5a43-4487-ba83-31999faf10b6.png)

### Describe the behavior you expected

The vicare integration setup UI  shows input fields withinput fields labelled.

### Steps to reproduce the issue

1. add new integration
2. select vicare

### What version of Home Assistant Core has the issue?

core-2021.12.2

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Version 96.0.4664.110 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

debian 11

**Comment by spacegaier** [comment] 2021-12-17 14:05
Duplicate of https://github.com/home-assistant/core/issues/61561.

**Closed by spacegaier** 2021-12-17 14:05 UTC
Labels: bug
