### ISSUE TITLE
Cannot access Settings->System

### ISSUE THREAD

**Issue by Stooovie** [home-assistant/frontend#13734] opened 2022-09-14 08:38 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After clicking "System", I get a blank page on all my devices, browsers and apps.

### Describe the behavior you expected

Be able to access Settings->System

### Steps to reproduce the issue

1. Go to Settings
2. Click System

### What version of Home Assistant Core has the issue?

2022.9.3

### What was the last working version of Home Assistant Core?

2022.9.2

### In which browser are you experiencing the issue with?

Edge, Chrome, Safari, HA app

### Javascript errors shown in your browser console/inspector

```txt
typography.js:181 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-card.ts:5:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
i @ typography.js:181
value @ ha-card.ts:5
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
t.firstUpdated @ card-mod.js?hacstag=190927524315:5
_$AE @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
F @ ha-menu-button.ts:11
n @ ha-dialog.ts:24
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
A @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
F @ ed9a6da7.js:1
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-list-item.ts:7
E @ typography.js:181
t @ typography.js:181
value @ hass-loading-screen.ts:11
value @ hass-loading-screen.ts:11
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
value @ app-drawer-layout.js:189
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
t @ home-assistant.ts:32
(anonymous) @ home-assistant.ts:32
i @ typography.js:181
s @ typography.js:181
value @ ha-navigation-list.ts:50
handleEvent @ styles.ts:370
notifyAction @ mwc-list-base.ts:270
setSelectedIndexOnAction_ @ eb39b60a.js:2
handleSingleSelection @ eb39b60a.js:2
onRequestSelected @ mwc-list-base.ts:270
handleEvent @ styles.ts:370
fireRequestSelected @ mwc-list-item-base.ts:224
onClick @ mwc-list-item-base.ts:224
cb @ 25f1190c.js:2
9typography.js:181 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-card.ts:5:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
i @ typography.js:181
value @ ha-card.ts:5
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
t.firstUpdated @ card-mod.js?hacstag=190927524315:5
_$AE @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
F @ ha-menu-button.ts:11
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
A @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
F @ ed9a6da7.js:1
E @ typography.js:181
t @ typography.js:181
p @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
o @ styles.ts:370
b @ styles.ts:370
w @ styles.ts:370
r @ ha-list-item.ts:7
E @ typography.js:181
t @ typography.js:181
value @ hass-loading-screen.ts:11
value @ hass-loading-screen.ts:11
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
value @ app-drawer-layout.js:189
value @ hass-loading-screen.ts:11
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
k @ styles.ts:370
_$AI @ styles.ts:370
m @ styles.ts:370
T @ styles.ts:370
_$AI @ styles.ts:370
S @ styles.ts:370
update @ styles.ts:370
performUpdate @ styles.ts:370
scheduleUpdate @ styles.ts:370
_$EC @ styles.ts:370
await in _$EC (async)
requestUpdate @ styles.ts:370
set @ styles.ts:370
t @ home-assistant.ts:32
(anonymous) @ home-assistant.ts:32
i @ typography.js:181
s @ typography.js:181
value @ ha-navigation-list.ts:50
handleEvent @ styles.ts:370
notifyAction @ mwc-list-base.ts:270
setSelectedIndexOnAction_ @ eb39b60a.js:2
handleSingleSelection @ eb39b60a.js:2
onRequestSelected @ mwc-list-base.ts:270
handleEvent @ styles.ts:370
fireRequestSelected @ mwc-list-item-base.ts:224
onClick @ mwc-list-item-base.ts:224
cb @ 25f1190c.js:2
:8123/config/system:1 
        
       Unchecked runtime.lastError: The message port closed before a response was received.
```

**Comment by ludeeus** [comment] 2022-09-14 08:38
Duplicate of https://github.com/home-assistant/frontend/issues/13728

**Closed by ludeeus** 2022-09-14 08:38 UTC
