### ISSUE TITLE
Energy dashboard desktop layout is only using 50% width of browser

### ISSUE THREAD

**Issue by ahlstromanton** [home-assistant/frontend#18517] opened 2023-11-02 21:28 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All the cards in the energy dashboard is using a total of 50% of the width of the viewport.

This can be mitigated somewhat by resizing the browser window past mobile breakpoint and back, but when refreshing or changing day to view, the issue comes back.

![image](https://github.com/home-assistant/frontend/assets/58640347/b965a297-7286-4685-bb45-55795751794c)

### Describe the behavior you expected

The energy dashboard should utilize all of the space in the viewport width-wise.

### Steps to reproduce the issue

Open the energy dashboard in desktop view.

### What version of Home Assistant Core has the issue?

2023.11.0

### What was the last working version of Home Assistant Core?

2023.10.x

### In which browser are you experiencing the issue with?

Chrome, Brave, Firefox

### Which operating system are you using to run this browser?

Win 11

**Comment by ildar170975** [comment] 2023-11-02 21:34
Do you have card-mod installed?

**Comment by karwosts** [comment] 2023-11-03 05:02
Duplicate of #18514

**Closed** 2023-11-03 05:02 UTC
