### ISSUE TITLE
The options aren't showing completely in the actions tab of the choose action

### ISSUE THREAD

**Issue by crispy78** [home-assistant/frontend#12205] opened 2022-04-03 06:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![image](https://user-images.githubusercontent.com/42983001/161414306-2a421d23-e5ae-446b-bb2c-31583bc19ef6.png)

When I create an automation and use the choose option, within the actions-tab the options of an instance aren't showing completely as shown in the screenshot.

### Describe the behavior you expected

The options-tab is showing completely in all other parts of the choose-action, so I'd expect it to behave the same for the actions-tab.

### Steps to reproduce the issue

1. Set screen resolution to 1920 x 1080
2. Select the default theme in HassIO
3. Create an automation and use the choose option and add an action
4. Click on the three dots on the right that you use to run, edit, duplicate or delete that action.

### What version of Home Assistant Core has the issue?

core-2022.3.8

### In which browser are you experiencing the issue with?

Microsoft Edge Version 100.0.1185.29 (Official build) (64-bit), Firefox 89.0 (64bit), Firefox 98.0.2 (64bit)

### Which operating system are you using to run this browser?

Microsoft Windows 10 21H2

**Comment by spacegaier** [comment] 2022-04-03 14:21
Duplicate of https://github.com/home-assistant/frontend/issues/12032

**Closed by spacegaier** 2022-04-03 14:21 UTC
