### ISSUE TITLE
Dutch translations yield errors

### ISSUE THREAD

**Issue by martinvanbuuren** [home-assistant/frontend#8616] opened 2021-03-11 07:38 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

During various actions in the UI, I get errors of the type:
Translation Error: The into string context variable "naam" was not provided to the string 
    "Bijwerken van {naam} naar versie {versie}".

### Describe the behavior you expected

I suspect that {naam} must have been {name}, {versie} should be {version}, etc. A translator also translated the placeholders/tags.

### Steps to reproduce the issue

1. Install the Dutch language pack and activate it.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.3

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by spacegaier** [comment] 2021-03-11 07:42
Duplicate of https://github.com/home-assistant/frontend/issues/8550 and https://github.com/home-assistant/frontend/issues/8569.

Translations are already fixed in dev.

**Closed by spacegaier** 2021-03-11 07:42 UTC
Labels: bug
