### ISSUE TITLE
Automations confuse entities with same friendly name (but different entity id)

### ISSUE THREAD

**Issue by hofst** [home-assistant/frontend#14443] opened 2022-11-20 10:36 UTC
### The problem

I have entities that have the same friendly name (but obviously different and unique entity ids).
The reason why they have the same friendly name is to have less cluttered dashboards but this is irrelevant for the issue.
Automations confuse those entities which creates very annoying bugs. 

**Here is how to repro it:**
- Choose two different entities and give them the same friendly name "test-entity" and different entity ids ("test-entitity-1" and "test-entity-2")
- Add a new automation -> add trigger -> state -> add "test-entity-2"
- Switch from visual editor to yaml editor and verify that "test-entity-2" has correctly been added to the trigger
- Switch back to visual editor, click on the entity name so it will open the entity selector list. It will now highlight "test-entity-1" which is false. But not only that, if you now click outside of the entity list to abort, it will apply the change and save the wrong entity.

Obviously there is some code in the entity selector list that is based on the friendly name instead of the entity id and that just picks the lexicographically first entity which is a wrong implementation.
This behavior reproes for me in the "state trigger" but not, e.g., in the "numeric state" trigger. When you have found the erroneous code, please double-check that there aren't more places that share this bug.

### What version of Home Assistant Core has the issue?

20221108.0 - latest

### What was the last working version of Home Assistant Core?

Has been there for at least half a year

### What type of installation are you running?

Home Assistant Core

**Comment by hofst** [comment] 2023-02-22 06:34
still a bug

**Comment by hofst** [comment] 2023-05-28 13:10
still a bug

**Comment by ildar170975** [comment] 2023-07-11 01:33
@hofst 
I am not sure this issue still valid - seems that entities are NOT selected at all after reopening the automation.
https://github.com/home-assistant/frontend/issues/13692#issuecomment-1629952508
So, there is an issue now - but not exactly the same that you described...

**Comment by ildar170975** [comment] 2023-07-21 14:26
Seems to be a common problem: https://github.com/home-assistant/frontend/issues/16179

**Comment by karwosts** [comment] 2023-07-23 15:04
Closing this as a duplicate of #13692, will try to consolidate this issue there.

**Closed** 2023-07-23 15:04 UTC
