### ISSUE TITLE
Energy Dashboard Some parts are not displaying correctly - missing data

### ISSUE THREAD

**Issue by princzkeljanos** [home-assistant/frontend#15236] opened 2023-01-27 12:23 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open Energy Dashboard, the "Energy Usage", "Solar production" and "Monitor individual devices" section showing no data, just the title of the section.
![image](https://user-images.githubusercontent.com/6016442/215084941-feb28fae-43de-4c2d-8f1b-10e74149be4c.png)
![image](https://user-images.githubusercontent.com/6016442/215084973-1f328132-66e1-4158-9e48-d06c43d4244f.png)
[13o7pfw9j6jkndx9hnd49y71ldqhwzgk.ui.nabu.casa-1674821998598.log](https://github.com/home-assistant/frontend/files/10518746/13o7pfw9j6jkndx9hnd49y71ldqhwzgk.ui.nabu.casa-1674821998598.log)
![image](https://user-images.githubusercontent.com/6016442/215086159-dd2696ee-a2f6-4a1c-909c-e88874d11700.png)

### Describe the behavior you expected

Wan to see data in these sections.

### Steps to reproduce the issue

1.Open "Energy" dashboard

### What version of Home Assistant Core has the issue?

2023.2.0b2

### What was the last working version of Home Assistant Core?

2023.1.X (not the beta)

### In which browser are you experiencing the issue with?

Google Chrome (109.0.5414.120), Edge, Apple iPhone HomeAssistant App

### Which operating system are you using to run this browser?

Windows 11, iOS

### Javascript errors shown in your browser console/inspector

```txt
typography.js:181 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at d.value (ha-chart-base.ts:134:1)
    at d.update (styles.ts:372:1)
    at d.performUpdate (styles.ts:372:1)
    at d.scheduleUpdate (styles.ts:372:1)
    at d._$Ej (styles.ts:372:1)
```

**Comment by frenck** [comment] 2023-01-27 12:32
duplicate of #15211

**Closed by frenck** 2023-01-27 12:32 UTC
