### ISSUE TITLE
Integrations not visible when using Norwegian language (Norsk Bokmål)

### ISSUE THREAD

**Issue by GunnarBjoru** [home-assistant/frontend#5695] opened 2020-05-01 20:40 UTC
## The problem

When I use Norwegian language (Norsk Bokmål) I get the information that nothing is configured yet in Integrations (Configuration, Integrations). But if I change to English, Sweedish and even the other Norwegian language (Norsk Nynorsk) I can see all my Integrations.

## Environment

- Home Assistant Core release with the issue: 0.110.0.dev20200501
- Last working Home Assistant Core release (if known): 0.109 dev
- Operating environment (Home Assistant/Supervised/Docker/venv): Running HA in Proxmox
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `configuration.yaml`

```yaml

```

## Traceback/Error logs

```txt

```

## Additional information

Frontend-versjon: 20200427.1 - latest

Supervisor:
Version | 220
Channel | dev

Host system:
System | HassOS 4.5
Deployment | development

**Comment by bramkragten** [comment] 2020-05-02 11:24
Duplicate of https://github.com/home-assistant/frontend/issues/5662

**Closed by bramkragten** 2020-05-02 11:24 UTC
