### ISSUE TITLE
Slider bar missing on iOS 15.8 - ERROR [frontend.js.latest.202310302]

### ISSUE THREAD

**Issue by Antipodn** [home-assistant/frontend#18691] opened 2023-11-18 01:18 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

All slider controls on HA App for iOS15 are missing their control bar, after HA upgrade. I believe it's a frontend issue.
Only these slider elements are displayed: Icon, Name and current Value.
Every instance produces an error in the logs, when the relevant dashboard is displayed.
They appear and operate correctly on Windows Firefox 119.0.1 (64-bit) and Edge 119.0.2151.58 (Official build) (64-bit), before and after cache's cleared.

### Describe the behavior you expected

To have the sliders visible.

### Steps to reproduce the issue

Open a dashboard containing a standard slider control on iOS15.2 or similar.
Look in the home-assistant.log file for the related error.

### What version of Home Assistant Core has the issue?

Core 2023.11.2

### In which browser are you experiencing the issue with?

HA App on iOS15.2

### Which operating system are you using to run this browser?

iOS 15

### State of relevant entities

Example from: input_number.set_sg_max_soc

State: 85

```
Attributes:
initial: null
editable: false
min: 50
max: 100
step: 1
mode: slider
friendly_name: Set Max SoC
```

### Problem-relevant frontend configuration

yaml
Here is an example of my HA YAML configuration. 

```
input_number:
  set_sg_min_soc:
    name: Set Min SoC
    min: 0
    max: 50
    step: 0.1
    mode: slider

  set_sg_max_soc:
    name: Set Max SoC
    min: 50
    max: 100
    step: 0.1
    mode: slider
```

### Javascript errors shown in your browser console/inspector

This is the error from the HA logs after viewing in iOS.
There are no errors when displayed on PC based browsers, neither in HA logs or in inspector.

```
2023-11-17 10:20:13.254 ERROR (MainThread) [frontend.js.latest.202310302] Uncaught error from WebKit 605.1.15 on iOS 15.8
TypeError: Cannot instantiate a custom element inside its own constructor during upgrades HTMLElement ([native code]::)
construct ([native code]::)
y (src/scoped-custom-element-registry.js:173:6)
super (src/reactive-element.ts:930:4)
A (src/lit-element.ts:115:)
super (slider.ts:256:4)
_ (::)
F (src/components/ha-slider.ts:6:39)
c (src/scoped-custom-element-registry.js:390:8)
a (src/scoped-custom-element-registry.js:236:20)
```

### Additional information

The HA Environment is:
    Core 2023.11.2
    Supervisor 2023.11.3
    Operating System 11.1
    Frontend 20231030.2

Image of iOS screen area.
![IMG_1503](https://github.com/home-assistant/frontend/assets/151280658/10099c40-d6dc-404c-b368-e44e262e1ee7)

**Comment by karwosts** [comment] 2023-11-18 01:31
Duplicate of #18600, and the fix is already in for next release.

**Closed by karwosts** 2023-11-18 01:31 UTC

**Comment by Antipodn** [comment] 2023-11-18 01:34
Thank you! Gosh, I will have to improve my search skills because that obvious duplicate didn't come up, after an extensive GitHub, Google and HA search.
