### ISSUE TITLE
Top navigations shows arrows when not needed. 

### ISSUE THREAD

**Issue by sco0ts** [home-assistant/frontend#16521] opened 2023-05-13 01:20 UTC
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using HA companion app on iOS. The arrows show at top when they are not needed. When I click them. They go away. 
![IMG_2132](https://github.com/home-assistant/frontend/assets/36104678/e290a0a4-f6c9-4f0a-8f52-89aab1031e1f)
![IMG_2133](https://github.com/home-assistant/frontend/assets/36104678/3265c018-5b61-4340-ae35-fbf09ae3348e)

### Describe the behavior you expected

The arrows would not show at all. 

### Steps to reproduce the issue

See my images. 
made that many icons to top bar. 
open app
press arrow

### What version of Home Assistant Core has the issue?

2023.5.2

**Comment by ildar170975** [comment] 2023-05-13 14:05
Seems to be same https://github.com/home-assistant/frontend/issues/16091

**Comment by karwosts** [comment] 2023-06-24 19:25
Closing as duplicate of #16091

**Closed by karwosts** 2023-06-24 19:25 UTC
