### ISSUE TITLE
No placeholder is shown for missing custom_components device

### ISSUE THREAD

**Issue by and7ey** [home-assistant/frontend#20799] opened 2024-05-15 17:26 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If no image is defined for custom component (in accordance with https://github.com/home-assistant/brands description), then HA shows wrong picture:
<img width="350" alt="image" src="https://github.com/home-assistant/frontend/assets/900474/b18bc932-0d99-4f36-87e6-26fa17c88145">

<img width="1139" alt="image" src="https://github.com/home-assistant/frontend/assets/900474/b631ae2c-1c59-4bd3-98bb-69da66b37841">

### Describe the behavior you expected

when I add custom component, then correct image "Icon not available" is shown:

<img width="367" alt="image" src="https://github.com/home-assistant/frontend/assets/900474/5c6ad675-14e3-4ef8-83d4-ea60cf8b2238">

### Steps to reproduce the issue

1. create new custom component
2. add it to HA
3. login/add device
4. go to device screen

### What version of Home Assistant Core has the issue?

2024.5.3

**Comment by and7ey** [comment] 2024-05-15 17:44
the problem exists both for light and dark modes

**Comment by steverep** [comment] 2024-05-16 12:11
Duplicate of #18106

**Closed by steverep** 2024-05-16 12:11 UTC
