### ISSUE TITLE
dropdown for zwave nodes configuration goes beyond to of window

### ISSUE THREAD

**Issue by fondberg** [home-assistant/frontend#6353] opened 2020-07-09 18:36 UTC
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem
Dropdown for zwave nodes beyond the top of the window when having a lot of nodes

![Screenshot 2020-07-09 at 20 07 10](https://user-images.githubusercontent.com/10739838/87077700-d320af80-c223-11ea-88cd-5321ed16a3d5.png)

## Expected behavior
The first nodes should appear and a scrolling down and up should work.

## Steps to reproduce
Kind of hard but add more than 20-25 zwave nodes and click the nodes dropdown  

## Environment
Home Assistant 0.112.4

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by bramkragten** [comment] 2020-07-09 20:14
Duplicate of #6322

**Closed by bramkragten** 2020-07-09 20:14 UTC
Labels: bug
