### ISSUE TITLE
Gauge card Pointer not working proper with Safari 15. ...

### ISSUE THREAD

**Issue by criticallimit** [home-assistant/frontend#10983] opened 2021-12-20 15:43 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Pointer in the Gauge Card is not working properly when Safari (15.2) is used .
On MacOS and IOS it is shown, but when Value is rising Pointer is moving out of Sight.

On iPados with older Safari it is working properly.

![Bildschirmfoto](https://user-images.githubusercontent.com/5613811/146793855-e1f56ac4-20ce-4a73-b5be-78289f838818.jpg)

![Bildschirmfoto](https://user-images.githubusercontent.com/5613811/146794253-4dac66f5-4b7c-4b1b-8e77-963ddcd86632.jpg)

### Describe the behavior you expected

.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.12.2

### What was the last working version of Home Assistant Core?

dont know

**Comment by spacegaier** [comment] 2021-12-20 17:59
Duplicate of https://github.com/home-assistant/frontend/issues/10910

**Closed by spacegaier** 2021-12-20 17:59 UTC
Labels: bug
