### ISSUE TITLE
New Thermostat is not working properly

### ISSUE THREAD

**Issue by Ferrox85** [home-assistant/frontend#19042] opened 2023-12-14 13:35 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It slows down the gui and even freezes it in both safari and chrome
The new thermostat gives an error in the console. I switched to an other thermostat card (better thermostat) no issues anymore.

### Describe the behavior you expected

No lagg

### Steps to reproduce the issue

1. Add a themostat entity to an empty dashboard
2.look in the console
3.
...

### What version of Home Assistant Core has the issue?

2023.12.2

### What was the last working version of Home Assistant Core?

2023.11

### In which browser are you experiencing the issue with?

Safari Versie 17.1.2 (19616.2.9.11.12) / chrome Versie 120.0.6099.109 (Officiële build) (arm64)

### Which operating system are you using to run this browser?

macOS sanoma 14.1.2 

### State of relevant entities

```txt
They are off.
```

### Javascript errors shown in your browser console/inspector

```txt
Safari:
[Error] Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.
	performUpdate (app.otA1ToECPHw.js:2:142696)
	(anonieme functie) (app.otA1ToECPHw.js:2:142209)

Chrome:
Uncaught (in promise) DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty. home assistant
```

**Comment by karwosts** [comment] 2023-12-14 16:11
Possible  duplicate of #18999 ?

**Comment by Ferrox85** [comment] 2023-12-14 16:45
Yes it is. Thanks. I thought when writing this it was an other problem, but I see the same issue after all.

**Comment by karwosts** [comment] 2023-12-14 17:33
Closing as duplicate.

**Closed by karwosts** 2023-12-14 17:33 UTC
