### ISSUE TITLE
New MWC component for entering input_datetime updates entity too eagerly when typing.

### ISSUE THREAD

**Issue by nikipore** [home-assistant/frontend#11945] opened 2022-03-05 09:52 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I try to enter a two-digit hour (say, 10) and don't type the "10" ultra-fast, the new MWC field will update the `input_datetime` entity to "1:00" instead of "10:00". I can workaround by

1. trying to enter a two digit hour several times until I've typed fast enough,
2. first entering the second digit and then prefixing the first digit "1".

Both approaches trigger (generally unwanted) updates of the entity with a wrong time.

Tried Chrome and Safari on an up-to-date Mac and the HA app on iOS.

### Describe the behavior you expected

I expect that either the entity update is less eager (say, lazy for 250~500 ms) or only triggered upon an explicit submit (pressing ENTER, focus leaving the field or so).

### Steps to reproduce the issue

1. Add an `input_datetime` entity which has time to Lovelace frontend.
2. Enter "10" in the hour field, typing somewhat slowly.
3. The entity will update the hour of the entity to "1" and lose focus of the input field.

### What version of Home Assistant Core has the issue?

core-2022.3.1

### What was the last working version of Home Assistant Core?

core-2022.2.x

### In which browser are you experiencing the issue with?

Google Chrome 99.0.4844.51

### Which operating system are you using to run this browser?

macOS 12.2.1

**Comment by emufan** [comment] 2022-03-11 07:36
Can second this. Unusable on e.g. iPhone. To enter a two-digit minutes, currently I have to try up to 10 times, fast, slow, enter one digit, e.g. 3, then focus is lost and it is shown as 03, then select 0, delete 0, move cursor behind 3 and enter 0. And all this, if the focus is not lost again in the meantime. Unusable.

**Comment by MuellerNicolas** [comment] 2022-03-24 15:07
> yes, same here. I only have this issue in the app so i'd put this issue in the android app github page. I do not see this behaviour in the chrome browser

I've the issue too. But I also have it on the Chrome Browser of my Smartphone. I already opened a ticket on the android project, but this led me here...

**Comment by emufan** [comment] 2022-05-11 17:13
Any news on this? On iPad or iPhone, you cannot type two-digits into such fields. Sometimes in the xth try. Even in Vivaldi it is happening on Windows:

I think it is dependent if there was a two digit input before. If yes, it is loosing focus after entering only one. If no, it is working most of the time to enter two.

30 minutes -> trying to enter 31 results in 03
03 minutes -> trying to enter 31 is mostly working

10 hours -> trying to add 11, resultes in 1
1 hours -> trying to add 11  is mostly working

**Comment by MuellerNicolas** [comment] 2022-05-12 06:11
> Any news on this? On iPad or iPhone, you cannot type two-digits into such fields. Sometimes in the xth try. Even in Vivaldi it is happening on Windows:
> 
> I think it is dependent if there was a two digit input before. If yes, it is loosing focus after entering only one. If no, it is working most of the time to enter two.
> 
> 30 minutes -> trying to enter 31 results in 03
> 03 minutes -> trying to enter 31 is mostly working
> 
> 10 hours -> trying to add 11, resultes in 1
> 1 hours -> trying to add 11  is mostly working

Yes, I have the same problem. On first try it adds a zero, if you retry it with the same first number, you can add the second one, just like it should.

**Comment by liquidacid** [comment] 2022-05-12 06:43
yea i have this same thing too, i got used to it actually :) Just try twice to add a double digit time first the first digit and then both

**Comment by emufan** [comment] 2022-08-11 19:50
Still not usable on mobile.

**Comment by steverep** [comment] 2022-08-17 00:31
Duplicate of #11861

**Closed** 2022-08-17 00:33 UTC
Labels: Duplicate

**Comment by steverep** [comment] 2022-08-17 00:35
Please subscribe to the duplicate referenced. I'll take a look soon.
