### ISSUE TITLE
Even build-in cards display as single column starting 0.110

### ISSUE THREAD

**Issue by mirekmal** [home-assistant/frontend#6013] opened 2020-05-24 07:28 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Expected behavior

Initial loading of view with several card displays them in single column, while there is enough space to wrap cards into more. Previously this type of behavior was linked to custom cards (especially stack-in cards), but now it appears olso to build in ones.
It is, however, not persistant, if page gets reloaded, cards get properly ordered in view.

## Steps to reproduce

Create a view with 4 large picture element cards.

## Environment

- Home Assistant release with the issue: 0.110.1 (but started on 0.0110)
- Last working Home Assistant release (if known): 0.109
- Browser and browser version: Safari (OS X), Chrome (OS X, Windows)
- Operating system: OS X, Windows

## State of relevant entities

YAML code of entire view (removed some repeating entities to shorteen, but basic structure retained)
```yaml
  - badges: []
    cards:
      - elements:
          - entity: binary_sensor.presence_30
            style:
              '--paper-item-icon-active-color': red
              '--paper-item-icon-color': '#BFBFBF'
              left: 49%
              top: 86%
            tap_action:
              action: none
            type: state-icon

        ...........

        image: /local/attic.png
        type: picture-elements

      - elements:
          - entity: binary_sensor.presence_34
            style:
              '--paper-item-icon-active-color': red
              '--paper-item-icon-color': '#BFBFBF'
              left: 26%
              top: 37%
            tap_action:
              action: none
            type: state-icon

        ..............

        image: /local/first-floor.png
        type: picture-elements

      - elements:
          - entity: binary_sensor.presence_34
            style:
              '--paper-item-icon-active-color': red
              '--paper-item-icon-color': '#BFBFBF'
              left: 26%
              top: 37%
            tap_action:
              action: none
            type: state-icon

        ..............

        image: /local/ground-floor.png
        type: picture-elements

      - elements:
          - entity: binary_sensor.presence_34
            style:
              '--paper-item-icon-active-color': red
              '--paper-item-icon-color': '#BFBFBF'
              left: 26%
              top: 37%
            tap_action:
              action: none
            type: state-icon

        ..............

        image: /local/basement.png
        type: picture-elements


    icon: 'mdi:motion-sensor'
    panel: false
    path: presence
    title: PRESENCE
```
Screenshow of initially loaded view:
![Screenshot 2020-05-24 at 08 26 18](https://user-images.githubusercontent.com/6892816/82748057-3e5f1100-9d9f-11ea-8d05-6cd1130f0875.png)

Screenshot of the same view after page reload (and how it should load initially):
![Screenshot 2020-05-24 at 09 18 28](https://user-images.githubusercontent.com/6892816/82748101-8d0cab00-9d9f-11ea-93c7-9acd393ae04a.png)

## Problem-relevant configuration

 As listed in point above.
```yaml

```

## Javascript errors shown in your browser console/inspector

N/A
```txt

```

## Additional information
Issue is even more inconsistent when custom cards are used (especially custom:stack-in-card or custom:vertical-stack-in-card), that causes vie not to load properly randomly or permanently (no cache cleanup, page reloading etc helps, but sometimes pages loads properly). It also seems inconsistant between browsers; below creenshots of the same page with custom elements loaded in Safari (1st picture) and Chrome (2nd picture), same OS, with the same size of browser window, after reloading page:
 
![Screenshot 2020-05-24 at 09 25 34](https://user-images.githubusercontent.com/6892816/82748261-ceea2100-9da0-11ea-85c2-93ea384017c8.png)

![Screenshot 2020-05-24 at 09 25 48](https://user-images.githubusercontent.com/6892816/82748271-d6112f00-9da0-11ea-8d0b-2ee369be3b27.png)

**Comment by bramkragten** [comment] 2020-05-24 07:34
We are working on a better solution for 0.111, but I restored the behavior of 0.109 in 0.110.2

**Comment by mirekmal** [comment] 2020-05-24 08:09
Great, thank you!
Is there any chance for custom cards to behave correctly (as it was prior to 0.107, I think), or it is in hands of cards developers to get this working correctly and adjust to new lovelace design?
It is quite serious issue, as now the only solution to put the cards where we want to is to use 'custom:layout-card', which forces to wrap everything into one card, making it not editable in UI and hard to maintain in yaml mode (lots of code in one piece)... My biggest view with everything wrapped into 'custom:layout-card' is almost 1100 lines of code (while it should be divided into 10 separate cards) :-)

**Comment by bramkragten** [comment] 2020-05-24 08:32
Please see below issue.

Duplicate of https://github.com/home-assistant/frontend/issues/5321

**Closed by bramkragten** 2020-05-24 08:32 UTC
Labels: bug
