### ISSUE TITLE
Beta 2023.2.0b1 empty energy dashboard

### ISSUE THREAD

**Issue by MOST2K2** [home-assistant/frontend#15222] opened 2023-01-26 17:29 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the beta update today i get an empty energy dashboard, see screenshot.

### Describe the behavior you expected

A working dashboard with bar charts.

### Steps to reproduce the issue

1. Configure energy dashboard
2. After some time open energy dashboard

See screenshot of broken energy board.
![image](https://user-images.githubusercontent.com/3817309/214906000-9b252af8-15a5-4625-9b96-08ed30f2b50a.png)

### What version of Home Assistant Core has the issue?

Home Assistant 2023.2.0b1 Supervisor 2023.01.1 Frontend 20230125.0 - latest

### What was the last working version of Home Assistant Core?

Previous beta was working, updated this morning

### Which operating system are you using to run this browser?

Ubuntu 22 and Android 13

**Comment by frenck** [comment] 2023-01-26 17:37
Duplicate of #15211

**Closed by frenck** 2023-01-26 17:37 UTC
