### ISSUE TITLE
History-Graph timeline sometimes not showing different colors for unique states

### ISSUE THREAD

**Issue by tylerpieper** [home-assistant/frontend#9554] opened 2021-07-12 21:38 UTC
I have a template sensor that is gathering the current state of each thermostat (idle, heating, cooling). Up until now, each state would show a different color on the history graph card, but now each state shows the same color, making it very hard to read. 

The card in question:
![image](https://user-images.githubusercontent.com/54639597/125359219-d1019d00-e31e-11eb-85e8-ef8bd3826db6.png)

The YAML for the card:
```
type: history-graph
entities:
  - entity: sensor.upstairs_hvac_status
    name: Upstairs
  - entity: sensor.downstairs_hvac_status
    name: Downstairs
  - entity: sensor.hvac_duty
    name: Combined
hours_to_show: 2
refresh_interval: 0
```

The two sensors in question (within Sensors.yaml) (I know I should be using state_attr):
```
- platform: template
  sensors: 
    downstairs_hvac_status:
      friendly_name: "Downstairs HVAC Status"
      value_template: '{{ states.climate.downstairs.attributes.hvac_action }}'
- platform: template
  sensors: 
    upstairs_hvac_status:
      friendly_name: "Upstairs HVAC Status"
      value_template: '{{ states.climate.Upstairs.attributes.hvac_action }}'
```

And the state attributes of one of the thermostats (climate.downstairs) (they are both identical):
```
hvac_modes:
  - 'off'
  - heat
  - cool
  - heat_cool
min_temp: 50
max_temp: 90
current_temperature: 77
temperature: 77
hvac_action: idle
friendly_name: Downstairs Thermostat
supported_features: 1
```
The thermostats are Honeywell Lyrics controlled via Homekit Controller. The hvac_action can be idle, cool, or heat (at least with my HVAC configuration).

_Originally posted by @tylerpieper in https://github.com/home-assistant/frontend/issues/9495#issuecomment-875826241_

Since I submitted via my comment on another issue, it appears I have bypassed the form. I will complete it below:
**I have updated to the latest available Home Assistant version. 
I have cleared the cache of my browser. 
I have tried a different browser to see if it is related to my browser.** 

**Describe the issue you are experiencing:** The history graph card sometimes does not use a different color for each state in a timeline. For example, monitoring my HVAC status, I'll see states of "cool" and "idle" throughout the day, but the graph will show the same light blue for both.

**Describe the behavior you expected:** I would expect the card will be rendered with a unique color for each unique state, so they can be easily differentiated.

**Steps to reproduce the issue:** 
1. Log into Home Assistant (I'm using the Nabu Casa cloud access)
2. View a dashboard with a history-graph card that shows a timeline
3. Sometimes you get different colors for each state, sometimes they are all blue

**What version of Home Assistant Core has the issue?** Previously 2021.7.0 but I just updated to 2021.7.1 and will close if it resolves this. 

**What was the last working version of Home Assistant Core?** 2021.6.x, before the overhaul of the history-graph card

**In which browser are you experiencing the issue with?** Google Chrome 91.0.4472.124

**Which operating system are you using to run this browser?** Windows 10 21H1

**Comment by tylerpieper** [comment] 2021-07-12 22:15
Re-confirmed that the issue occurs in 2021.7.1 on Chrome, Edge, and Firefox.

**Comment by tylerpieper** [comment] 2021-07-12 23:17
Here's what the card looks like when it does decide to load correctly: 
![image](https://user-images.githubusercontent.com/54639597/125367206-96066600-e32c-11eb-9349-a89609a6ef94.png)

Sometimes rebooting the server fixes the card, sometimes a refresh of a page breaks it.

**Comment by bramkragten** [comment] 2021-07-13 09:49
Rebooting the server will not be the thing fixing this, the refresh probably does.

Can you share the result of the history API call? You can find this in the network section of the browser dev tools (something like: `/api/history/period/2021-07-13T07:00:00Z?end_time=2021-07-13T10:00:00Z&minimal_response&filter_entity_id=...`)

**Comment by tylerpieper** [comment] 2021-07-13 15:48
@bramkragten here's the full response with the rendering malfunctioning. I'll see if I can coax it into rendering correctly and grab it again. This was an incognito window, fresh login, no cache all that and it loaded incorrectly.
`[[{"entity_id": "sensor.upstairs_hvac_status", "state": "cooling", "attributes": {"friendly_name": "Upstairs HVAC Status"}, "last_changed": "2021-07-13T13:43:53.718000+00:00", "last_updated": "2021-07-13T13:43:53.718000+00:00"}, {"state": "idle", "last_changed": "2021-07-13T13:49:26.033241+00:00"}, {"state": "unknown", "last_changed": "2021-07-13T14:33:49.519848+00:00"}, {"entity_id": "sensor.upstairs_hvac_status", "state": "idle", "attributes": {"friendly_name": "Upstairs HVAC Status"}, "last_changed": "2021-07-13T14:34:13.641413+00:00", "last_updated": "2021-07-13T14:34:13.641413+00:00"}], [{"entity_id": "sensor.downstairs_hvac_status", "state": "idle", "attributes": {"friendly_name": "Downstairs HVAC Status"}, "last_changed": "2021-07-13T13:43:53.718000+00:00", "last_updated": "2021-07-13T13:43:53.718000+00:00"}, {"state": "cooling", "last_changed": "2021-07-13T13:44:43.118647+00:00"}, {"state": "idle", "last_changed": "2021-07-13T13:50:23.113458+00:00"}, {"state": "cooling", "last_changed": "2021-07-13T14:21:23.104448+00:00"}, {"state": "idle", "last_changed": "2021-07-13T14:27:23.102580+00:00"}, {"state": "unknown", "last_changed": "2021-07-13T14:33:49.519783+00:00"}, {"state": "idle", "last_changed": "2021-07-13T14:34:13.641251+00:00"}, {"entity_id": "sensor.downstairs_hvac_status", "state": "cooling", "attributes": {"friendly_name": "Downstairs HVAC Status"}, "last_changed": "2021-07-13T15:42:55.081113+00:00", "last_updated": "2021-07-13T15:42:55.081113+00:00"}], [{"entity_id": "sensor.hvac_duty", "state": "True", "attributes": {"friendly_name": "hvac_duty"}, "last_changed": "2021-07-13T13:43:53.718000+00:00", "last_updated": "2021-07-13T13:43:53.718000+00:00"}, {"state": "False", "last_changed": "2021-07-13T13:50:23.113899+00:00"}, {"state": "True", "last_changed": "2021-07-13T14:21:23.105044+00:00"}, {"state": "False", "last_changed": "2021-07-13T14:27:23.103032+00:00"}, {"state": "unknown", "last_changed": "2021-07-13T14:33:49.522426+00:00"}, {"state": "False", "last_changed": "2021-07-13T14:34:13.651191+00:00"}, {"entity_id": "sensor.hvac_duty", "state": "True", "attributes": {"friendly_name": "hvac_duty"}, "last_changed": "2021-07-13T15:42:55.082139+00:00", "last_updated": "2021-07-13T15:42:55.082139+00:00"}]]`

**Comment by bramkragten** [comment] 2021-07-13 17:46
Do you use any custom cards (with graphs?)

**Comment by tylerpieper** [comment] 2021-07-13 17:48
No. The only custom card I'm using at the moment is https://github.com/custom-cards/button-card, and that's on a different tab of this dashboard.

**Comment by tylerpieper** [comment] 2021-07-14 17:43
Still occurring in 2021.7.2

**Comment by tylerpieper** [comment] 2021-07-14 17:44
In case it wasn't clear, it appears that this issue only is occurring for certain sensors for me. Other sensors' history graphs render just fine, like the state of my MyQ garage door:
![image](https://user-images.githubusercontent.com/54639597/125668162-9faacd63-9d6b-472a-970d-2ce9cff721a8.png)

**Comment by bramkragten** [comment] 2021-08-07 10:07
I am still not able to reproduce

**Comment by eyager1** [comment] 2021-08-11 22:13
I am having the exact same issue with a template sensor that performs the same function as the OP.  I was getting the same blue on blue issue

The "idle" state appears to have a hard coded color by default of #377eb8
https://github.com/home-assistant/frontend/blob/dev/src/resources/ha-style.ts

But the first color in the index for non-hardcoded colors is also #377eb8
https://github.com/home-assistant/frontend/blob/dev/src/common/color/colors.ts

I thought I could outsmart it by changing the color in a custom theme I use.

```state-idle-color: "#fe4ee7"```

Which resulted in something completely unexpected, the color for the cooling state changed as well.  Why such a similar shade of pink was chosed for the result is unknown.

![idle_graph](https://user-images.githubusercontent.com/44526531/129106515-f16de86c-e4d4-4db1-9375-df15af91848c.png)

Later by hitting F5, the color suddenly switched back to what was expected.  

![idle_graph_2](https://user-images.githubusercontent.com/44526531/129109254-d95ac1a7-a3ea-4e3a-a204-95fc522bcd55.png)

I don't know if the fix for this issue is simply changing the default idle state color to something that won't collide with an automatically chosen state color, or there is also a strange rendering bug as well.

**Comment by bramkragten** [comment] 2021-08-13 19:10
thanks for that info @eyager1 really helpful!

**Closed** 2021-08-16 03:45 UTC
Labels: element: chart
