### ISSUE TITLE
Card Button not showing

### ISSUE THREAD

**Issue by leofig-rj** [home-assistant/frontend#16173] opened 2023-04-13 14:04 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The card "button" is not showing anything after installing Home Assistant 2023.4.3 (Frontend: 20230411.0).

### Describe the behavior you expected

My screens are no longer working as they came up to version 2023.4.2

### Steps to reproduce the issue

1. Insert a button card in Dashboard.

### What version of Home Assistant Core has the issue?

2023.4.3

### What was the last working version of Home Assistant Core?

2023.4.2

**Comment by FuzzyMistborn** [comment] 2023-04-13 14:08
Dupe of https://github.com/home-assistant/frontend/issues/16172

**Comment by frenck** [comment] 2023-04-13 16:36
This has been fixed in Home Assistant 2023.4.4, please upgrade.

**Closed by frenck** 2023-04-13 16:36 UTC

**Comment by leofig-rj** [comment] 2023-04-13 18:57
Fixed!
Thanks
