### ISSUE TITLE
Profile Page - Primary/Accent colour text is clipping into the selection box

### ISSUE THREAD

**Issue by declan1080** [home-assistant/frontend#18727] opened 2023-11-23 10:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When using Firefox to view the profile page it is showing the primary and accent colour text clipping into the colour picker box.

### Describe the behavior you expected

In Chrome the text is alligned correctly as shown below:
![image](https://github.com/home-assistant/frontend/assets/150525624/b05e4f16-9091-4bc6-95e6-27202df49f58)

In Firefox the text is misalligned
![image](https://github.com/home-assistant/frontend/assets/150525624/d4a2e4e9-bf18-43fb-837c-1c0b5c9e8c90)

### Steps to reproduce the issue

1. Navigate to HA on Firefox.
2. Navigate to the profile tab.
3. Scroll down to the primary/accent colour section.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### In which browser are you experiencing the issue with?

Firefox - 120.0

### Which operating system are you using to run this browser?

Windows 11 - 23H2 22631

**Comment by karwosts** [comment] 2023-11-23 16:27
Duplicate of #17524

**Closed by karwosts** 2023-11-23 16:27 UTC
