### ISSUE TITLE
device_class battery icons not displaying percentage battery icons anymore in Hassio V 2021.10.5 - always display mdi:battery "full battery" icon

### ISSUE THREAD

**Issue by peterhoe** [home-assistant/frontend#10303] opened 2021-10-16 20:26 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

noticed that my battery icons all display full battery icons rather than displaying different battery icons depending on state of charge

appeared to have changed when updating to 2021.10.5?

These were working in 2021.9.X

behaviour also seen in mobile app & browser Chrmoe & edge

Entity
sensor.modbus_ss_charge_level
 
State
11

State attributes (YAML, optional)

1 unit_of_measurement: '%'
2 friendly_name: Battery Charge
3 device_class: battery

![battery-icon-state](https://user-images.githubusercontent.com/36558013/137601330-09fcef02-5136-4925-8bbd-145cf082961e.jpg)

### Describe the behavior you expected

battery icons change depending on state of battery charge 

eg
used to display mdi:battery-10 mdi:battery-20 mdi:battery-30 etc
depending on state of charge in %

### Steps to reproduce the issue

update to 2021.10.5 from 2021.9.x

### What version of Home Assistant Core has the issue?

2021.10.5

### In which browser are you experiencing the issue with?

Google Chrome Version 94.0.4606.81 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

windows 10

### State of relevant entities

```txt
Entity
sensor.modbus_ss_charge_level
 
State
11

State attributes (YAML, optional)

1 unit_of_measurement: '%'
2 friendly_name: Battery Charge
3 device_class: battery
```

**Comment by spacegaier** [comment] 2021-10-16 20:28
Duplicate of https://github.com/home-assistant/frontend/issues/10245 and I already fixed that in dev via https://github.com/home-assistant/frontend/pull/10246.

**Closed by spacegaier** 2021-10-16 20:28 UTC
Labels: bug
