### ISSUE TITLE
climate.set_temperature and media_player.volume_set templates get wiped out from the new GUI

### ISSUE THREAD

**Issue by Chreece** [home-assistant/frontend#8577] opened 2021-03-07 11:12 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you have a template for the above services and you edit the automation/script the data gets wiped out, the save button appers

### Describe the behavior you expected

The data shouldn't be wiped out.

### Steps to reproduce the issue

1. Use template on one of the above services for automation or script
2. Open the automation or script to edit edit
3. The issue comes up
...

### What version of Home Assistant Core has the issue?

core-2021.3.0

### What was the last working version of Home Assistant Core?

core-2021.2.3

### In which browser are you experiencing the issue with?

Google Chrome 89.0.4389.82

### Which operating system are you using to run this browser?

Windows 10 19041.804

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by estevez-dev** [comment] 2021-03-07 11:24
Looks like a duplicate of #8561

**Comment by spacegaier** [comment] 2021-03-07 11:33
@Chreece Can you please share the involved automation so we can check if it is indeed the same issue as in #8561 (so related to a numeric attribute).

**Comment by Chreece** [comment] 2021-03-07 16:01
of course:
`
- service: climate.set_temperature
        data:
          temperature: '{{ states("input_number.heizung_temperature_zuhause") }}'
        target:
          entity_id: climate.wohnzimmer_thermostat
`

`    - service: media_player.volume_set
      data:
        volume_level: '{{ volume }}'
      target:
        entity_id: media_player.spotify_chreecegr
`

**Comment by bramkragten** [comment] 2021-03-07 16:30
Yes, this is a duplicate of #8561

**Closed by bramkragten** 2021-03-07 16:30 UTC
Labels: bug

**Comment by Chreece** [comment] 2021-03-07 16:50
Thank you, I'm sorry for that...
