### ISSUE TITLE
Else branch of If action missing Paste option under Add action

### ISSUE THREAD

**Issue by tetele** [home-assistant/frontend#16879] opened 2023-06-12 11:49 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I Cut an action from an automation edit screen (GUI) and try to paste it under the Else branch of an If action, the Paste option is not there. The action can be pasted under the Then branch.

### Describe the behavior you expected

I can paste a cut/copied action wherever I have the "Add action" button

### Steps to reproduce the issue

1. Create a new automation
2. Add any action to it (e.g. Call Service -> `light.toggle`)
3. Add an If-then action and enable the Else branch ("Add else branch")
4. Cut the first action (hamburger menu on the Call Service action -> Cut)
5. Click the "Add action" on the Else branch of the If action

Expected: I have a "Paste (Call service)" option
Actual: I don't :)

### What version of Home Assistant Core has the issue?

2023.6.1

### In which browser are you experiencing the issue with?

Google Chrome 113.0.5672.127 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### Javascript errors shown in your browser console/inspector

```txt
none
```

**Comment by karwosts** [comment] 2023-06-12 14:18
This was recently reported and fixed, should be fixed in the next release with a frontend update.

**Comment by tetele** [comment] 2023-06-12 14:21
Ah, sorry, I searched, but only among open issues, knowing that the functionality was 1 week old :D

**Comment by karwosts** [comment] 2023-06-24 12:51
Closing as duplicate of #16838

**Closed by karwosts** 2023-06-24 12:51 UTC
