### ISSUE TITLE
State color of thermostat entity based on wrong attribute.

### ISSUE THREAD

**Issue by MarekLe** [home-assistant/frontend#14608] opened 2022-12-07 22:22 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

New color scheme for thermostat is... not usable..... Icon of thermostat is now red not when the state is 'heating'. It's now red when the 'operation' is set to 'heat'. So for my setup it is always red.......
In previous versions of HA colour of thermostat icon was based on state (heat/idle). It was very useful. Now it's based on 'operation' mode.
Thermostat in my setup is set to 'heat' operation for about 99.9% of time (I think it's common for everyone). So the icon is RED all the time, no matter if the termostat is in heat or idle state.
![image](https://user-images.githubusercontent.com/30925920/206308430-88bec40c-26cc-48b5-8618-a55ff0e555b3.png)

### Describe the behavior you expected

Thermostat icon color should be based on heat/idle state.

### Steps to reproduce the issue

1. Set the termostat to 'Operation' = 'Heat
2. Set temperature setpoint belos current themperature sensor (state = idle)
3. Icon of the termostat will be RED......

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.0 Supervisor 2022.11.2 Operating System 9.3 Frontend 20221207.0 - latest

### What was the last working version of Home Assistant Core?

Home Assistant 2022.11.0

### In which browser are you experiencing the issue with?

Google Chrome Wersja 108.0.5359.94

### Which operating system are you using to run this browser?

Windows 10 Pro. Compilation 19044.1645

**Comment by spacegaier** [comment] 2022-12-08 00:08
@piitaya Can you weigh in here? I think we should represent the current state as we apparently did before (and not the mode that an entity might be in).

**Comment by piitaya** [comment] 2022-12-08 07:12
The state is heat but the action is idle or heating. 

The color is based on state for every entity. For for climate it's hvac mode. Some climate doesn't have hvac action.

In tile card, there is badge to display the action (what you are interested in).
I will look how we can solve this.

**Comment by MarekLe** [comment] 2022-12-08 07:19
Now my cart with termostats looks like this:
![image](https://user-images.githubusercontent.com/30925920/206383490-e7254077-0837-472f-937f-e6630d0d6aea.png)
All items are red (orange ;-)) but only two of them are heating now.

**Comment by danielsmith89** [comment] 2022-12-08 09:18
I'm seeing the same, and as I use a picture entities card I relied on being able to make a quick glance to see if the heating was active, and now I have to open the entity details to see the correct status. Would be great if there was an option to turn off the new colours for just the thermostat (or go back to how they were)

**Comment by mhu1987** [comment] 2022-12-08 19:57
@piitaya 
Yes, the state is heat or off, but more precisely it should be operational and off. Hvac_action idle or heating.

**Comment by SN0WTR00PER** [comment] 2022-12-09 06:35
It could be cool if there was multiple option to accomodate the taste different users.  Personnally, I think that a thermostat should gradually change from blue to light yellow, then yellow, then orange en red depending ot the actual power output of a thermostat.   If not, going back to what is was is a better representation of the real state of a device.

**Comment by oxc** [comment] 2022-12-09 08:55
It's interesting that there is already an `idle` color defined for climate, but not used here. 

I agree that the former selection based on the current action was much more informative than the state based one.
It would be interesting to distinguish between idle and state=off, but not strictly necessary imho.

**Comment by Mariusthvdb** [comment] 2022-12-09 11:35
seeing the same for stock thermostat cards and since no screens were posted here yet, please let me add that:

this is actually heating
<img width="478" alt="Scherm­afbeelding 2022-12-09 om 09 56 21" src="https://user-images.githubusercontent.com/33354141/206693813-3b2298c0-5672-4831-a300-8d1425564b2c.png">
<img width="266" alt="Scherm­afbeelding 2022-12-09 om 09 57 41" src="https://user-images.githubusercontent.com/33354141/206693819-bdf34942-0128-4099-b851-ae51e4a9f1f0.png">


and this is idle:

<img width="402" alt="Scherm­afbeelding 2022-12-09 om 10 13 36" src="https://user-images.githubusercontent.com/33354141/206693895-590c2533-d552-4c11-ae1f-a485871099c6.png">
<img width="218" alt="Scherm­afbeelding 2022-12-09 om 10 15 09" src="https://user-images.githubusercontent.com/33354141/206693898-2163ce9d-678b-4d91-9402-f2f0d67135dc.png">

**Comment by ChristophCaina** [comment] 2022-12-09 11:54
I can confirm this.
The state colors for thermostats are not really usefull if they are linked to the operational state / selected profile...

All thermostats are in "Auto" Mode - all state colors are green, independend if they are heating or in Idle:
![grafik](https://user-images.githubusercontent.com/26391061/206696401-683da848-5559-401a-868c-f940e4a50ff3.png)

Switching some of them to "heat" - the Icon color does change to red/orange - even if they are in idle:
![grafik](https://user-images.githubusercontent.com/26391061/206696522-d61aee6e-f6f6-4270-87ca-0ccd47c2d6b6.png)

this also applies for the Thermostat Card itself - although, I don't have much issues with this ...
The Thermostat Card itself could be without any colors in my opinion ... it wouldn't change much on its main purpose...

![grafik](https://user-images.githubusercontent.com/26391061/206696937-6250a2b7-67b3-45a5-9255-6f0e0656d240.png)
![grafik](https://user-images.githubusercontent.com/26391061/206696952-061cb03a-b30e-48ea-953d-34190ae54c22.png)
![grafik](https://user-images.githubusercontent.com/26391061/206696962-5afe62da-03ae-4252-82ee-cf764a0d6398.png)
![grafik](https://user-images.githubusercontent.com/26391061/206696970-8fd3874c-d10b-4328-a16c-72d2eaa054d2.png)

**Comment by Fr3n3z1** [comment] 2022-12-12 00:04
Same issue here since version 2022.12.2

it's very annoying to no longer have the heating status.

Before, when the heating was on, the icon was red. And when the heating was off, the icon was gray in color.

It was very easy to see the heating status at a glance.

Does anyone have a tip for changing this, or do you think this will be fixed in a future release?

Thanks in advance.

**Comment by seanblanchfield** [comment] 2022-12-12 14:33
I have temporarily worked around this in my Picture Elements floorplan using  the `config-template-card` HACS addon. I wrapped my thermostat's `state-icon` in a `config-template-card` and then overrode the CSS var `--rgb-state-climate-heat-color` with a templated value (this is one of the new state colors introduced in 2022.12). 

The strange RGB tuples below are an approximation of a suitable grey and orange in the new format, which is discussed in [#14666](https://github.com/home-assistant/frontend/issues/14666).

``` yaml
- type: custom:config-template-card
  entities:
    - climate.boiler_thermostat
  element:
    type: state-icon
    entity: climate.boiler_thermostat
  style:
    "--rgb-state-climate-heat-color": >-
      ${ states["climate.boiler_thermostat"].attributes.hvac_action ==
        'idle'  ?
        '200,200,200' :
        '255,120,0' 
      }

```

I think there should be a way to do something similar with a regular lovelace `thermostat` card, perhaps with the additional use of the `lovelace-card-mod` addon.

**Comment by teknomar7** [comment] 2022-12-12 14:37
The lock icon for my yale lock has a similar issue.  Shows red when locked and blue when unlocked.  Previously it would show yellow when unlocked and blue when locked.

**Comment by teknomar7** [comment] 2022-12-12 15:02
@ChristophCaina Thanks. Hadn't seen an issue linked around that in the discussions.

**Comment by ChristophCaina** [comment] 2022-12-12 15:18
@teknomar7 : no problem :)
If you don't find an issue ticket - you should consider to open one.
This ticket is explicit mentioned "thermostats" - and the issue here is, that thermostats behave completely different from lock entities.

So mixing up different cases will make it worse for everyone to understand what the topic is about :)

the issue you're probably searching is:
#14680

some of the PRs related to that:
#14633 and #14672

**Comment by SN0WTR00PER** [comment] 2022-12-13 07:56
I really don't know why they changed the thermostat colour behaviour.  I'm gonna stick to my old HA version until they fix that...

**Closed** 2022-12-13 15:49 UTC

**Comment by oxc** [comment] 2022-12-13 15:55
@piitaya, do I read this correctly that thermostats will now switch between "heating" HAVC action and "heating" state? I don't see in the changes how a idle thermostat in heating state would get drawn as "idle"

**Comment by NickM-27** [comment] 2022-12-13 15:58
> @piitaya, thanks for the quick fix! But do I read this correctly that thermostats will now switch between "heating" HAVC action and "heating" state? I don't see in the changes how a idle thermostat in heating state would get drawn as "idle"

No, it'd saying if a climate entity supports the hvac_action state attribute then that will be the source instead of the entities state. So if the hvac_action is supported and is currently idle, then the icon will be grey to reflect that.

**Comment by oxc** [comment] 2022-12-13 16:08
Ok, thanks, I see, because _computeColor returns undefined. I was confused by the ["heating", "cooling", "drying"] check

**Comment by MarekLe** [comment] 2022-12-14 13:47
I don't understand why this issue is closed. Problem still exists. Thermostats are still red even though they are 'Idle'.

**Comment by oxc** [comment] 2022-12-14 13:47
It works for me after today's update.

**Comment by MarekLe** [comment] 2022-12-14 13:49
Bingo! I'm sorry. I didn't refresh frontend after update.
It's OK now.

**Comment by Mariusthvdb** [comment] 2022-12-14 15:01
still identical to what it was before ....
<img width="520" alt="Scherm­afbeelding 2022-12-14 om 13 51 26" src="https://user-images.githubusercontent.com/33354141/207630792-56283172-6fec-43a1-a765-fe807458149e.png">
<img width="543" alt="Scherm­afbeelding 2022-12-14 om 13 52 12" src="https://user-images.githubusercontent.com/33354141/207630802-234ea344-1d3a-4416-b3ae-5e4e3ef03537.png">

**Comment by NickM-27** [comment] 2022-12-14 15:02
It's working great here with 2022.12.5, maybe that card isn't respecting the color for some reason

**Comment by NickM-27** [comment] 2022-12-14 15:14
> (which was supposed to have been changed in the last update?)

I don't believe that is the case, I think that is just the way these cards work. all my entity cards show the correct color based on the hvac_action (which they did not before 2022.12.5). 

Basically, the fixes described here are working as intended and the behavior on those cards is unrelated

**Comment by NickM-27** [comment] 2022-12-14 15:27
Thermostat / tile card and entity icon are two different things. 

This did fix the entity icons color as it was supposed to, my point being that the statement "this did nothing" is false. 

The card color behavior is unrelated is my other point, as it clearly is using a different set of rules for coloring and I'm not convinced this PR was meant to change that.

**Comment by Mariusthvdb** [comment] 2022-12-14 16:07
not going into semantics too muchr, but the title of this issue is _State color of thermostat entity based on wrong attribute_

and the PR says to fix that: _If the entity support hvac_action, use action instead of state for icon color._

added to that, I dont think I stated: "this did nothing". It might have changed an icon, but it didnt fix the state color to the entity, in either thermostat card, or tile card.

as far as my examples go, this should be reopened.

**Comment by NickM-27** [comment] 2022-12-14 16:15
> as far as my examples go, this should be reopened.

Look at the screenshot used in the example by the OP of this issue, that issue is now fixed in 2022.12.5, thus this issue is closed. 

I'd recommend making a new issue for the thermostat / tile card as that is unrelated to the issue reported here (the entity icon when used in more-info and the entities card)

**Comment by NickM-27** [comment] 2022-12-14 16:29
also, the thermostat card is working the way it has always worked. I just tested in 2022.10 and it is working the same way it does today

![Screen Shot 2022-12-14 at 09 25 00 AM](https://user-images.githubusercontent.com/14866235/207652443-e17f5169-9c0a-4b92-a637-19bbae12eabf.png)

![Screen Shot 2022-12-14 at 09 24 52 AM](https://user-images.githubusercontent.com/14866235/207652472-00d75400-94c0-46af-86b8-21a8e53ecd32.png)

![Screen Shot 2022-12-14 at 09 27 16 AM](https://user-images.githubusercontent.com/14866235/207652494-591b88f3-4dc8-4d07-b80b-41edb060b508.png)

**Comment by ChristophCaina** [comment] 2022-12-14 16:30
I would agree, that this should be a new topic.

As far as I can tell - the "default" have has been restored, or better: The new color options have been adjusted.
The Thermostat card itself is - for me - behaving completely the same as it was all the time before.

If this behave should be changed (to match the new entity color schema) - this should be a new issue imho

**Comment by ChristophCaina** [comment] 2022-12-14 16:41
I think, I know why this happened...
Since the Thermostat cards are working as pre-2022.12 version, the same "logic" was implemented for the state icons that will be used in the different other cards.

This has been now corrected - but since nothing was changed in the Thermostat card, this is still changing the color based on the active havc state - and not based on the action itself.

**Comment by ChristophCaina** [comment] 2022-12-14 16:48
Created a new Issue (Change Request) #14784
The Thermostat Card should follow the same color schema / logic as the entity state.

**Comment by piitaya** [comment] 2022-12-14 18:49
We reverted the changes from mode to action for climate color in entities card and more info because it's was like this before. 
The goal of the color update was to add new color system by domain, not to change the current rules.

Thanks for moving the discussion by creating a feature change. 🙂
