### ISSUE TITLE
Entity IDs are not renamed

### ISSUE THREAD

**Issue by AngellusMortis** [home-assistant/frontend#19635] opened 2024-02-02 18:48 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If an entity's entity ID does not match the entity/device name, choosing "Rename Entity IDs" will not work on the entity ID. 

### Describe the behavior you expected

Entity IDs should be renamed according to new device name

### Steps to reproduce the issue

1. Open device
2. Click Edit in Top Right
3. Update Device Name
4. Click "No" on the confirmation prompt to rename Entity IDs
5. Update the Device Name again
6. Click "Rename" on the confirmation prompt to rename Entity IDs

https://github.com/home-assistant/frontend/assets/490848/e1d89dd7-1bb9-4c7c-83b8-a3900e84e710

This is also re-producible if the device/entity names are updated from upstream. In my case, I renamed the devices in UniFi Protect and reloaded the integration so the devices/entities would get their new proper names. Now I cannot rename the device manually to bulk update all of the entity IDs. 

Bulk renaming the entity IDs is really useful for upgrading/replacing devices which is what I am doing here. I replaced 4 outside cameras with newer models. Renamed the old ones and then disabled them. Then renamed the new ones to match what the old ones were.

### What version of Home Assistant Core has the issue?

core-2024.1.6

### What was the last working version of Home Assistant Core?

2023.12 ish? maybe?

### In which browser are you experiencing the issue with?

Edge (Chromium)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

Enabled and working? Basically trying to upgrade/replace a device. 

Renamed old device, verified entity IDs on it were renamed. Then disabled it. Renamed replacement device, all of the entity IDs are still the old default name (`ai_pro_*`).

### Problem-relevant frontend configuration

N/A.

### Javascript errors shown in your browser console/inspector

None.

### Additional information

The device does have a lot of entities that may be causing it (40+).

**Comment by Alex-joomla** [comment] 2024-02-29 19:44
I even don't get the dialogue box where HomeAssistant asks if it should rename the entitys accordingly

**Comment by karwosts** [comment] 2024-03-03 17:41
> I even don't get the dialogue box where HomeAssistant asks if it should rename the entitys accordingly

Note the dialog popup is only given to users with "Advanced Mode" enabled.

**Comment by karwosts** [comment] 2024-03-03 17:57
When renaming entity ids, ids are only modified if the entity id contains exactly the slug of the old device name, and only that subset of the entity id is modified to the new name.

So if you're renaming "Foo Device" to "Bar Device", `sensor.xxxx_foo_device_yyyy` will be renamed `sensor.xxxx_bar_device_yyyy`, but an entity that does not contain the string `foo_device` is not modified.

If you want to bulk rename entities that don't match the current device name, you may be able to take advantage of this by renaming the device multiple times, first rename it such that it matches the part of the id that you want renamed, and then try renaming it a second time.

**Comment by ildar170975** [comment] 2024-03-03 18:24
> only given to users with "Advanced Mode" enabled

Off-topic, but so far see no reason to have this "advanced mode" disabled.

**Comment by shred86** [comment] 2024-04-14 20:30
> When renaming entity ids, ids are only modified if the entity id contains exactly the slug of the old device name, and only that subset of the entity id is modified to the new name.
> 
> So if you're renaming "Foo Device" to "Bar Device", `sensor.xxxx_foo_device_yyyy` will be renamed `sensor.xxxx_bar_device_yyyy`, but an entity that does not contain the string `foo_device` is not modified.
> 
> If you want to bulk rename entities that don't match the current device name, you may be able to take advantage of this by renaming the device multiple times, first rename it such that it matches the part of the id that you want renamed, and then try renaming it a second time.

Thank you @karwosts for sharing this. I could not figure out why sometimes the device_id would not update and this is the reason. I do think this is a bug because you still get the dialog asking you if you want to rename your device_id, but it's not actually doing anything which makes it very confusing.

**Comment by chojnicki** [comment] 2024-07-14 13:58
> When renaming entity ids, ids are only modified if the entity id contains exactly the slug of the old device name, and only that subset of the entity id is modified to the new name.
> 
> So if you're renaming "Foo Device" to "Bar Device", `sensor.xxxx_foo_device_yyyy` will be renamed `sensor.xxxx_bar_device_yyyy`, but an entity that does not contain the string `foo_device` is not modified.
> 
> If you want to bulk rename entities that don't match the current device name, you may be able to take advantage of this by renaming the device multiple times, first rename it such that it matches the part of the id that you want renamed, and then try renaming it a second time.


Thank you for that. I struggled with that for a long time. I wonder who come up with such retarded implementation.

**Comment by shadow7412** [comment] 2024-09-28 01:19
It seems that devices that are unnamed cannot be bulked renamed in this either... even though the option comes up (with advanced mode on) it doesn't appear to actually rename anything.

**Comment by karwosts** [comment] 2024-09-28 02:32
This should be improved by https://github.com/home-assistant/frontend/pull/21952

**Comment by lcombs15** [comment] 2024-10-02 02:28
Also running into this trying to rename entity IDs of scripts

**Comment by karwosts** [comment] 2024-11-20 20:43
Closing this as the rename is currently working as intended. 

If you're doing a device rename, the old name must be in the entity id as otherwise we would not have any idea what to name the new entity id. If the device name is not in the entity id it will not be renamed, this is by design. And the new dialogs make that clearer.

**Closed by karwosts** 2024-11-20 20:43 UTC

**Comment by TiganSan** [comment] 2024-12-06 21:48
Then what is the best way to rename the Entity IDs for a device that has 68 entities?  The default name that was used during the initial setup is 20 characters long and I want to shorten it to something shorter and more meaningful.

**Comment by karwosts** [comment] 2024-12-06 21:49
> Then what is the best way to rename the Entity IDs for a device that has 68 entities? 

What is the current device name and what is an example of the kind of entity renames you want to perform?

**Comment by TiganSan** [comment] 2024-12-09 03:03
The new entity is the Everything Presence Lite and the name that was used by HA during setup is:
everything_presence_lite_5aa1ec
One of the entity names show is: sensor.everything_presence_lite_5aa1ec_target_3_resolution
I want to rename the device to "Precense-3"  So, I am expecting the entity names to also change to something like "sensor.presence_3_target_3_resolution"
It used to be that a when I renamed the device in the list, the system would ask me if I also want to update the entity names.  This behavior seem to have changed now!!

**Comment by karwosts** [comment] 2024-12-09 03:11
> It used to be that a when I renamed the device in the list, the system would ask me if I also want to update the entity names.

It still does, if you have Advanced Mode enabled. Always been that way.

**Comment by nicola-spreafico** [comment] 2024-12-14 18:33
> > It used to be that a when I renamed the device in the list, the system would ask me if I also want to update the entity names.
> 
> It still does, if you have Advanced Mode enabled. Always been that way.

Thank you, you saved my day.
I don't know about "Always been that way", in the past I always had the entity ids auto rename active by default, I did not know about "advanced mode" until now.

I activated the advanced mode and finally the entities auto rename dialog started to be shown again.
