### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')

### ISSUE THREAD

**Issue by dinan5** [home-assistant/frontend#10908] opened 2021-12-14 00:21 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Every since 12.21.0  i am getting these messages in my log

Logger: frontend.js.latest.202112120
Source: components/system_log/__init__.py:189
First occurred: 2:04:41 PM (3 occurrences)
Last logged: 2:19:15 PM

http://xx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')

### Describe the behavior you expected

Not to get these error messages

### Steps to reproduce the issue

1. purely using HA reproduces it.
2.
3.
...

### What version of Home Assistant Core has the issue?

12.21.1

### What was the last working version of Home Assistant Core?

11.21.5

### In which browser are you experiencing the issue with?

Version 96.0.4664.93 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

**Comment by spacegaier** [comment] 2021-12-14 23:18
I am afraid this is not enough information to go on. "purely using HA" does not reproduce it on my end. I wouldn't be surprised if this was related to a custom element. Are you using any custom UI components, e.g. via HACS?

**Comment by dinan5** [comment] 2021-12-14 23:57
Yes, I am.  can you please help me determine how to identify source? thank you.

**Comment by dinan5** [comment] 2021-12-15 02:41
I found this adjacent info in the log tonight. 

2021-12-14 21:35:18 ERROR (MainThread) [frontend.js.latest.202112120] http://xx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
2021-12-14 21:35:18 ERROR (MainThread) [frontend.js.latest.202112120] http://xx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
2021-12-14 21:35:18 ERROR (MainThread) [frontend.js.latest.202112120] http://xx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
2021-12-14 21:35:18 ERROR (MainThread) [frontend.js.latest.202112120] http://xx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
2021-12-14 21:35:18 ERROR (MainThread) [frontend.js.latest.202112120] http://xx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
2021-12-14 21:35:18 ERROR (MainThread) [frontend.js.latest.202112120] http://xx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
2021-12-14 21:35:18 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsp://****:****@xx.xxx.xxx.xxx:554/Streaming/Unicast/channels/901
2021-12-14 21:35:18 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsp://****:****@xx.xxx.xxx.xxx:554/Streaming/Unicast/channels/102
2021-12-14 21:35:18 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsp://****:****@xx.xxx.xxx.xxx:554/Streaming/Unicast/channels/202
2021-12-14 21:35:18 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsp://****:****@xx.xxx.xxx.xxx:554/Streaming/Unicast/channels/302
2021-12-14 21:35:18 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsp://****:****@xx.xxx.xxx.xxx:554/Streaming/Unicast/channels/402
2021-12-14 21:35:18 INFO (MainThread) [homeassistant.components.stream] Started stream: rtsp://****:****@xx.xxx.xxx.xxx:554/Streaming/Unicast/channels/502

**Comment by dinan5** [comment] 2021-12-21 00:13
Hello - Any update on this?  anything else I can provide to assist?  Thanks.

**Comment by emontnemery** [comment] 2021-12-21 07:56
Try disabling the custom UI element to verify the error goes away, then re-enable them until you find the culprit.

**Comment by dinan5** [comment] 2021-12-21 15:24
All custom UIs and themes are removed.  It is still occurring.

**Comment by dinan5** [comment] 2021-12-21 17:51
found it, it was a theme.

**Comment by dinan5** [comment] 2021-12-21 18:19
I take that back, still happening.

**Comment by dinan5** [comment] 2021-12-21 18:34
If I had to guess, it is related to the Picture Card being used for video, per the adjuacent video messages above.

**Comment by OhioSpyderman** [comment] 2021-12-28 14:54
Getting the same error as well.
Had hoped the latest 21.12.6 would fix it.

"http://xxx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')"

For what it's worth, it showed up 2 times since the install of the new core, approximately 3.5 hours ago.

**Comment by maddeuce** [comment] 2021-12-29 20:15
Try 21871 time .....

Logger: frontend.js.latest.202112270
Source: components/system_log/__init__.py:189
First occurred: 9:33:23 AM (24871 occurrences)
Last logged: 10:55:07 AM

http://192.168.100.2:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')

> Getting the same error as well. Had hoped the latest 21.12.6 would fix it.
> 
> "http://xxx.xxx.xxx.xxx:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')"
> 
> For what it's worth, it showed up 2 times since the install of the new core, approximately 3.5 hours ago.

Mine 24871 time haha.

Logger: frontend.js.latest.202112270
Source: components/system_log/__init__.py:189
First occurred: 9:33:23 AM (24871 occurrences)
Last logged: 10:55:07 AM

http://xxx.xxx.xx.xxx/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')

**Comment by spacegaier** [comment] 2022-01-02 16:52
I looked into it after I now faced the same error in my instances and found the culprit (HLS streaming). Fix is on its way.

**Comment by OhioSpyderman** [comment] 2022-01-02 16:59
Excuse me, but what is "HLS Streaming"?
Does it have anything to do with these other errors I have?

http://192.168.1.45:8123/frontend_latest/93104ce0.js:8:3340 Uncaught TypeError: Cannot read properties of null (reading 'removeAttribute')
11:57:29 AM – (ERROR) components/system_log/__init__.py - message first occurred at 11:23:29 AM and shows up 2 times
Error doing job: Unclosed client session
10:49:47 AM – (ERROR) runner.py
Config entry '555179153516' for ambient_station integration not ready yet: One or more namespaces failed to connect; Retrying in background
10:49:45 AM – (WARNING) config_entries.py - message first occurred at 10:49:28 AM and shows up 6 times
Config entry failed: One or more namespaces failed to connect
10:49:30 AM – (ERROR) Ambient Weather Station

Just curious...

Bob.

**Comment by spacegaier** [comment] 2022-01-02 19:20
It only has to do with the first one (from `/frontend_latest/93104ce0.js:8:3340`). HLS is a streaming standard. Your favorite internet search engine can provide more technical details if desired.

**Comment by OhioSpyderman** [comment] 2022-01-02 19:26
Yeah, sorry, I should have searched.
Thanks for the explanation though.

Bob.

**Comment by dmylnka** [comment] 2022-01-06 12:33
i experience the same issue and i resolved by disabling HACS frontend components. root cause was cheduler card frontend which on latest version 2.3.0 caused this issue. I load the previous version 2.2.0 and everything is in line. I hope this may help anyone to identify root cause of that issue.

**Closed** 2022-01-07 16:44 UTC
Labels: bug

**Comment by Jesspu** [comment] 2022-01-24 05:26
I am having this issue as well when using a picture glance card with my nest integration and a live feed. It loads fine at first, but after it runs for a bit I get this error, and then have to reload the page to get it some back.
