### ISSUE TITLE
Button type cards not showing after last update

### ISSUE THREAD

**Issue by razorsec-art** [home-assistant/frontend#16166] opened 2023-04-13 11:39 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

After upgrade to last version I cannot see the button type card entities that I use all over my different dashboards. They appear using raw editor but not visually present. 

### Describe the behavior you expected

Button cards should appear

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.4.3

### In which browser are you experiencing the issue with?

App and edge browser 

### Which operating system are you using to run this browser?

iOS

**Comment by ludeeus** [comment] 2023-04-13 11:40
Duplicate of https://github.com/home-assistant/frontend/issues/16155

**Closed by ludeeus** 2023-04-13 11:40 UTC
