### ISSUE TITLE
:0:0 ResizeObserver loop completed with undelivered notifications.

### ISSUE THREAD

**Issue by nawwman** [home-assistant/frontend#14834] opened 2022-12-18 09:07 UTC
### The problem

I get this ERROR in my System logs:

```
 Logger: frontend.js.latest.202211080
Source: components/system_log/__init__.py:256
First occurred: 09:32:15 (8 occurrences)
Last logged: 10:03:21
:0:0 ResizeObserver loop completed with undelivered notifications.
```

### What version of Home Assistant Core has the issue?

core-2022.11.4

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

not sure

**Comment by steverep** [comment] 2023-01-17 22:27
Duplicate of #9022

**Closed by steverep** 2023-01-17 22:27 UTC
Labels: frontend
