### ISSUE TITLE
Settings > System is totally blank

### ISSUE THREAD

**Issue by Banditen01** [home-assistant/frontend#13749] opened 2022-09-14 13:04 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I go to Settings > System the window is totally blank

### Describe the behavior you expected

Opposite what described, expected to be able to see logs etc.

### Steps to reproduce the issue

1. Go to Settings
2. Go to System
3.
...

### What version of Home Assistant Core has the issue?

core 2022.9.3

### What was the last working version of Home Assistant Core?

core 2022.9.2

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.125

### Which operating system are you using to run this browser?

Windows10 and Ubuntu 20.04.5 LTS

**Comment by ludeeus** [comment] 2022-09-14 13:20
Duplicate of https://github.com/home-assistant/frontend/issues/13728
Update to 2022.9.4

**Closed by ludeeus** 2022-09-14 13:20 UTC
