### ISSUE TITLE
Settings > System page wont load + js error in frontend

### ISSUE THREAD

**Issue by sdotter** [home-assistant/frontend#13742] opened 2022-09-14 09:34 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Home Assistant > Settings > System page wont load.
It stays blank and get throws an js error:

`typography.js:181 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'language')
    at i (typography.js:181:1)
    at r.value (ha-state-icon.ts:20:1)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)`

### Describe the behavior you expected

Just load the page :)

### Steps to reproduce the issue

1. Settings
2. System
3. Blank + js error
...

### What version of Home Assistant Core has the issue?

2022.9.3

**Comment by ludeeus** [comment] 2022-09-14 09:36
Duplicate of https://github.com/home-assistant/frontend/issues/13728

fixed Home Assistant in 2022.9.4

**Closed by ludeeus** 2022-09-14 09:36 UTC
