### ISSUE TITLE
Dashboard/Tab has an extra 24px added to the tab display resulting in a vertical scroll bar appearing.

### ISSUE THREAD

**Issue by Kertz1954** [home-assistant/frontend#16016] opened 2023-04-01 22:06 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Afer updating from 0b3 to 0b4, every Dashboard/Tab has an extra 24px added to the tab display resulting in a vertical scroll bar appearing.
Refreshing the browser (Opera & Google Chrome) using the refresh icon clears this problem.

On adding a new Dashboard, setting the tab to Sidebar and adding 2 HA Button cards, one left, the other right, the vertical scroll bar appears again.

Moving to any other Dashboard/Tab thereafter retains the scroll bar until the browser refresh icon is clicked.

### Describe the behavior you expected

Same display for all Dashboards/Tabs as in 2023.3.6

### Steps to reproduce the issue

Afer updating from 0b3 to 0b4, every Dashboard/Tab has an extra 24px added to the tab display resulting in a vertical scroll bar appearing.
Refreshing the browser (Opera & Google Chrome) using the refresh icon clears this problem.

On adding a new Dashboard, setting the tab to Sidebar and adding 2 HA Button cards, one left, the other right, the vertical scroll bar appears again.

Moving to any other Dashboard/Tab thereafter retains the scroll bar until the browser refresh icon is clicked.

### What version of Home Assistant Core has the issue?

2023.4.0b0 - 0b4

### What was the last working version of Home Assistant Core?

2023.3.6

### In which browser are you experiencing the issue with?

Opera & Google Chrome

### Which operating system are you using to run this browser?

Linux latest.

### Additional information

![dashboard_tab_extra_24px](https://user-images.githubusercontent.com/67558244/229316833-98117141-d2a3-4970-8924-c5fa15c2c265.png)

views:
  - theme: Backend-selected
    title: Home
    type: sidebar
    badges: []
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: switch.lounge
        view_layout:
          position: sidebar
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: toggle
        entity: light.kitchen_lights

**Comment by Kertz1954** [comment] 2023-04-02 00:18
I also tried this with 2 Markdowb cards. Same result.

**Comment by kulmegil** [comment] 2023-04-02 12:06
> On adding a new Dashboard, setting the tab to Sidebar and adding 2 HA Button cards, one left, the other right, the vertical scroll bar appears again.

Yeah, it's the [Button Card issue](/custom-cards/button-card/issues/672)
But there might be other custom cards that causes this to look for.

It can be tracked down css changes on `<action-handler>` elements, that was handled in frontend fix #15978

**Comment by Kertz1954** [comment] 2023-04-02 13:47
Yes, the HA button still give a double scroll bar when editing.

However, the HA Markdown card does not give a double scroll bar when editing, but still leaves a vertical scroll bar one saved.

**Comment by bramkragten** [comment] 2023-04-02 15:54
Can't reproduce:

<img width="1680" alt="CleanShot 2023-04-02 at 17 53 43@2x" src="https://user-images.githubusercontent.com/5662298/229364181-5c1a41e6-64f4-486a-8031-597026ad5325.png">

**Comment by Kertz1954** [comment] 2023-04-02 16:39
Very strange. The problem does not occurr on 2023.3.6 so there is a problem somewhere.

When time permits, I will do a completly new installation and see if it persits.

In the meantime, thanks for testing and pointing out the other issue I had with z-index.

You might as well close this issue.

**Comment by piitaya** [comment] 2023-04-03 13:49
Should be fixed with https://github.com/custom-cards/button-card/releases/tag/v3.5.0

**Closed by piitaya** 2023-04-03 13:49 UTC
