### ISSUE TITLE
Automation visual editor doesn't show action that includes a deleted device

### ISSUE THREAD

**Issue by jtaseff** [home-assistant/frontend#16986] opened 2023-06-21 05:02 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I had an automation that interacted with a couple of Roku TV devices.

At some point, the Roku integration lost one device. I deleted and re-added it. Then it had the same device name, but a different device ID.

In the automation editor, the whole block (if device is playing media, pause media player) disappeared. I added a new one. Later I just discovered that the whole block still existed in YAML and in the trace, but was not shown in the visual editor.

### Describe the behavior you expected

An automation action that involves a deleted device should still show 

### Steps to reproduce the issue

1. Make automation
2. Delete device (or force it to be lost/unavailable somehow, then delete)
3. Add same device with same name, creating a new device ID
4. Check automation YAML vs visual editor
...

### What version of Home Assistant Core has the issue?

2023.6.2, Frontend 20230608.0

### In which browser are you experiencing the issue with?

Firefox

### State of relevant entities

```txt
- if:
      - condition: state
        entity_id: media_player.roku_ys00nj280733
        state: playing
    then:
      - service: media_player.media_pause
        data: {}
        target:
          device_id: 6671c53453d0a86fcc1e4e2b7243d259
    else:
      - if:
          - condition: state
            entity_id: media_player.roku_ys00nj280733
            state: paused
        then:
          - service: media_player.media_play
            data: {}
            target:
              device_id: 6671c53453d0a86fcc1e4e2b7243d259
```

**Comment by karwosts** [comment] 2023-06-22 17:27
Mine just shows this after deleting a device. I'll have to check if it's something specific to the if/then block. 


![image](https://github.com/home-assistant/frontend/assets/32912880/4e925a5c-5f1a-4ba0-93f4-0e63307db72d)

![image](https://github.com/home-assistant/frontend/assets/32912880/58a79dff-bfd7-4fda-8256-e780cfa78b35)

**Comment by karwosts** [comment] 2023-06-23 16:46
I can't reproduce it sorry. 

If you can reproduce it with an explicitly exact sequence of steps I can follow, including creating and deleting a device that does not require me to have any specific hardware or login credentials, then I can try again.

**Comment by silamon** [comment] 2023-06-23 19:34
> I can't reproduce it sorry.
> 
> If you can reproduce it with an explicitly exact sequence of steps I can follow, including creating and deleting a device that does not require me to have any specific hardware or login credentials, then I can try again.

Reproduction: 
Try to save this automation: 
```
alias: New Automation
description: ""
trigger: []
condition:
  - condition: state
    entity_id: vacuum.unexisting
    state: paused
action: []
mode: single
```
Upon save, the condition will go invisible, upon opening after save the condition is still invisible.
I can put up a pull request somewhere next week, since I'm working on getting those descriptions translated.

**Comment by karwosts** [comment] 2023-06-23 21:12
That sounds like maybe duplicate of #16643. 

I'm not sure if your original issue with _devices_ is something different than this with entities. 

I can reproduce this entity issue, it's due to an error being thrown trying to generate the description, and that should be solvable by just wrapping the describe functions in a try/catch block.

**Closed** 2023-06-26 09:47 UTC
