### ISSUE TITLE
Thermostat dial not working after update to 2023.3.0

### ISSUE THREAD

**Issue by liquidat** [home-assistant/frontend#15679] opened 2023-03-02 14:06 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the update to 2023.3.0, the thermostat dial is not working anymore. Previously there was a dot which could be dragged to change the temperature. That dot is not there anymore, I am not able to change the temperature that way:
![Screenshot from 2023-03-02 14-58-35](https://user-images.githubusercontent.com/1998084/222449341-4b1268f2-7c2f-4e65-b582-66925210e969.png)

I have to click the three dots in the top right corner and change the temperature by clicking the up/down arrows.
![Screenshot from 2023-03-02 14-58-40](https://user-images.githubusercontent.com/1998084/222449444-c3489a98-adf4-4ab4-8325-f57c9236043b.png)

This behavior is consistent across browsers (Firefox, Brave) and also appears on the mobile application.

### Describe the behavior you expected

I would like to be able to use the thermostat dial to do drag&drop to change the temperature. There is no dot anymore, I cannot drag&drop anymore.

### Steps to reproduce the issue

1. Set up homeassistant with a thermostat
2. Add thermostat card to dashboard
3. Try to change the temperature on the thermostat via drag&drop

### What version of Home Assistant Core has the issue?

Home Assistant 2023.3.0

### What was the last working version of Home Assistant Core?

Home Assistant 2023.2.5

### In which browser are you experiencing the issue with?

Firefox 110, Chrome Version 110.0.5481.177, Android app beta-3200-4b22c2b4-full

### Which operating system are you using to run this browser?

Fedora Linux 37, Android 13

**Comment by piitaya** [comment] 2023-03-02 14:08
Hello 👋 It's a duplicate of https://github.com/home-assistant/frontend/issues/15662. It will be fixed in the next patch

**Closed by piitaya** 2023-03-02 14:08 UTC
