### ISSUE TITLE
History graph/timeline is missing or incomplete in 0.111.2 

### ISSUE THREAD

**Issue by Hacker-CB** [home-assistant/frontend#6167] opened 2020-06-14 20:32 UTC
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

History graph for sensors and binary_sensors is missing or incomplete.

<img width="741" alt="image" src="https://user-images.githubusercontent.com/4232995/84603284-da0f0900-ae95-11ea-98f8-ccfdc75eb096.png">

Graph in the picture starts from 11:14.

Same situation with graphs from the other sensors.

## Expected behavior

It should starts from 10:05pm

## Environment

- Home Assistant release with the issue: 0.111.2
- Last working Home Assistant release (if known): 0.110.x
- Browser and browser version: Safari 13.1.1
- Operating system: MacOS 10.15.5

## State of relevant entities

```yaml
```

## Problem-relevant configuration

```yaml
recorder:
  auto_purge: 1
  purge_keep_days: 5
  db_url: mysql://XXXXXX@172.17.0.1/XXXXXX?charset=utf8
```

## Javascript errors shown in your browser console/inspector

```txt

```

**Comment by fedebruni84** [comment] 2020-06-14 20:49
Same here, almost all sensors do not display history graph. Seems empty but it's not 

![IMG_0541](https://user-images.githubusercontent.com/37954254/84603768-358ac800-ae91-11ea-9420-8b134e1409e8.jpeg)

**Comment by frenck** [comment] 2020-06-14 21:01
duplicate of #6161

**Closed by frenck** 2020-06-14 21:01 UTC
Labels: bug
