### ISSUE TITLE
Adding an empty card to a section destroys the whole section 

### ISSUE THREAD

**Issue by michaelarnauts** [home-assistant/frontend#21273] opened 2024-07-03 18:40 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I tried to create the following cards in a section:

AA BB
CC __
DD EE

Every (double) letter is a card, resized to be two units wide. The __ card was supposed to be empty. Drag and drop didn't work since the DD card snapped next to the CC one.

I've tried adding an empty card, by selecting Manual Card and removing all yaml. It have a warning that the yaml was invalid, but it was allowed to add anyway. When adding it, the whole section is removed, including existing items.

### Describe the behavior you expected

If "empty" cards are not supported, it shouldn't allow the card to be added.

Ideally, it should support drag and drop to create gaps, but that's a feature request.

### Steps to reproduce the issue

1. Add a new card to an existing section.
2. Use Manual YAML
3. Remove the whole body
4. Add the card
...

### What version of Home Assistant Core has the issue?

2024.7

### In which browser are you experiencing the issue with?

Chrome 126

### Which operating system are you using to run this browser?

Android 14

**Comment by MindFreeze** [comment] 2024-07-25 06:08
I can't reproduce this. Not allowed to save invalid YAML

**Comment by michaelarnauts** [comment] 2024-07-25 11:12
I still can in 2024.7.3

Just add a manual card. And remove the text. I made a screenshot to show that Dave is available.

![Screenshot_20240725-131112](https://github.com/user-attachments/assets/cd059d8e-f794-4d9c-a65c-dfc1db9c8066)

**Comment by piitaya** [comment] 2024-09-02 08:57
I pushed a fix to avoid the full section not displayed but you should not use wrong config to add gap (as it will display an error).

**Closed** 2024-09-02 11:21 UTC
