### ISSUE TITLE
Automation popup menu closes when an automation in the list gets executed

### ISSUE THREAD

**Issue by Xitee1** [home-assistant/frontend#13664] opened 2022-09-08 18:15 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I go to the automation dashboard and click on the 3 dots of an automation to open the menu, then the menu closes itself again when any automation gets executed (when the "last executed" changes).

### Describe the behavior you expected

That the menu stays open while automations are getting executed

### Steps to reproduce the issue

1. Go to the automations list
2. Click on the 3 dots from an automation to open the menu
3. Wait until any automation gets triggered
4. Watch how the popup disappears

### What version of Home Assistant Core has the issue?

core-2022.9.0

### In which browser are you experiencing the issue with?

Firefox, Chrome

### Which operating system are you using to run this browser?

Linux Mint, Windows 10

### Additional information

![firefox_tq1QJIWJil](https://user-images.githubusercontent.com/59659167/189195852-97512a94-0d95-4112-b8c5-9728955a9e6f.gif)

**Comment by chertvl** [comment] 2022-09-11 17:49
Same. For a very long time.

**Comment by chillymattster** [comment] 2022-12-04 20:06
Same for me as well.
In my case the described behaviour is especially forced by having automations running in a very short interval caused by the solution for ["Change scan_interval for AndroidTV integration"](https://community.home-assistant.io/t/change-scan-interval-for-androidtv-integration/408835).

For me the popup menu is currently unusable.

**Comment by karwosts** [comment] 2023-06-12 02:07
Fix PR has been filed.

**Comment by karwosts** [comment] 2023-07-01 04:18
Fixed by #17049

**Closed by karwosts** 2023-07-01 04:18 UTC
