### ISSUE TITLE
Inconsistent treatment of duration sensor

### ISSUE THREAD

**Issue by jamesonuk** [home-assistant/frontend#18561] opened 2023-11-07 13:49 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have setup the speedtest integration and adding the ping sensor to various cards results in different displays.   Only the entity and sensor card seem to pick up the unit of measure where as the others (tile, entities, glance) don't and end up showing the value in seconds.

Clicking through on the cards that do so the right value also shows this raw value

![image](https://github.com/home-assistant/frontend/assets/1040621/ef52b199-1b69-4703-9124-e0681f08eb3a)

### Describe the behavior you expected

I would expect all cards to display the same and pick up unit of measure.  In this case I would expect them all to say 8ms not 0.008

### Steps to reproduce the issue

1. Install and configure speedtest integration (although I suspect this will be the same for any duration sensor)
2. Add ping sensor to different cards

### What version of Home Assistant Core has the issue?

2023.11.1

### In which browser are you experiencing the issue with?

Google Chrome 119.0.6045.106

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
State is 8
Attributes are
state_class: measurement
server_name: London
server_country: United Kingdom
server_id: "40788"
unit_of_measurement: ms
attribution: Data retrieved from Speedtest.net by Ookla
device_class: duration
icon: mdi:speedometer
friendly_name: SpeedTest Ping
```

### Problem-relevant frontend configuration

```yaml
title: Testing
views:
  - title: ping
    path: ping
    badges: []
    cards:
      - type: entity
        entity: sensor.speedtest_ping
      - type: tile
        entity: sensor.speedtest_ping
      - type: entities
        entities:
          - entity: sensor.speedtest_ping
      - type: glance
        entities:
          - entity: sensor.speedtest_ping
      - graph: line
        type: sensor
        detail: 1
        entity: sensor.speedtest_ping
```

**Comment by ildar170975** [comment] 2023-11-07 15:41
Suggestion:
If a sensor has “device_class: duration” and it’s state is less than 1 sec - show a state in a numeric format with UoM; if more than or equal to 1 sec - show in “duration format”, i.e. as “hh:mm:ss”.

**Comment by Morgane-dotcom** [comment] 2023-11-10 16:25
I have the same issue.
It worked fine until HA version 2023.9.3 : 'ms' units were displayed properly in entity cards.
Whatever change was made in the later versions should be reverted

**Comment by mat4444** [comment] 2023-11-11 16:21
To make it clear for the devs, here is how it was displayed in an entity card in version 2023.9.x :
![image](https://github.com/home-assistant/frontend/assets/53400792/44609176-1a2f-4f36-9ade-577786174004)

That's how it shows now in version 2023.11.x
![image](https://github.com/home-assistant/frontend/assets/53400792/23c8cbca-ab14-426b-b31b-856ca6edb8a8)

The old formatting was much more clear

**Comment by Manuel1948** [comment] 2023-11-28 06:10
hope this will be fixed soon, also raised this bug a few weeks before

**Comment by mat4444** [comment] 2024-01-04 03:38
Still the same issue in 2024.1 release. Is there any plan to revert back the changes made on time entities ?

**Comment by wigster** [comment] 2024-01-10 21:43
This is also a problem with sensors with large durations — I have a few with states of months or even 100 days (eg time to service of a car). This is also displayed in hours.

**Comment by karwosts** [comment] 2024-01-15 14:47
Believe this is a duplicate of #18151, so I will close this as a duplicate. 

I did merge a change there to hopefully improve the situation, you can read about it there.

**Closed by karwosts** 2024-01-15 14:47 UTC
