### ISSUE TITLE
Demo website Energy tab does not load data

### ISSUE THREAD

**Issue by martivilella** [home-assistant/frontend#12775] opened 2022-05-25 10:23 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The Energy tab in the home-assistant.io Demo page shows empty graph and loading texts.

### Describe the behavior you expected

Populated graphs with sample data

### Steps to reproduce the issue

1. Open the Energy tab of the Demo website: [https://demo.home-assistant.io/#/energy](https://demo.home-assistant.io/#/energy)

### What version of Home Assistant Core has the issue?

na

### In which browser are you experiencing the issue with?

Mozilla Firefox 91.9.0esr

### Which operating system are you using to run this browser?

Windows 10 20H2

**Comment by spacegaier** [comment] 2022-05-25 17:43
Duplicate of https://github.com/home-assistant/frontend/issues/12500

**Closed by spacegaier** 2022-05-25 17:43 UTC
