### ISSUE TITLE
/config/system panel in not more visible after the last update

### ISSUE THREAD

**Issue by aldaha** [home-assistant/frontend#13740] opened 2022-09-14 09:15 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The panel /config/system is blank after the last update of Home Assistant OS
Home Assistant 2022.9.3
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.1 - latest
The other panel is fine.

### Describe the behavior you expected

view system panel

### Steps to reproduce the issue

1. go to http://homeassistant.local/config/system
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.9.3

### What was the last working version of Home Assistant Core?

2022.9.2

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102

### Which operating system are you using to run this browser?

windows 10

**Comment by ludeeus** [comment] 2022-09-14 09:16
Duplicate of https://github.com/home-assistant/frontend/issues/13728

fixed Home Assistant in 2022.9.4

**Closed by ludeeus** 2022-09-14 09:16 UTC
