### ISSUE TITLE
ios companion app on ios 14 beta 5

### ISSUE THREAD

**Issue by VaughanGerson** [home-assistant/frontend#6657] opened 2020-08-20 08:49 UTC
Hey,

I recently updated to ios 14 beta 5 and wanted to let you know that after updating a few hours ago the ios mobile app no longer works correclty, the app launches but as soon as you try and tap on any sensor the app crashes.

**Comment by bramkragten** [comment] 2020-08-20 10:45
Duplicate of #6654

**Closed by bramkragten** 2020-08-20 10:45 UTC
Labels: bug
