### ISSUE TITLE
Calendar translations missing

### ISSUE THREAD

**Issue by breti** [home-assistant/frontend#8337] opened 2021-02-06 09:17 UTC
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Since core-2021.2.0 or core-2021.2.1, calendar resources like button labels aren't translated anymore.

![grafik](https://user-images.githubusercontent.com/3628895/107114109-aa1cd780-6863-11eb-933c-0387cbfa9465.png)

## Expected behavior

I'd expect to see translated texts for "today" and "My Calendars"

## Steps to reproduce

Just add a calendar to home assistant. Side-Panel and lovelace card view are affected.

## Environment

- Home Assistant release with the issue: core-2021.2.1
- Last working Home Assistant release (if known): core-2021.1.5
- Browser and browser version: FF 85.0.1, Chrome 88.0.4324.150
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

There are no errros logged.

```txt

```

## Additional information

Perhaps related to https://github.com/home-assistant/frontend/pull/8235?

**Comment by spacegaier** [comment] 2021-02-06 19:58
Yes, my PR you mentioned fixed a general translation loading error for the calendars, but that meant we had to move some translation keys. Now the actual translations need to catch up. For German I had already added the new ones after the PR but they had to be fetched and will be incorporated in the next frontend release.

So not a bug, but just regular translation topic.

**Closed by spacegaier** 2021-02-06 19:58 UTC
Labels: bug
