### ISSUE TITLE
User interface do not work with id but names when same name of entities allowed

### ISSUE THREAD

**Issue by pyramidak** [home-assistant/frontend#13520] opened 2022-08-30 12:33 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is allowed and ok:
name:Kitchen;entity_id:light.kitchen
name:Kitchen;entity_id:switch.kitchen
name:Kitchen;entity_id:fun.kitchen

But your user interface (script, automation) does not work with id of entity, but with name.
I choose fun.kitchen, but always first one light.kitchen is selected.

### Describe the behavior you expected

When I choose fun.kitchen, the interface should really select fun.kitchen.

### Steps to reproduce the issue

1. when you programm selection list and name is not unique
2. selection list has always visible item name and hidden item id
3. when user choose name, item list should return id
...

### What version of Home Assistant Core has the issue?

latest

### What was the last working version of Home Assistant Core?

who knows if ever

### Additional information

I´ve just paid a year subscription of NabuCasa. So no rush to fix this. Let others to feel it. Your HA loyal user.

**Comment by ildar170975** [comment] 2022-08-30 19:31
https://github.com/home-assistant/frontend/issues/13412#issuecomment-1221024129

**Comment by spacegaier** [comment] 2022-09-05 19:53
Sound like a duplicate of https://github.com/home-assistant/frontend/issues/12889

**Closed by spacegaier** 2022-09-05 19:53 UTC
