### ISSUE TITLE
Cannot edit text in Lovelace cards on IOS devices

### ISSUE THREAD

**Issue by KennethLavrsen** [home-assistant/frontend#8848] opened 2021-04-07 21:28 UTC
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Open HA in Safari on iPad.
Edit Dashboard
Try to edit a normal entity card.
Use the Show Code Editor mode
Try and type something. Watch a character being entered and the cursor jumping away. Note that backspace does not work making it impossible to edit existing text

### Describe the behavior you expected

Normal text editing

### Steps to reproduce the issue

Open HA in Safari on iPad.
Edit Dashboard
Try to edit a normal entity card.
Use the Show Code Editor mode
Try and type something. Watch a character being entered and the cursor jumping away. Note that backspace does not work making it impossible to edit existing text

### What version of Home Assistant Core has the issue?

core-2021.4.0

### What was the last working version of Home Assistant Core?

core-2021.3.4

### In which browser are you experiencing the issue with?

Safari on IOS

### Which operating system are you using to run this browser?

IOS fully up to date

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

**Comment by KennethLavrsen** [comment] 2021-04-07 21:31
Same in Google Chrome on IOS (which we all know share library with Safari) but then I am sure it is not a cache problem because that was first time I logged in with that browser on my HA

**Comment by KennethLavrsen** [comment] 2021-04-08 06:55
Confirmed problem is also on IOS on iPhone

**Comment by LEJOUI** [comment] 2021-04-10 12:55
In addition I also can’t edit texts in the developer tools.

**Comment by KennethLavrsen** [comment] 2021-04-11 12:49
Extra info. I do not see the problem in the CodeMirror 6 demo pages. And yes. I have cleared the cache. I have tried on my wife’s ipad and she never previously edited code anywhere. It is not a cache issue. Something in HA is implemented so CodeMirror does not work. And it is related to control of the cursor position.

**Comment by spacegaier** [comment] 2021-04-11 14:23
Presumably the CM6 demo pages use their latest library version. In the last couple of weeks they released some patch versions that might fix some of the issues. Bram is already looking into bumping our dependencies to the newer versions.

**Comment by pedolsky** [comment] 2021-04-11 16:19
Even directly in the app I can’t edit text in cards or raw config editor.

**Comment by emufan** [comment] 2021-04-15 19:09
I second this. Editing is completely destroyed with 2021.4. Before is was already bad (copy and paste) was only possible line by line and not for selected blocks, but now nothing is possible anymore. Backspace results in nothing. Entering characters enter them always at the beginning from the whole yaml file currently in editor. Etc etc.

**Comment by spacegaier** [comment] 2021-04-15 19:55
As I wrote [here ](https://community.home-assistant.io/t/2021-4-for-our-advanced-users/297058/671?u=spacegaier)earlier today:

The above mentioned `codemirror` component versions bump unfortunately according to Bram did not solve the reported issue. We need a minimal reproducible example for the upstream `codemirror` library. The issue [was raised there](https://github.com/codemirror/codemirror.next/issues/414) a few weeks ago already, but they could not reproduce it in vanilla (confirmed also here by users via their demo page).

=> We need leads in the code or something reproducible for the `codemirror` maintainers. Help very much welcome!

**Comment by emufan** [comment] 2021-04-15 20:46
Hm. Didn't get this. Isnt it reproducible for everyone? Or is it working for some users? Didn't read until now, that it is working anywhere. 

And yes, demo page vanilla is working here as well. Including block copy and paste, what was not working here in the last versions.

**Comment by spacegaier** [comment] 2021-04-15 21:22
I assume the issue is reproducible for all iOS users, but not in vanilla `codemirror`. So either it is an issue inside `codemirror` itself, that just not takes effect on their demo page or it is specific to the HA usage of `codemirror`. Depending on that we either need a reproducible example for the `codemirror` maintainers or we need to understand where HA interferes.

Until someone finds either of those, a fix will not materialize itself.

**Comment by emufan** [comment] 2021-04-16 06:44
Still not understand, for what who is looking for in terms of reproducible example. It's reproducible on every ios device in mobilde safari in every installation.

Or e.g. go to https://demo.home-assistant.io/#/lovelace/0 and you have the same reproducible example, if you edit the lovelace and go to the yaml mode in any card.. It behaves slightly different than in the app, but it is impossible to edit anything as well.

**Comment by bramkragten** [comment] 2021-04-16 12:39
It is not for the Home Assistant devs, but the CodeMirror devs.

Created a repo for them (<https://shrub-smoggy-phosphorus.glitch.me/>), so hopefully, they will fix this soon.

**Comment by bramkragten** [comment] 2021-04-16 14:32
Duplicate of https://github.com/home-assistant/frontend/issues/8542

**Closed by bramkragten** 2021-04-16 14:32 UTC
Labels: bug, code-editor, safari
