### ISSUE TITLE
More-info card overflow on attributes

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant/frontend#18027] opened 2023-09-26 13:29 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

![Sep-26-2023 15-24-13](https://github.com/home-assistant/frontend/assets/33354141/4421888c-9c79-4812-b7ef-496d911ce7e8)

also note the odd font.
I have set no font family anywhere, so this should be using system default

### Describe the behavior you expected

all of the attribute to remain inside the card

### Steps to reproduce the issue

1. see yaml below
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.9.3

### In which browser are you experiencing the issue with?

Chrome, Safari

### Which operating system are you using to run this browser?

macOS 13.6

### Additional information

```
      - unique_id: persistent_notifications_overview
        device_class: timestamp
        state: >
          {{now()}}
        attributes:
          notifications: >
            {% set msgs = this.attributes.get('notifications',[]) %}
            {% if trigger.id == 'start' %}
              {{[]}}
            {% elif trigger.update_type == 'added' %}
              {% set new =
               [ {"id": trigger.notification.notification_id,
                  "title": trigger.notification.title,
                  "message": trigger.notification.message,
                  "created_at": trigger.notification.created_at.isoformat()} ]%}
              {{msgs + new}}
            {% else %}
              {{msgs|rejectattr('id','eq',trigger.notification.notification_id)|list}}
            {% endif %}
# unique: https://community.home-assistant.io/t/heads-up-2023-6-longer-has-persistent-notifications-in-states-what-to-do/578654/135
          history: >
            {%- set previous = this.attributes.history|default([]) %}
            {% if trigger.update_type == 'added' %}
            {% set new = [{
                "id": trigger.notification.notification_id,
                "title": trigger.notification.title,
                "message": trigger.notification.message,
                "created_at": trigger.notification.created_at.isoformat()}] %}
            {{previous[-3:] + new}}
            {% else %} {{previous[-4:]}}
            {% endif %}
```

**Comment by karwosts** [comment] 2023-09-26 14:05
Duplicate of #17932

**Closed by karwosts** 2023-09-26 14:05 UTC

**Comment by Mariusthvdb** [comment] 2023-09-26 15:36
sorry for the duplicate, missed it because of the title I suppose.
