### ISSUE TITLE
Energy Distibrution hardware acceleration high GPU usage

### ISSUE THREAD

**Issue by ricko1** [home-assistant/frontend#17941] opened 2023-09-16 19:40 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open the energy tab my gpu usage goes up a lot. It causes stuttering/freezes when browsing with background compute tasks.

In Google Chrome it's about 6% on my RTX 3070 at 1815mhz (I have seen it use 20 to 30% at lower clocks)
In Firefox it's about 11%, Edge is also about 6%

Using 1/10th of a mid-high end GPU to render such a simple animation is unacceptable.

I have pinpointed the problem to the Energy Distribution card (widget?) with the moving dots representing energy flow. That got automatically added to the overview tab and deleting it removed the problem from the overview tab.
 
Trying it on my 2014 Windows 10 laptop with Intel HD 4600 graphic's and the result is 1% usage with Chrome. That is okay since it's rounding up.
However in Firefox it's 22% usage on the HD 4600. That means the issue is not Nvidia related.

Disabling hardware acceleration also fixes it (obviously)

### Describe the behavior you expected

<1% gpu usage for rendering just 3 simple dots.

### Steps to reproduce the issue

1. Open task manager. performance tab -> GPU
2. Open chrome, firefox or edge 
3. Open home assistant energy dashboard (with configured solar and grid usage)
4. View task manager 3D graph

### What version of Home Assistant Core has the issue?

All versions this year since setup in februari

### In which browser are you experiencing the issue with?

Chrome, Firefox and edge on multiple pc's, all versions this year so far

### Which operating system are you using to run this browser?

Windows 10

### Additional information

System specs:
Ryzen 5800X
64 GB 3600mhz RAM
Asus TUF RTX 3070
1TB 980 pro SSD
Windows 10 pro 64bit

**Comment by karwosts** [comment] 2023-09-16 23:54
Duplicate of #13816

**Closed by karwosts** 2023-09-16 23:54 UTC
