### ISSUE TITLE
Views visibility - bug

### ISSUE THREAD

**Issue by josefkrtil** [home-assistant/frontend#6650] opened 2020-08-19 08:00 UTC
User is able to see first View at dashboard although he has set up visibility of this View to NO. Second and other is not visible. If you change order of Views, than the new  first View is visible. You do not see title or icon, but you can see first View. If you change another view (with title or icon) you are not able to see first View again. If you change panel and will go back to overview, than you can see first of all Views again without permission to see it.

**Comment by bramkragten** [comment] 2020-08-19 08:06
Duplicate of #5327

**Closed by bramkragten** 2020-08-19 08:06 UTC
