### ISSUE TITLE
Area Dashboard is only showing Battery as alert class, if entity is not diagnostic

### ISSUE THREAD

**Issue by ChristophCaina** [home-assistant/frontend#20968] opened 2024-06-03 09:05 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the Area Card, you can setup battery entities as alarm device.
![grafik](https://github.com/home-assistant/frontend/assets/26391061/b9e54118-d625-4837-a755-4f2a12191329)

It seems, that this is only working, if the Battery information is setup as regular entity... like in the above case, my weatherstation.
![grafik](https://github.com/home-assistant/frontend/assets/26391061/d4c4db23-7ed5-49fa-bb37-57328cb20671)

You cannot setup the battery in the Area Card, if the battery entity is within the diagnostic section, like the battery information from my window sensor in the bathroom.
![grafik](https://github.com/home-assistant/frontend/assets/26391061/a2cd7463-36da-4c7d-8626-4d1f6245c1d2)
![grafik](https://github.com/home-assistant/frontend/assets/26391061/11273e27-bd92-46c6-b37e-01d94d5066f4)

I've already created an issue within core - but I am not sure, if this is a core issue or a frontend topic ...?
https://github.com/home-assistant/core/issues/118361

### Describe the behavior you expected

The Area Card should be able to access battery information, even if the battery entity was created as "diagnostic" device.

### Steps to reproduce the issue

1. Create two areas
2. for both areas, create entities... 
2 a. device in area 1 should have a battery entity as diagnostic
2 b. device in area 2 should have a battery entity as regular sensor
3. try to configure battery information for both areas as alert class.
...

### What version of Home Assistant Core has the issue?

2024.6.0b6

**Comment by karwosts** [comment] 2024-06-03 12:37
Duplicate of #19951

**Closed by karwosts** 2024-06-03 12:37 UTC
