### ISSUE TITLE
Generated Lovelace can't update on/off state for scripts

### ISSUE THREAD

**Issue by OleksandrBerchenko** [home-assistant/frontend#5527] opened 2020-04-12 12:55 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Generated Lovelace UI is not able to update on/off state of scripts.

## Expected behavior

On/off state of scripts correctly updates in near real-time (like on the old "states" UI).

## Steps to reproduce

1. On a generated Lovelace UI find a script with a toggle switch not "Execute" button (any script with wait or delay inside).
2. Turn the script on:
- The script is running, but UI toggle immediately returns to Off state.
3. Refresh the page:
- UI toggle correctly displays On state.
4. Turn the script off:
- The script successfully stops running, but UI toggle immediately returns to On state.
5. Refresh the page:
- UI toggle correctly displays Off state.

## Environment

- Home Assistant release with the issue: 0.108.3, frontend version: 20200407.2
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Firefox 74.0 + Chrome 80.0
- Operating system: Windows 10

## Problem-relevant configuration

n/a

## Javascript errors shown in your browser console/inspector

n/a

## Additional information

n/a

**Comment by iantrich** [comment] 2020-04-14 03:01
duplicate of #3276

**Closed by iantrich** 2020-04-14 03:01 UTC
Labels: bug
