### ISSUE TITLE
Quickbar shortcuts "e" & "c" trigger the quickbar when typing in some text fields on a mobile device

### ISSUE THREAD

**Issue by rccoleman** [home-assistant/frontend#7517] opened 2020-10-28 22:01 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The new Quickbar shortcuts ("e" and "c") trigger the Quickbar when typing into some text boxes.  Examples are typing into the dev->Templates or the service data field of dev->Services, or (I'm told) editing automations.  There may be others.  This behavior seems to be limited to mobile devices (I use an iPhone) and I don't see the behavior in my desktop browser (Chrome).

## Expected behavior

The Quickbar shortcuts should not trigger when typing text into a textbox, or maybe not at all on a mobile device.  Maybe only if a physical keyboard is attached, such as with an iPad?

## Steps to reproduce

Go to Dev->Services or Dev->Templates on an iOS device and hit "c" or "e" in the text box for service data or the template text field.  Note that the Quickbar appears.

## Environment

- Home Assistant release with the issue: 0.117
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Official Home Assistant iOS app
- Operating system: iOS 14.1

## State of relevant entities

None

## Problem-relevant configuration

None

## Javascript errors shown in your browser console/inspector

None

**Comment by bpottle1** [comment] 2020-10-28 22:14
I also get the same effect with the quick bar on mobile when in the script or automation editors. It only happens when typing in a text field for yaml though. i.e. editing in yaml in the UI or editing a portion of the automation in yaml, like variables.

**Comment by SeanPM5** [comment] 2020-10-28 22:46
This issue also occurs on the official macOS app too (which shares the same codebase as iOS app).

Go to **Developer Tools** -> **Services**, select `notify.mobile_app_your_macbook_pro` service. When you attempt to type "message" into the "Service Data" text field it'll open the Quick Bar entity filter mode.

As a temporary solution you can disable Keyboard Shortcuts on your profile page while on your mobile device. The preference is device specific.

**Comment by rccoleman** [comment] 2020-10-28 22:55
Good call on disabling.  I forgot they added that, and it will be perfect on the phone.

**Comment by donkawechico** [comment] 2020-10-29 00:34
> This issue also occurs on the official macOS app too

Weird. It doesn't repro for me on macOS app O_o. I assume the macOS app is just a web view and doesn't need to be updated?

**Comment by donkawechico** [comment] 2020-10-29 01:32
Unfortunately, I can't repro this issue anywhere. Let alone on something I have development access to.

But @zsarnett was able to reproduce the issue on iOS safari using browserstack, and I think I know why the issue is occurring, but the fix would be pretty sloppy and brittle.

I think the solution here is to find some way of detecting mobile app users and disabling keyboard shortcuts completely. Finding another triggering input entirely (like a button) for mobile.

**Comment by SeanPM5** [comment] 2020-10-29 02:15
Yeah that's correct. Should be fixable in the frontend without requiring a new app build.

I can reproduce it in the macOS app (2020.7 10) but not in desktop Safari (14.0.1) - I'm on macOS Big Sur public beta if that makes a difference. I can reproduce this in mobile Safari (iOS 14.2) so it's browser-related rather than app-related.

One thing to note - on iPhone/mobile, the Quick Bar dialog takes up the entire screen. You can't tap away from it nor is there an ESC key to press on iOS virtual keyboard. So the only way to dismiss the QB is by selecting an entity and then closing the more-info dialog. Which makes this bug feel a tad more clunky.

**Comment by rccoleman** [comment] 2020-10-29 02:18
Right, I have to select something and then hit the "x" to dismiss the dialog to get back to what I was doing.

**Comment by donkawechico** [comment] 2020-10-29 04:13
Well I think I have a fix for mobile at least. But since I can't repo on the macOS app I'm not sure if it'll fix there. I suspect it won't since it wouldn't have a mobile userAgent.

**Closed** 2020-10-29 16:18 UTC
Labels: bug

**Comment by donkawechico** [comment] 2020-10-30 00:45
I believe this should be fixed for mobile in the next patch. If it's not, please re-open the issue.

If the issue appears in macOS app, please open a new issue.

**Comment by SeanPM5** [comment] 2020-10-30 18:07
Just confirming it's fixed on both iOS and macOS after the 0.117.1 patch 👍
