### ISSUE TITLE
Energy dashboard does not show correct values in custom range

### ISSUE THREAD

**Issue by teodorch85** [home-assistant/frontend#19850] opened 2024-02-21 17:50 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In energy dashboard using custom range the values are not correct.
Only the low carbon is changing when changing range.

![image](https://github.com/home-assistant/frontend/assets/8177657/3ae3be05-74bc-4e2d-a76e-fa6b85227774)

![image](https://github.com/home-assistant/frontend/assets/8177657/325b2462-43ed-48ba-8fbb-149288e73210)

@TillFleisch reproduced the problem

              @teodorch85, please open a separate issue for this (if there isn't already one), so that we can keep track of this issue. I too can replicate this on a (core 2024.2.2/front 20240207.1) instance. The reported values don't change, once enough days have been selected so that "months" are shown in the bar charts. Adding a day in this scenario does not change the values when it should. Note that the low-carbon circle does change.

_Originally posted by @TillFleisch in https://github.com/home-assistant/frontend/issues/14337#issuecomment-1957375449_

### Describe the behavior you expected

Using the addon below the values are correct
https://github.com/flixlix/energy-period-selector-plus

![image](https://github.com/home-assistant/frontend/assets/8177657/8a4b2fef-cad7-495e-a1ee-0a399d52da40)

### Steps to reproduce the issue

1. Energy dashboard
2. Select custom range
3. Change range and the values do not change
...

### What version of Home Assistant Core has the issue?

2024.2.2

**Comment by karwosts** [comment] 2024-03-01 17:03
Seems that the backend just does not handle statistics requests where the start time is not aligned with the period in the way that is expected.

If you say you want monthly statistics, than it always returns the full month's summary, regardless to if you set the starttime of the request for the 1st, or the 30th, or anywhere in between.

I guess our options for dealing with this would be:

 - Backend change to behavior (unlikely?)
 - Always request full hourly resolution and summarize in the frontend (seems inefficient, but this is probably what period-selector-plus does)
 - Somehow change the picker to reflect that this is an invalid selection when using monthly resolution.
 
 Curious if we would ever want to support user chosen resolution as well, instead of hardcoding monthly resolution at >35 days, the answer to this might be tied up with the answer to that.

**Comment by karwosts** [comment] 2024-03-03 14:28
Realize this is a duplicate of older bug #18883, so close this as duplicate.

**Closed by karwosts** 2024-03-03 14:28 UTC
Labels: panel: energy
