### ISSUE TITLE
Automation/Script Editor break delay

### ISSUE THREAD

**Issue by skycryer** [home-assistant/frontend#5542] opened 2020-04-15 10:27 UTC
## The problem
I moved my scripts into scripts.yaml to use script editor, same for automations. If I now try to edit the script/automation the delay data got loaded as [object Object] so I am not able to edit it. And saving break the script/automation because it also get written into files as [object Object]. 

## Environment
Home Assistant 0.108.3

- Home Assistant Core release with the issue: 0.108.3
- Last working Home Assistant Core release (if known): Never
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker
- Integration causing this issue: 
- Link to integration documentation on our website: 

## Problem-relevant `scripts.yaml`

```yaml
bedroom_underground_light_off:
  alias: Schalte Untergrund Bett Beleuchtung nach 30 Sekunden aus
  sequence:
  - delay:
      seconds: 30
  - service: switch.turn_off
    data:
      entity_id: switch.bedroom_bed_light_switch

```

## Traceback/Error logs

```txt

```

**Comment by T-bond** [comment] 2020-08-01 19:37
![image](https://user-images.githubusercontent.com/3778556/89109152-ec8dd380-d43e-11ea-8c1a-d6eaf835aeb2.png)
Still happens on: 113.3

```YAML
  - delay:
      milliseconds: 200
```

**Comment by HugoPeters1024** [comment] 2020-09-04 21:59
I am experiencing the same issue, as described in this issue which turned out to be a duplicate: #6164

**Comment by skycryer** [comment] 2020-12-04 10:38
Problem is still the same on 0.118.4, no fix yet

**Comment by emufan** [comment] 2021-01-24 15:04
Still there in 2021.1. Heard from this old bug, because I opened the same [here](https://github.com/home-assistant/frontend/issues/8200). Thanks for pointing here spacegaier.

**Comment by i00** [comment] 2021-01-25 06:40
Duplicate of #4733

**Closed** 2021-01-27 09:46 UTC
Labels: editor: automation, editor: script
