### ISSUE TITLE
Missing text in translation - automatization

### ISSUE THREAD

**Issue by misa1515** [home-assistant/frontend#18894] opened 2023-12-04 19:33 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words in translation (screenshots attached)

![Screenshot](https://github.com/home-assistant/frontend/assets/61636045/cc1a5e10-c190-4866-b04f-55bedb0bd7fe)

![Screenshot2](https://github.com/home-assistant/frontend/assets/61636045/a7b73c69-84c7-4f90-89ab-6f0cd243e0fa)

![Screenshot3](https://github.com/home-assistant/frontend/assets/61636045/66f3fec1-d470-4f2b-b22e-7b3c22cca80e)

![Screenshot4](https://github.com/home-assistant/frontend/assets/61636045/fb748b3d-b4e3-4b5c-95c6-fcf9809836b2)

![Screenshot5](https://github.com/home-assistant/frontend/assets/61636045/f3735b86-cfca-4269-8078-5478da2cb61c)

![Screenshot6](https://github.com/home-assistant/frontend/assets/61636045/89103d9d-a788-4010-b48c-f1de56987ce8)

![Screenshot7](https://github.com/home-assistant/frontend/assets/61636045/7e28bdb1-5ad9-4c1b-87a4-06a531429a20)

### Describe the behavior you expected

Please add missing words to translation

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.11.3

### What was the last working version of Home Assistant Core?

not relevant

**Comment by karwosts** [comment] 2024-01-05 00:44
Many of these have been addressed, also mostly duplicate of #18362

**Closed by karwosts** 2024-01-05 00:44 UTC
Labels: localization
