### ISSUE TITLE
Entity ID Color

### ISSUE THREAD

**Issue by milandzuris** [home-assistant/frontend#17126] opened 2023-06-30 20:28 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Entity ID is too Dark, on some monitors i don't see ID
![image](https://github.com/home-assistant/frontend/assets/42905545/e02ba8fd-babe-44a0-9be4-bfeece3b68a2)

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

2023.7.0b3

**Comment by karwosts** [comment] 2023-06-30 21:07
Duplicate of #17110

already fixed

**Closed by karwosts** 2023-06-30 21:07 UTC
