### ISSUE TITLE
After core-2021.11.0 & core-2021.11.1 Update, HA Mobile & Fully Browser on tablets, stuck on "Loading Data"

### ISSUE THREAD

**Issue by pickonedev** [home-assistant/frontend#10563] opened 2021-11-04 16:38 UTC
### The problem

Hi!

After I updated to core-2021.11.0, the android application Home Assistant, it is not working anymore.
When I open the android app, it got stuck on "Loading Data".
The only workaround is to restart Home Assistant Server but keep the android app running with "Loading Data". After the server has started, the android app will work as well, till I close the app and reopen...
Everytime I open the android app, I must restart server to make it works.
On my phone there is no such problem, only on my Huawei T10s tablets.

### What version of Home Assistant Core has the issue?

core-2021.11.0 & core-2021.11.1

### What was the last working version of Home Assistant Core?

core-2021.10.7

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

-

**Comment by balloob** [comment] 2021-11-07 15:56
Moved this to the frontend. Do you know what timezone is being sent by Kiosk Browser? Seems like it's not a correct one.

**Comment by Jpsy** [comment] 2021-11-07 16:57
@balloob: 
The timezone is correct on Fully. But it is used for a polyfill which has a missing timezone list. 
See https://github.com/home-assistant/frontend/issues/10548 for a complete analysis.

**Comment by balloob** [comment] 2021-11-07 17:30
Thanks, marking this as duplicate of #10548

**Closed by balloob** 2021-11-07 17:30 UTC

**Comment by Jpsy** [comment] 2021-11-09 17:59
Solved in 2021.11.2.
MANY THANKS!

**Comment by pickonedev** [comment] 2021-11-11 16:56
Yes, the actual problem has been solved.

Now I found another issue.
Sometimes the application from the tablets it is closing by itself.
I have 6 tablets in my house, I am use them as light switches and stuff, but after this 2021.11.2 update, I find that often, the application dissapear from screen and I need to reopen manually the app

Anybody have this problem as well?

**Comment by xfader2018** [comment] 2021-11-11 18:44
Don't hijack this topic for your other problem but create your own topic.

**Comment by xfader2018** [comment] 2021-11-11 18:44
> Yes, the actual problem has been solved.
> 
> Now I found another issue. Sometimes the HA application from the tablets it is closing by itself. I have 6 tablets in my house, I am using them as light switches and stuff, but after this 2021.11.2 update, I find that often, the application dissapear from screen and I need to reopen manually
> 
> Anybody have this problem as well?
> 
> I thought that the problem appear from the new HACS addon which I installed (Browser_Mod), but today I have uninstalled the mod and the issue still persists...

Don't hijack this topic for your other problem but create your own topic.

**Comment by pickonedev** [comment] 2021-11-11 18:45
> 
> 
> > Yes, the actual problem has been solved.
> > Now I found another issue. Sometimes the HA application from the tablets it is closing by itself. I have 6 tablets in my house, I am using them as light switches and stuff, but after this 2021.11.2 update, I find that often, the application dissapear from screen and I need to reopen manually
> > Anybody have this problem as well?
> > I thought that the problem appear from the new HACS addon which I installed (Browser_Mod), but today I have uninstalled the mod and the issue still persists...
> 
> Don't hijack this topic for your other problem but create your own topic.

If you didn't look, it is my own topic as well 🥇

**Comment by xfader2018** [comment] 2021-11-11 18:49
No I didn't look that is my bad but you shouldn't consolidate issues into one topic imho. 🙏🏻
