### ISSUE TITLE
Energy sensors bar / hint order mismatch

### ISSUE THREAD

**Issue by gec75** [home-assistant/frontend#16423] opened 2023-05-05 09:46 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It's a restively small issue, but a little annoying.
I have three energy sensors which are visible in the energy dashboard.
There is no legend in the top (bar) diagram, only a hint/popup window when moving with the mouse over a bar.
What I don't like is, the visual vertical ordering of the sensors are reversed. 
I hope the screenshot is self-describing.
![image](https://user-images.githubusercontent.com/6347511/236426458-c038749d-47bd-4a83-9708-1f12347f11b3.png)

The colors are also not very distinctive, but that's another issue.

### Describe the behavior you expected

I would like to see the same vertical order.

### Steps to reproduce the issue

1. Add at least 2 energy sensors and wait for data to appear on the energy dashboard
2. Move the mouse over any bar

### What version of Home Assistant Core has the issue?

2023.5.1

**Comment by karwosts** [comment] 2023-06-24 22:49
Duplicate of #12996

**Closed by karwosts** 2023-06-24 22:49 UTC
