### ISSUE TITLE
Cover Icon for STOPPED State

### ISSUE THREAD

**Issue by uspass** [home-assistant/frontend#9102] opened 2021-05-05 09:38 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When STOP is done during OPENING or CLOSING, the cover icon shows "hass:garage-open" or "hass:garage" respectively.
As far as I can tell there is no way (beside actually seeing the garage door) to distinguish between this state and OPEN state (or CLOSED state respectively) on the front end screen.
I reckon this comes from frontend/src/common/entity/cover_icon.ts file.
.....
  switch (stateObj?.attributes.device_class) {
    case "garage":
      switch (state) {
        case "opening":
          return "hass:arrow-up-box";
        case "closing":
          return "hass:arrow-down-box";
        case "closed":
          return "hass:garage";
        default:
          return "hass:garage-open";
      }
....
I reckon the problem might be solve by adding:
        case "stopped":
          return "hass:garage-alert";

### Describe the behavior you expected

When STOP is done during OPENING or CLOSING, the cover icon should show "hass:garage-alert", or any other relevant icon, different from "hass:garage-open", "hass:garage"

### Steps to reproduce the issue

1. Garage door is OPEN. The icon shows "hass:garage-open"
2. Press CLOSE. The state is CLOSING. The icon shows "hass:arrow-down-box"
3. Press STOP. The state is STOPPED. The icon shows "hass:garage" as in step 4,  which doesn't reflect the real status. The door is partially closed.

4. Garage door is CLOSED. The icon shows "hass:garage"
5. Press OPEN. The state is OPENING. The icon shows "hass:arrow-up-box"
6. Press STOP. The state is STOPPED. The icon shows "hass:garage-open"as in step 1, which doesn't reflect the real status. The door is partially open.

### What version of Home Assistant Core has the issue?

core-2021.4.6

### Problem-relevant frontend configuration

```yaml
Cover.yaml
- platform: mqtt
  name: "Usa Garaj"
  unique_id: 'Cover-25-25-F3'
  device_class: garage
  state_topic: 'stat/GarageDoor/STATE'
  state_open: 'OPEN'
  state_closed: 'CLOSED'
  state_opening: 'OPENING'
  state_closing: 'CLOSING'
  state_stopped: 'STOPPED'
  command_topic: 'cmnd/GarageDoor/EVENT'
  payload_open: 'OPEN'
  payload_close: 'CLOSE'
  payload_stop: 'STOP'
  availability_topic: 'tele/GarageDoor/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  optimistic: false
```

**Comment by spacegaier** [comment] 2021-05-05 17:03
Initial gut feeling: Your proposal feels a bit wrong, since the frontend should not assume a state but instead the frontend should only render what the backend tells it to. If the garage is open and something starts the closing process, but then stops it, it is up to the backend to determine the correct state. IMHO "open" would still be correct as the garage has not reported that it is closed now. It also might be by design that a user only wanted to half close it (car too long or something sticking out currently or some work being done in the garage that requires air circulation but door is half closed to reduce noise getting out). Equating that to an alert state might therefore not be correct either.

**Comment by uspass** [comment] 2021-05-05 19:10
> 
> 
> Initial gut feeling: Your proposal feels a bit wrong, since the frontend should not assume a state but instead the frontend should only render what the backend tells it to. If the garage is open and something starts the closing process, but then stops it, it is up to the backend to determine the correct state. IMHO "open" would still be correct as the garage has not reported that it is closed now. It also might be by design that a user only wanted to half close it (car too long or something sticking out currently or some work being done in the garage that requires air circulation but door is half closed to reduce noise getting out). Equating that to an alert state might therefore not be correct either.

I reckon you don't get the problem. During opening if you press on the entity card the stop button in the middle of opening, one can't see in the frontend if the door is fully closed or somewhere in between.
For the second part of your comment,  I have mentioned the garage-alert icon (and I said "or any other relevant icon") because I couldn't find a, say, half open garage door icon in the mdi. It is not an alert.

**Comment by uspass** [comment] 2021-05-05 19:11
Sorry, closed by mistake

**Comment by spacegaier** [comment] 2021-05-05 19:41
> 
> I reckon you don't get the problem. During opening if one presses on the entity card the stop button in the middle of opening, one can't see in the frontend if the door is fully closed or somewhere in between.

Yes, because the frontend doesn't really know. We use the state value that the backend provides and that is currently "open" ( technically `default`) or "closed". Some covers can provide a percentage value for the opening state, but probably not all. So relying on that won't work for all (would require some sort of support flag similar to dimming/brightness for lights).

**Comment by uspass** [comment] 2021-05-05 20:28
So, basically you say it is better not to have a status indicator for the stop command which would reflect the actual state.
That means you prefer to have an image which is ambiguous, not knowing if the door is really closed or stopped in the middle of opening.
Well, it looks strange to me, but hey, it is your choice.

Thank you for your time

**Comment by spacegaier** [comment] 2021-05-06 03:05
> 
> 
> So, basically you say it is better not to have a status indicator for the stop command which would reflect the actual state.

No, that is not what I am saying. I am saying that this should/cannot be driven by the frontend, but the backend has to provide that info (the "actual state" from a technical perspective according to the backend is "open" or "closed" currently). 

If the garage is open and you start closing it, but then press stop in the frontend, we could show another icon temporarily, but once you refresh the frontend page it will be gone since the frontend is rendered based on the backend data and the backend is only providing "open" or "closed" currently.

Alternatively, as I said above the frontend could potentially check if the cover supports position values and then react to those rather than just the state. But not all covers are able to.

https://developers.home-assistant.io/docs/core/entity/cover

> 
> Well, it looks strange to me, but hey, it is your choice.

No it's not my choice 😃. I just voiced my initial opinion, but a) I am happy to be convinced otherwise and b) it's a community project. @bramkragten as the frontend lead is the much more important member anyway...

**Comment by bramkragten** [comment] 2021-05-06 07:40
Normally you would use `current_cover_position` to see if it is totally opened/closed or partially, but your device doesn't seem to support that?

<https://developers.home-assistant.io/docs/core/entity/cover#states> we can only work with the official states, if you would like to add a new state, you should open an architecture issue <https://github.com/home-assistant/architecture>.

**Closed by bramkragten** 2021-05-06 07:40 UTC
Labels: bug
