### ISSUE TITLE
Conditional Cards leaving blanks on screen with Dashboard Sections

### ISSUE THREAD

**Issue by RonnieRocket2** [home-assistant/frontend#20938] opened 2024-05-31 11:38 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since a recent update, I within the last few weeks, the conditional cards I have on my Dashboard which uses sections does not work properly and leaves blank spaces instead of the items below the area moving up to replace the conditional cards that are not being displayed. This is only in the dashboard with the new sections format not on the conventional dashboard.

### Describe the behavior you expected

When the conditional entity is false the area on the screen should not be blank and other active cards should populate the area

### Steps to reproduce the issue

1.Load my normal dashboard 
2. No special conditions.
3.
...

### What version of Home Assistant Core has the issue?

2024.6.0b3

### In which browser are you experiencing the issue with?

All browsers not specific

### Which operating system are you using to run this browser?

Windows 10 and Amazon Echo 15

**Comment by piitaya** [comment] 2024-05-31 12:10
It's a duplicate of https://github.com/home-assistant/frontend/issues/20923

**Closed** 2024-05-31 12:10 UTC

**Comment by RonnieRocket2** [comment] 2024-05-31 12:19
Correct thank you, I did not see this one,

 

Kind regards

Ron
