### ISSUE TITLE
View visible: option not limiting access for non-listed users

### ISSUE THREAD

**Issue by maslyankov** [home-assistant/frontend#20942] opened 2024-05-31 21:55 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

 When you hide a view for an user, if you know or guess the view url, you can still access it using the user it is hidden for.

### Describe the behavior you expected

When user is not in "visible" list, when accessing the url, should get blank page or redirected to home.

### Steps to reproduce the issue

1. Create a dashboard with multiple views
2. Limit visibility for specific user for one of the views
3. Login as the specific user and try to access the url that should be hidden for that user
4. The url, page and everything on it stays accessible

### What version of Home Assistant Core has the issue?

2024.5.5

**Comment by karwosts** [comment] 2024-05-31 22:33
Duplicate of #20655, and (unfortunately) documented current behavior. 

https://www.home-assistant.io/dashboards/views/#visible  

> Note: This is only for the display of the tabs. The URL path is still accessible)

**Closed by karwosts** 2024-05-31 22:33 UTC
