### ISSUE TITLE
Energy Graphing on Latest Beta 2023.2.0b1

### ISSUE THREAD

**Issue by dracos1985** [home-assistant/frontend#15224] opened 2023-01-26 20:54 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Latest Beta has broken energy & Solar graphs.

![Screenshot_20230126-204632](https://user-images.githubusercontent.com/27774461/214947838-3b6b83f2-c94f-4081-a786-4e885e2a47fc.png)

### Describe the behavior you expected

Graphing to show as normal.

### Steps to reproduce the issue

1. Update to latest beta
2. Fail to see graphs
...

### What version of Home Assistant Core has the issue?

2023.2.0b1

### What was the last working version of Home Assistant Core?

2023.1

### In which browser are you experiencing the issue with?

The app and all browsers 

### Which operating system are you using to run this browser?

HAOS

### Additional information

If I try to place the graph elsewhere in Lovelace, it fails to load.

**Comment by steverep** [comment] 2023-01-26 22:12
Duplicate of #15211

**Closed by steverep** 2023-01-26 22:12 UTC

**Comment by steverep** [comment] 2023-01-26 22:13
Already fixed for next beta drop

**Comment by dracos1985** [comment] 2023-01-28 10:57
![Screenshot_20230128-105607](https://user-images.githubusercontent.com/27774461/215262888-9b845a6b-37ab-42a7-9d0b-59c59667468b.png)
![Screenshot_20230128-105439](https://user-images.githubusercontent.com/27774461/215262890-5c4bbf1b-1345-4427-a75c-d7884d5b8d3a.png)

FYI:
Unfortunately, 2 beta updates later and it's stil broken.

**Comment by dracos1985** [comment] 2023-01-29 10:50
Now updated and fixed in beta 4. Thanks.
