### ISSUE TITLE
Onboarding: Constantly pestered to add a card

### ISSUE THREAD

**Issue by legomind** [home-assistant/frontend#6760] opened 2020-09-01 02:53 UTC
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
Every time the home assistant app (android) or the main page loads (chrome, windows, linux) I am pestered with a dialog that prompts me to add something to my lovelace page.

```
Which card would you like to add to your "Overview" view?
```

## Expected behavior
I should not be asked to add a card if I have already done so.

## Steps to reproduce
Open home assistant web page.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt
None
```

**Comment by ludeeus** [comment] 2020-09-01 07:51
Duplicate of https://github.com/home-assistant/frontend/issues/6604

**Closed by ludeeus** 2020-09-01 07:51 UTC
Labels: bug
