### ISSUE TITLE
Chart card X axis displaying more than configured

### ISSUE THREAD

**Issue by Lectere** [home-assistant/frontend#15438] opened 2023-02-13 12:55 UTC
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Chart card X axis displaying more days than it should. 

![image](https://user-images.githubusercontent.com/4771745/218462093-956d1b09-ba6d-4ab2-84c9-6d3dc089b3aa.png)

I've configured my chart to display 3 days. But on the X axis I see more than 8 days back...

I've had this is several setups/installations, changing the days to 2 or 4 does not solve the problem.

### Describe the behavior you expected

The chart should display only the amount of days configured in it's yaml. 

### Steps to reproduce the issue

1. add a chart card to the dashboard
2. wait a few days
3.  the chart now displays more days than configured
...

### What version of Home Assistant Core has the issue?

2023.1.7

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

both edge / chrome and the app

### Which operating system are you using to run this browser?

android / windows

### State of relevant entities

```txt
occurs with several entities, both temprature and humidty

I suspect it has to things need to happend for the problem to occour; -missing value of one of the graph series -a reboot
```

### Problem-relevant frontend configuration

```yaml
square: false
columns: 1
type: grid
cards:
  - show_name: true
    show_icon: false
    show_state: true
    type: glance
    entities:
      - entity: sensor.openweathermap_humidity
        name: Buiten
      - entity: sensor.multisensor_7_humidity
        name: Woonkamer
      - entity: sensor.lumi_lumi_airmonitor_acn01_humidity
        name: Keuken
      - entity: sensor.lumi_lumi_weather_humidity
        name: Badkamer
    title: Luchtvochtigheid
  - chart_type: line
    period: 5minute
    days_to_show: 3
    type: statistics-graph
    entities:
      - entity: sensor.openweathermap_humidity
        name: Buiten
      - entity: sensor.multisensor_7_humidity
        name: Woonkamer
      - entity: sensor.lumi_lumi_airmonitor_acn01_humidity
        name: Keuken
      - entity: sensor.lumi_lumi_weather_humidity
        name: Badkamer
    stat_types:
      - mean
```

**Comment by ildar170975** [comment] 2023-02-13 14:26
Strange, do not observe this in my setup:

![изображение](https://user-images.githubusercontent.com/71872483/218484522-4d12884b-cad1-480b-94f9-f4894c01dcd1.png)

**Comment by Lectere** [comment] 2023-02-13 15:20
I think it has something to do with one of the sensors not being avaible for a period of time, but then again, i'm not sure...

**Comment by karwosts** [comment] 2023-02-13 15:42
Does it happen for all statistics graphs, or just some? Can you change the behavior by adding or removing specific entitites? 

Also cannot reproduce. 

And not sure if related, but I've come to always ask this when people report wacky unexplained frontend behavior: do you have any mods installed, like card-mod or browser-mod? Anything non-standard that you feel worth mentioning?

**Comment by Lectere** [comment] 2023-02-13 15:49
I've tried to take out the series one by one. 

And when I remove this series; 

      - entity: sensor.lumi_lumi_weather_humidity
        name: Badkamer

It displaying as normal;

![image](https://user-images.githubusercontent.com/4771745/218504854-700f6f12-7321-4d19-8227-cc79a54ed051.png)

This falls within my suspicion that it has something to do with devices becomming unavailable. The device 'sensor.lumi_lumi_weather_humidity' had connection problems for a while, but started working again. This in combination with a system reset has something to do with it.

**Comment by Lectere** [comment] 2023-02-13 15:51
Just to be sure, I'm gonna do the same with the temperature graph... 

![image](https://user-images.githubusercontent.com/4771745/218505823-d287bff0-4688-434b-bbd3-cd085f50183a.png)

Yes

**Comment by Lectere** [comment] 2023-02-13 16:19
My best gues would be that something goes wrong when reboting HA while a device is in a error state. I think / know a database purge for old values would solve this. So it's something in HA.

**Comment by Lectere** [comment] 2023-02-25 09:20
On an other setup I have the same problem after a reboot; 

![image](https://user-images.githubusercontent.com/4771745/221349270-65265873-3d99-48bf-ab3e-3b468980d1e4.png)

**Comment by Lectere** [comment] 2023-02-25 09:21
prolly somewhere betwean august 2022 and now something same data was missing. Or maybe a value is missing during a reboot.

**Comment by Lectere** [comment] 2023-02-25 09:33
With 600k installations, I can't bel

> Does it happen for all statistics graphs, or just some? Can you change the behavior by adding or removing specific entitites? Can you find any statistics chart that works correctly? Is it always ~9 days, or some other duration?
> 
> Also cannot reproduce.
> 
> And not sure if related, but I've come to always ask this when people report wacky unexplained frontend behavior: do you have any mods installed, like card-mod or browser-mod? Anything non-standard that you feel worth mentioning?

I think it has to do with the saving the values of devices when resetting your device. Plus having missing values in the series.

**Comment by Lectere** [comment] 2023-02-25 09:48
Glad to see I'm not the only one, this is a real issue...

https://github.com/home-assistant/frontend/issues/15438

**Comment by karwosts** [comment] 2023-02-25 15:02
Did a little more digging in my dev environment, but had to make a fake unavailable sensor for a couple days.

So I had a sensor that went unavailable at 3:30pm local time on feb 23. I allowed it to become available again around 6:20am on feb 25. I have a statistics chard configured to show 1 day for this sensor. It is now ~6:40am So I would expect to see 6:40am on feb 24 to 6:40am on feb 25.

When this chart loads, it sends this request to core. This looks correct. No start time, and 6:48am in my local time on the previous day (exactly 1 day ago). 
```
Sending:
{
    "type": "recorder/statistics_during_period",
    "start_time": "2023-02-24T13:48:18.341Z",
    "statistic_ids": [
        "sensor.office_light_power"
    ],
    "period": "5minute",
    "units": {
        "power": "W"
    },
    "types": [
        "mean",
        "min",
        "max"
    ],
    "id": 36
}
```

This is the dataset I get back in response (I annotated the timestamps for readability)
```
Received:

{
    "sensor.office_light_power": [
        {
            "start": 1677195000000,
                Thu Feb 23 2023 23:30:00 GMT+0000
                Thu Feb 23 2023 15:30:00 GMT-0800 (Pacific Standard Time)
               
            "end": 1677195300000,
                Thu Feb 23 2023 23:35:00 GMT+0000
                Thu Feb 23 2023 15:35:00 GMT-0800 (Pacific Standard Time)

            "mean": 66,
            "min": 66,
            "max": 66
        },
        {
            "start": 1677334800000,
                Sat Feb 25 2023 14:20:00 GMT+0000 
                Sat Feb 25 2023 06:20:00 GMT-0800 (Pacific Standard Time)

            "end": 1677335100000,
                Sat Feb 25 2023 14:25:00 GMT+0000
               	Sat Feb 25 2023 06:25:00 GMT-0800 (Pacific Standard Time)

            "mean": 0,
            "min": 0,
            "max": 0
        },
        {
            "start": 1677335100000,
            "end": 1677335400000,
            "mean": 0,
            "min": 0,
            "max": 0
        },
        {
            "start": 1677335400000,
            "end": 1677335700000,
            "mean": 0,
            "min": 0,
            "max": 0
        },
        {
            "start": 1677335700000,
            "end": 1677336000000,
            "mean": 0,
            "min": 0,
            "max": 0
        },
        {
            "start": 1677336000000,
            "end": 1677336300000,
            "mean": 0,
            "min": 0,
            "max": 0
        }
    ]
}
```

So it does seem that if the start window falls on when a sensor was unavailable, the core API request will return the most recent datapoint before that, no matter how much older it is than the requested start time. Not sure if that's a bug or not, but even so there's probably a way to clamp the statistics chart to not show that time.

**Comment by karwosts** [comment] 2023-02-25 15:36
Filed a core issue with this data, lets see if it gets any traction.

**Comment by Lectere** [comment] 2023-02-25 15:51
Good news! But if you say it's no bug, is there a way to prevent this?

**Comment by karwosts** [comment] 2023-02-25 15:54
I don't think there's anything you can do right now as an end user. 

If nobody from core wants to fix the issue, in theory the frontend code could be changed to work around this behavior, but I don't know if that change would be accepted to frontend, or if they would just say it needs to be fixed in core.

**Comment by ildar170975** [comment] 2023-02-25 15:56
> Filed a core issue with this data, lets see if it gets any traction.

Could you please post a link to the core issue you registered?
BTW - please accept my "thanks" for your efforts!

**Comment by ildar170975** [comment] 2023-02-25 15:57
Then we'll be waiting for any reaction in the core issue...
@karwosts - thanks a lot for your efforts!

**Comment by karwosts** [comment] 2023-02-25 15:57
It's automatically included above in the comment thread, but I'll add it here if you missed it:

[karwosts](https://github.com/karwosts) mentioned this issue Feb 25, 2023
statistics_during_period call returns datapoints older than requested home-assistant/core#88757

**Comment by karwosts** [comment] 2023-07-06 14:34
This appears to be fixed for me,  I no longer see statistics chart fetching further than requested.

**Comment by karwosts** [comment] 2023-07-20 22:49
I'll close this since it now seems fixed to me, please comment or open a new ticket if you see more issues.

**Closed by karwosts** 2023-07-20 22:49 UTC
